// Party figure parts: heads, faces, hair, bodies (per outfit style), capes and
// headgear. See chars.js for the palette letters; chars_party.js has the party table.
(function (R) {
  'use strict';
  const A = (R.Art = R.Art || {});
  const CA = (A.Chars = A.Chars || {});
  const P = (CA.parts = CA.parts || {});
  const L = (y, g, x) => ({ y, g, x: x || 0 });

  // ------------------------------------------------------------ head (skin)
  P.head = {
    down: L(4, [
      '...ssssssssss...',
      '...ssssssssss...',
      '...ssssssssss...',
      '...sssssssssd...',
      '..ssssssssssdd..',
      '..tsssssssssdd..',
      '...tssssssssd...',
      '.....sssssd.....',
    ]),
    up: L(4, [
      '...ssssssssss...',
      '...ssssssssss...',
      '...ssssssssss...',
      '...ssssssssss...',
      '..dssssssssssd..',
      '..dssssssssssd..',
      '...ssssssssss...',
      '.....ssssss.....',
    ]),
    right: L(4, [
      '...ssssssssss...',
      '...ssssssssss...',
      '...ssssssssss...',
      '...ssssssssss...',
      '...ssssssssss...',
      '...sssssssssss..',
      '....sssssssssd..',
      '......sssssd....',
    ]),
  };

  // ------------------------------------------------------------ faces
  P.face = {
    boy: {
      down: L(8, ['.....e....e.....', '.....e....e.....']),
      right: L(8, ['..........e.....', '..........e.....']),
    },
    gentle: {
      down: L(8, ['....ee....ee....', '....ew....we....', '....m......m....']),
      right: L(8, ['..........ee....', '..........ew....', '............m...']),
    },
    sharp: {
      down: L(8, ['....ee....ee....', '.....e....e.....', '....m......m....']),
      right: L(8, ['..........ee....', '..........e.....', '............m...']),
    },
    // old: eyes narrowed to one row, a 1px crease at each outer corner (dokka, bartolo, boden, berna, lazaro)
    old: {
      down: L(8, ['................', '...dee....eed...', '................']),
      right: L(8, ['................', '..........eed...', '................']),
    },
    // narrow: long slit eyes (2px, one row) with a 1px lid shadow above (shigure, sylvain, morga)
    narrow: {
      down: L(8, ['....d......d....', '....ee....ee....']),
      right: L(8, ['...........d....', '..........ee....']),
    },
  };

  // ------------------------------------------------------------ hair
  // Yuki: spiky dark-brown
  P.hairYuki = {
    down: L(1, [
      '.......3........',
      '...3..3343..3...',
      '..334334443433..',
      '..233444444332..',
      '.23344444333332.',
      '.22341333313322.',
      '.2232.232..2322.',
      '..1..........1..',
    ]),
    up: L(1, [
      '.......3........',
      '...3..3343..3...',
      '..334334443433..',
      '..233444444332..',
      '.23344444333332.',
      '.22334433333322.',
      '.22333333333322.',
      '.12233333333221.',
      '..122333333221..',
      '...1223223221...',
      '....12.12.21....',
    ]),
    right: L(1, [
      '......3.........',
      '..3..333..3.....',
      '..33334443333...',
      '.2334444444332..',
      '.23344444433332.',
      '2233444333312222',
      '2233333.2.3.2.2.',
      '.22333..........',
      '..2332..........',
      '...22...........',
    ]),
  };
  // Non: soft long pink-brown hair, gentle side-swept bangs
  P.hairNon = {
    down: L(2, [
      '.....233332.....',
      '...2344444332...',
      '..234444433332..',
      '.23444443333332.',
      '.23443333333332.',
      '.233..332333232.',
      '.23..........32.',
      '.23..........32.',
      '.22..........22.',
      '.12..........21.',
      '.12..........21.',
      '.12..........21.',
      '..1..........1..',
    ]),
    up: L(2, [
      '.....333333.....',
      '...3344444433...',
      '..234444444332..',
      '.23344444433332.',
      '.23344443333332.',
      '.23333333333332.',
      '.22333333333322.',
      '.22333333333322.',
      '.12233333333221.',
      '.12223333332221.',
      '.11222333322211.',
      '..112222222211..',
      '...1112222111...',
      '.....111111.....',
    ]),
    right: L(2, [
      '.....333333.....',
      '...3344444433...',
      '..23444444443...',
      '.2344444444332..',
      '.23334443333332.',
      '.23333333.3.32..',
      '.2333332........',
      '.223332.........',
      '.22333..........',
      '.12233..........',
      '.1222...........',
      '..1122..........',
      '...11...........',
    ]),
  };
  // Metem: short silver-lilac bob with straight bangs (+ big ribbon, see P.ribbon)
  P.hairMetem = {
    down: L(2, [
      '.....333333.....',
      '...3344444433...',
      '..234444444332..',
      '.23344444433332.',
      '.23344443333332.',
      '.22332332332322.',
      '.22..........22.',
      '.22..........22.',
      '.122........221.',
      '..11........11..',
    ]),
    up: L(2, [
      '.....333333.....',
      '...3344444433...',
      '..234444444332..',
      '.23344444433332.',
      '.23344443333332.',
      '.23333333333332.',
      '.22333333333322.',
      '.12233333333221.',
      '.11222222222211.',
      '..111111111111..',
    ]),
    right: L(2, [
      '.....333333.....',
      '...3344444433...',
      '..23444444443...',
      '.2344444444332..',
      '.233344433333332',
      '.2333333332.....',
      '.2333332........',
      '.223332.........',
      '.122222.........',
      '..1111..........',
    ]),
  };
  P.ribbon = {
    down: L(1, [
      '..PQQ.....QQP...',
      '.PQRRQ...QRRQP..',
      '.PQQRQPQPQRQQP..',
      '..PPQQ...QQPP...',
    ]),
    up: L(1, [
      '..PQQ.....QQP...',
      '.PQRRQ...QRRQP..',
      '.PQQRQPQPQRQQP..',
      '..PPQQPPPQQPP...',
      '......PQP.......',
    ]),
    right: L(1, [
      '..QQP...........',
      '.QRRQP..........',
      '.QRQQPQP........',
      '..PPQP..........',
      '...QP...........',
    ]),
  };

  // ------------------------------------------------------------ bodies
  // fighter: tunic + shoulder guards + belt + boots (warrior)
  P.body = P.body || {};
  P.body.fighter = {
    walk: true,
    down: L(12, [
      '....EFBCBBFE....',
      '...EFFBCBBBEE...',
      '...BEBBCBBBEA...',
      '...sABBCBBBAs...',
      '...sLMMHIMMLs...',
      '....BBCBBBBA....',
      '....VWWVVWWV....',
      '....VWV..VWV....',
      '....LMN..LMN....',
      '....LMN..LLN....',
      '...LLMN.........',
    ]),
    up: L(12, [
      '....EFBBBBFE....',
      '...EFFBBBBBEE...',
      '...BEBBBBBBEA...',
      '...sABBBBBBAs...',
      '...sLMMMMMMLs...',
      '....BBBBBBBA....',
      '....VWWVVWWV....',
      '....VWV..VWV....',
      '....LMN..LMN....',
      '....LMN..LLN....',
      '...LLMN.........',
    ]),
    right: [
      L(12, [
        '.....EFBBB......',
        '....EFFEBBB.....',
        '....EFEEBBBB....',
        '.....BssBBBB....',
        '....LMssHMML....',
        '....BBCBBBBA....',
        '....VWWVVWV.....',
        '...VWV..VWV.....',
        '...LMN...LMN....',
        '..LMN....LMMN...',
        '..LLN.....LLLN..',
      ]),
      L(12, [
        '.....EFBBB......',
        '....EFFEBBB.....',
        '....EFEEBBBB....',
        '.....BssBBBB....',
        '....LMssHMML....',
        '....BBCBBBBA....',
        '.....VWVVWV.....',
        '.....VWVWV......',
        '.....LMNMN......',
        '.....LMNMN......',
        '.....LLMMLN.....',
      ]),
    ],
  };

  // robe: long robe with a front stole (sub), trim cuffs & belt (priest, mages, sage)
  P.body.robe = {
    walk: true,
    down: L(12, [
      '....BCDEEDBA....',
      '...BCBDFEDBBA...',
      '..BCBBDFEDBBAA..',
      '..BCBBDFEDBBAA..',
      '..HIBBDFEDBBHG..',
      '..ssBHHIIHHBsd..',
      '...BCBDFEDBBA...',
      '...BCBDFEDBBA...',
      '..BCBBDFEDBBBA..',
      '..ABBBDEEDBBAA..',
      '...LLN..........',
    ]),
    up: L(12, [
      '....BCBBBBBA....',
      '...BCBBBBBBBA...',
      '..BCBBBBBBBBAA..',
      '..BCBBBBBBBBAA..',
      '..HIBBBBBBBBHG..',
      '..ssBHHHHHHBsd..',
      '...BCBBBBBBBA...',
      '...BCBBBBBBBA...',
      '..BCBBBBBBBBBA..',
      '..ABBBBBBBBBAA..',
      '...LLN..........',
    ]),
    right: [
      L(12, [
        '.....BCBBBD.....',
        '....BCBBBBDE....',
        '....BCBCBBDE....',
        '....BCBCCBDE....',
        '....BCBIHBDE....',
        '....BHHssHHH....',
        '....BCBBBBDE....',
        '...BCBBBBBDE....',
        '...BCBBBBBBDE...',
        '...ABBBBBBBDE...',
        '...LN.....LLN...',
      ]),
      L(12, [
        '.....BCBBBD.....',
        '....BCBBBBDE....',
        '....BCBCBBDE....',
        '....BCBCCBDE....',
        '....BCBIHBDE....',
        '....BHHssHHH....',
        '....BCBBBBDE....',
        '...BCBBBBBDE....',
        '...BCBBBBBBDE...',
        '...ABBBBBBBDE...',
        '......LLLN......',
      ]),
    ],
  };
  // armor: plate with pauldrons, trim belt, sub tabard (knight lines)
  P.body.armor = {
    walk: true,
    down: L(12, [
      '...BCCBHHBCBA...',
      '..BCCCBCBBBBBA..',
      '..ABBACCBBBAAA..',
      '...BBBCBBBBBA...',
      '...ABHHIHHHBA...',
      '....BCDEEDBA....',
      '....ABDEEDBA....',
      '....BCB..BBA....',
      '....BCB..BBA....',
      '....BCB..AAA....',
      '...AABA.........',
    ]),
    up: L(12, [
      '...BCCBBBBCBA...',
      '..BCCCBBBBBBBA..',
      '..ABBABBBBBAAA..',
      '...BBBCBBBBBA...',
      '...ABHHHHHHBA...',
      '....BCBBBBBA....',
      '....ABBBBBBA....',
      '....BCB..BBA....',
      '....BCB..BBA....',
      '....BCB..AAA....',
      '...AABA.........',
    ]),
    right: [
      L(12, [
        '.....BCCBB......',
        '....BCCCBBB.....',
        '....ACCBBBBA....',
        '.....BCBBBBA....',
        '....BHCBHHHB....',
        '....BCDEEBBA....',
        '....ABDEEBA.....',
        '...BCB..BCB.....',
        '...BCB...BCB....',
        '..BCB....BCBA...',
        '..AAA.....AAAA..',
      ]),
      L(12, [
        '.....BCCBB......',
        '....BCCCBBB.....',
        '....ACCBBBBA....',
        '.....BCBBBBA....',
        '....BHCBHHHB....',
        '....BCDEEBBA....',
        '.....BDEEBA.....',
        '.....BCBCA......',
        '.....BCBCA......',
        '.....BCBBA......',
        '.....AAAAAA.....',
      ]),
    ],
  };
  // light: tunic, scarf, belt, leggings, boots (thief, hunter, bard)
  P.body.light = {
    walk: true,
    down: L(12, [
      '....GHIIHHHG....',
      '...BCBGHHGBBA...',
      '...BCBBGGBBBA...',
      '...sCBBBBBBAs...',
      '...sDEFFEEEDd...',
      '....BCBBBBBA....',
      '....VWV..VWV....',
      '....VWV..VWV....',
      '....LMN..LMN....',
      '....LMN..LLN....',
      '...LLMN.........',
    ]),
    up: L(12, [
      '....GHHHHHHG....',
      '...BCBBBBBBBA...',
      '...BCBBBBBBBA...',
      '...sCBBBBBBAs...',
      '...sDEEEEEEDd...',
      '....BCBBBBBA....',
      '....VWV..VWV....',
      '....VWV..VWV....',
      '....LMN..LMN....',
      '....LMN..LLN....',
      '...LLMN.........',
    ]),
    right: [
      L(12, [
        '.....GHIHH......',
        '....BCGHHBB.....',
        '....BCBBBBBB....',
        '.....BssBBBB....',
        '....DEssEEED....',
        '....BCBBBBBA....',
        '....VWV..VW.....',
        '...VWV...VWV....',
        '...LMN...LMN....',
        '..LMN....LMMN...',
        '..LLN.....LLLN..',
      ]),
      L(12, [
        '.....GHIHH......',
        '....BCGHHBB.....',
        '....BCBBBBBB....',
        '.....BssBBBB....',
        '....DEssEEED....',
        '....BCBBBBBA....',
        '.....VWVVWV.....',
        '.....VWVWV......',
        '.....LMNMN......',
        '.....LMNMN......',
        '.....LLLLN......',
      ]),
    ],
  };
  // light with a short skirt (girls)
  P.body.lightF = {
    walk: true,
    down: L(12, [
      '....GHIIHHHG....',
      '...BCBGHHGBBA...',
      '...BCBBGGBBBA...',
      '...sCBBBBBBAs...',
      '...sDEFFEEEDd...',
      '...BCBBBBBBBA...',
      '...ABBBABBBAA...',
      '....VWV..VWV....',
      '....LMN..LMN....',
      '....LMN..LLN....',
      '...LLMN.........',
    ]),
    up: L(12, [
      '....GHHHHHHG....',
      '...BCBBBBBBBA...',
      '...BCBBBBBBBA...',
      '...sCBBBBBBAs...',
      '...sDEEEEEEDd...',
      '...BCBBBBBBBA...',
      '...ABBBABBBAA...',
      '....VWV..VWV....',
      '....LMN..LMN....',
      '....LMN..LLN....',
      '...LLMN.........',
    ]),
    right: [
      L(12, [
        '.....GHIHH......',
        '....BCGHHBB.....',
        '....BCBBBBBB....',
        '.....BssBBBB....',
        '....DEssEEED....',
        '...BCBBBBBBBA...',
        '...ABBBBBBBAA...',
        '...VWV...VWV....',
        '...LMN...LMN....',
        '..LMN....LMMN...',
        '..LLN.....LLLN..',
      ]),
      L(12, [
        '.....GHIHH......',
        '....BCGHHBB.....',
        '....BCBBBBBB....',
        '.....BssBBBB....',
        '....DEssEEED....',
        '....BCBBBBBBA...',
        '....ABBBBBBAA...',
        '.....VWVWV......',
        '.....LMNMN......',
        '.....LMNMN......',
        '.....LLLLN......',
      ]),
    ],
  };
  // fighter with a skirt (girls)
  P.body.fighterF = {
    walk: true,
    down: L(12, [
      '....EFBCBBFE....',
      '...EFFBCBBBEE...',
      '...BEBBCBBBEA...',
      '...sABBCBBBAs...',
      '...sLMMHIMMLs...',
      '...BCBBCBBBBA...',
      '...ABBBABBBAA...',
      '....VWV..VWV....',
      '....LMN..LMN....',
      '....LMN..LLN....',
      '...LLMN.........',
    ]),
    up: L(12, [
      '....EFBBBBFE....',
      '...EFFBBBBBEE...',
      '...BEBBBBBBEA...',
      '...sABBBBBBAs...',
      '...sLMMMMMMLs...',
      '...BCBBBBBBBA...',
      '...ABBBABBBAA...',
      '....VWV..VWV....',
      '....LMN..LMN....',
      '....LMN..LLN....',
      '...LLMN.........',
    ]),
    right: [
      L(12, [
        '.....EFBBB......',
        '....EFFEBBB.....',
        '....EFEEBBBB....',
        '.....BssBBBB....',
        '....LMssHMML....',
        '...BCBBCBBBBA...',
        '...ABBBBBBBAA...',
        '...VWV...VWV....',
        '...LMN...LMN....',
        '..LMN....LMMN...',
        '..LLN.....LLLN..',
      ]),
      L(12, [
        '.....EFBBB......',
        '....EFFEBBB.....',
        '....EFEEBBBB....',
        '.....BssBBBB....',
        '....LMssHMML....',
        '....BCBCBBBBA...',
        '....ABBBBBBAA...',
        '.....VWVWV......',
        '.....LMNMN......',
        '.....LMNMN......',
        '.....LLLLN......',
      ]),
    ],
  };
  // gi: sleeveless martial-arts top, sash, baggy trousers, leg wraps (monk)
  P.body.gi = {
    walk: true,
    down: L(12, [
      '....BCBssBBA....',
      '..tsBCBBsBBAsd..',
      '..tsBCBBBBBAsd..',
      '..HIBCBBBBBAHG..',
      '..tsDEFFEEFEsd..',
      '....BCDEBBBA....',
      '...BCBBDBBBBA...',
      '...BCBA..BBBA...',
      '....IHI..IHI....',
      '....LMN..LLN....',
      '...LLMN.........',
    ]),
    up: L(12, [
      '....BCBBBBBA....',
      '..tsBCBBBBBAsd..',
      '..tsBCBBBBBAsd..',
      '..HIBCBBBBBAHG..',
      '..tsDEEFFEEEsd..',
      '....BCBDEBBA....',
      '...BCBBBDBBBA...',
      '...BCBA..BBBA...',
      '....IHI..IHI....',
      '....LMN..LLN....',
      '...LLMN.........',
    ]),
    right: [
      L(12, [
        '.....BCBss......',
        '....BCBBBsd.....',
        '....BCtsBBB.....',
        '....BCtsBBB.....',
        '....BCHIBBB.....',
        '....DEtsEEED....',
        '...BCBBBBBBA....',
        '..BCBA...BCBA...',
        '..IHI.....IHI...',
        '..LMN.....LMMN..',
        '..LLN......LLLN.',
      ]),
      L(12, [
        '.....BCBss......',
        '....BCBBBsd.....',
        '....BCtsBBB.....',
        '....BCtsBBB.....',
        '....BCHIBBB.....',
        '....DEtsEEED....',
        '....BCBBBBBA....',
        '....BCBBBBBA....',
        '.....IHIHI......',
        '.....LMNMN......',
        '.....LLLLN......',
      ]),
    ],
  };
  // coat: long open coat over a shirt/apron, belt with vials (alchemist)
  P.body.coat = {
    walk: true,
    down: L(12, [
      '....BCFFFFBA....',
      '...BCBFEEFBBA...',
      '...BCBFEEFBBA...',
      '...sCBFEEFBAd...',
      '...sBHLMMLGBd...',
      '...BCBFEEFBBA...',
      '...BCBVWWVBBA...',
      '...ACBV..VBAA...',
      '....LMN..LMN....',
      '....LMN..LLN....',
      '...LLMN.........',
    ]),
    up: L(12, [
      '....BCBBBBBA....',
      '...BCBBBBBBBA...',
      '...BCBBBBBBBA...',
      '...sCBBBBBBAd...',
      '...sBLLMMLLBd...',
      '...BCBBBBBBBA...',
      '...BCBBABBBBA...',
      '...ACBBABBBAA...',
      '....LMN..LMN....',
      '....LMN..LLN....',
      '...LLMN.........',
    ]),
    right: [
      L(12, [
        '.....BCBFF......',
        '....BCBBFEF.....',
        '....BCBBBFE.....',
        '.....BssBFE.....',
        '....LMssLGH.....',
        '....BCBBBFE.....',
        '...BCBBBBVWV....',
        '..BCBA...VWV....',
        '...LMN...LMN....',
        '..LMN....LMMN...',
        '..LLN.....LLLN..',
      ]),
      L(12, [
        '.....BCBFF......',
        '....BCBBFEF.....',
        '....BCBBBFE.....',
        '.....BssBFE.....',
        '....LMssLGH.....',
        '....BCBBBFE.....',
        '....BCBBBVW.....',
        '....BCBAVWV.....',
        '.....LMNMN......',
        '.....LMNMN......',
        '.....LLLLN......',
      ]),
    ],
  };
  // ninja: wrapped suit, arm/leg wraps (trim), scarf (sub)
  P.body.ninja = {
    walk: true,
    down: L(12, [
      '....DEFFEEED....',
      '...BCDEEEDBBA...',
      '...BCBBDEBBBA...',
      '...HCBBBEBBAH...',
      '...sDEEEEEEDd...',
      '....BCBBBBBA....',
      '....BCB..BBA....',
      '....IHI..IHI....',
      '....BCB..BBA....',
      '....ACA..BBA....',
      '...AACA.........',
    ]),
    up: L(12, [
      '....DEEEEEED....',
      '...BCDEEEDBBA...',
      '...BCBBBBBBBA...',
      '...HCBBBBBBAH...',
      '...sDEEEEEEDd...',
      '....BCBBBBBA....',
      '....BCB..BBA....',
      '....IHI..IHI....',
      '....BCB..BBA....',
      '....ACA..BBA....',
      '...AACA.........',
    ]),
    right: [
      L(12, [
        '.....DEFFE......',
        '....BCDEEBB.....',
        '....BCBBBBBB....',
        '.....HssBBBB....',
        '....DEssEEED....',
        '....BCBBBBBA....',
        '....BCB..BC.....',
        '...IHI...IHI....',
        '...BCB...BCB....',
        '..BCA....BCBA...',
        '..AAA.....AAAA..',
      ]),
      L(12, [
        '.....DEFFE......',
        '....BCDEEBB.....',
        '....BCBBBBBB....',
        '.....HssBBBB....',
        '....DEssEEED....',
        '....BCBBBBBA....',
        '.....BCBBC......',
        '.....IHIHI......',
        '.....BCBCA......',
        '.....BCBCA......',
        '.....AAAAAA.....',
      ]),
    ],
  };

  // ------------------------------------------------------------ capes
  // cape.back is drawn behind the body (down/right), cape.up over the back.
  P.cape = P.cape || {};
  P.cape.long = {
    back: {
      down: L(13, [
        '..D..........D..',
        '..D..........D..',
        '..DE........ED..',
        '..DE........ED..',
        '..DE........ED..',
        '..DE........ED..',
        '..DE........ED..',
        '..GH........HG..',
      ]),
      right: [
        L(12, [
          '....DE..........',
          '...DEE..........',
          '...DEE..........',
          '..DEEF..........',
          '..DEEF..........',
          '..DEEF..........',
          '.DDEEF..........',
          '.DEEF...........',
          '.DDEE...........',
          'GGHH............',
        ]),
        L(12, [
          '....DE..........',
          '...DEE..........',
          '...DEE..........',
          '...DEEF.........',
          '...DEEF.........',
          '..DDEEF.........',
          '..DEEF..........',
          '..DEEF..........',
          '..DDEE..........',
          '..GGH...........',
        ]),
      ],
    },
    up: L(12, [
      '...EFFEEEEED....',
      '..DEFFEEEEEEDD..',
      '..DEFEEDEEEEDD..',
      '..DEFEEDEEEDDD..',
      '..DEFEEDEEEDDD..',
      '..DEFEEDEEEDDD..',
      '..DEFEEDEEEDDD..',
      '..DEFEEDEEEDDD..',
      '..DEFEEDEEDDDD..',
      '..GHHGGGGHGGGG..',
    ]),
  };
  // hero: long cape with the crest emblem on the back
  P.cape.crest = {
    back: P.cape.long.back,
    up: L(12, [
      '...EFFEEEEED....',
      '..DEFFEEEEEEDD..',
      '..DEFEEGHEEEDD..',
      '..DEFEGIIHEDDD..',
      '..DEFEHIIHEDDD..',
      '..DEFEEGHEEDDD..',
      '..DEFEEDEEEDDD..',
      '..DEFEEDEEEDDD..',
      '..DEFEEDEEDDDD..',
      '..GHHGGGGHGGGG..',
    ]),
  };
  // short shoulder mantle (bard)
  P.cape.mantle = {
    back: {
      down: L(13, [
        '..D..........D..',
        '..DE........ED..',
        '..DE........ED..',
      ]),
      right: L(12, [
        '....DE..........',
        '...DEE..........',
        '...DEEF.........',
        '..DDEE..........',
        '..DDD...........',
      ]),
    },
    up: L(12, [
      '...EFFEEEEED....',
      '..DEFFEEEEEEDD..',
      '..DEFEEDEEEEDD..',
      '..DEFEEDEEEDDD..',
      '..DDEDDDEDDDD...',
    ]),
  };

  // ------------------------------------------------------------ headgear
  // clipY: hair rows above this are removed before the hat is drawn.
  P.hat = P.hat || {};
  // iron half-helm with horns (warrior) — steel XYZ, bone ij
  P.hat.horned = {
    hairClip: 5,
    down: L(0, [
      '.j............j.',
      '.ji..........ij.',
      '.ji...ZZYY...ij.',
      '..iiXZZZYYYXii..',
      '...XZZYYYYYYX...',
      '..XYGYYGYYGYYX..',
    ]),
    up: L(0, [
      '.j............j.',
      '.ji..........ij.',
      '.ji...ZZYY...ij.',
      '..iiXZZYYYYXii..',
      '...XZYYYYYYYX...',
      '..XYGYYGYYGYYX..',
    ]),
    right: L(0, [
      '...j......j.....',
      '...ij....ji.....',
      '....i.ZZYiY.....',
      '....XiZYYiYX....',
      '...XZZYYYYYYX...',
      '..XYGYYGYYGYYX..',
    ]),
  };
  // open-face helm with a plume and cheek guards (knight) — main helm, sub plume, trim band
  P.hat.plume = {
    bow: { down: [10, 3], up: [1, 3], right: [3, 3] },
    hairClip: 6,
    down: L(1, [
      '......EF........',
      '.....BEFB.......',
      '...BCCBEBBBA....',
      '..BCCBBBBBBBAA..',
      '..BCHHHHHHHHBA..',
      '..BA........AB..',
      '..BA........AA..',
      '..BA........AA..',
      '...A........A...',
    ]),
    up: L(1, [
      '......EF........',
      '.....BEFB.......',
      '...BCCBEBBBA....',
      '..BCCBBEBBBBAA..',
      '..BCBBBEBBBBBA..',
      '..BCBBBBBBBBBA..',
      '..ABBBBBBBBBAA..',
      '..ABBBBBBBBBAA..',
      '...AAAAAAAAAA...',
    ]),
    right: L(1, [
      '....DEFF........',
      '..DDEEFBC.......',
      '.D..BCCBBBBA....',
      '...BCCBBBBBBA...',
      '..BCBBBBBHHHHA..',
      '..BCBBBA........',
      '..BBBBBA........',
      '..ABBBA.........',
      '...AAA..........',
    ]),
  };
  // winged helm (paladin) — main helm, sub wings, trim gem
  P.hat.winged = {
    hairClip: 6,
    down: L(1, [
      '.F............F.',
      '.EF..BCCBBA..FE.',
      '.DEFBCCBBBBAFED.',
      '..DEBCBBBBBBAED.',
      '..BCBBBHIBBBBA..',
      '..BA........AB..',
      '..BA........AA..',
      '..BA........AA..',
      '...A........A...',
    ]),
    up: L(1, [
      '.F............F.',
      '.EF..BCCBBA..FE.',
      '.DEFBCCBBBBAFED.',
      '..DEBCBBBBBBAED.',
      '..BCBBBBBBBBBA..',
      '..BCBBBBBBBBBA..',
      '..ABBBBBBBBBAA..',
      '..ABBBBBBBBBAA..',
      '...AAAAAAAAAA...',
    ]),
    right: L(1, [
      '.....F..........',
      '....EFF.........',
      '...DEFBBBBA.....',
      '...DEBCBBBBBA...',
      '..BCBBBBBBBHIA..',
      '..BCBBBA........',
      '..BBBBBA........',
      '..ABBBA.........',
      '...AAA..........',
    ]),
  };
  // dragon helm (dragoon) — main helm, sub fins, trim horns
  P.hat.dragon = {
    hairClip: 6,
    down: L(1, [
      '..I..........I..',
      '..HI.BCCBA..IH..',
      '...HBCCBBBBAH...',
      '.DEBCCBBBBBBAED.',
      '.D.BCBBHHBBBA.D.',
      '..BA..BCBA..AB..',
      '..BA...BA...AA..',
      '..BA........AA..',
      '...A........A...',
    ]),
    up: L(1, [
      '..I..........I..',
      '..HI.BCCBA..IH..',
      '...HBCCBBBBAH...',
      '.DEBCCBEBBBBAED.',
      '.D.BCBBEBBBBA.D.',
      '..BCBBBEBBBBBA..',
      '..ABBBBBBBBBAA..',
      '..ABBBBBBBBBAA..',
      '...AAAAAAAAAA...',
    ]),
    right: L(1, [
      'IH..............',
      '.IHH.BCCB.......',
      '..HBCCBBBBBA....',
      '.DEBCBBBBBBBBA..',
      'DE.BCBBBBBHHBBA.',
      '..BCBBBA...BCA..',
      '..BBBBBA....A...',
      '..ABBBA.........',
      '...AAA..........',
    ]),
  };
  // spiked closed helm with visor slit (dark knight) — main helm, sub eye glow, trim spikes
  P.hat.dark = {
    hairClip: 7,
    hideFace: true,
    down: L(1, [
      '...I..I..I..I...',
      '...HI.HI.HI.HI..',
      '..BCCBBBBBBBBA..',
      '..BCBBBBBBBBBA..',
      '..BCBBBBBBBBBA..',
      '..BCAAAAAAAAAA..',
      '..BAAEFAAFEAAA..',
      '..BCBBBBBBBBBA..',
      '..ABBBBBBBBBAA..',
      '...ABBBBBBBBA...',
    ]),
    up: L(1, [
      '...I..I..I..I...',
      '...HI.HI.HI.HI..',
      '..BCCBBBBBBBBA..',
      '..BCBBBBBBBBBA..',
      '..BCBBBBBBBBBA..',
      '..BCBBBBBBBBBA..',
      '..BCBBBBBBBBBA..',
      '..ABBBBBBBBBAA..',
      '..AABBBBBBBBAA..',
      '...AAAAAAAAAA...',
    ]),
    right: L(1, [
      '....I..I..I.....',
      '....HI.HI.HI....',
      '...BCCBBBBBBA...',
      '..BCBBBBBBBBBA..',
      '..BCBBBBBBBBBA..',
      '..BCBBBBAAAAAA..',
      '..BCBBBBAAAFEA..',
      '..BCBBBBBBBBBA..',
      '..ABBBBBBBBBA...',
      '...ABBBBBBBA....',
    ]),
  };
  // circlet with a gem (hero) — trim band, gem o/O
  P.hat.circlet = {
    hairClip: 0,
    down: L(4, ['.......HI.......', '..GHHHHoOHHHHG..', '.......GH.......']),
    up: L(5, ['..GHHHHHHHHHHG..']),
    right: L(4, ['............HI..', '..GHHHHHHHHHoO..', '............GH..']),
  };
  // tall cap (priest) — main cap, sub side panels, trim band & stripe
  P.hat.mitre = {
    bow: { down: [10, 4], up: [1, 4], right: [3, 4] },
    hairClip: 6,
    down: L(0, [
      '................',
      '......CBBA......',
      '.....CCHBBA.....',
      '....CCBIHBBA....',
      '...ECCBIHBBAD...',
      '..DEGHHIIHHGED..',
      '..DE........ED..',
      '..D..........D..',
    ]),
    up: L(0, [
      '................',
      '......CBBA......',
      '.....CCBBBA.....',
      '....CCBBBBBA....',
      '...ECCBBBBBAD...',
      '..DEGHHHHHHGED..',
      '..DEEDDDDDDEED..',
      '...DE......ED...',
    ]),
    right: L(0, [
      '................',
      '......CBA.......',
      '.....CCBBA......',
      '....CCBBBHA.....',
      '...ECCBBBIHA....',
      '..DEGHHHHHIHG...',
      '..DE............',
      '..D.............',
    ]),
  };
  // hood (white mage; spellblade/sage via remap) — main hood, sub edge
  P.hat.hood = {
    bow: { down: [10, 4], up: [1, 4], right: [2, 4] },
    hairClip: 6,
    down: L(1, [
      '.....BCCBA......',
      '....BCCCBBA.....',
      '...BCCBBBBBA....',
      '..BCCBBBBBBBAA..',
      '..BCEEEEEEEEBA..',
      '..BE........EA..',
      '..BE........EA..',
      '..BE........EA..',
      '..BE........EA..',
      '..BBE......EBA..',
      '...BBE....EBA...',
      '....ABBEEBBA....',
    ]),
    up: L(1, [
      '.....BCCBA......',
      '....BCCCBBA.....',
      '...BCCBBBBBA....',
      '..BCCBBBBBBBAA..',
      '..BCBBBBBBBBBA..',
      '..BCBBBBBBBBBA..',
      '..BCBBBBBBBBBA..',
      '..BCBBBBBBBBBA..',
      '..BCBBBBBBBBBA..',
      '..ABBBBBBBBBAA..',
      '...ABBBBBBBBA...',
      '....AABBBBAA....',
    ]),
    right: L(1, [
      '....BCCBA.......',
      '...BCCCBBA......',
      '..BCCBBBBBA.....',
      '.BCCBBBBBBBA....',
      '.BCBBBBBBBEEE...',
      '.BCBBBBBBE......',
      '.BCBBBBBBE......',
      '.BCBBBBBE.......',
      '.ABBBBBBE.......',
      '..ABBBBBE.......',
      '...ABBBBE.......',
      '....ABBA........',
    ]),
  };
  // pointed hat with a bent tip (mage) — main hat, trim band
  P.hat.witch = {
    bow: { down: [9, 3], up: [2, 3], right: [3, 3] },
    hairClip: 6,
    down: L(0, [
      '................',
      '.........BA.....',
      '.......CBBA.....',
      '......CBBBA.....',
      '.....CBBBBBA....',
      '....GHHIHHHG....',
      '..CCBBBBBBBBBA..',
      '...AAAAAAAAAA...',
    ]),
    up: L(0, [
      '................',
      '.....AB.........',
      '.....ABBC.......',
      '.....ABBBC......',
      '....ABBBBBC.....',
      '....GHHHHHHG....',
      '..CCBBBBBBBBBA..',
      '...AAAAAAAAAA...',
    ]),
    right: L(0, [
      '................',
      '..AB............',
      '...ABC..........',
      '....BBCC........',
      '....BBBBBA......',
      '....GHHHHHG.....',
      '.CCBBBBBBBBBBA..',
      '..AAAAAAAAAAA...',
    ]),
  };
  // tall crooked hat with a very wide brim and a star (black mage)
  P.hat.wide = {
    bow: { down: [9, 4], up: [2, 4], right: [3, 4] },
    hairClip: 7,
    down: L(0, [
      '.......BA.......',
      '......CBA.......',
      '......CBBA......',
      '.....CBBBA......',
      '....CBBHBBA.....',
      '....BGHIHGBA....',
      '.CCCBBBBBBBBBAA.',
      '..AAAAAAAAAAAA..',
    ]),
    up: L(0, [
      '.......BA.......',
      '......CBA.......',
      '......CBBA......',
      '.....CBBBA......',
      '....CBBBBBA.....',
      '....BGHHHGBA....',
      '.CCCBBBBBBBBBAA.',
      '..AAAAAAAAAAAA..',
    ]),
    right: L(0, [
      '....BA..........',
      '....CBA.........',
      '.....CBA........',
      '.....CBBA.......',
      '....CBBHBA......',
      '....BGHHHGBA....',
      'CCCBBBBBBBBBBBA.',
      '.AAAAAAAAAAAAA..',
    ]),
  };
  // tied bandana (thief) — main cloth
  P.hat.bandana = {
    bow: { down: [10, 3], up: [5, 5], right: [0, 4] },
    hairClip: 5,
    down: L(2, [
      '.....BCCBBA.....',
      '...BCCBBBBBBA...',
      '..BCCBBBBBBBBA..',
      '..ABBBBBBBBBAAB.',
      '.............BA.',
      '..............A.',
    ]),
    up: L(2, [
      '.....BCCBBA.....',
      '...BCCBBBBBBA...',
      '..BCCBBBBBBBBA..',
      '..ABBBBCBBBBAA..',
      '......BCBA......',
      '.....BA..BA.....',
      '.....A....A.....',
    ]),
    right: L(2, [
      '....BCCBBA......',
      '...BCCBBBBBA....',
      '..BCCBBBBBBBA...',
      '.BCBBBBBBBBBBA..',
      'BA..............',
      'A...............',
    ]),
  };
  // headband with long tails (monk) — trim cloth
  P.hat.headband = {
    hairClip: 0,
    down: L(5, [
      '..GHHIIHHHHG....',
      '...........GH...',
    ]),
    up: L(5, [
      '..GHHHHHHHHHHG..',
      '......GHIG......',
      '.....GH..HG.....',
      '.....G....G.....',
      '.....G.....G....',
    ]),
    right: L(5, [
      '.GHHHHHHHHHHG...',
      'GH..............',
      'G...............',
    ]),
  };
  // feathered cap (hunter) — main cap, trim feather
  P.hat.feather = {
    bow: { down: [10, 4], up: [1, 4], right: [3, 4] },
    hairClip: 5,
    down: L(0, [
      '............I...',
      '...........IH...',
      '.....BCBBAIH....',
      '....BCCBBBAH....',
      '...BCCBBBBBBA...',
      '..ACCBBBBBBBBA..',
    ]),
    up: L(0, [
      '...I............',
      '...HI...........',
      '....HIBCBBA.....',
      '....HBCCBBBA....',
      '...BCCBBBBBBA...',
      '..ACCBBBBBBBBA..',
    ]),
    right: L(0, [
      '.I..............',
      '.HI.............',
      '..HIBCBA........',
      '..AHCCBBBA......',
      '.ABCCBBBBBBA....',
      '..ABBBBBBBBBBA..',
    ]),
  };
  // floppy beret with a long plume (bard) — main cap, trim plume
  P.hat.beret = {
    bow: { down: [10, 4], up: [1, 4], right: [2, 4] },
    hairClip: 5,
    down: L(0, [
      '.I..............',
      '.HI.............',
      '..HIBCCCBA......',
      '..BCCCBBBBBBA...',
      '.BCBBBBBBBBBBA..',
      '..ABBBBBBBBBAAA.',
    ]),
    up: L(0, [
      '..............I.',
      '.............IH.',
      '......ABCCCBIH..',
      '...ABBBBBBCCCB..',
      '..ABBBBBBBBBBCB.',
      '.AAABBBBBBBBBA..',
    ]),
    right: L(0, [
      '..I.............',
      '..HI............',
      '...HIBCCCBA.....',
      '..BCCCBBBBBBA...',
      '.BCBBBBBBBBBBA..',
      '..AAABBBBBBBA...',
    ]),
  };
  // goggles pushed up on the forehead (alchemist) — leather strap, trim lenses
  P.hat.goggles = {
    hairClip: 0,
    down: L(4, [
      '...LMML..LMML...',
      '..LMIHNLLNIHML..',
      '...LGGL..LGGL...',
    ]),
    up: L(5, [
      '..LMMMMMMMMMML..',
    ]),
    right: L(4, [
      '.........LMML...',
      '..LMMMMMLNIHML..',
      '.........LGGL...',
    ]),
  };
  // ninja hood & mask with a headband — main cloth, sub band
  P.hat.ninja = {
    bow: { down: [10, 4], up: [1, 4], right: [2, 4] },
    hairClip: 7,
    down: L(1, [
      '.....BCCBA......',
      '....BCCCBBA.....',
      '...BCCBBBBBA....',
      '..BCCBBBBBBBAA..',
      '..BCBBBBBBBBBA..',
      '..EFFEEEEEEEED..',
      '..BC........BA..',
      '..BC........BA..',
      '..BCBBBBBBBBBA..',
      '..ABCBBBBBBBAA..',
      '...ABBBBBBBBA...',
    ]),
    up: L(1, [
      '.....BCCBA......',
      '....BCCCBBA.....',
      '...BCCBBBBBA....',
      '..BCCBBBBBBBAA..',
      '..BCBBBBBBBBBA..',
      '..EFFEEEEEEEED..',
      '..BCBBBEFBBBBA..',
      '..BCBBBEEFBBBA..',
      '..BCBBBBEFFBBA..',
      '..ABBBBBBEFBAA..',
      '...ABBBBBBEFA...',
    ]),
    right: L(1, [
      '....BCCBA.......',
      '...BCCCBBA......',
      '..BCCBBBBBA.....',
      '.BCCBBBBBBBA....',
      '.BCBBBBBBBBBA...',
      'DEEEFFEEEEEEE...',
      'E.BCBBBBB.......',
      'E.BCBBBBB.......',
      '..BCBBBBBBBBBA..',
      '..ABBBBBBBBBA...',
      '...ABBBBBBBA....',
    ]),
  };
  // wrapped turban with a jewel (sage) — sub cloth, trim jewel setting
  P.hat.turban = {
    bow: { down: [10, 4], up: [1, 4], right: [2, 4] },
    hairClip: 6,
    down: L(0, [
      '................',
      '.....EFFFE......',
      '...DEFFFEEED....',
      '..DEFFEEEDDED...',
      '..EFEEEDDEEEED..',
      '..DEEDDGoGDDED..',
      '...DDEEEEEEDD...',
    ]),
    up: L(0, [
      '................',
      '.....EFFFE......',
      '...DEFFFEEED....',
      '..DEFFEEEDDED...',
      '..EFEEEDDEEEED..',
      '..DEEDDEEEDDED..',
      '...DDEEEEEEDD...',
    ]),
    right: L(0, [
      '................',
      '....EFFFE.......',
      '..DEFFFEEED.....',
      '.DEFFEEEDDEDD...',
      '.EFEEEDDEEEEED..',
      '.DEEDDEEEDDGoG..',
      '..DDEEEEEEDD....',
    ]),
  };
  // tall hat with a crescent (time mage) — sub hat, main band, trim crescent
  P.hat.tophat = {
    bow: { down: [10, 4], up: [1, 4], right: [3, 4] },
    hairClip: 6,
    down: L(0, [
      '................',
      '....DEFFFEED....',
      '....DEIIFEED....',
      '....DIFFFEED....',
      '....DEIIFEED....',
      '....BCCBBBBA....',
      '..DEEFFEEEEEDD..',
      '...DDDDDDDDDD...',
    ]),
    up: L(0, [
      '................',
      '....DEFFFEED....',
      '....DEFFFEED....',
      '....DEFFEEED....',
      '....DEFFEEED....',
      '....BCCBBBBA....',
      '..DEEFFEEEEEDD..',
      '...DDDDDDDDDD...',
    ]),
    right: L(0, [
      '................',
      '....DEFFFED.....',
      '....DEFIIED.....',
      '....DEFFFID.....',
      '....DEFIIED.....',
      '....BCCBBBA.....',
      '.DEEFFEEEEEEED..',
      '..DDDDDDDDDDD...',
    ]),
  };

  // The party table (20 companions + the hero) is in chars_party.js; it replaces
  // the Crest per-job looks (DESIGN §11.3.2).
  P.party = P.party || {};
})(window.RPG);
