// V1 — "Faithful": the measured target (38 px, 2.7 heads, 6-tone blue coat, hue-shifted ramps,
// mixed outline: near-black + material darks), hand-placed clean clusters.
// Arun: lantern in the left hand, sword on the back (hilt over the right shoulder), amber scarf.
'use strict';
(function (G) {
  const C = G.C5, R = C.ramp;
  const pal = {};
  const put = (keys, list) => keys.split('').forEach((k, i) => (pal[k] = list[i]));
  put('X', ['#1d1519']);                         // near-black outline (warm neutral)
  put('Z', ['#2e1618']);                         // lashes
  put('1234', R([[10, 0.62, 0.45], [17, 0.48, 0.74], [24, 0.30, 0.94], [33, 0.14, 1.0]]));      // skin
  put('5', ['#f0a08a']);                                                                          // blush
  put('abcde', R([[352, 0.58, 0.22], [6, 0.62, 0.36], [16, 0.64, 0.53], [25, 0.60, 0.71], [36, 0.46, 0.88]])); // chestnut hair
  put('ABCDEF', R([[246, 0.58, 0.18], [232, 0.56, 0.30], [222, 0.52, 0.44], [215, 0.47, 0.58], [207, 0.38, 0.72], [196, 0.26, 0.86]])); // coat blue
  put('mnop', R([[12, 0.66, 0.50], [24, 0.62, 0.74], [36, 0.50, 0.90], [46, 0.26, 0.99]]));     // amber scarf
  put('ghij', R([[335, 0.30, 0.16], [5, 0.26, 0.26], [18, 0.24, 0.37], [28, 0.22, 0.49]]));      // trousers
  put('KLMN', R([[352, 0.55, 0.20], [10, 0.60, 0.34], [22, 0.58, 0.50], [32, 0.48, 0.66]]));     // leather
  put('OPRSW', R([[245, 0.28, 0.24], [228, 0.18, 0.46], [212, 0.12, 0.68], [200, 0.06, 0.88], [50, 0.05, 1.0]])); // steel
  put('GHJ', R([[22, 0.72, 0.46], [36, 0.64, 0.74], [48, 0.40, 0.96]]));                          // brass
  put('yY', R([[204, 0.72, 0.50], [184, 0.52, 0.82]]));                                           // iris
  put('TUV', ['#fff8dc', '#ffc85a', '#e0802a']);                                                  // lantern glow

  const LANTERN = ['..X..', '.XPX.', 'XPRPX', 'XUTUX', 'XUTTX', 'XVUUX', 'XPPPX', '.XXX.'];

  // ---------------------------------------------------------------- front (walk down)
  const down = C.compose(20, 38, [
    { x: 1, y: 11, rows: [ // sword hilt over the right shoulder (behind)
      'XX...',
      'XRX..',
      '.XKX.',
      'XPRPX',
    ] },
    { x: 0, y: 0, rows: [
      '...........XX.......',
      '.......XXXXdcX......',
      '.....XXcddeecXX.....',
      '....XcdeeddcccbX....',
      '...XcdedcccccbcbX...',
      '..XbcdcccbcccbbcbX..',
      '..XbccbccbccbcbbbX..',
      '..Xbcb3cb3cbc3bbbX..',
      '..Xbc33ZZ33ZZ33cbX..',
      '..Xbc33Wy33Wy33cbX..',
      '..Xbc33YY33YY32cbX..',
      '..Xab3533333352baX..',
      '..XaX2333333332XaX..',
      '...X..XX1111XX..X...',
      '......XmnoonmX......',
      '....XEDnoponmCBX....',
      '...XEDDmnoonmCCBX...',
      '..XEDAonDBDCCBACBX..',
      '..XEDAomDBDCCBACBX..',
      '..XEDAnmDHDCBBACBX..',
      '..XpoAmDDBCCBBAonX..',
      '..X32ADDCHCBBAA32X..',
      '..X21KMNMHJMLLK21X..',
      '....XDEDCBCCBBBX....',
      '....XDEDCBCCBCBX....',
      '...XDEDDCBBCCBCBX...',
      '...XDEDCCAACCBCBX...',
      '...XDEDCAhhACBCBX...',
      '..XCDDCAXhhXACBBAX..',
      '...XXgghgXXghggXX...',
      '.....XijX..XjiX.....',
      '.....XijX..XjiX.....',
      '.....XhiX..XihX.....',
      '....XNMLX..XLMNX....',
      '....XMLKX..XKLMX....',
      '....XMLKX..XKLMX....',
      '...XNMLKX..XKLMNX...',
      '...XXXXXX..XXXXXX...',
    ] },
    { x: 14, y: 23, rows: LANTERN },
  ], 'v1 down');
  const downWalk = { y: 29, rows: [
    '...XXgghgXXghggXX...',
    '.....XijX..XjiX.....',
    '.....XijX..XjiX.....',
    '....XNMLX..XihX.....',
    '....XMLKX..XihX.....',
    '....XMLKX.XLMNX.....',
    '...XNMLKX.XKLMX.....',
    '...XXXXXX.XXXXX.....',
    '..........XXXXX.....',
  ] };

  // ---------------------------------------------------------------- side (walk right)
  const side = C.compose(20, 38, [
    { x: 0, y: 25, rows: ['..XX', '.XKX', 'XKX.', 'XX..'] }, // scabbard tip behind
    { x: 0, y: 0, rows: [
      '........XXX.........',
      '......XXcdeX........',
      '....XXccddeeXX......',
      '...XbccddeedccX.....',
      '..XbccdddddcccbX....',
      '..XbcccdddccccbbX...',
      '.XbbccccccccbcbbX...',
      '.Xabcbccbcbbc3b3X...',
      '.Xabcbcbbc33ZZ33X...',
      '.Xabcbcbbc33yW333X..',
      '.Xabcbcbbc33YY33X...',
      '..Xabcbbab33353X....',
      '...XabaX23332X......',
      '....XXXXX111XX......',
      '...XnmXmnnoX........',
      '..XnmXCDEDonX.......',
      '..XmXXDEEDCCBX......',
      '....XCCAEDACBX......',
      '....XDCCAEDABX......',
      '....XDCCBAEDAX......',
      '....XDCCBBAponX.....',
      '....XDCBBBAX332X....',
      '....XLMNMLKX21X.....',
      '....XDCCBBBCX.......',
      '...XDDCCBBBCX.......',
      '...XDDCCBBBCBX......',
      '..XDDCCBBABCBX......',
      '..XDDCCBAABCBX......',
      '.XCDDCCBBAAX........',
      '..XXXXghhiX.........',
      '.....XghijX.........',
      '.....XghijX.........',
      '.....XghiiX.........',
      '.....XKLMNX.........',
      '.....XKLMNNX........',
      '.....XKLMMNNX.......',
      '.....XKLLMMMX.......',
      '.....XXXXXXXX.......',
    ] },
    { x: 11, y: 23, rows: LANTERN },
  ], 'v1 side');
  const sideWalk = { y: 29, rows: [
    '..XXXghhiXX.........',
    '....XghXhijX........',
    '...XghX.XhijX.......',
    '..XghX...XhijX......',
    '..XKLX...XKLMNX.....',
    '.XKLMX...XKLMNNX....',
    '.XKLMX...XKLMMNNX...',
    'XKLLX....XKLLMMMX...',
    'XXXX.....XXXXXXXX...',
  ] };
  const sideWalkB = { y: 29, rows: [
    '..XXXghhiXX.........',
    '....XhiXghgX........',
    '...XhiX.XghgX.......',
    '..XhijX..XghgX......',
    '..XKLX...XKLMNX.....',
    '.XKLMX...XKLMNNX....',
    '.XKLMX...XKLMMNNX...',
    'XKLLX....XKLLMMMX...',
    'XXXX.....XXXXXXXX...',
  ] };

  // ---------------------------------------------------------------- back (walk up)
  const up = C.compose(20, 38, [
    { x: 1, y: 23, rows: LANTERN },
    { x: 0, y: 0, rows: [
      '...........XX.......',
      '.......XXXXdcX......',
      '.....XXcddeecXX.....',
      '....XcdeeddcccbX....',
      '...XcdeddccccbcbX...',
      '..XbcddcccbcccbcbX..',
      '..XbcdccbccbccbcbX..',
      '..XbccbccbcbccbbbX..',
      '..XbcbcbbcbbcbcbbX..',
      '..XbbcbcbbcbbcbbaX..',
      '..XabbcbbabbcbbbaX..',
      '..XabbabbabbabbaaX..',
      '...XaXabbbbaXaXaX...',
      '......XX1111XX......',
      '......XmnnnnmX......',
      '....XDEmnnnmCCBX....',
      '...XDEDCmnnmCCCBX...',
      '..XEDADDCBCCBBACBX..',
      '..XEDADCCBCCBBACBX..',
      '..XEDADCCBCCBBACBX..',
      '..XpoADCCBCBBBAonX..',
      '..X32ADCCBCBBBA32X..',
      '..X21KLMLKLMLLK21X..',
      '....XDEDCCBCCBBX....',
      '....XDEDCCBCCBBX....',
      '...XDEDDCCBCCBBBX...',
      '...XDEDDCCACCBBBX...',
      '...XDEDCCAACCBBBX...',
      '..XCDDCCAXXACBBBAX..',
      '...XXgghgXXghggXX...',
      '.....XhiX..XihX.....',
      '.....XhiX..XihX.....',
      '.....XghX..XhgX.....',
      '....XLMLX..XLMLX....',
      '....XKLKX..XKLKX....',
      '....XKLKX..XKLKX....',
      '....XKLKX..XKLKX....',
      '....XXXXX..XXXXX....',
    ] },
    { x: 0, y: 11, rows: [ // scabbard across the back, hilt over the right shoulder
      '................X...',
      '...............XRX..',
      '..............XKX...',
      '.............XPRPX..',
      '............XLKX....',
      '...........XLKX.....',
      '..........XLKX......',
      '.........XLKX.......',
      '........XLKX........',
      '........XLKX........',
      '.......XLKX.........',
      '.......XLKX.........',
      '......XLKX..........',
      '.....XLKX...........',
      '.....XMKX...........',
      '....XMKX............',
      '....XXX.............',
    ] },
    { x: 1, y: 23, rows: LANTERN.slice(0, 1) },
  ], 'v1 up');
  const upWalk = { y: 29, rows: [
    '...XXgghgXXghggXX...',
    '.....XhiX..XihX.....',
    '.....XhiX..XihX.....',
    '....XLMLX..XghX.....',
    '....XKLKX..XghX.....',
    '....XKLKX.XLMLX.....',
    '....XKLKX.XKLKX.....',
    '....XXXXX.XKLKX.....',
    '..........XXXXX.....',
  ] };

  // ---------------------------------------------------------------- battle (3/4, facing left, sword raised)
  const battle = C.compose(30, 38, [
    { x: 21, y: 13, rows: [ // scarf tail streaming back (behind)
      'XnoX..',
      'XmnnX.',
      '.XmnnX',
      '..XmX.',
      '...X..',
    ] },
    { x: 19, y: 16, rows: [ // far arm (behind)
      'XCBX',
      'XCBX',
      'XBAX',
      'X21X',
      '.XX.',
    ] },
    { x: 7, y: 0, rows: [
      '..........XX......',
      '......XXXXdcX.....',
      '....XXcddeeccXX...',
      '...XcdeeddcccbbX..',
      '..XcdedccccbcbbbX.',
      '.XbcdcccbccbbcbbX.',
      '.XbccbccbcbcbbbbbX',
      '.Xc3cb3cbcbcbbbbbX',
      '.X3Z33ZZ3bcbcbbbaX',
      '.X3y33Wy3bcbcbbbaX',
      '.X3Y33YY3bbcbbbaX.',
      '..X3533353abbbbaX.',
      '..X2333332XaabaX..',
      '...X11111XXXXaX...',
    ] },
    { x: 8, y: 14, rows: [
      '...XmnoonmX...',
      '..XDEnoponCBX.',
      '.XDEDmnomCCBBX',
      '.XEDDonBDCCBBX',
      '.XEDDomBDCCBAX',
      '.XEDDnmHDCBBAX',
      '.XDDDmBBCCBBAX',
      '.XDDCBHCCBBAAX',
      '.XKMNMHJMLLKKX',
    ] },
    { x: 5, y: 23, rows: [
      '....XDEDCCBCCBBBX.',
      '...XDEDDCCBCCBBBX.',
      '...XDEDCCABCCBBBBX',
      '..XDEDCCAhABCCBBBX',
      '..XCDDCAhhhACCBBAX',
      '.XCDDCAXhhXXACBBAX',
    ] },
    { x: 5, y: 29, rows: [
      '...XghhX..XhghX...',
      '..XghijX..XhihX...',
      '..XhijX...XhihX...',
      '.XhijX....XhihX...',
      '.XNMLX....XNMLX...',
      'XNMLKX....XMLKX...',
      'XMLKX....XNMLKX...',
      'XNMLKX...XNMLKX...',
      'XXXXXX...XXXXXX...',
    ] },
    { x: 1, y: 1, rows: [ // sword, raised on guard
      '..X.....',
      '.XWX....',
      '.XSPX...',
      '.XSPX...',
      '.XSPX...',
      '..XSPX..',
      '..XSPX..',
      '..XSPX..',
      '..XSRX..',
      '...XSPX.',
      '...XSPX.',
      '...XSPX.',
      '...XRPX.',
      '....XSPX',
      '....XSPX',
      '..XGHJJHX',
      '....XLX.',
      '....XLX.',
      '....XJX.',
      '.....X..',
    ] },
    { x: 4, y: 15, rows: [ // near (sword) arm over the body
      '.....XEE',
      '....XEDC',
      'X332oDCA',
      'X221XCAX',
      '.XXX.XX.',
    ] },
  ], 'v1 battle');

  G.VARIANTS.v1 = {
    id: 'v1', short: 'faithful', name: '計測どおり（38px・2.7頭身・6段の青）',
    desc: 'STYLE_REFERENCE の数値そのまま。手置きのくっきりした塊、影は赤紫・明部は黄へずらす、縁は黒と素材の暗色を混ぜる。',
    pal,
    mats: { skin: '1234', hair: 'abcde', coat: 'ABCDEF', scarf: 'mnop', pants: 'ghij', leather: 'KLMN', steel: 'OPRSW', brass: 'GHJ', eye: 'yY' },
    emissive: 'TUV', noLit: 'ZWyY', outlineKeys: 'X', lit: { half: 0.7 },
    battleZoom: 4,
    views: {
      down: { rows: down, walk: downWalk, neck: 14, waist: 22, lightSide: 1, lamp: [16, 27] },
      side: { rows: side, walk: sideWalk, walkB: sideWalkB, neck: 14, waist: 22, lightSide: 1, lamp: [13, 27] },
      up: { rows: up, walk: upWalk, neck: 14, waist: 22, lightSide: -1, lamp: [3, 27] },
      battle: { rows: battle, neck: 14, waist: 22, lightSide: -1, anchor: [14, 38] },
    },
  };
})(window);
