// V2 — "Fine": a larger sprite (46 px, 2.7 heads) with more face detail (3-row irises with a lash
// wing, tiny mouth), a knee-length open coat over a cream shirt, red neckerchief, book-strap belt.
'use strict';
(function (G) {
  const C = G.C5, R = C.ramp;
  const pal = {};
  const put = (keys, list) => keys.split('').forEach((k, i) => (pal[k] = list[i]));
  put('X', ['#1b1418']);
  put('Z', ['#2a1216']);
  put('1234', R([[8, 0.60, 0.46], [16, 0.46, 0.75], [24, 0.29, 0.95], [34, 0.13, 1.0]]));
  put('5', ['#f29a86']);
  put('abcde', R([[350, 0.55, 0.20], [4, 0.60, 0.34], [15, 0.62, 0.50], [24, 0.60, 0.68], [36, 0.48, 0.86]]));
  put('ABCDEF', R([[250, 0.60, 0.16], [236, 0.60, 0.27], [226, 0.58, 0.40], [218, 0.52, 0.54], [210, 0.44, 0.68], [198, 0.30, 0.84]]));
  put('mnop', R([[28, 0.30, 0.62], [36, 0.22, 0.80], [42, 0.14, 0.92], [48, 0.07, 0.99]]));    // cream shirt
  put('qrs', R([[352, 0.70, 0.42], [2, 0.66, 0.62], [12, 0.54, 0.82]]));                        // red neckerchief
  put('ghij', R([[330, 0.28, 0.15], [0, 0.25, 0.25], [16, 0.24, 0.36], [26, 0.22, 0.48]]));
  put('KLMN', R([[350, 0.55, 0.19], [8, 0.60, 0.33], [20, 0.58, 0.49], [30, 0.48, 0.66]]));
  put('OPRSW', R([[245, 0.28, 0.24], [228, 0.18, 0.46], [212, 0.12, 0.68], [200, 0.06, 0.88], [50, 0.05, 1.0]]));
  put('GHJ', R([[22, 0.72, 0.46], [36, 0.64, 0.74], [48, 0.40, 0.96]]));
  put('yY', R([[200, 0.74, 0.46], [182, 0.54, 0.80]]));
  put('TUV', ['#fff8dc', '#ffc85a', '#e0802a']);

  const LANTERN = ['..X..', '.XPX.', 'XPRPX', 'XUTUX', 'XTTUX', 'XUTUX', 'XVUUX', 'XPPPX', '.XXX.'];

  // ---------------------------------------------------------------- front
  const down = C.compose(24, 46, [
    { x: 1, y: 14, rows: ['XX...', 'XRX..', '.XKX.', '.XKX.', 'XPRPX'] },
    { x: 0, y: 0, rows: [
      '............XX..........',
      '........XXXXdcX.........',
      '......XXcdddeecXX.......',
      '.....XcddeeeedccbX......',
      '....XcddeeddddccbbX.....',
      '...XbcddddcccccbcbbX....',
      '...XbcdcccbcccbccbcbX...',
      '..XbccdccbccbcccbccbbX..',
      '..XbcccbcbcccbccbcbcbX..',
      '..Xbcbbcc3cbcc3bcbcbbX..',
      '..Xbcb33ZZZ33ZZZ33bcbX..',
      '..Xbcb333Wy33Wy333bcbX..',
      '..Xbca333yY33yY332acbX..',
      '..Xbca353YY33YY352acbX..',
      '..Xabb33333213333bbaX...',
      '..XaX.X2333333332X.XaX..',
      '...X...XX111111XX...X...',
      '........XqrssrqX........',
      '....XDEEDFqrsrqACCBX....',
      '...XEDCDEFqrsqACBCBAX...',
      '...XEDCDEFnqrnACBCBAX...',
      '...XEDCDEFoqrnACBCBAX...',
      '...XEDCDEDoqsnACBCBAX...',
      '...XEDCDEDonHmACBCBAX...',
      '...XponDDConmmBBCBonmX..',
      '...X332DDCnHmmBBB332X...',
      '...X221DCCnmmmBBA221X...',
      '....XXXKLMNHJNMLKXXX....',
      '.....XDEEDCnmCBBBAX.....',
      '.....XDEEDAhhACBBBX.....',
      '....XDEEDCAhiACBBBBX....',
      '....XDEDDCAhiACCBBBX....',
      '...XDEEDCBAhiACCBBBAX...',
      '...XDEDDCBAihABCBBBAX...',
      '..XCDEDCCBAihABCCBBAAX..',
      '..XBCDDCBAXhhXACBBBAAX..',
      '....XXXXghXXXXhgXXXX....',
      '.......XhiX..XihX.......',
      '.......XijX..XjiX.......',
      '.......XhiX..XihX.......',
      '......XNMLX..XLMNX......',
      '......XMLKX..XKLMX......',
      '......XNMKX..XKMNX......',
      '......XMLKX..XKLMX......',
      '.....XNMLKX..XKLMNX.....',
      '.....XXXXXX..XXXXXX.....',
    ] },
    { x: 7, y: 27, rows: ['XLLX', 'XpoX', 'XLLX'] }, // small book strapped to the belt
    { x: 17, y: 27, rows: LANTERN },
  ], 'v2 down');
  const downWalk = { y: 36, rows: [
    '....XXXXghXXXXhgXXXX....',
    '.......XhiX..XihX.......',
    '.......XijX..XjiX.......',
    '.......XhiX..XihX.......',
    '......XNMLX..XihX.......',
    '......XMLKX..XihX.......',
    '......XNMKX.XLMNX.......',
    '......XMLKX.XKLMX.......',
    '.....XNMLKX.XKMNX.......',
    '.....XXXXXX.XXXXX.......',
  ] };

  // ---------------------------------------------------------------- side (facing right)
  const side = C.compose(24, 46, [
    { x: 0, y: 32, rows: ['..XX', '.XKX', 'XKX.', 'XX..'] },
    { x: 0, y: 0, rows: [
      '..........XXX...........',
      '........XXcdeX..........',
      '......XXccddeeX.........',
      '.....XbccddeeddXX.......',
      '....XbccdddddccccX......',
      '...XbcccddddcccccbX.....',
      '...XbcccdcccccbcbbX.....',
      '..XbbccccccccbccbbbX....',
      '..XbbcccbcccbcbcbbbX....',
      '.Xabbcbccbcbbcbc3b3X....',
      '.Xabbcbccbcbc3ZZZ33X....',
      '.Xabbcbccbcbc33Wy33X....',
      '.Xabbcbccbcbc33yY333X...',
      '.Xabbcbccbab33YY3332X...',
      '.Xabbcbcbaba335333X.....',
      '..XabcbbaXa2333332X.....',
      '...XabaXXX.X11111X......',
      '....XqrXXqrssqX.........',
      '...XqrsXDEEDqrqX........',
      '...XrsXDEEEDCqnX........',
      '....XXDEEDDCAonX........',
      '.....XDCAEDACBonX.......',
      '.....XDCCAEDACBnX.......',
      '.....XDCCBAEDACBX.......',
      '.....XDCCBBAEDAmX.......',
      '.....XDCCBBBApoonX......',
      '.....XDCCBBBBAX3332X....',
      '.....XKLMNMLKXX2221X....',
      '.....XDCCBBBBCX.........',
      '....XDDCCBBBBCX.........',
      '....XDDCCBBBBCBX........',
      '...XDDCCBBBBBCBX........',
      '...XDDCCBBBABCBX........',
      '..XDDCCBBBAABCBX........',
      '..XDDCCBBBAABBCBX.......',
      '.XCDDCCBBAAXABCBX.......',
      '..XXXXXXghhiXXXX........',
      '.......XghijX...........',
      '.......XghijX...........',
      '.......XghiiX...........',
      '.......XghiiX...........',
      '.......XKLMNX...........',
      '.......XKLMNNX..........',
      '.......XKLMMNNX.........',
      '.......XKLLMMMNX........',
      '.......XXXXXXXXX........',
    ] },
    { x: 15, y: 28, rows: LANTERN },
  ], 'v2 side');
  const sideWalk = { y: 36, rows: [
    '..XXXXXXghhiXXXX........',
    '......XghXhijX..........',
    '.....XghX.XhijX.........',
    '....XghX...XhijX........',
    '....XghX....XhijX.......',
    '...XKLX.....XKLMNX......',
    '...XKLMX....XKLMNNX.....',
    '..XKLMX.....XKLMMNNX....',
    '..XKLLX.....XKLLMMMX....',
    '.XXXXX......XXXXXXXX....',
  ] };
  const sideWalkB = { y: 36, rows: [
    '..XXXXXXghhiXXXX........',
    '......XhiXghgX..........',
    '.....XhiX.XghgX.........',
    '....XhijX..XghgX........',
    '....XhijX...XghgX.......',
    '...XKLX.....XKLMNX......',
    '...XKLMX....XKLMNNX.....',
    '..XKLMX.....XKLMMNNX....',
    '..XKLLX.....XKLLMMMX....',
    '.XXXXX......XXXXXXXX....',
  ] };

  // ---------------------------------------------------------------- back
  const up = C.compose(24, 46, [
    { x: 2, y: 27, rows: LANTERN },
    { x: 0, y: 0, rows: [
      '............XX..........',
      '........XXXXdcX.........',
      '......XXcdddeecXX.......',
      '.....XcddeeeedccbX......',
      '....XcddeeddddccbbX.....',
      '...XbcddddcccccbcbbX....',
      '...XbcdcccbcccbccbcbX...',
      '..XbccdccbccbcccbccbbX..',
      '..XbcccbcbcccbccbcbcbX..',
      '..XbccbccbcbccbcbccbbX..',
      '..XbcbccbcbbcbcbbcbcbX..',
      '..XbbcbcbbcbbcbbcbcbbX..',
      '..XabbcbbcbbabbcbbbbaX..',
      '..XabbcbbabbabbcbbbbaX..',
      '..XabbabbabbabbabbbaaX..',
      '..XaXabbabbaabbabbaXaX..',
      '...X.XXaXX1111XXaXX.X...',
      '........XqrrrrqX........',
      '....XDEEDDqrrqCCCBBX....',
      '...XEDCDEDDqqCCBBCBAX...',
      '...XEDCDEDDCCCCBBCBAX...',
      '...XEDCDEDCCBCCBBCBAX...',
      '...XEDCDEDCCBCCBBCBAX...',
      '...XEDCDDDCCBCCBBCBAX...',
      '...XponDDCCCBCCBBonmX...',
      '...X332DDCCCBCCBB332X...',
      '...X221DCCCCBCCBB221X...',
      '....XXXKLMLKKLMLKXXX....',
      '.....XDEEDCCCCBBBBX.....',
      '.....XDEEDCCCCBBBBX.....',
      '....XDEEDDCCCCBBBBBX....',
      '....XDEEDDCCACBBBBBX....',
      '...XDEEDDCCAACCBBBBBX...',
      '...XDEEDDCCAACCBBBBBX...',
      '..XCDEEDDCAAACCBBBBBAX..',
      '..XBCDDDCCAXXACCBBBAAX..',
      '....XXXXghXXXXhgXXXX....',
      '.......XhiX..XihX.......',
      '.......XhiX..XihX.......',
      '.......XghX..XhgX.......',
      '......XLMLX..XLMLX......',
      '......XKLKX..XKLKX......',
      '......XKLKX..XKLKX......',
      '......XKLKX..XKLKX......',
      '......XKLKX..XKLKX......',
      '......XXXXX..XXXXX......',
    ] },
    { x: 0, y: 13, rows: [
      '...................X....',
      '..................XRX...',
      '.................XKX....',
      '.................XKX....',
      '...............XPRPX....',
      '..............XLKX......',
      '.............XLKX.......',
      '.............XLKX.......',
      '............XLKX........',
      '...........XLKX.........',
      '...........XLKX.........',
      '..........XLKX..........',
      '.........XLKX...........',
      '.........XLKX...........',
      '........XLKX............',
      '.......XLKX.............',
      '.......XLKX.............',
      '......XMKX..............',
      '.....XMKX...............',
      '.....XXX................',
    ] },
    { x: 2, y: 27, rows: LANTERN.slice(0, 1) },
  ], 'v2 up');
  const upWalk = { y: 36, rows: [
    '....XXXXghXXXXhgXXXX....',
    '.......XhiX..XihX.......',
    '.......XhiX..XihX.......',
    '.......XghX..XhgX.......',
    '......XLMLX..XhgX.......',
    '......XKLKX..XhgX.......',
    '......XKLKX.XLMLX.......',
    '......XKLKX.XKLKX.......',
    '......XXXXX.XKLKX.......',
    '............XXXXX.......',
  ] };

  // ---------------------------------------------------------------- battle (3/4 left, sword on guard)
  const battle = C.compose(34, 46, [
    { x: 25, y: 16, rows: ['XqrX...', 'XqrsX..', '.XqrsX.', '..XqrX.', '...XX..'] },
    { x: 24, y: 19, rows: ['XCBX', 'XCBX', 'XBAX', 'XBAX', 'X21X', '.XX.'] },
    { x: 9, y: 0, rows: [
      '............XX......',
      '........XXXXdcX.....',
      '......XXcdddeecXX...',
      '.....XcddeeeedccbX..',
      '....XcddeeddddccbbX.',
      '...XbcddddcccccbcbbX',
      '..XbcdcccbcccbccbcbX',
      '.XbccdccbccbcccbccbX',
      '.XbccbcbcccbccbcbcbX',
      '.Xbc3cc3cbcbcbccbcbX',
      '.X3ZZ33ZZZ3bcbcbcbbX',
      '.X3Wy33Wy33bcbcbcbbX',
      '.X3yY33yY33bcbcbbbaX',
      '.X3YY33YY32abcbcbbaX',
      '.X3533313332abbbbaX.',
      '..X23333332XabbbaX..',
      '...X1111111XXXaXX...',
    ] },
    { x: 10, y: 17, rows: [
      '....XqrssrqX....',
      '...XDEqrsrqCBX..',
      '..XDEDFqrsqACBBX',
      '..XEDDFnqrnACBBX',
      '..XEDDFoqrnACBAX',
      '..XEDDEoqsnABBAX',
      '..XEDDDonHmABBAX',
      '..XDDDDonmmABBAX',
      '..XDDDCnHmmABAAX',
      '..XDDCCnmmmABAAX',
      '..XKLMNHJNMLKKKX',
    ] },
    { x: 13, y: 27, rows: ['XLLX', 'XpoX', 'XLLX'] },
    { x: 6, y: 28, rows: [
      '.....XDEEDCnmCBBBBX...',
      '....XDEEDCAhhACBBBBX..',
      '....XDEEDCAhiACBBBBBX.',
      '...XDEEDDCAhiACCBBBBX.',
      '...XDEEDDCAhiACCBBBBBX',
      '..XDEEDDCBAihACCBBBBBX',
      '..XCDEDDCBAXXACCBBBBAX',
      '.XCDDDCBAX..XACBBBAAX.',
    ] },
    { x: 5, y: 36, rows: [
      '...XXghhX...XXhghX....',
      '..XghijX.....XhihX....',
      '..XhijX......XhihX....',
      '.XhijX.......XhihX....',
      '.XhijX.......XhihX....',
      '.XNMLX.......XNMLX....',
      'XNMLKX.......XMLKX....',
      'XMLKX.......XNMLKX....',
      'XNMLKX......XNMLKX....',
      'XXXXXX......XXXXXX....',
    ] },
    { x: 1, y: 0, rows: [
      '...X......',
      '..XWX.....',
      '..XSPX....',
      '..XSPX....',
      '..XSPX....',
      '..XSPX....',
      '...XSPX...',
      '...XSPX...',
      '...XSRX...',
      '...XSPX...',
      '....XSPX..',
      '....XSPX..',
      '....XSPX..',
      '....XRPX..',
      '....XSPX..',
      '.....XSPX.',
      '.....XSPX.',
      '.....XSPX.',
      '.....XRPX.',
      '...XGHJJHX',
      '......XLX.',
      '......XLX.',
      '......XLX.',
      '......XJX.',
      '.......X..',
    ] },
    { x: 5, y: 18, rows: [
      '........XEE',
      '.......XEDC',
      '......XEDCA',
      'X3332opDDCA',
      'X2221XXDCAX',
      '.XXXX..XXX.',
    ] },
  ], 'v2 battle');

  G.VARIANTS.v2 = {
    id: 'v2', short: 'fine 46px', name: '大きめ・顔を細かく（46px）',
    desc: '46px に上げて顔を描き込む（虹彩 3 段＋まつ毛の払い、小さな口）。膝までの開いたコート＋生成りのシャツ＋赤いスカーフ、腰に本。',
    pal,
    mats: { skin: '1234', hair: 'abcde', coat: 'ABCDEF', shirt: 'mnop', scarf: 'qrs', pants: 'ghij', leather: 'KLMN', steel: 'OPRSW', brass: 'GHJ', eye: 'yY' },
    emissive: 'TUV', noLit: 'ZWyY', outlineKeys: 'X', lit: { half: 0.7 },
    battleZoom: 3,
    views: {
      down: { rows: down, walk: downWalk, neck: 17, waist: 27, lightSide: 1, lamp: [19, 32] },
      side: { rows: side, walk: sideWalk, walkB: sideWalkB, neck: 17, waist: 27, lightSide: 1, lamp: [17, 33] },
      up: { rows: up, walk: upWalk, neck: 17, waist: 27, lightSide: -1, lamp: [4, 32] },
      battle: { rows: battle, neck: 17, waist: 27, lightSide: -1, anchor: [17, 46] },
    },
  };
})(window);
