#!/usr/bin/env node
// English voice texts (owner 2026-10-10: an English voice version) → design/voice/en_lines.csv
//
//   node tools/voice_en_lines.js            (re)write design/voice/en_lines.csv for the ids of design/voice/en_scope.txt
//   node tools/voice_en_lines.js --check    only check (exit 1 on a problem); writes nothing
//
// Columns: id, speaker, kind, source, en_text, direction, ja_text
//   en_text    what the English actor says (tools/voice_tts.js --lang en reads it)
//   source     i18n:<key>#<page>  = the game's own English localization (v2/src/i18n/en), regenerated by this tool
//              written            = a short battle shout without an i18n key (companions b_<char>_<kind>_<n> and the hero
//                                   v_hero_<g>_<kind>_<n>); kept as it is in the CSV (edit the CSV by hand to change one)
//   direction  the acting note (English, from casting.json / story_v2_lines.csv / battle_lines.csv / boss_lines.csv;
//              notes about Japanese words are rewritten in DIRECTION_EN below)
//   ja_text    the Japanese line the Japanese voice says (for review)
// How a story line finds its English text: the voice id in v2/src (ev.say / caption … R.T('key') … voice: 'id' or
// voice: [ids] = one id per page) gives the key and page; ids that only sit in a list constant (P2_VOICE, SONG_VOICE …)
// are found by their Japanese text in the ja table. Boss lines use bossVoice.<id>.
// Spoken form: no line breaks, no ♪, "…" → "...", ALL-CAPS subtitles (the mist beast, the orrery) in normal case, and
// the hero's name left out exactly as the Japanese voice leaves it out ({hero} is typed by the player; the voice skips it).
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const V2 = path.join(ROOT, 'v2');
const CSV = path.join(ROOT, 'design', 'voice', 'en_lines.csv');
const SCOPE = path.join(ROOT, 'design', 'voice', 'en_scope.txt');
const COLS = ['id', 'speaker', 'kind', 'source', 'en_text', 'direction', 'ja_text'];
const CJK = /[぀-ヿ㐀-䶿一-鿿＀-￯]/;

// acting notes that talk about Japanese words → English
const DIRECTION_EN = {
  v_berna_roa_02: 'Tearful pride, emotional homecoming, trembling warm pace, rich choked volume.',
  v_berna_depart_02: 'warm farewell; after "take care" she starts to say the apprentice\'s name and cannot find it: the line trails off unfinished, a tiny stall',
  v_berna_intro_01: 'after hearing the new apprentice\'s name: a short, clear, affirmative "yes" (not a hesitant hmm), then warm fond approval like a grandmother, a small smile in the voice',
};

function parseCsv(txt) {
  const rows = [];
  let row = [], cur = '', q = false;
  const s = txt.replace(/^﻿/, '');
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (q) { if (c === '"' && s[i + 1] === '"') { cur += '"'; i++; } else if (c === '"') q = false; else cur += c; continue; }
    if (c === '"') q = true;
    else if (c === ',') { row.push(cur); cur = ''; } else if (c === '\n' || c === '\r') {
      if (c === '\r' && s[i + 1] === '\n') i++;
      row.push(cur); cur = '';
      if (row.length > 1 || row[0] !== '') rows.push(row);
      row = [];
    } else cur += c;
  }
  if (cur !== '' || row.length) { row.push(cur); rows.push(row); }
  const head = rows.shift() || [];
  return rows.map((r) => Object.fromEntries(head.map((h, i) => [h, r[i] == null ? '' : r[i]])));
}
const cell = (v) => { const s = String(v == null ? '' : v); return /[",\n\r]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s; };
function toCsv(rows) { return [COLS.join(','), ...rows.map((r) => COLS.map((c) => cell(r[c])).join(','))].join('\n') + '\n'; }
function loadRows(file) { return fs.existsSync(file || CSV) ? parseCsv(fs.readFileSync(file || CSV, 'utf8')) : []; }

// ------------------------------------------------------------------ spoken English
const norm = (s) => String(s).replace(/\\n/g, '').replace(/[\s「」『』♪　]/g, '');
/** subtitle text → what the actor says */
function spokenEn(s) {
  let t = String(s).replace(/♪/g, '').replace(/…/g, '...').replace(/[‘’]/g, "'").replace(/[“”]/g, '"');
  t = t.replace(/\s*\n\s*/g, ' ').replace(/\s+/g, ' ').trim();
  t = t.replace(/\s*--\s*/g, ' — ').replace(/ — \.\.\./g, ' —...');   // the subtitle's "--" is a dash (a pause)
  t = t.replace(/,$/, '...');   // a line that breaks off ("...Off you go,") trails off
  // floor numbers of the Great Archive ("on 3F") as said aloud
  const ORD = ['', 'first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh', 'eighth', 'ninth'];
  t = t.replace(/\bon ([1-9])F\b/g, (m, d) => `on the ${ORD[+d]} floor`).replace(/\b([1-9])F\b/g, (m, d) => `the ${ORD[+d]} floor`);
  // ALL-CAPS subtitles (a monster's broken voice): normal case so the actor does not spell or shout every word
  const letters = t.replace(/[^A-Za-z]/g, '');
  if (letters.length >= 4 && letters === letters.toUpperCase()) {
    t = t.toLowerCase().replace(/^([^a-z]*)([a-z])/, (m, a, b) => a + b.toUpperCase())
      .replace(/([^.]\.|[!?])(\s+)([a-z])/g, (m, a, s2, b) => a + s2 + b.toUpperCase())
      .replace(/\bi\b/g, 'I');
  }
  return t;
}
/** leave the hero's name out, as the Japanese voice does ("{hero}! Welcome back." → "Welcome back.") */
function dropHero(t) {
  let s = t;
  // a leading vocative: "{hero}, ", "{hero}! ", "Ah, {hero}! "
  s = s.replace(/^(?:[A-Z][a-z]*, )?\{hero\}[.!?,]*\s*/, '');
  // inside: ", {hero}" / " {hero}," (e.g. "Thank you, {hero}.")
  s = s.replace(/,\s*\{hero\}(?=[.!?,])/g, '').replace(/\{hero\},\s*/g, '').replace(/\s*\{hero\}/g, '');
  s = s.replace(/^\s*([a-z])/, (m, c) => c.toUpperCase());
  return s.trim();
}

// ------------------------------------------------------------------ where each voice id plays in v2
function walk(d) { return fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)])); }
/** voice id → [{key, page, pages, file}] from `R.T('key') … voice: 'id' | voice: [ids]` on one source line */
function sourceUses() {
  const out = {};
  for (const f of walk(path.join(V2, 'src')).filter((x) => x.endsWith('.js') && !/[\\/]i18n[\\/]/.test(x))) {
    const lines = fs.readFileSync(f, 'utf8').split('\n');
    for (const ln of lines) {
      if (/^\s*\/\//.test(ln)) continue;
      const vm = /voice:\s*(\[[^\]]*\]|'(v_[a-z0-9_]+)')/.exec(ln);
      if (!vm) continue;
      const ids = vm[2] ? [vm[2]] : [...vm[1].matchAll(/'(v_[a-z0-9_]+)'/g)].map((m) => m[1]);
      const km = /R\.T\('([^']+)'/.exec(ln.slice(0, vm.index));
      if (!km) continue;
      ids.forEach((id, i) => (out[id] = out[id] || []).push({ key: km[1], page: vm[2] ? null : i, pages: ids.length, file: path.relative(ROOT, f) }));
    }
  }
  return out;
}

// ------------------------------------------------------------------ build the rows
function derive() {
  const { readTables } = require(path.join(V2, 'tools', 'i18n_audit.js'));
  const { T } = readTables();
  const VT = require('./voice_tts');
  const C = VT.loadCasting();
  const all = VT.allLines(C);
  const byId = Object.fromEntries(all.map((l) => [l.id, l]));
  const scope = fs.readFileSync(SCOPE, 'utf8').split(/\s+/).filter(Boolean);
  const prev = Object.fromEntries(loadRows().map((r) => [r.id, r]));
  const uses = sourceUses();
  const ents = [];
  for (const [k, v] of Object.entries(T.ja)) [].concat(v).forEach((s, i) => ents.push({ k, i, arr: Array.isArray(v), n: norm(s) }));
  const page = (key, i, lang) => { const v = T[lang][key]; return Array.isArray(v) ? v[i == null ? 0 : i] : i ? undefined : v; };
  const rows = [], problems = [], notes = [];
  for (const id of scope) {
    const l = byId[id];
    if (!l) { problems.push(`${id}: not a voice line of tools/voice_tts.js`); continue; }
    const kind = l.hero ? l.kind : l.battle ? l.kind : l.bossv ? l.kind : l.story2 || 'story';
    const speaker = l.hero ? 'hero_' + l.hero : l.battle ? 'b_' + l.battle : l.bossv ? 'boss_' + l.bossv : l.speaker;
    const direction = DIRECTION_EN[id] || l.direction || '';
    const ja = VT.spoken(l.text);
    const row = { id, speaker, kind, source: '', en_text: '', direction, ja_text: ja };
    if (l.hero || l.battle) {
      const p = prev[id];
      if (!p || p.source !== 'written' || !p.en_text) problems.push(`${id}: battle shout has no written English text in ${path.basename(CSV)}`);
      else { row.source = 'written'; row.en_text = p.en_text; }
      rows.push(row);
      continue;
    }
    let key = null, pg = null;
    if (l.bossv) { key = 'bossVoice.' + id; if (T.en[key] == null) problems.push(`${id}: no ${key} in v2/src/i18n/en`); }
    else {
      let u = uses[id] || [];
      // more than one place (a caption and a lore entry): the ones whose Japanese is the recorded line
      const same = (x) => { const v = page(x.key, x.page, 'ja'); return v != null && (norm(v) === norm(l.text) || norm(v).includes(norm(l.text))); };
      if (u.length > 1 && u.some(same)) u = u.filter(same);
      const keys = [...new Set(u.map((x) => spokenEn(page(x.key, x.page, 'en') || x.key)))];
      if (keys.length > 1) problems.push(`${id}: plays with more than one English text: ${u.map((x) => x.key + '#' + x.page).join(' ')}`);
      if (u.length) {
        key = u[0].key; pg = u[0].page;
        if (u[0].pages > 1) {
          const nj = [].concat(T.ja[key] || []).length, ne = [].concat(T.en[key] || []).length;
          if (nj !== u[0].pages || ne !== u[0].pages) problems.push(`${id}: ${key} has ${nj} ja / ${ne} en pages for ${u[0].pages} voices`);
        } else if (Array.isArray(T.ja[key])) {
          // one voice on a say with pages: the page whose Japanese is the line
          const i = T.ja[key].findIndex((s) => norm(s) === norm(l.text) || norm(s).includes(norm(l.text)));
          pg = i < 0 ? 0 : i;
        }
        const jt = page(key, pg, 'ja');
        if (jt == null) problems.push(`${id}: ${key}#${pg} has no Japanese text`);
        else if (norm(jt) !== norm(l.text) && !norm(jt).includes(norm(l.text))) notes.push(`${id}: the v2 text changed since the Japanese recording ("${norm(l.text)}" → "${norm(jt)}"); English follows v2`);
      } else {
        // only in a list constant: find the line by its Japanese text
        const n = norm(l.text);
        let c = ents.filter((e) => e.n === n);
        if (!c.length) c = ents.filter((e) => e.n.includes(n));
        const ens = [...new Set(c.map((e) => spokenEn(page(e.k, e.arr ? e.i : null, 'en') || '')))];
        if (!c.length) problems.push(`${id}: Japanese text not found in v2/src/i18n/ja (${n})`);
        else if (ens.length > 1) problems.push(`${id}: Japanese text matches keys with different English: ${c.map((e) => e.k).join(' ')}`);
        else { key = c[0].k; pg = c[0].arr ? c[0].i : null; }
      }
    }
    if (key) {
      const src = page(key, pg, 'en');
      if (src == null) problems.push(`${id}: no English for ${key}${pg != null ? '#' + pg : ''}`);
      else {
        let en = spokenEn(src);
        const jaPage = page(key, pg, 'ja') || '';
        if (/\{hero\}/.test(en)) {
          if (/\{hero\}/.test(l.text)) problems.push(`${id}: the Japanese voice says {hero}?`);
          if (/\{hero\}/.test(jaPage) || !/\{hero\}/.test(l.text)) en = dropHero(en);
        }
        row.source = `i18n:${key}#${pg == null ? 0 : pg}`;
        row.en_text = en;
      }
    }
    rows.push(row);
  }
  for (const r of rows) {
    if (!r.en_text) continue;
    if (/[{}<>[\]]/.test(r.en_text)) problems.push(`${r.id}: markup left in "${r.en_text}"`);
    if (CJK.test(r.en_text)) problems.push(`${r.id}: Japanese characters in "${r.en_text}"`);
    if (CJK.test(r.direction)) problems.push(`${r.id}: Japanese characters in the direction (add it to DIRECTION_EN)`);
  }
  return { rows, problems, notes };
}

function main(argv) {
  const { rows, problems, notes } = derive();
  for (const n of notes) console.log('  · ' + n);
  for (const p of problems) console.log('  ✗ ' + p);
  const by = {};
  for (const r of rows) by[r.source.split(':')[0] || 'missing'] = (by[r.source.split(':')[0] || 'missing'] || 0) + 1;
  if (argv.includes('--check')) {
    const cur = Object.fromEntries(loadRows().map((r) => [r.id, r]));
    const drift = rows.filter((r) => !cur[r.id] || COLS.some((c) => (cur[r.id][c] || '') !== (r[c] || '')));
    for (const r of drift.slice(0, 20)) console.log(`  ✗ ${r.id}: ${path.basename(CSV)} is not up to date (run node tools/voice_en_lines.js)`);
    console.log(`[voice_en_lines] ${rows.length} lines (${Object.entries(by).map(([k, v]) => k + ' ' + v).join(', ')}), ${problems.length} problem(s), ${drift.length} out of date`);
    return problems.length || drift.length ? 1 : 0;
  }
  fs.writeFileSync(CSV, toCsv(rows));
  console.log(`[voice_en_lines] ${path.relative(ROOT, CSV)}: ${rows.length} lines (${Object.entries(by).map(([k, v]) => k + ' ' + v).join(', ')}), ${problems.length} problem(s)`);
  return problems.length ? 1 : 0;
}

module.exports = { parseCsv, toCsv, loadRows, spokenEn, dropHero, derive, CSV, COLS };
if (require.main === module) process.exitCode = main(process.argv.slice(2));
