#!/usr/bin/env node
// Voice texts of the dubbed versions (owner 2026-10-10: English; later the same day Mandarin and Korean)
//   → design/voice/en_lines.csv, zh_lines.csv, ko_lines.csv
//
//   node tools/voice_en_lines.js [--lang en|zh|ko]          (re)write design/voice/<lang>_lines.csv for the ids of
//                                                          design/voice/voice_scope.txt (553 ids; en_scope.txt = the first 537)
//   node tools/voice_en_lines.js --check [--lang zh]        only check (exit 1 on a problem); writes nothing
//   zh = Mandarin: the text of v2/src/i18n/zh-Hans (one set for the game languages zh-Hans and zh-Hant); ko = v2/src/i18n/ko.
//
// Columns: id, speaker, kind, source, <lang>_text, direction, ja_text   (zh / ko also: en_text, the English line the
//          written text follows)
//   <lang>_text what the actor says (tools/voice_tts.js --lang <lang> reads it)
//   source     i18n:<key>#<page>  = the game's own localization (v2/src/i18n/<lang>), regenerated by this tool
//              written            = a short battle shout without an i18n key (companions b_<char>_<kind>_<n> and the hero
//                                   v_hero_<g>_<kind>_<n>); kept as it is in the CSV (edit the CSV by hand to change one)
//              reuse              = zh / ko only: a pure cry (design/voice/cry_reuse.txt); no text, no recording: the game
//                                   plays the Japanese file in every language
//   direction  the acting note (English, from casting.json / story_v2_lines.csv / battle_lines.csv / boss_lines.csv;
//              notes about Japanese words are rewritten in DIRECTION_EN below)
//   ja_text    the Japanese line the Japanese voice says (for review)
// How a story line finds its English text: the voice id in v2/src (ev.say / caption … R.T('key') … voice: 'id' or
// voice: [ids] = one id per page) gives the key and page; ids that only sit in a list constant (P2_VOICE, SONG_VOICE …)
// are found by their Japanese text in the ja table. Boss lines use bossVoice.<id>.
// Spoken form: no line breaks, no ♪, "…" → "...", ALL-CAPS subtitles (the mist beast, the orrery) in normal case, and
// the hero's name left out exactly as the Japanese voice leaves it out ({hero} is typed by the player; the voice skips it).
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const V2 = path.join(ROOT, 'v2');
const DIR = path.join(ROOT, 'design', 'voice');
const SCOPE = path.join(DIR, 'voice_scope.txt');   // the 553 lines of the dubbed versions (en_scope.txt = the first 537)
const CRY = path.join(DIR, 'cry_reuse.txt');       // zh / ko: pure cries, the Japanese file is played
const COLS = ['id', 'speaker', 'kind', 'source', 'en_text', 'direction', 'ja_text'];
const CJK = /[぀-ヿ㐀-䶿一-鿿＀-￯]/;
const KANA = /[぀-ヿ]/;
/** per version: i18n table of v2/src/i18n, CSV file, text column, columns */
const LANGS = {
  en: { table: 'en', csv: path.join(DIR, 'en_lines.csv'), col: 'en_text', cols: COLS },
  zh: { table: 'zh-Hans', csv: path.join(DIR, 'zh_lines.csv'), col: 'zh_text', cols: ['id', 'speaker', 'kind', 'source', 'zh_text', 'direction', 'ja_text', 'en_text'] },
  ko: { table: 'ko', csv: path.join(DIR, 'ko_lines.csv'), col: 'ko_text', cols: ['id', 'speaker', 'kind', 'source', 'ko_text', 'direction', 'ja_text', 'en_text'] },
};
const CSV = LANGS.en.csv;
/** the ids of a list file (one per line; blank lines and # comments ignored) */
function readList(file) { return fs.existsSync(file) ? fs.readFileSync(file, 'utf8').split(/\r?\n/).map((x) => x.replace(/#.*/, '').trim()).filter(Boolean) : []; }

// acting notes that talk about Japanese words → English
const DIRECTION_EN = {
  v_berna_roa_02: 'Tearful pride, emotional homecoming, trembling warm pace, rich choked volume.',
  v_berna_depart_02: 'warm farewell; after "take care" she starts to say the apprentice\'s name and cannot find it: the line trails off unfinished, a tiny stall',
  v_berna_intro_01: 'after hearing the new apprentice\'s name: a short, clear, affirmative "yes" (not a hesitant hmm), then warm fond approval like a grandmother, a small smile in the voice',
};

function parseCsv(txt) {
  const rows = [];
  let row = [], cur = '', q = false;
  const s = txt.replace(/^﻿/, '');
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (q) { if (c === '"' && s[i + 1] === '"') { cur += '"'; i++; } else if (c === '"') q = false; else cur += c; continue; }
    if (c === '"') q = true;
    else if (c === ',') { row.push(cur); cur = ''; } else if (c === '\n' || c === '\r') {
      if (c === '\r' && s[i + 1] === '\n') i++;
      row.push(cur); cur = '';
      if (row.length > 1 || row[0] !== '') rows.push(row);
      row = [];
    } else cur += c;
  }
  if (cur !== '' || row.length) { row.push(cur); rows.push(row); }
  const head = rows.shift() || [];
  return rows.map((r) => Object.fromEntries(head.map((h, i) => [h, r[i] == null ? '' : r[i]])));
}
const cell = (v) => { const s = String(v == null ? '' : v); return /[",\n\r]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s; };
function toCsv(rows, cols) { cols = cols || COLS; return [cols.join(','), ...rows.map((r) => cols.map((c) => cell(r[c])).join(','))].join('\n') + '\n'; }
function loadRows(file) { return fs.existsSync(file || CSV) ? parseCsv(fs.readFileSync(file || CSV, 'utf8')) : []; }

// ------------------------------------------------------------------ spoken English
const norm = (s) => String(s).replace(/\\n/g, '').replace(/[\s「」『』♪　]/g, '');
/** subtitle text → what the actor says */
function spokenEn(s) {
  let t = String(s).replace(/♪/g, '').replace(/…/g, '...').replace(/[‘’]/g, "'").replace(/[“”]/g, '"');
  t = t.replace(/\s*\n\s*/g, ' ').replace(/\s+/g, ' ').trim();
  t = t.replace(/\s*--\s*/g, ' — ').replace(/ — \.\.\./g, ' —...');   // the subtitle's "--" is a dash (a pause)
  t = t.replace(/,$/, '...');   // a line that breaks off ("...Off you go,") trails off
  // floor numbers of the Great Archive ("on 3F") as said aloud
  const ORD = ['', 'first', 'second', 'third', 'fourth', 'fifth', 'sixth', 'seventh', 'eighth', 'ninth'];
  t = t.replace(/\bon ([1-9])F\b/g, (m, d) => `on the ${ORD[+d]} floor`).replace(/\b([1-9])F\b/g, (m, d) => `the ${ORD[+d]} floor`);
  // ALL-CAPS subtitles (a monster's broken voice): normal case so the actor does not spell or shout every word
  const letters = t.replace(/[^A-Za-z]/g, '');
  if (letters.length >= 4 && letters === letters.toUpperCase()) {
    t = t.toLowerCase().replace(/^([^a-z]*)([a-z])/, (m, a, b) => a + b.toUpperCase())
      .replace(/([^.]\.|[!?])(\s+)([a-z])/g, (m, a, s2, b) => a + s2 + b.toUpperCase())
      .replace(/\bi\b/g, 'I');
  }
  return t;
}
/** leave the hero's name out, as the Japanese voice does ("{hero}! Welcome back." → "Welcome back.") */
function dropHero(t) {
  let s = t;
  // a leading vocative: "{hero}, ", "{hero}! ", "Ah, {hero}! "
  s = s.replace(/^(?:[A-Z][a-z]*, )?\{hero\}[.!?,]*\s*/, '');
  // inside: ", {hero}" / " {hero}," (e.g. "Thank you, {hero}.")
  s = s.replace(/,\s*\{hero\}(?=[.!?,])/g, '').replace(/\{hero\},\s*/g, '').replace(/\s*\{hero\}/g, '');
  s = s.replace(/^\s*([a-z])/, (m, c) => c.toUpperCase());
  return s.trim();
}

// ------------------------------------------------------------------ where each voice id plays in v2
function walk(d) { return fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)])); }
/** voice id → [{key, page, pages, file}] from `R.T('key') … voice: 'id' | voice: [ids]` on one source line */
function sourceUses() {
  const out = {};
  for (const f of walk(path.join(V2, 'src')).filter((x) => x.endsWith('.js') && !/[\\/]i18n[\\/]/.test(x))) {
    const lines = fs.readFileSync(f, 'utf8').split('\n');
    for (const ln of lines) {
      if (/^\s*\/\//.test(ln)) continue;
      const vm = /voice:\s*(\[[^\]]*\]|'(v_[a-z0-9_]+)')/.exec(ln);
      if (!vm) continue;
      const ids = vm[2] ? [vm[2]] : [...vm[1].matchAll(/'(v_[a-z0-9_]+)'/g)].map((m) => m[1]);
      const km = /R\.T\('([^']+)'/.exec(ln.slice(0, vm.index));
      if (!km) continue;
      ids.forEach((id, i) => (out[id] = out[id] || []).push({ key: km[1], page: vm[2] ? null : i, pages: ids.length, file: path.relative(ROOT, f) }));
    }
  }
  return out;
}

// ------------------------------------------------------------------ spoken Mandarin / Korean
/** numbers as said aloud: Chinese 1-99 in hanzi ("3层" → "三层"), Korean 1-999 as Sino-Korean ("20년" → "이십 년", "3층" → "삼 층") */
function zhNum(n) {
  const d = '零一二三四五六七八九';
  if (n < 10) return d[n];
  if (n < 20) return '十' + (n % 10 ? d[n % 10] : '');
  if (n < 100) return d[Math.floor(n / 10)] + '十' + (n % 10 ? d[n % 10] : '');
  return String(n);
}
function koSino(n) {
  const d = ['', '일', '이', '삼', '사', '오', '육', '칠', '팔', '구'];
  if (n >= 1000 || n < 1) return String(n);
  const h = Math.floor(n / 100), t = Math.floor((n % 100) / 10), o = n % 10;
  return (h ? (h > 1 ? d[h] : '') + '백' : '') + (t ? (t > 1 ? d[t] : '') + '십' : '') + d[o];
}
/** subtitle text → what the Mandarin actor says: no ♪, no line breaks (Chinese has no spaces), "..." → "……", "--" → "——";
 *  a line that breaks off with a comma trails off ("……") */
function spokenZh(s) {
  let t = String(s).replace(/♪/g, '').replace(/\.{3,}/g, '……').replace(/…+/g, '……').replace(/[“”]/g, '"').replace(/[‘’]/g, "'");
  t = t.replace(/\s*\n\s*/g, (m, o, all) => (/[A-Za-z0-9]$/.test(all.slice(0, o)) && /^[A-Za-z0-9]/.test(all.slice(o + m.length)) ? ' ' : ''));
  t = t.replace(/\s*--\s*/g, '——').replace(/[ 　]+/g, ' ').trim();
  t = t.replace(/(\d+)(?=[层年个盏])/g, (m, n) => zhNum(+n)).replace(/[，,]$/, '……');
  return t;
}
/** … Korean: line breaks become spaces, "…" → "...", "--" → "—"; digits before 년 / 층 are said as Sino-Korean numbers */
function spokenKo(s) {
  let t = String(s).replace(/♪/g, '').replace(/…+/g, '...').replace(/\.{3,}/g, '...').replace(/[“”]/g, '"').replace(/[‘’]/g, "'");
  t = t.replace(/\s*\n\s*/g, ' ').replace(/\s*--\s*/g, ' — ').replace(/\s+/g, ' ').trim();
  t = t.replace(/(\d+)(년|층)/g, (m, n, u) => koSino(+n) + (u === '층' ? ' 층' : ' 년')).replace(/,$/, '...');
  return t;
}
const SPOKEN = { en: (s) => spokenEn(s), zh: spokenZh, ko: spokenKo };
/** leave the hero's name out, as the Japanese voice does. Chinese: "{hero}，欢迎回来。" → "欢迎回来。"; Korean: "{hero}야, ..." → "..." */
function dropHeroCjk(t, lang) {
  let s = t;
  if (lang === 'zh') {
    s = s.replace(/^(?:[^，。！？{]{0,6}[，,])?\{hero\}[，,。！？!?、]*\s*/, '');                 // a leading vocative ("啊，{hero}！")
    s = s.replace(/[，,、]\s*\{hero\}(?=[。！？!?，,…])/g, '').replace(/\{hero\}[，,、]\s*/g, '').replace(/\{hero\}/g, '');
    s = s.replace(/^[，,、！？!?。\s]+/, '');
  } else {
    s = s.replace(/^(?:[^,.!?{]{0,8}[,，]\s*)?\{hero\}(?:님|씨|야|아|이여|여)?[,，.!?…]*\s*/, '');   // a leading vocative ("{hero}, ...", "{hero}야! ...")
    s = s.replace(/,\s*\{hero\}(?:님|씨|야|아)?(?=[.!?,…])/g, '').replace(/\{hero\}(?:님|씨|야|아)?,\s*/g, '');
    s = s.replace(/\{hero\}(?:님|씨|야|아)?/g, '');
    s = s.replace(/^[,，.!?\s]+/, '');
  }
  return s.replace(/\s{2,}/g, ' ').trim();
}

// ------------------------------------------------------------------ build the rows
function derive(lang) {
  lang = lang || 'en';
  const L = LANGS[lang];
  if (!L) throw new Error(`unknown --lang ${lang} (en | zh | ko)`);
  const sp = SPOKEN[lang];
  const { readTables } = require(path.join(V2, 'tools', 'i18n_audit.js'));
  const { T } = readTables();
  const VT = require('./voice_tts');
  const C = VT.loadCasting();
  const all = VT.allLines(C);
  const byId = Object.fromEntries(all.map((l) => [l.id, l]));
  const scope = readList(SCOPE);
  const cry = new Set(lang === 'en' ? [] : readList(CRY));
  const prev = Object.fromEntries(loadRows(L.csv).map((r) => [r.id, r]));
  const enRows = lang === 'en' ? {} : Object.fromEntries(loadRows(LANGS.en.csv).map((r) => [r.id, r]));
  const uses = sourceUses();
  const ents = [];
  for (const [k, v] of Object.entries(T.ja)) [].concat(v).forEach((s, i) => ents.push({ k, i, arr: Array.isArray(v), n: norm(s) }));
  const page = (key, i, lg) => { const v = T[lg][key]; return Array.isArray(v) ? v[i == null ? 0 : i] : i ? undefined : v; };
  const tg = L.table;   // the table of this version ('en' | 'zh-Hans' | 'ko')
  const rows = [], problems = [], notes = [];
  const col = L.col;
  for (const id of scope) {
    const l = byId[id];
    if (!l) { problems.push(`${id}: not a voice line of tools/voice_tts.js`); continue; }
    const kind = l.hero ? l.kind : l.battle ? l.kind : l.bossv ? l.kind : l.story2 || 'story';
    const speaker = l.hero ? 'hero_' + l.hero : l.battle ? 'b_' + l.battle : l.bossv ? 'boss_' + l.bossv : l.speaker;
    const direction = DIRECTION_EN[id] || l.direction || '';
    const ja = VT.spoken(l.text);
    const row = { id, speaker, kind, source: '', [col]: '', direction, ja_text: ja };
    if (lang !== 'en') row.en_text = (enRows[id] || {}).en_text || '';
    if (cry.has(id)) { row.source = 'reuse'; rows.push(row); continue; }
    if (l.hero || l.battle) {
      const p = prev[id];
      if (!p || p.source !== 'written' || !p[col]) problems.push(`${id}: battle shout has no written ${lang} text in ${path.basename(L.csv)}`);
      else { row.source = 'written'; row[col] = p[col]; }
      rows.push(row);
      continue;
    }
    let key = null, pg = null;
    if (l.bossv) { key = 'bossVoice.' + id; if (T[tg][key] == null) problems.push(`${id}: no ${key} in v2/src/i18n/${tg}`); }
    else {
      let u = uses[id] || [];
      // more than one place (a caption and a lore entry): the ones whose Japanese is the recorded line
      const same = (x) => { const v = page(x.key, x.page, 'ja'); return v != null && (norm(v) === norm(l.text) || norm(v).includes(norm(l.text))); };
      if (u.length > 1 && u.some(same)) u = u.filter(same);
      const keys = [...new Set(u.map((x) => sp(page(x.key, x.page, tg) || x.key)))];
      if (keys.length > 1) problems.push(`${id}: plays with more than one ${lang} text: ${u.map((x) => x.key + '#' + x.page).join(' ')}`);
      if (u.length) {
        key = u[0].key; pg = u[0].page;
        if (u[0].pages > 1) {
          const nj = [].concat(T.ja[key] || []).length, ne = [].concat(T[tg][key] || []).length;
          if (nj !== u[0].pages || ne !== u[0].pages) problems.push(`${id}: ${key} has ${nj} ja / ${ne} ${tg} pages for ${u[0].pages} voices`);
        } else if (Array.isArray(T.ja[key])) {
          // one voice on a say with pages: the page whose Japanese is the line
          const i = T.ja[key].findIndex((s) => norm(s) === norm(l.text) || norm(s).includes(norm(l.text)));
          pg = i < 0 ? 0 : i;
        }
        const jt = page(key, pg, 'ja');
        if (jt == null) problems.push(`${id}: ${key}#${pg} has no Japanese text`);
        else if (norm(jt) !== norm(l.text) && !norm(jt).includes(norm(l.text))) notes.push(`${id}: the v2 text changed since the Japanese recording ("${norm(l.text)}" → "${norm(jt)}"); ${lang} follows v2`);
      } else {
        // only in a list constant: find the line by its Japanese text
        const n = norm(l.text);
        let c = ents.filter((e) => e.n === n);
        if (!c.length) c = ents.filter((e) => e.n.includes(n));
        const ens = [...new Set(c.map((e) => sp(page(e.k, e.arr ? e.i : null, tg) || '')))];
        if (!c.length) problems.push(`${id}: Japanese text not found in v2/src/i18n/ja (${n})`);
        else if (ens.length > 1) problems.push(`${id}: Japanese text matches keys with different ${lang} text: ${c.map((e) => e.k).join(' ')}`);
        else { key = c[0].k; pg = c[0].arr ? c[0].i : null; }
      }
    }
    if (key) {
      const src = page(key, pg, tg);
      if (src == null) problems.push(`${id}: no ${tg} text for ${key}${pg != null ? '#' + pg : ''}`);
      else {
        let tx = sp(src);
        const jaPage = page(key, pg, 'ja') || '';
        if (/\{hero\}/.test(tx)) {
          if (/\{hero\}/.test(l.text)) problems.push(`${id}: the Japanese voice says {hero}?`);
          if (/\{hero\}/.test(jaPage) || !/\{hero\}/.test(l.text)) tx = lang === 'en' ? dropHero(tx) : dropHeroCjk(tx, lang);
        }
        row.source = `i18n:${key}#${pg == null ? 0 : pg}`;
        row[col] = tx;
      }
    }
    rows.push(row);
  }
  for (const r of rows) {
    if (!r[col]) continue;
    if (/[{}<>[\]]/.test(r[col])) problems.push(`${r.id}: markup left in "${r[col]}"`);
    if (lang === 'en' ? CJK.test(r[col]) : KANA.test(r[col])) problems.push(`${r.id}: ${lang === 'en' ? 'Japanese characters' : 'kana'} in "${r[col]}"`);
    if (lang === 'ko' && /[一-鿿]/.test(r[col])) problems.push(`${r.id}: hanja/kanji in the Korean text "${r[col]}"`);
    if (CJK.test(r.direction)) problems.push(`${r.id}: Japanese characters in the direction (add it to DIRECTION_EN)`);
  }
  return { rows, problems, notes, lang, cols: L.cols, csv: L.csv };
}

function main(argv) {
  const li = argv.indexOf('--lang');
  const lang = li >= 0 ? argv[li + 1] : 'en';
  const { rows, problems, notes, cols, csv } = derive(lang);
  for (const n of notes) console.log('  · ' + n);
  for (const p of problems) console.log('  ✗ ' + p);
  const by = {};
  for (const r of rows) by[r.source.split(':')[0] || 'missing'] = (by[r.source.split(':')[0] || 'missing'] || 0) + 1;
  if (argv.includes('--check')) {
    const cur = Object.fromEntries(loadRows(csv).map((r) => [r.id, r]));
    const drift = rows.filter((r) => !cur[r.id] || cols.some((c) => (cur[r.id][c] || '') !== (r[c] || '')));
    for (const r of drift.slice(0, 20)) console.log(`  ✗ ${r.id}: ${path.basename(csv)} is not up to date (run node tools/voice_en_lines.js --lang ${lang})`);
    console.log(`[voice_en_lines] ${lang}: ${rows.length} lines (${Object.entries(by).map(([k, v]) => k + ' ' + v).join(', ')}), ${problems.length} problem(s), ${drift.length} out of date`);
    return problems.length || drift.length ? 1 : 0;
  }
  fs.writeFileSync(csv, toCsv(rows, cols));
  console.log(`[voice_en_lines] ${path.relative(ROOT, csv)}: ${rows.length} lines (${Object.entries(by).map(([k, v]) => k + ' ' + v).join(', ')}), ${problems.length} problem(s)`);
  return problems.length ? 1 : 0;
}

module.exports = { parseCsv, toCsv, loadRows, spokenEn, spokenZh, spokenKo, dropHero, dropHeroCjk, derive, readList, CSV, COLS, LANGS, SCOPE, CRY };
if (require.main === module) process.exitCode = main(process.argv.slice(2));
