// 生成物（design/art_ref/gen/env/_tools/under/field_isles/ の areas_isles.py → fit.py → tomap.py）。手で直さない: 配置は areas_isles.py、当たりは fit.py で作り直す。
// エリア i_cape「ネレイの岬道」（二つの海にはさまれた細い尾根、48×40）。エリア切り替えのフィールド（maps/field_00_kit.js、諸島の凡例は field_isles_00_kit.js）。
//   出口: w → i_cove.east, n → nerei.gate
//   絵: field/under/i_cape（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("i_cape", {
    name: R.T('map.field_isles_cape.i_cape.name'), region: "r_isles", outside: "sea",
    legend: R.FieldArea.ISLE_LEGEND, theme: 'field', bgm: 'overworld', bbg: 'isles', propSet: 'isles', propSetBase: 'harbor',
    light: R.FieldArea.ISLE_LIGHT,
    rows: [
      "~~~~~~~~~~~~~RR,,,,,..,;rr;;;RR~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~RR,,,TT..,,;;;;TRR~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~RRr,,,,..,,,rr;;,R~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~RRrT,,..,,,rr;,R~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~RRrTT,..,,bTr;,R~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~RR;r;,..,\"\"\"\"r,,~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~RR,r;,..,,\"\"\"rrR~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~RR,,,,..,,\"\"\"\",R~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~RRbT,r,,..,,\"\"r,R~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~RRTT,,,,..,,\"Xrr,R~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~RRRTTr,rT..,,,,,,,,R~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~RRRbT;;;T..,,,,,,,,R~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~RRrrrrrr;..,,,,r,TRR~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~RR,Trrr;;;..,r,,,,TrRR~~~~~~~~~~~~~~~",
      "~~~~~~~~~~RR,,TT;r;;;..;rr,,rTrRR~~~~~~~~~~~~~~~",
      "~~~~~~~~~RRr,,,;;;rT..;;;;;,,,,,R~~~~~~~~~~~~~~~",
      "~~~~~~~~RR,,\"r;;;;r;..;;;r;r,,rRR~~~~~~~~~~~~~~~",
      "~~~~~~~RR,TT,,,;r;r;..;;Xr;,,,TRR~~~~~~~~~~~~~~~",
      "~~~~~~RR,,TT,TT;;;;..;;;;;;,,,,,,R~~~~~~~~~~~~~~",
      "~~RRRRR,,,,,,,,;;;...;;;,,,T,,,,,R~~~~~~~~~~~~~~",
      "RRR,RR,,,,r,,,,;;...;;r,,,,r,rr,,R~~~~~~~~~~~~~~",
      "RR;;;,,,,,r,,,,,...T;T,rrT,,,,,,,,R~~~~~~~~~~~~~",
      ";;rrrrr,bT,;;;....TTTT,,,r,,,,,,,,R~~~~~~~~~~~~~",
      ";;;,,,,,,,......,TTTTT,,,,,,,,,,,,R~~~~~~~~~~~~~",
      "..............,TTTTTT,,,,,,,,,,,,rR~~~~~~~~~~~~~",
      "...........;;,,Tr,,,r,r,,,TT,,,,,rRR~~~~~~~~~~~~",
      ".;;;;,,,,,,rr,,,,,,,r,rT,TTTTT,r,TRR~~~~~~~~~~~~",
      ";rrrr,,,,rr,,,,Xr,,,,,rT,TTTTT,,,TRR~~~~~~~~~~~~",
      "RRRRRRR,,,,,,T,rr,,rr,,r,r,TT,,rTTRR~~~~~~~~~~~~",
      "RRRRRRRRRr,,TT,,rr,,,,,,TT,,,,,rTRR~~~~~~~~~~~~~",
      "~~~~~~~RRR,,\"\",,,,,\"\",,,,,,,,,\"\"RR~~~~~~~~~~~~~~",
      "~~~~~~~~~RR,,,,,;,,,\",,bT,,,,,,RR~~~~~~~~~~~~~~~",
      "~~~~~~~~~~RRRr,rrr;,,,,,,,,,r,,,R~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~RRRrrr;r,r\"r,,,r,,,RR~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~RRr,,,,,r,,,,,,,,R~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~RR,\"\",,,,,,\"r,,R~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~RRr,\"r,,,,,,\",,R~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~RR,r,,,,,,\"\"rR~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~RR;;;,,,,,\"\",R~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~RR;rrr,r,\",R~~~~~~~~~~~~~~~~~~~~",
    ],
    objects: [
      {"type":"examine","x":24,"y":18,"event":"isles_signal_mast"},
      {"type":"sign","x":11,"y":28,"text":R.T('map.field_isles_cape.i_cape.objects.1.text')},
      {"type":"chest","id":"i_cape_c1","x":28,"y":22,"item":"i_clear","n":2},
      {"type":"waylamp","id":"wl_i_cape_1","x":13,"y":21,"lit":true},
      {"type":"waylamp","id":"wl_i_cape_2","x":23,"y":8,"lit":true},
    ],
    npcs: [

    ],
    spawns: {"west":{"x":1,"y":25,"dir":"e"},"north":{"x":21,"y":1,"dir":"s"}},
    exits: [{"x":0,"y":25,"w":1,"h":2,"to":{"map":"i_cove","spawn":"east"}},{"x":21,"y":0,"w":2,"h":1,"to":{"map":"nerei","spawn":"gate"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_isles"}],
    art: {"image":"field/under/i_cape","painted":[],"overlay":"field/under/i_cape_over"},
    meta: {"sub":R.T('map.field_isles_cape.i_cape.meta.sub'),"worldRect":[660,480,48,40]},
    links: {},
  });
})(window.RPG);
