// 生成物（design/art_ref/gen/env/_tools/under/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// エリア f_hut「きこりの野」（森の手前の切り株の野、52×40）。エリア切り替えのフィールド（maps/field_00_kit.js）。
//   出口: e → f_cross.west, w → f_fern.east
//   絵: field/under/f_hut（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("f_hut", {
    name: "きこりの野", region: "r_forest", outside: "forest_dark",
    rows: [
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwwFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwFFFFFFFFFFFFFTFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwwFTT,,TTTT,TT,,TT",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFTTT;;Twww;,,,,,,,,,,,,,;",
      "FFFFFFFFTTTTTTTTTTTTTTTTTTTT;;\";;;www;T,,,,,\"w,,,,,;",
      "FFFFFFFTTTTTrTTTTTTTTTTTTTTT,;,;;;ww;;,,,,,,\",;;,,,,",
      "FFFFFFFTTTTTTTTTTTTTTTTTTTT,,TT;;;www,,,,,,;;;;;;,,,",
      "FFFFFFFFTTTTTTTTTTT,TTTTTTT,,TT;;;www,,,,,,\";\";;;;,,",
      "FFFFFFFFTTTTTTTTTT,,,T,TTT,,,,T,,,RwwR,,,,\"\"XXX,;;;;",
      "FFFFFFFFFTFFFFTTTTTT,,,,TTTT,,;;;,,www,,,,,,XXX,;;;,",
      "FFFFFFFFFFFFFFTTTTTT,,XX,,TT;;,,,,,wwww;,,,,XXX;;;;,",
      "FFFFFFFFFFFFFFTTTTT,,,,,,,,,;T;;;;;wwww;;,,,,,,;;;\"\"",
      "FFFFFFFFFFFFFFTTTr,,,,,,,,,X;XX;;;;www,;\",;,,,,;;;\"\"",
      "FFFFFFFFFFFFFFTTT,,XX,,,,,,;,XX;;;;;www,TT,,;;;;;;\",",
      "FFFFFFFFFFFFFFTT,,,,XXXXXXXX,,XX;;;;www,TT,;;,;;;,,,",
      "FFFFFFFFFFFFFFF;;X,,XXXXXXXX,,,,;;;;wwr,TT;;;;;;;;,;",
      "FFFFFFTFFFFFFFFF,,,,XXXXXXXX,,XXX;;www,,,,;;;;;;;;;;",
      "FFFFFFFFFFFFFFFF,,,,XXXXXXXXXX,,,;;www,,;;X;;;;;;;;;",
      "FFFFFFFFFFFFFFFFFFX,XXXXXXXX,,,,;;;www,,;;;;;;;;;;;;",
      "FFFFFFFFFFFFFFFFFF,,XXXX.XXX,,,;;;,www,;;;;;;;;;;;;.",
      "FFFFFFFFFFFFFTTTTTT,X,,,,,,,,\"X;;;,www..............",
      "FFFFFFFFFFFTTTTTXTT,,,;::,;........w==..............",
      "FFFFFFFFFFFTTTTTT,T,;..::..........w==,,;;;;;;;;;;;;",
      "TTTTTTTrT...................,;;;;;;===,,,,;;;;;;,,,;",
      "......................,,;,,,,,;;;;,===.;,,,;;;;;;,,,",
      "F......,.....;;;..,TT;,,,,,,,;;,;;;rwww,,,,,;;;,;,,r",
      "FFFFFFFFFFF,;;r;FFTTTT;,,,r,,,,,,;;wwww,,,,,;;;,,;;;",
      "FFFFFFFFFFF,;;;,FFTTTT;,,,,,,,,,,;,,www,,,,;;;;,,;;;",
      "FFFTTTFTTTFFF;;TTTTTTT;,,r,,T.,,,;,,www,,,;;;;;;;,;,",
      "TTTTTTTTTTFFFFFTTTTTTTT;,,,;,,.,,;;;ww,,;;;;;;;;;;,,",
      "TTTTTTTTTTFFFFFFTTTTTT;;,,T,,,,.,;;;www,;;;;;;;;;;;,",
      "FFTTTTTTTTFFFFFTTTTTTT,,T,,,,,TTw;;;ww,;;;;;;;;;;,,,",
      "FFFFFFFFFFFFFFFTTTTTTT,T,TT,,TT,;rr;ww,;;;;;\";;;,,,,",
      "FFFFFFFFFFFFFFFTTTTTTT.,,;T;,,,;;;;www;;;;;;;;;;;;;;",
      "FFFFFFFFFFFFFFFTTTTTTTTT,T,,,,,,;;;www;;;,;;;;;;;;r;",
      "FFFFFFFFFFFFFTTTTTTTTTTTT;;,,,,;;;;;ww;,;,,;;;;;;;;;",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFT,,T,,,;;;www;,,,;;;;;;;\"\"",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,;;wwTFFFTTTTT,,TT;",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwwFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwwFFFFFFFFFFFFF",
    ],
    objects: [
      {"type":"door","x":23,"y":19,"look":"none","to":{"map":"hut","spawn":"door"}},
      {"type":"examine","x":45,"y":10,"event":"world_poi_shrine"},
      {"type":"waylamp","id":"wl_forest_1","x":33,"y":20,"lit":"q_forest_fireflies_1","event":"forest_waylamp"},
      {"type":"sign","x":21,"y":21,"text":"きこりの休み小屋\n旅の人も、ひと休みを。"},
      {"type":"prop","id":"lantern","x":26,"y":20},
      {"type":"chest","id":"f_hut_c1","x":17,"y":13,"item":"i_potion","n":2},
    ],
    npcs: [

    ],
    spawns: {"east":{"x":50,"y":23,"dir":"w"},"west":{"x":1,"y":24,"dir":"e"},"hut":{"x":23,"y":20,"dir":"s"}},
    exits: [{"x":51,"y":23,"w":1,"h":2,"to":{"map":"f_cross","spawn":"west"}},{"x":0,"y":24,"w":1,"h":2,"to":{"map":"f_fern","spawn":"east"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_forest"}],
    art: {"image":"field/under/f_hut","painted":[],"overlay":"field/under/f_hut_over"},
    meta: {"sub":"森の手前の切り株の野","worldRect":[170,160,70,60]},
    links: {"hut":{"map":"f_hut","spawn":"hut"}},
  });
})(window.RPG);
