// 生成物（design/art_ref/gen/env/_tools/under/field_desert/ の areas_desert.py → fit.py → tomap.py）。手で直さない: 配置は areas_desert.py、当たりは fit.py で作り直す。
// エリア d_west「鷹の台地」（カシムの西の野、60×44）。エリア切り替えのフィールド（maps/field_00_kit.js、砂漠の凡例は field_desert_00_kit.js）。
//   出口: n → d_pass.south, e → kasim.gate_w, s → d_caravan.north, 門 → desert_hawks_1.mouth, 門 → desert_mirage.road
//   絵: field/under/d_west（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("d_west", {
    name: R.T('map.field_desert_west.d_west.name'), region: "r_desert", outside: "dune_sand",
    legend: R.FieldArea.DESERT_LEGEND, theme: 'desert', bgm: 'desert', bbg: 'desert',
    rows: [
      "uubuuuuuuuuuuuuusssssssssuuuu...uuuuuuuuuuuuuuuuuusssssXXXXX",
      "uuruuuuuuuuuuuussssssssssuuuu...uuuuuuuuuuuuuuuuussssssXXXXX",
      "uussuuuuuuuuuuussssssssssuuuu...uuuuuuuuuuuuuuurussssssXXXXX",
      "uussssruuuuusssssssssuuruuuuuu..uuuuuuuuuuuuuuuuussssssXXXXX",
      "uussssssuuuussssssssuuuuuuuuuu..uusuuuuuuuuuuuussssssssXXXXX",
      "uusssssssuusssssssssuuuuuuuuuu..ssssssuuuuuuuuussssssuuXXXXX",
      "uursssssssssrssssssssuuuuuuuuuu..sssssssuuuuTsuussssTuuXXXXX",
      "usssssRRRRRRRRRRRRRsssuuuuuuuuu..sssssssuuuuurrusssTTTuXXXXX",
      "ssssRRRRRRRRRRRRRRRRRsssuuuuuuus..ssssssuuuuuuuuusTTTTTXXXXX",
      "sssRRRRRRRRRRRRRRRRRRRsssuuuuuus...sssuuuuuuuuuuusTTTTTXXXXX",
      "ssrRRRRRRRRRRRRRRRRRRRRssuuuuuuss...sssuuuuuuuuuusTTTTTXXXXX",
      "ssRRRRRRRRRRRRRRRRRRRRRssuuuuussss...sssssuuuuussuuTTTsXXXXX",
      "rrRRRRRRRRRRRRRRRRRRRRRuuuuuuusssss...sssssssssssuuuussXXXXX",
      "srRRRRRRRRRRRRRRRRRRRRRuuuuuuussssss...ssssssssssssuurrXXXXX",
      "ssRRRRRRRRRRRRRRRRRRRRRruuuuuuussssss....ssssssssssurTTXXXXX",
      "srRRRRRRRRRRRRRRRRRRRRRruuuuuusssssssss...sssrsssrsuTTrXXXXX",
      "ssRRRRRRRRRRRRRRRRRRRRRsuuuuuussssssssss....sssssssuuTuXXXXX",
      "ssRRRRRRRRRRRRRRRRRRRRRsruusrkksssssssssus....sssssuuuuXXXXX",
      "uusRRRRRRRRRRRRRRRRRRRrskkkkkkkkkkssssuuuuu.....sssuuuuXXXXX",
      "ubsrRRRRRRRRRRRRRRRRRrskkkkkkkkkkkkksssusssss...............",
      "sssrrRRRRRRRRRRRRRRRrskkkkkkkkkkkkkkkssssssssus.........TT..",
      "ssssrRRRRRRRRRRRRRRrsskkkkkkkckkkkkkksssssssuuu..ssssu..TTT.",
      "sssssrRRRRRRRRRRRRrusskkkkkkkkkkkkkkuuuuuuusuuu..ssuussXXXXX",
      "ssssssssrRRRRRRRuuuuuuukkkkkkkkkkkkkuuuubuuuuu..ussuuusXXXXX",
      "ssrsssrsssrr:ruuuuuruuukkkkkkkkkkkkuuuuuuuuuuu..uuuuuuuXXXXX",
      "ssssssssssss::uuuuuuuuuuuburuuuuuuuuruuuuuuuuu..uuuuuuuXXXXX",
      "ssssssbssbssu:::::uuuuuruuuuuuuuusuuuuruuuuuu..uuuuuuuuXXXXX",
      "RRRRsssssssuuuuu:::::uuuuuuuuuuuuuuubuuuuuuu...uuuuuuuuXXXXX",
      "RRRRrsssssssuuuuuuu::::::uuuuuuuuuuuuuuuuuu...uuuuuuuuuXXXXX",
      "RRRRRusssssssuuuuruuuuu::::::uuuuuuuuuuuuu...uuuuuuuTTuXXXXX",
      "RRRRRuussssssuuuuuuuuuuuuuu::::::uuuuuuuu...uuuuuuTTTTTXXXXX",
      "RRRRRruussssssuuuuuuuuuuuuuuuuu:::::::::::.uuuuuusTTTTTXXXXX",
      "RRRRRRuusssssssuruuuuussssuuuuuuuuuuuu::::uuuuuussTTTTTXXXXX",
      "RRRRRRussssssssuuuuusssssssssssuuusuuu...uuuuuuuussTTTTXXXXX",
      "RRRRRrusssssssssuuuusssssssssssssssssu..uuuuuuuuuusTTTsXXXXX",
      "RRRRruussssssssssuuussssssssssssssssu..uuuuuuuuuuuuTTTsXXXXX",
      "RRRRuuuusssssssssuuussssssssrsssssss...uuuuuuuuuuuusTssXXXXX",
      "RRRuuuuusssssrsssuuussssssssssssssss..uuuuuuuuuuuusssssXXXXX",
      "Ruuuuuuuuuuuusssssussssssssssssssss..suuuuuuuuussssssssXXXXX",
      "uuuuuuuuuuuuussssssssssssssssssssss..suurussuusssssssssXXXXX",
      "uuuuusruuuuuusssssssssssssssssssss...sssuusssssssssssssXXXXX",
      "uuuuuuuuuuuuusssssssssssssssssssss..ssssuusssssssssssssXXXXX",
      "uuuuuuuuuuuuuuusssssssssssssssssss..urssssssssssssssTssXXXXX",
      "uuuruuuuuuuuubussssssssbssssssssss..ussssssssssssssssssXXXXX",
    ],
    objects: [
      {"type":"examine","x":29,"y":21,"event":"desert_mirage_empty","cond":{"not":"desert_night"}},
      {"type":"prop","id":"lantern","x":25,"y":19,"cond":"desert_night"},
      {"type":"prop","id":"lantern","x":33,"y":19,"cond":"desert_night"},
      {"type":"prop","id":"lantern","x":25,"y":23,"cond":"desert_night"},
      {"type":"prop","id":"lantern","x":33,"y":23,"cond":"desert_night"},
      {"type":"prop","id":"lantern","x":29,"y":18,"cond":"desert_night"},
      {"type":"sign","x":35,"y":24,"text":R.T('map.field_desert_west.d_west.objects.6.text')},
      {"type":"sign","x":15,"y":27,"text":R.T('map.field_desert_west.d_west.objects.7.text')},
      {"type":"sign","x":50,"y":23,"text":R.T('map.field_desert_west.d_west.objects.8.text')},
      {"type":"waylamp","id":"wl_desert_beacon_1","x":43,"y":31,"lit":"q_kasim_beacon_1","event":"desert_beacon"},
      {"type":"waylamp","id":"wl_d_west_gate_n","x":50,"y":18,"lit":true},
      {"type":"waylamp","id":"wl_d_west_gate_s","x":49,"y":24,"lit":true},
      {"type":"waylamp","id":"wl_d_west_road","x":34,"y":12,"lit":true},
      {"type":"prop","id":"bones","x":9,"y":26},
      {"type":"prop","id":"thorn_bush","x":16,"y":29},
      {"type":"prop","id":"copper_brazier","x":53,"y":19},
      {"type":"prop","id":"copper_brazier","x":53,"y":22},
    ],
    npcs: [

    ],
    spawns: {"north":{"x":30,"y":1,"dir":"s"},"kasim":{"x":58,"y":20,"dir":"w"},"south":{"x":34,"y":42,"dir":"n"},"hawks":{"x":12,"y":25,"dir":"s"},"mirage":{"x":29,"y":22,"dir":"s"}},
    exits: [{"x":30,"y":0,"w":2,"h":1,"to":{"map":"d_pass","spawn":"south"}},{"x":59,"y":20,"w":1,"h":2,"to":{"map":"kasim","spawn":"gate_w"}},{"x":34,"y":43,"w":2,"h":1,"to":{"map":"d_caravan","spawn":"north"}},{"x":12,"y":24,"w":1,"h":1,"to":{"map":"desert_hawks_1","spawn":"mouth"}},{"x":29,"y":21,"w":1,"h":1,"to":{"map":"desert_mirage","spawn":"road"},"cond":"desert_night"}],
    triggers: [{"id":"desert_ambush_1","x":39,"y":32,"w":5,"h":3,"on":"step","event":"desert_ambush_1","cond":["desert_caravan_on","!desert_ambush_1_done"]}],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_desert_caravan","cond":"desert_caravan_on"},{"rect":null,"zone":"zw_desert"}],
    art: {"image":"field/under/d_west","painted":[],"overlay":"field/under/d_west_over"},
    meta: {"sub":R.T('map.field_desert_west.d_west.meta.sub'),"worldRect":[40,400,116,70]},
    links: {"kasim":{"map":"d_west","spawn":"kasim"},"hawks":{"map":"d_west","spawn":"hawks"},"mirage":{"map":"d_west","spawn":"mirage"}},
  });
})(window.RPG);
