// 生成物（design/art_ref/gen/env/_tools/under/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// エリア f_lookout「見晴らし台」（跳ね橋と北の海、48×40）。エリア切り替えのフィールド（maps/field_00_kit.js）。
//   出口: s → f_roa.north, n → f_cross.bridge
//   絵: field/under/f_lookout（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("f_lookout", {
    name: "見晴らし台", region: "prologue", outside: "sea",
    rows: [
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~RRXXR~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~RRRR,\"T\"RRRRRRRRR",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~rRR,,\"\"\"\"\"\"\"\"\"\"\",,",
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~~~RRR\",\"\"\"T\"\"\",,\"\"\",",
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~~~RRR,,\"\"\"\"\"\"\",\",\",\"",
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~srRRR,,\"\",,,\"\",\",,,r",
      "~~~~~~~~~~~~~~~~~~~~~~==~~~\",,rRR,,,,,,\"\"\"\",,,,,",
      "~~~~~~~~~~~~~~~~~~~~cccccc\",,,rRR,,,,,,\",XX\"\",\",",
      "~~~~~~~~~~~~~~~~~~sscccccc,,,,rRR,,,,,,,:XX\"\"\"\",",
      "ssssssssrXXss~~~sss\"cccccc,,,,rRc,,,,,,::XX\"\"\"\",",
      "\"\"\"\"\"\",TT,r;sssss\"\"\"\"..,;;;;;;rRc,,,,,,::XX\"\"r,,",
      "\"\"\"\"\"\"\"\";\",;;;;\";\"\"\"\"..;;;;;;\";Rc,,,,,::\"XX,,,,,",
      "\"\"\"\"\"\"\"\"\"\"\";;;;\"\"\"\"\"\"\"..;;;\"\"\"\"Rc,,,,::,,,\",,,,,",
      "\"\"\"\"\"r\"TTT\";;;;\"\"\",\"\"\"..;;\"\"\"\"\",,R,,,::,,,,,,,,,",
      "TTTT,TTTTT\";;;;r\";,,,,..,;;\"\"\"\"rrRRRccc,,,,,,,,,",
      "TTTTTTTTTTT;;;;\"\";,,,,..,,\"\"\"\"\"r\"RRRcccRRRRRRRRR",
      "TTTTTTTTTTTT;;;;\",,,,,..,,,\"\"\",,,RRRrccRRRRRRRRR",
      "TTTTTTTTTTTTTT;\"\"\",,,,..,,\"\"\"\"\",,,rrr:\"rrrTrrrrr",
      "TTTTTTTTTTTTTTr\"\"\",,,,..,,\"\"\"\"\",,,,T::;;;;;\"\"\"\"\"",
      "TTTTTTTTTTTTTT;;r\",r,,..,,\"\"\"\",,,::::,\"\";;;;;;\"\"",
      "TTTTTTTTTTTTT;;;;;;;;,..\"\"\"\"\"\":::::,,,\"\"\"\";TTT;;",
      "TTTTTTTTTTTTT\";;;;;;\"\"..\"\"\",::::\",,,,,\"\"\"\"\"TTT;,",
      "TTTTTTTTTTTTT\";;;;;;;\"..\"\"::::\"\"\"\"\"\"\"\"\"\"\"\"\"TTT;,",
      "TTTTTTTTTTTTT;;;;;;\"\"\".::::\"\"\"\"\"\"\"\"\"\"\"\"\";;;;;;;;",
      "TTTTTTTTTTT,\";;;;;;;;..::\"\"\"\"\"\"\"\"\"\"\"\"\"\";;;\";;;;\"",
      "TTTTTTTTTTTT\"T;;;,;;;;..\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\";;T,,,\"\"",
      "TTTTTTTTTTr\"\"\",,,,;;\"\"..\"\"\"\"\"\"\"\"\"\"\"\"\"\"TTTTTT,,,\"",
      "Tr,TTT,,;;\"\"\"\"\",,;;\"\";..,,,\"\"\"TTTT\"\"\";TTTTTT,,,,",
      "\",,,,,,,;;;;;,\"\";;;;;;;..;;\"\"TTTTT;;;;rTTTTT,,,,",
      ",,,,,,,,,;;\"\",;;;;;;,;;..;,,\"TTTTT;;;;;;;;\";,,,,",
      "\",,,,,,,,;;;;;\";;;;;,,;..,,\"\"\";;;;,;,,,,;;\";,;;,",
      "\",,,,,,;;;\";;;;;\";;;\",,...\"\"\"\";;;;,,,,\"\"\"\"\";;;\"\"",
      ",\",,,,;;\"\";;;TTTT\";;;\"\"\"..\"\"\"\";;;;,,,,\"\"\"\"\"\";\"\"\"",
      "\"\"\",,,,\"\"\"\"TTTTTTT;;;\"\"\"..\"\"\"\"\";\",,,,,\"\"\"\"\"\";;\"\"",
      ",\"\",,,\"\",,,,TTTTTFF;\";,\"..\"\"\"\";;;,,,,,,\"\"\"\"\";\"\"\"",
      "FFFFFFFFFF,FFFFFFFFFFFFF..\"FFFFFFFF,,FFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFFFF",
    ],
    objects: [
      {"type":"waylamp","id":"wl_pen_lookout","x":38,"y":13,"lit":"prologue_lamp_lookout","event":"world_pen_lamp"},
      {"type":"examine","x":41,"y":11,"event":"world_poi_pen_lookout"},
      {"type":"sign","x":39,"y":17,"text":"見晴らし台\n半島の北の海を見わたす。"},
      {"type":"prop","id":"lamp_post","x":20,"y":13},
      {"type":"prop","id":"lamp_post","x":25,"y":13},
      {"type":"prop","id":"bollard","x":21,"y":10},
      {"type":"sign","x":26,"y":13,"text":"跳ね橋\n北 → 北の野"},
      {"type":"chest","id":"f_lookout_c1","x":45,"y":7,"item":"i_ether","n":1},
    ],
    npcs: [
      {"id":"bridge_guard","look":"npc_guard_2","name":"橋番","x":24,"y":11,"dir":"w","move":"still","pushable":false,"talk":"world_bridge_guard","reward":"news","key":"world_bridge_guard"},
    ],
    spawns: {"south":{"x":24,"y":38,"dir":"n"},"bridge":{"x":22,"y":1,"dir":"s"}},
    exits: [{"x":24,"y":39,"w":2,"h":1,"to":{"map":"f_roa","spawn":"north"}},{"x":22,"y":0,"w":2,"h":1,"to":{"map":"f_cross","spawn":"bridge"},"cond":"prologue_done"}],
    triggers: [],
    tilePatches: [{"cond":"!prologue_done","rect":[22,1,2,8],"rows":["~~","~~","~~","~~","~~","~~","~~","~~"]}],
    zones: [{"rect":null,"zone":"zw_peninsula"}],
    art: {"image":"field/under/f_lookout","painted":[],"overlay":"field/under/f_lookout_over","closed":"field/under/f_lookout_closed"},
    meta: {"sub":"跳ね橋と北の海","worldRect":[238,214,70,46]},
    links: {},
  });
})(window.RPG);
