// 生成物（design/art_ref/gen/env/_tools/under/field_desert/ の areas_desert.py → fit.py → tomap.py）。手で直さない: 配置は areas_desert.py、当たりは fit.py で作り直す。
// エリア d_pass「赤岩の峠」（森から砂漠へ下りる道、52×40）。エリア切り替えのフィールド（maps/field_00_kit.js、砂漠の凡例は field_desert_00_kit.js）。
//   出口: n → f_south.south, s → d_west.north, 門 → sandedge.gate, 門 → desert_rocks.mouth
//   絵: field/under/d_pass（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("d_pass", {
    name: "赤岩の峠", region: "r_desert", outside: "dune_sand",
    legend: R.FieldArea.DESERT_LEGEND, theme: 'desert', bgm: 'desert', bbg: 'desert',
    rows: [
      "RRRRRRRRRRRRRRRRRRRRRRRss..ssRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRss..suRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRss..uuRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRs...ssRRRRRRuuRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRs...sssRRRbuuuRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRss..;sssuuuuuuuuRRRRRRRR:RRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRss..;sssuuuuruuuuRRRRRRR:RRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRss..ssssuuuuuRRRusRRRRRR:RRRRR",
      "RRRRRRRRRRRRRRRRRRRRssss..sssbuuuuuRRRusssRRRR:RRRRR",
      "RRRRRRRRRRRRRRRRRRssssss..ssssuuuuuuuuusssssRR:ssRRR",
      "RRRRRRRRRRRRRRRRsssssss..ssssssuuuuuuuussssss::sssRR",
      "RRRRRRRRRRRRsssssssssss:.ssssssuuuuuuuuusss::::sss;b",
      "RRRkkkkksssssssssssrss.:::ssssssuuuuuuuuu::::sssss;s",
      "ssssssksssssssssssssss..s::::ssssuuuuuu:::::sssssRRs",
      "sssXXXXXXXXXXXXXsssss..ssss::::::::::::::uuusssssRRR",
      "sssXXXXXXXXXXXXXsssss..ssbsssssss:ussssuuuuuussssRRR",
      "sssXXXXXXXXXXXXXssss..sssssssssssssssssuuuuuuuusssss",
      "sssXXXXXXXXXXXXXssss..sssssssssssssssssuuuuuuuusssss",
      "sssXXXXXXXXXXXXXssss..sssssssrsssssssssuuuuuuuusssss",
      "sssXXXXXXXXXXXXXsss..ssssssssssssssssssuuuuuuuuussss",
      "sssXXXXXXXXXXXXXss....sssssssssssssrssssssuuuuuuuuss",
      "sssXXXXXXXXXXXXXs.....ssssssssssssssssssssuuuuuuuuss",
      "sssXXXXXXXXXXXXX..ss..sssssssssssssTs,,,sssuuuuuuuss",
      "sssXXXXXX:XXXXXX.ssss..sssssssssssks,www,Tuuuuuuubus",
      "ssssssss........sssss..ssssssssssss,,www,,uuuuuuuuuu",
      "sssssssu.....uuussssss..ssssbssssss,,www,suuuuuuuuuu",
      "rsssssuuuuuuuuusssssss...sssssssssssT,,,Truuuuuuuuru",
      "ssssssuuuuuuuuussssssss...ssssbssssssssssuuuuuuuuuuu",
      "ssssssuuuuuuuuusssssssss...ssssssssssssssuuuuuuuuubu",
      "ssssuuuuuuuuuuussssssssss..sskkkssssssssuuuuuuuuuuuu",
      "sssuuuuuuuuuuuusssssssssss..skkkksssssuuuuuuuuuuuuuu",
      "ssuuuuuuuuubuuussssbssssss..sskksuuuuuuuuuubuuuuuuus",
      "ssuuuuuuuuuuuuusssssssssss..sssssuuuuuuuuuuuuuruusss",
      "uuuuuuuuubuuuuusssssssssss..ssssuuuuuuuuuuuuuuuuusss",
      "uuuuuuuuuuuruuusssssssssss..ssssuuuuuubuuuuuuuuussss",
      "uuuuuuuuuuuuuussssrssssssss..sssssuusuuuuuuuuuusssss",
      "uuuuuuuuuuuuuussssssssskkss..sssssuusuuuuuuuuussssss",
      "uuuuuuuuuuuuuusssssssssssss..sssrsuussuuuuuuuussssss",
      "uuuuuuuuuuuuuusssssssssssss..sssssssssssssuuuuubssss",
      "uuuuuuuuuuuuusssssssssssss...sssssssssssssuuuuuuuuus",
    ],
    objects: [
      {"type":"sign","x":27,"y":8,"text":"ザハラ砂漠\n北 → ヴェルダの森　南 → カシム"},
      {"type":"sign","x":12,"y":26,"text":"宿場「砂の縁」\n森と砂漠と灰の街道の、まん中の宿"},
      {"type":"sign","x":44,"y":13,"text":"北の岩場\n「岩が動いた」と隊商が言う。"},
      {"type":"waylamp","id":"wl_d_pass_1","x":22,"y":16,"lit":true},
      {"type":"waylamp","id":"wl_d_pass_2","x":28,"y":31,"lit":true},
      {"type":"prop","id":"cart_barrels","x":13,"y":26},
      {"type":"prop","id":"copper_brazier","x":7,"y":25},
    ],
    npcs: [
      {"id":"pilgrim","look":"npc_desert_old_f","name":"夜明け待ちの巡礼","x":30,"y":28,"dir":"s","move":"still","talk":"desert_world_pilgrim","reward":"news","key":"world_pilgrim"},
    ],
    spawns: {"north":{"x":25,"y":1,"dir":"s"},"south":{"x":27,"y":38,"dir":"n"},"sandedge":{"x":9,"y":25,"dir":"s"},"rocks":{"x":46,"y":6,"dir":"s"}},
    exits: [{"x":24,"y":0,"w":3,"h":1,"to":{"map":"f_south","spawn":"south"}},{"x":27,"y":39,"w":2,"h":1,"to":{"map":"d_west","spawn":"north"}},{"x":9,"y":23,"w":1,"h":1,"to":{"map":"sandedge","spawn":"gate"}},{"x":46,"y":5,"w":1,"h":1,"to":{"map":"desert_rocks","spawn":"mouth"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_desert_road"}],
    art: {"image":"field/under/d_pass","painted":[]},
    meta: {"sub":"森から砂漠へ下りる道","worldRect":[70,358,110,64]},
    links: {"sandedge":{"map":"d_pass","spawn":"sandedge"},"rocks":{"map":"d_pass","spawn":"rocks"}},
  });
})(window.RPG);
