// 生成物（design/art_ref/gen/env/_tools/under/field_desert/ の areas_desert.py → fit.py → tomap.py）。手で直さない: 配置は areas_desert.py、当たりは fit.py で作り直す。
// エリア d_south「沈んだ柱の浜」（カシムの南の砂丘、56×44）。エリア切り替えのフィールド（maps/field_00_kit.js、砂漠の凡例は field_desert_00_kit.js）。
//   出口: n → d_east.south, w → d_caravan.east
//   絵: field/under/d_south（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("d_south", {
    name: R.T('map.field_desert_south.d_south.name'), region: "r_desert", outside: "dune_sand",
    legend: R.FieldArea.DESERT_LEGEND, theme: 'desert', bgm: 'desert', bbg: 'desert',
    rows: [
      "uuuuuuuuuuuuuuuusssssssssuuuuusuTuuuuuuuuuu::uuuuussssss",
      "uuuuuuuuuuuuuuuussssssssuuuuuuuuruuuuuuuuuu::usTuussssss",
      "uuuuuuuuuuuuuuusssssssssuuuuuuuuuuuuuuuuuu::uuuuuussssss",
      "uuuuuuuuuuuuuuussssssssuuuuuuuuuuuuuuuuuuu::uuuuuussssss",
      "uuuuuuuussskkkkkksssssssuuuuuuuuuuuuuuuuu::uuuuuuussssss",
      "uuuuuuussskkkkkkkkkkuusuuuuuuuuuuuuuss.uu::uuuuuuussssss",
      "uuuuussssTkkkkkkkkkksuuuuuuuuuuuuuuuuuuT::uuuuuuuuusrTus",
      "suu.ssrsskkkkkkkkkkkkuuuuuuuuuususTuuuu::usRRRRuuuuuruuu",
      "uussssssskkkkkkkkkkkkuuuuuuuuuuussTuuuu::u.RRRRruuuuuuuu",
      "uusssssrsTTkkkkkkkkkuuuuuuuuuuussssuuu::uu.RRRRruuuuuuuu",
      "uussusssssskkkkkksssuuuuuuuuuuussssuu::uuuuruuuuuuuuuuuu",
      "ssssusssssssssssssssuuuuuuuuuuusssss::ssssuuuuubsuuuruuu",
      "ssssuusssssssssssuuTruuuuuuuuuusss:::sssssusuuursTuuuuuu",
      "sssuuusssssssssssuuuuuuuuuuuuuuu:::sssssssssssuuusuuuuuu",
      "sssuuusssssssssssuuuuuuuuuuu::::.:ssssTssssssssssssuuuuu",
      "sssuuuussssssssssuu::::::::sTT:ussTsssTssssTssssssssssuu",
      ":::::.::::::::::::::::::.TT,TT,,sssssssssssTsssssssssssu",
      "sssssssTTsussssssuuuuuuu,TTwwwwTTTssussssssssssssssssssu",
      "sssssssssssussssuuuuuuuu,TTwwww~TTsuTsssssssssssssssssss",
      "sssssssssssssssssuuuuuuu,TTwwww~TTusuussssssskkkssssssuu",
      "ssssuuuusssssssssuuuuuuuu,TT~~~TTTuuTuusTskkkkkkkTuuuuuu",
      "ssssTTuussssssssuuuuuuuuusTTTTTTTuuuuuuusskkkkkkkkkuuuuu",
      "sssssuuuuusssssuuuuuuuuuuuTu:TTuTuuuuuuuuukkkkkkkkkuuuuu",
      "ssssssuususssssuuuuuuuuuuuuu::uuuuuuuuuuuukkkkkkkkkuuuuu",
      "ssssssssssssssuuuuuuuuuuuuuu::uuuuuuussusuuukkkkkuuuuuuu",
      "sssssssssRsTsuuuuuuuuuusuuuu::uuuuuuu.Rr.suuukkuuuuuuuuu",
      "sssssssssRrrTuuuuuuuuuuuTuuu::uuusuuuRRrsTru.uuuuuuuuuuu",
      "sssssssssRrrruu.uuuuuuuuuuuu::uuuuTuuurruruuTuuuuuususuu",
      "sssssssssTrruuuuTuuuuuuuuuuu::uuuuuuuuuuuuuuuuuuuuuTTTuu",
      "uuussuuuuuuuuuuuuuuuuuuuuuuu::uuuuuuuuuuuuuuus.ssuuuuuuu",
      "uuuuuuuuuuuuuuuuuuuuuuuuuuuu::uuuuuuuuuuuuuuuTRRRuuusuuu",
      "uuuuuuuuuuuuuuuuuuuussssuuuuuuuuuuuuuuuuuuuuuuRRrruurruu",
      "uuuuuuuuuuuuuuuuuuuussssssssuXuuuuuuuuuuusuuuurrruuuuuuu",
      "uuuuuuuuuuuuuuuuuuusssssssXTsTuuXuuuuuuussruuuuuuuuusuus",
      "uuuuuuuuuuuuuuusssssssssXTTrXXXsruXuuuuusssussuuuussurus",
      "ssussssssuuusssssssssssssTssXXXsssrssssussssssssssssssss",
      "ssssssssssssssssssssssssssssXsXsssssssssssssssssssssssss",
      "ssssTsssss~~.TTsssssssssrssssssssssssssssssssssssTTsssss",
      "s~sssss~s~~~~~~ssssssssssTssss~~ssssssssssssssssssssssss",
      "~~~~~~~~~~~~~~~~~~~~~~sssssss~~~~~~~ssssss~TTssuuus~~~ss",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~sssssss~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    ],
    objects: [
      {"type":"stairs","x":29,"y":36,"to":{"map":"desert_temple_1","spawn":"entrance"},"cond":{"any":["cleared_r_desert",{"var":"desert_nights","gte":3}]},"look":"none"},
      {"type":"examine","x":29,"y":36,"event":"desert_temple_sand","cond":{"not":{"any":["cleared_r_desert",{"var":"desert_nights","gte":3}]}}},
      {"type":"sign","x":24,"y":36,"text":R.T('map.field_desert_south.d_south.objects.2.text')},
      {"type":"examine","x":11,"y":6,"event":"desert_dig","dig":1},
      {"type":"prop","id":"sand_mound","x":12,"y":6},
      {"type":"examine","x":16,"y":5,"event":"desert_dig","dig":2},
      {"type":"prop","id":"sand_mound","x":17,"y":5},
      {"type":"examine","x":13,"y":9,"event":"desert_dig","dig":3},
      {"type":"prop","id":"sand_mound","x":14,"y":9},
      {"type":"spring","id":"world_desert_spring","x":16,"y":6,"cond":"desert_dig_found"},
      {"type":"prop","id":"tent","x":45,"y":21},
      {"type":"prop","id":"tent","x":49,"y":22},
      {"type":"prop","id":"clay_jars","x":44,"y":23},
      {"type":"prop","id":"bones","x":50,"y":25},
      {"type":"waylamp","id":"wl_d_south_1","x":39,"y":11,"lit":true},
    ],
    npcs: [
      {"id":"lost_camel","look":"ani_camel","name":R.T('map.field_desert_south.d_south.lost_camel.name'),"x":40,"y":29,"dir":"w","move":"still","cond":["desert_camel_asked","!desert_camel_found"],"talk":"desert_camel_world","reward":"side","key":"world_lost_camel"},
    ],
    spawns: {"north":{"x":44,"y":1,"dir":"s"},"west":{"x":1,"y":16,"dir":"e"},"temple":{"x":29,"y":37,"dir":"s"}},
    exits: [{"x":44,"y":0,"w":2,"h":1,"to":{"map":"d_east","spawn":"south"}},{"x":0,"y":16,"w":1,"h":2,"to":{"map":"d_caravan","spawn":"east"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_desert_caravan","cond":"desert_caravan_on"},{"rect":null,"zone":"zw_desert"}],
    art: {"image":"field/under/d_south","painted":[],"overlay":"field/under/d_south_over"},
    meta: {"sub":R.T('map.field_desert_south.d_south.meta.sub'),"worldRect":[150,430,140,71]},
    links: {"temple":{"map":"d_south","spawn":"temple"}},
  });
})(window.RPG);
