// 生成物（design/art_ref/gen/env/_tools/under/field_desert/ の areas_desert.py → fit.py → tomap.py）。手で直さない: 配置は areas_desert.py、当たりは fit.py で作り直す。
// エリア d_caravan「隊商路」（野営地をつなぐ砂の道、60×40）。エリア切り替えのフィールド（maps/field_00_kit.js、砂漠の凡例は field_desert_00_kit.js）。
//   出口: n → d_west.south, e → d_south.west, w → d_hollow.caravan, w → d_coast.caravan, 門 → desert_camp1.road, 門 → desert_camp2.road
//   絵: field/under/d_caravan（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("d_caravan", {
    name: R.T('map.field_desert_caravan.d_caravan.name'), region: "r_desert", outside: "dune_sand",
    legend: R.FieldArea.DESERT_LEGEND, theme: 'desert', bgm: 'desert', bbg: 'desert',
    rows: [
      "RRRRRRRRRRRRRRRRRRRssssssuuuuu..uuuuuuuuuuuuuuuuuussssssssss",
      "RRRRRRRRRRRRRRRRRRRssssssuuuuu..uuuuuuuuuuuuuuuuuusssrssssss",
      "RRRRRRRRRRRRRRRRRRTsssssuuuuuu..uuuuuuuuuuuuuuuuusssssssssss",
      "RRRRRRRRRRRRRRRRRTsssuuuuuuuuu..uuuuuuuuuuuuuuuuusssssssssss",
      "RRRRRRRRRRRRRRRsrsssuuuuuuuuuu..uuuuuuuuuuuuuuussussRRRRRsss",
      "RRRRRRRRRRRRRRssssssuuruuuuRRR....sssuuuuuuuuuusrssrRRRRRsss",
      "uussRRRRRTssssssssussTuuuuuRRR.....sssssuuuuuuuuussTrRRRRsss",
      "ussssssssssssssuuuuussuuuuuRR..uss...sssuuuuuuuuussuuuuussss",
      ":::::::::::::::::uuuusuuuuuuu..ussss....uuuuuuuuurssbsusssss",
      "ssssss:::::::::::::::::::uuu..uusuusss.....uuuuuussssssssrss",
      "ssssssssssssssuuuuuuuu::::::::usssssssuu.........ussssssssss",
      "RRRrsssssssssssuussuussssuuu::ussssssssssuuuu.............ss",
      "RRRRRRRrssssssssbsssuuuuuuuu..sssssssssssssusssssuu.........",
      "RRRRRRRRRRTsssssssssuuuuuuuuu..ussssssssssssssssssuuuusssuuu",
      "RRRRRRRRRRrssssssssssuuuuuuuu..usssssssssssssssssssuuussuuuu",
      "RRRRRRRRRRssuuusssssssuuuuuuu..ssssssssssssrsssssssuuuuuuuuu",
      "RRRRRRRRRTbssTTssssssssuuuuuuu:.sssssssssssssssssssuuuuuuuuu",
      "RRRRRRRRTsssssssssssssssuuuuu.::sssssssbuRRRRRRRTssuuuuuuuuu",
      "uTsuTTuusssssssssssssssssuuuu..:::ssssuuRRRRRRRRRTsuuuuuuuuu",
      "uusuuuuuussssssssssssssssuuuu..us::ssssuRRRRRRRRRRsuuuuubuuu",
      "ssuuuuuuussssuussssssssuuuuu..uuus:::ssRRRRRRRRRRRrssuuuuuuu",
      "ssssssssssssuuuussssrsuuuuu...uuuusu::sRRRRRRRRRRRrssuuuuuuu",
      "sssssssssussuuuuuuuuuuuuuu...uuuuuuuu:::RRRRRRRRRrsuussuuuuu",
      "sssssssssTssuuuuuuuuuuuu....uuuuuuuuuuu:rr:RRRRRruuuuusuuuuu",
      "ssssssssssrsuuuuuuuuuu.....uuuuuuuuuuuuuur:TRRTuuuuuuuuuuuus",
      "ssssssssssssuuuuuuu......uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuss",
      "ssssssssssssuuu...::..uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuubuuuss",
      "sssssssss........::uuuuuuuuuuuuuuuuubuuuuuuuuuuuuuuuuuuuuuus",
      "...............u::uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuus",
      ".........ssssuuX:uuuXuuuuuuuuuuuuuuuruuuuuuuuuuuuuuuuuuuuuus",
      "suuuuuuusssssuuX:XuuXuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuRRRRuuuus",
      "uuuuuuuusssuuuRRRRRRuuuuuuuuuuuuuuuuuuuuuuuuuuruuRRRRRRRuuss",
      "uuuuuuuusssuRRRRRRRRRrsssuuuuuuuuuuuuuuuuuuuuuuuuRRRRRRRssss",
      "uuuuuuuTsssRRRRRRRRRRrssssssssuuuuuuuuuuuuuuuuuuuRRRRRRRssss",
      "uuuuuTRRsssRRRRRRRRRRTsssssssssssssuuuuuuuuuuuuuuuTRRRTsssss",
      "uuuuuRRRRssRRRRRRRRRRssssrsssssssssuuuuuuuuuuuuuuuussssbssss",
      "uuuuRRRRRTssRRRRRRRRRsssbssssssssssuuuuuuuubuuuuuuusssssssss",
      "uuuuRRRRRssssRRRRRRRTsssssssssssssssuuuuuuuuuuuuuuusssssssss",
      "uuuuuuuuuuuuusssTsTsssssbsssssssssssssuuuuuuuuuussssssssssss",
      "uuuuuuuuuuuuuussssssssssssssssssssssssuuuuusuuusssssssssssss",
    ],
    objects: [
      {"type":"sign","x":39,"y":25,"text":R.T('map.field_desert_caravan.d_caravan.objects.0.text')},
      {"type":"sign","x":19,"y":29,"text":R.T('map.field_desert_caravan.d_caravan.objects.1.text')},
      {"type":"sign","x":8,"y":10,"text":R.T('map.field_desert_caravan.d_caravan.objects.2.text')},
      {"type":"sign","x":27,"y":13,"text":R.T('map.field_desert_caravan.d_caravan.objects.3.text')},
      {"type":"waylamp","id":"wl_desert_beacon_2","x":23,"y":26,"lit":"q_kasim_beacon_2","event":"desert_beacon"},
      {"type":"prop","id":"tent","x":39,"y":22},
      {"type":"prop","id":"copper_brazier","x":44,"y":25},
      {"type":"prop","id":"clay_jars","x":13,"y":29},
      {"type":"prop","id":"bones","x":33,"y":34},
      {"type":"prop","id":"cactus","x":47,"y":15},
    ],
    npcs: [

    ],
    spawns: {"north":{"x":30,"y":1,"dir":"s"},"east":{"x":58,"y":12,"dir":"w"},"hollow":{"x":1,"y":8,"dir":"e"},"coast":{"x":1,"y":29,"dir":"e"},"camp1":{"x":42,"y":24,"dir":"s"},"camp2":{"x":16,"y":29,"dir":"n"}},
    exits: [{"x":30,"y":0,"w":2,"h":1,"to":{"map":"d_west","spawn":"south"}},{"x":59,"y":12,"w":1,"h":2,"to":{"map":"d_south","spawn":"west"}},{"x":0,"y":8,"w":1,"h":2,"to":{"map":"d_hollow","spawn":"caravan"},"cond":{"any":[{"choice":"ch_desert_route","is":"short"},"cleared_r_desert"]}},{"x":0,"y":29,"w":1,"h":2,"to":{"map":"d_coast","spawn":"caravan"}},{"x":42,"y":23,"w":1,"h":1,"to":{"map":"desert_camp1","spawn":"road"}},{"x":16,"y":30,"w":1,"h":1,"to":{"map":"desert_camp2","spawn":"road"}}],
    triggers: [{"id":"desert_ambush_2","x":24,"y":22,"w":5,"h":4,"on":"step","event":"desert_ambush_2","cond":["desert_caravan_on","!desert_ambush_2_done"]}],
    tilePatches: [{"cond":{"not":{"any":[{"choice":"ch_desert_route","is":"short"},"cleared_r_desert"]}},"rect":[0,7,2,4],"rows":["rr","rr","rr","rr"]}],
    zones: [{"rect":null,"zone":"zw_desert_caravan","cond":"desert_caravan_on"},{"rect":null,"zone":"zw_desert"}],
    art: {"image":"field/under/d_caravan","painted":[],"overlay":"field/under/d_caravan_over","closed":"field/under/d_caravan_closed"},
    meta: {"sub":R.T('map.field_desert_caravan.d_caravan.meta.sub'),"worldRect":[60,440,100,61]},
    links: {"camp1":{"map":"d_caravan","spawn":"camp1"},"camp2":{"map":"d_caravan","spawn":"camp2"}},
  });
})(window.RPG);
