// 生成物（design/art_ref/gen/env/_tools/under/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// エリア f_roa「ロアの丘」（羊の丘と古井戸、52×40）。エリア切り替えのフィールド（maps/field_00_kit.js）。
//   出口: w → roa.gate, n → f_lookout.south, e → f_cape.west
//   絵: field/under/f_roa（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("f_roa", {
    name: "ロアの丘", region: "prologue", outside: "forest_dark",
    rows: [
      "FFFFFFFFFFFFFFFFFFFFF,rrrrrrrr;..;;;;;,,wwrrrrrrrrrr",
      "FFFFFFFFFFFFFFFFFFFFF,,,,rrrrr...;;;;;,Twwwrrrrrrrrr",
      "FFFFFFFFFFFFFFFFFFFFT,,,,,,;;;..;;;;;;,,www,rrrrrrrr",
      "FFFFFFFFFFFT,,TTTTTTT,,,,,,,r...T,,,;;;Twww,rrrrrrrr",
      "FFFFFFFFTT,,,,;TTTT,,,,,,,,,r..,,,,,,;,,Tww,rrrrrrrr",
      "FFFFFFFF,,,,,;XXXXXXX,,,,,;r...,,,,TTT,,ww,,,rrrrrrr",
      "FFFFFFFT,,,,XX,,,,,,X,,,,,r...,,,,,TTT,,ww,,RRrrrrrr",
      "FFFFFFT;;,,X,,,,,,,,X,,r,,...,,,,,,TTT,,ww,,RRRRrrrr",
      "FFFFFT;;;,X,X,X,,,,,X,,,,...,,,,,,,,,,,ww,,,,TRRRRRR",
      "FFFFFT,;,,X,,,,,X,,,X,,,...,,,\",,,,,,,,ww,,,,,,,,RRR",
      "FFFFFT,,,,XX,,X,,,,,X,,\"..,,,\"\"\",,,,,,,ww,,,,,,,,,,,",
      "FFFFFT,,,,X,,,,,,X,,X,,..,\"\"\"\"\"\",,,,;;,wT,,,,,,,,,,,",
      "FFFFFT,,,,X,X,,X,,,X,,...,,\"\",,,,,,,;;,ww,,,,,,\",,,,",
      "FFFFF,,,TTXXX,,XXXX,,,..,,,TTT,,,,,T,;,ww,,\",XXX,,,,",
      "FFFFFF,,TT,,,c,,,,,,,..,,,TTTTT,;TTTT;,ww,,\"\"XXXX,,,",
      "FFFFFFT,T,,,,,,,,TT,,..,\"\"TTTTT,;,TTT,,ww,\"\",XXXX,,,",
      "FFFFFFT;;,,,,,,,,,T,..cXc\"\"TTT,,,,,T,,,www\"\",XXXX,,,",
      "FFFFF;;;;,T,,,;,,,,...ccc,,,TT,,,,,,,,,www\"\",::r,,,,",
      "F.X.T..;;;,,;;;........,,,,,,,,,,,,,T,,www,,,::,,,,,",
      "....................;....,,,,,,,,,,,,T,ww,,,,::,,,,,",
      "FFFF........X.X.;;;;;;.....,,,,,,,,,,,,ww,,,T:.T\",,,",
      "FFXFT,,,;;;;X;X;;;;;;;;;.....X,,,,,T,,www,,,T:TTT,,,",
      "FFFFTT;;;;;;:;;;;;;;;;;;,,.....,,,,,,,www,,,T:.TT,,,",
      "FFFFFT;;;;;;:,;;;;;;;;;;,,,,.....,,,,,,ww,,,T:TTT,,,",
      "FFFFFT;;;,,,:,,,,,,,,,T,,,,,,,....,,,,,ww,,,::;,,,,,",
      "FFFFFT;;,,,r:,XX,,,,,,,,,,,,,,,,....,,,==,,,:;,,,,,\"",
      "FFFFFT,,,,XX,,,,XXr,,,,,,,,,,,,,,......==...:;,,,,T,",
      "FFFFFT,,XXr,,,,,,,Xr,,,,,,,,,,,,,;;....ww.....,,,,,,",
      "FFFFT,,,r,XX,,,,,,,X,,,,\"Tw,,,,,T;;;;;;ww,,,.....,,,",
      "FFFFT,,,r,Xr,,,,,,,X,,,,wwwwT,,,,;T;;;;ww,,,,,......",
      "FFFFT,,,r,,,,,,,,,,X,,,wwwwww,,,,;;;;;;ww,,,,,,,....",
      "FFFFT,,,Xr,,,,,,,,,X,,wwwwwww,,TTT;;;;;www,,,,,,,,,,",
      "FFFFT,,T,r,,,,,,,,XX,,wwwwww,,,TTTT;;;;Tww;;,,,,,,,,",
      "FFFFT,,,,,Xr,,,,XXX,,,,,ww,,,,,TTT,T,;;;\"ww,,,TTT,,,",
      "FFFFT,,,r,,X:XXXr,,,,,,,,,,,,,,,,,,,,,\";;ww,,TTTTT;;",
      "FFFF,,,,,,,,,;;;,,,,,,,,,,,,,,,,,,,,\"\"\"\"\"ww,,TTTTT;;",
      "FFFFF,,,,,,,,,;;,,,,,,,,,,,,,,,,,,FFF\"\"\",ww,,FFF;;;;",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,,wwwFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwwFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwwFFFFFFFF",
    ],
    objects: [
      {"type":"stairs","x":23,"y":16,"to":{"map":"well","spawn":"entrance"}},
      {"type":"sign","x":21,"y":15,"text":"旅人の古井戸\n枯れ井戸。底へ下りる縄ばしごがある。"},
      {"type":"examine","x":14,"y":10,"event":"world_poi_stones"},
      {"type":"examine","x":29,"y":21,"event":"world_poi_shrine"},
      {"type":"waylamp","id":"wl_pen_road","x":34,"y":24,"lit":"prologue_lamp_road","event":"world_pen_lamp"},
      {"type":"sign","x":5,"y":17,"text":"ロアの里\n語り部の里。"},
      {"type":"sign","x":43,"y":27,"text":"東 → 港町ファロス・灯台の岬\n北 → 見晴らし台・跳ね橋"},
      {"type":"chest","id":"f_roa_c1","x":49,"y":11,"item":"i_potion","n":1},
      {"type":"examine","x":46,"y":16,"event":"world_poi_windmill"},
    ],
    npcs: [
      {"id":"shepherd","look":"npc_old_m_2","name":"羊飼いの年寄り","x":14,"y":31,"dir":"w","move":"still","cond":"prologue_done","talk":"world_shepherd","reward":"news","key":"world_shepherd"},
    ],
    spawns: {"roa":{"x":1,"y":19,"dir":"e"},"north":{"x":31,"y":1,"dir":"s"},"east":{"x":50,"y":29,"dir":"w"},"well":{"x":22,"y":17,"dir":"s"}},
    exits: [{"x":0,"y":19,"w":1,"h":2,"to":{"map":"roa","spawn":"gate"}},{"x":31,"y":0,"w":2,"h":1,"to":{"map":"f_lookout","spawn":"south"}},{"x":51,"y":29,"w":1,"h":2,"to":{"map":"f_cape","spawn":"west"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_prologue"}],
    art: {"image":"field/under/f_roa","painted":["stairs_down@23,16"],"overlay":"field/under/f_roa_over"},
    meta: {"sub":"羊の丘と古井戸","worldRect":[222,246,70,60]},
    links: {"roa":{"map":"f_roa","spawn":"roa"},"well":{"map":"f_roa","spawn":"well"}},
  });
})(window.RPG);
