// 生成物（design/art_ref/gen/env/_tools/under/field_ash/ の areas_ash.py → fit.py → tomap.py）。手で直さない: 配置は areas_ash.py、当たりは fit.py で作り直す。
// エリア a_foot「火山のふもと」（カルデラの東、火の鳥の眠る山、56×44）。エリア切り替えのフィールド（maps/field_00_kit.js、灰の荒野の凡例は field_ash_00_kit.js）。
//   出口: w → caldera.gate_e, n → a_bridge.south, s → a_beach.foot
//   絵: field/under/a_foot（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("a_foot", {
    name: R.T('map.field_ash_foot.a_foot.name'), region: "r_ash", outside: "rock",
    legend: R.FieldArea.ASH_LEGEND, theme: 'ash', bgm: 'overworld', bbg: 'ash', propSet: 'ash', propSetBase: 'village',
    light: R.FieldArea.ASH_LIGHT,
    rows: [
      "RRTrsssuuuusuuTrrrrr.ssbTssssuuuuusTTRRRRRRRRRRRRRRRRRRR",
      "RRrrsssssuuuuurrrrrT..ssTssssuuuuuuTTRRRRRRRRRRRRRRRRRRR",
      "RRrrssssssssssrrrrTs..ssssuuuuuuuuusRRRRRRRRRRRRRRRRRRRR",
      "RRrTsssssssssssssTss..ssssuuuuuuuuusRRRRRRRRRRRRRRRRRRRR",
      "RRrTssssssssssssssss..ssssuuuuuuuuuRRRRRRRRRRRRRRRRRRRRR",
      "RRrussssssssssssssss..ssssuuuuussusRRRRRRRRRRRRRRRRRRRRR",
      "RRrTssssssssskrrrTs..sssRRRRRrussssRRRRRRRRRRRRRRRRRRRRR",
      "RRrTssssssRRTkrrrrs..ssuRRRRRrsssssRRRRRRRRRRRRRRRRRRRRR",
      "RRrrsssssRRRrTrrrT...susRRRRrTsssssTRRRRRRRRRRRRRRRRRRRR",
      "RRrTsssssRRRrTrrrs..sssTTTTTTussssssRRRRRRRRRRRRRRRRRRRR",
      "RRrrssssssTrrTrTs...TsuuuuuuuusssrTsRRRRRRRRRRRRRRRRRRRR",
      "RRrrTsssssssbTsssT.sssuuuuuuuussrTTsRRRRRRRRRRRRRRRRRRRR",
      "RRrrTsTsssssTTsssT..TsuuuuruuussTTssRRRRRRRRRRRRRRRRRRRR",
      "RRrrssTkrTssssss.T.TTsuuuuuuuussssssRRRRRRRRRRRRRRRRRRRR",
      "RRrrsTrrrsssssrT..sTrsuuuuuuuussssssrRRRRRRRRRRRRRRRRRRR",
      "RRrrsTrrTsssssTT..ssssrTuuuuuussssssTRRRRRRRRRRRRRRRRRRR",
      "RRrrsTssssssssss..sssssruuuuussssssssRRRRRRRRRRRRRRRRRRR",
      "RRrrssssssssssss.sssssruuuuuusssbTssTRRRRRRRRRRRRRRRRRRR",
      "RRrrsssssssssss..sssssuTuuuuusssTTsssX:XRRRRRRRRRRRRRRRR",
      "XXrTsssssssssss..sssssuu...........TT.ccRRRRRRRRRRRRRRRR",
      "Tlrrsss..............................rX:XRRRRRRRRRRRRRRR",
      "........................usuuuuusss...ccccRRRRRRRRRRRRRRR",
      ".T......sssssTsssss..suTuuuusssssuuucccccRRRRRRRRRRRRRRR",
      "RRrTsssssssssssssss..suuuuuusssussuuuTTrRRRRRRRRRRRRRRRR",
      "XXrrsssssssssssssss..uuuuuuuuuuuuTTuuussrRRRRRRRRRRRRRRR",
      "RRrrsssssssssssssuu..uurruuuuuuuuussusssTrRRRRRRRRRRRRRR",
      "RRrrssssssssssssuuu.uuruuuuuuuuuuusssssuuTrRRRRRRRRRRRRR",
      "RRrrssssssssssssuuu.uuuuuuruuuuuuusssssuuuTrRRRRRRRRRRRR",
      "RRrrssssssssssuuru..uuuuuuuuuuuuuuussssuuuuTrRRRRRRRRRRR",
      "RRrrsTssssTssuuuuu..uuuruuuuuRRRTuruuuruuuuuTrRRRllRRRRR",
      "RRrTsrsssssssuuuuu..sssssssssRRRruuuubTTsssuuTrrlllRRRRR",
      "RRrTsssssssuuuuuu..ssssssssssTRRruubTTTsssssssTlllRRRRRR",
      "RRrrsssuusuuuRRRRT.sssssssssssTrrurTTuussssssslllRRRRRRR",
      "RRrruuuuuuuuRRRRRr.sssssssssssssssssssssssssssllRRRRRRRR",
      "RRrruuuuuuurRRRRrrsssssssssssssssssssssssssslllRRRRRRRRR",
      "RRrrusTTssssTrrrTssssssssssssssTssssssssssllllRRRRRRRRRR",
      "RRbTTsTTTTsssss..sssssssssssssTrsssrrsssslllRRRRRRRRRRRR",
      "RRrrTsTTrTsssss..sssssssssssssssssrrrssslllRRRRRRRRRRRRR",
      "RRrruusTTsssss..sssssssrrssssssssrrrrsssllRRRRRRRRRRRRRR",
      "RRrruurTuuuuss..ssssssssTsssrTssTrrrrTslllRRRRRRRRRRRRRR",
      "RRrrssuuuuuuss..ssssssssssssTTssrrrrrrsllRRRRRRRRRRRRRRR",
      "RRrrssuurruuss..ssssssssssssrrssssrrrrrllRRRRRRRRRRRRRRR",
      "RRrrssssuuuuus..sssssssssssrrrsssssrrrrllRRRRRRRRRRRRRRR",
      "RRrrssssuuuuus.ssssssssssssTrrsssssrrrrllRRRRRRRRRRRRRRR",
    ],
    objects: [
      {"type":"stairs","x":39,"y":20,"to":{"map":"ash_volcano_1","spawn":"entrance"},"cond":"ash_champion","look":"none"},
      {"type":"examine","x":39,"y":20,"event":"ash_rockdoor_world","cond":{"not":"ash_champion"}},
      {"type":"sign","x":34,"y":22,"text":R.T('map.field_ash_foot.a_foot.objects.2.text')},
      {"type":"sign","x":5,"y":24,"text":R.T('map.field_ash_foot.a_foot.objects.3.text')},
      {"type":"waylamp","id":"wl_a_foot_gate","x":6,"y":20,"lit":true},
      {"type":"waylamp","id":"wl_a_foot_1","x":19,"y":17,"lit":true},
      {"type":"prop","id":"iron_brazier","x":38,"y":20},
      {"type":"prop","id":"iron_brazier","x":40,"y":20},
      {"type":"prop","id":"lava_glow","x":44,"y":35},
      {"type":"prop","id":"lava_glow","x":40,"y":40},
    ],
    npcs: [

    ],
    spawns: {"caldera":{"x":1,"y":21,"dir":"e"},"north":{"x":20,"y":1,"dir":"s"},"south":{"x":14,"y":42,"dir":"n"},"volcano":{"x":39,"y":21,"dir":"s"}},
    exits: [{"x":0,"y":21,"w":1,"h":2,"to":{"map":"caldera","spawn":"gate_e"}},{"x":20,"y":0,"w":2,"h":1,"to":{"map":"a_bridge","spawn":"south"}},{"x":14,"y":43,"w":2,"h":1,"to":{"map":"a_beach","spawn":"foot"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":[0,18,40,6],"zone":"zw_ash_road"},{"rect":null,"zone":"zw_ash_plain"}],
    art: {"image":"field/under/a_foot","painted":["lava_glow"],"overlay":"field/under/a_foot_over","emit":"field/under/a_foot_emit"},
    meta: {"sub":R.T('map.field_ash_foot.a_foot.meta.sub'),"worldRect":[519,384,99,66]},
    links: {"caldera_e":{"map":"a_foot","spawn":"caldera"},"volcano":{"map":"a_foot","spawn":"volcano"}},
  });
})(window.RPG);
