// 生成物（design/art_ref/gen/env/_tools/under/field_ash/ の areas_ash.py → fit.py → tomap.py）。手で直さない: 配置は areas_ash.py、当たりは fit.py で作り直す。
// エリア a_foot「火山のふもと」（カルデラの東、火の鳥の眠る山、56×44）。エリア切り替えのフィールド（maps/field_00_kit.js、灰の荒野の凡例は field_ash_00_kit.js）。
//   出口: w → caldera.gate_e, n → a_bridge.south, s → a_beach.foot
//   絵: field/under/a_foot（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("a_foot", {
    name: R.T('map.field_ash_foot.a_foot.name'), region: "r_ash", outside: "rock",
    legend: R.FieldArea.ASH_LEGEND, theme: 'ash', bgm: 'overworld', bbg: 'ash', propSet: 'ash', propSetBase: 'village',
    light: R.FieldArea.ASH_LIGHT,
    rows: [
      "RRkssssuuuuruuukkkks.ssrsssssuuuuuruuRRRRRRRRRRRRRRRRRRR",
      "RRsssssssuuuuukkkkss..sssssssuuuuuuuRRRRRRRRRRRRRRRRRRRR",
      "RRssssssssssssssssss..ssssuuuuuuuuusRRRRRRRRRRRRRRRRRRRR",
      "RRusssrrssssssssssrs..ssssuuuuuuuuusRRRRRRRRRRRRRRRRRRRR",
      "RRuussrrrsssssssssss..ssssuuuuuuuuuRRRRRRRRRRRRRRRRRRRRR",
      "RRuussrrrsssssssssss..ssssuuuuusrusRRRRRRRRRRRRRRRRRRRRR",
      "RRssssssssssskkksss..sssrsssruussssRRRRRRRRRRRRRRRRRRRRR",
      "RRsssssssrssrkkkkss..ssurrrrrrsssssRRRRRRRRRRRRRRRRRRRRR",
      "RRsssssssrrrrkkkss...surrrrrrrssssssRRRRRRRRRRRRRRRRRRRR",
      "RRsssssssrrrrkksss..sssuuuuuuussssssRRRRRRRRRRRRRRRRRRRR",
      "RRsssssssssssssss...ssuuuuuuuusssssrRRRRRRRRRRRRRRRRRRRR",
      "RRsssrssssssssrrs..sssuuuuuuuussssrsRRRRRRRRRRRRRRRRRRRR",
      "RRsssssrsssssssss..sssuuuuuuuussssssRRRRRRRRRRRRRRRRRRRR",
      "RRssssskssssssss..rrssuuuuuuuussssssRRRRRRRRRRRRRRRRRRRR",
      "RRksskksssssssss..ssssuuuuuuuusssssssRRRRRRRRRRRRRRRRRRR",
      "RRsssrssssssssss..sssssuruuuuusssssssRRRRRRRRRRRRRRRRRRR",
      "RRsssrssssssssss..sssssuuuuuurrssssssRRRRRRRRRRRRRRRRRRR",
      "RRssssssssssssss.sssssuuruuuurrssssssRRRRRRRRRRRRRRRRRRR",
      "RRsssssssssssss..sssssuuruuuurrrsssssXRRRRRRRRRRRRRRRRRR",
      "XXsssssssssssss..sssssuu..............R:RRRRRRRRRRRRRRRR",
      "..sssss...............................cccRRRRRRRRRRRRRRR",
      "........................usuuuuusssuus.cccRRRRRRRRRRRRRRR",
      "........sssssssssss..suuuuuusrrssuuuuuusRRRRRRRRRRRRRRRR",
      "RRsssssssssssssssss..suuuuuusrrusuuuuursRRRRRRRRRRRRRRRR",
      "XXsssssssssssssssss..uuuuuuuurruuuuuuursuRRRRRRRRRRRRRRR",
      "RRsssssssssssssssuu..uuuuuuuuuuuuussusssuuRRRRRRRRRRRRRR",
      "RRssssssssssssssuuu.uuuuuuuuuuuuuusssssuuuuRRRRRRRRRRRRR",
      "RRssssssrrssssssuuu.uuuuuuuuuuuuuussrrsuuuuuRRRRRRRRRRRR",
      "RRssssssrrrsssuuuu..uuuuuuuuuuuuuuusrrruuuuuuRRRRRRRRRRR",
      "RRsssssrrrrssuuuuu..uuuuuuuuusssuuuuuuuuuuuuuuRRRllRRRRR",
      "RRsssssssrssruuuuu..ssssssssrrrruuuuuuuusssuusuulllRRRRR",
      "RRsrsssssssuuuuuu..sssssssssrrrrruuuuuussssssrslllRRRRRR",
      "RRsssssuusuuussss..sssssssssssrruuussuussssrsslllRRRRRRR",
      "RRssuuuuuuuusssrrr.sssssssssssssssssssssssssslllRRRRRRRR",
      "RRssuuuuuuusrrrrr.sssssssssssssssssssssssssslllRRRRRRRRR",
      "RRssusssssssrrrr.sssssssssrrsssssssssssrssllllRRRRRRRRRR",
      "RRsssrrrsssssss..ssssssssrrrsssssssksssrslllRRRRRRRRRRRR",
      "RRssurrrrssssss..sssssssssrrsssssskksssslllRRRRRRRRRRRRR",
      "RRssuurrssrsss..ssssssssssssrsssskskssssllRRRRRRRRRRRRRR",
      "RRssuuuuuurrss..ssssssssssssrssskkkkksslllrRRRRRRRRRRRRR",
      "RRssssuuurrrrs..srsssssssssssssssskkkssllRRRRRRRRRRRRRRR",
      "RRssssuuuurrss..sssssrrsssssksssssskkksllRRRRRRRRRRRRRRR",
      "RRssssssuuuuus..ssssssssssskksssssskkskllRRRRRRRRRRRRRRR",
      "RRssssssuuuuus.ssssssssssssskssssssskkkllRRRRRRRRRRRRRRR",
    ],
    objects: [
      {"type":"stairs","x":39,"y":19,"to":{"map":"ash_volcano_1","spawn":"entrance"},"cond":"ash_champion","look":"none"},
      {"type":"examine","x":39,"y":19,"event":"ash_rockdoor_world","cond":{"not":"ash_champion"}},
      {"type":"sign","x":34,"y":22,"text":R.T('map.field_ash_foot.a_foot.objects.2.text')},
      {"type":"sign","x":5,"y":24,"text":R.T('map.field_ash_foot.a_foot.objects.3.text')},
      {"type":"waylamp","id":"wl_a_foot_gate","x":5,"y":19,"lit":true},
      {"type":"waylamp","id":"wl_a_foot_1","x":21,"y":18,"lit":true},
      {"type":"prop","id":"iron_brazier","x":38,"y":19},
      {"type":"prop","id":"iron_brazier","x":40,"y":19},
      {"type":"prop","id":"lava_glow","x":44,"y":35},
      {"type":"prop","id":"lava_glow","x":40,"y":40},
    ],
    npcs: [

    ],
    spawns: {"caldera":{"x":1,"y":21,"dir":"e"},"north":{"x":20,"y":1,"dir":"s"},"south":{"x":14,"y":42,"dir":"n"},"volcano":{"x":39,"y":20,"dir":"s"}},
    exits: [{"x":0,"y":21,"w":1,"h":2,"to":{"map":"caldera","spawn":"gate_e"}},{"x":20,"y":0,"w":2,"h":1,"to":{"map":"a_bridge","spawn":"south"}},{"x":14,"y":43,"w":2,"h":1,"to":{"map":"a_beach","spawn":"foot"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":[0,18,40,6],"zone":"zw_ash_road"},{"rect":null,"zone":"zw_ash_plain"}],
    art: {"image":"field/under/a_foot","painted":["lava_glow"],"emit":"field/under/a_foot_emit"},
    meta: {"sub":R.T('map.field_ash_foot.a_foot.meta.sub'),"worldRect":[519,384,99,66]},
    links: {"caldera_e":{"map":"a_foot","spawn":"caldera"},"volcano":{"map":"a_foot","spawn":"volcano"}},
  });
})(window.RPG);
