// 生成物（design/art_ref/gen/env/_tools/under/field_desert/ の areas_desert.py → fit.py → tomap.py）。手で直さない: 配置は areas_desert.py、当たりは fit.py で作り直す。
// エリア d_pass「赤岩の峠」（森から砂漠へ下りる道、52×40）。エリア切り替えのフィールド（maps/field_00_kit.js、砂漠の凡例は field_desert_00_kit.js）。
//   出口: n → f_south.south, s → d_west.north, 門 → sandedge.gate, 門 → desert_rocks.mouth
//   絵: field/under/d_pass（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("d_pass", {
    name: R.T('map.field_desert_pass.d_pass.name'), region: "r_desert", outside: "dune_sand",
    legend: R.FieldArea.DESERT_LEGEND, theme: 'desert', bgm: 'desert', bbg: 'desert',
    rows: [
      "RRRRRRRRRRRRRRRRRRRRRRRTs..srRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRTs..srRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRTs..uTRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRT...sTRRRRRsurRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRs...ssTRRRsuuTRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRTs..TsssuuuuuuuTRRRRRRRR:RRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRTs..TsssuuuuruuuTRRRRRRR:RRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRss..ssssuuuuuuuuuTRRRRRR:RRRRR",
      "RRRRRRRRRRRRRRRRRRRRssss..ssssuuuuuuuuussTRRRR:RRRRR",
      "RRRRRRRRRRRRRRRRRRssssss..ssssuuuuuuuuussssTRR:sTRRR",
      "RRRRRRRRRRRRRRRRsssssss..ssssssuuuuuuuusssssTr:ssTRR",
      "RRRRRRRRRRRRssssssTssss:.ssssssuuuuuuuuussTTrT:sssTR",
      "RRRssTTssssssrssssssss.:::ssssssuuuuuuuuurrr:sssssTR",
      "ssssssssssssssssssssss..s::TTssssuuuuuurrrr:sssssRRR",
      "sssXXXXXXXXXXXXXTssss..ssssTTrTrrrrrrrrrruuussssTRRR",
      "sssXXXXXXXXXXXXXTbsss..sssssssssTrTTTTsuuuuuusssTRRR",
      "sssXXXXXXXXXXXXXTsss..sssssssssssTsssssuuuuuuuussTTs",
      "sssXXXXXXXXXXXXXTsss..sssssssssssssssssuuuuuuuusssss",
      "sssXXXXXXXXXXXXXTsss..srsssssssssssssssuuuuuuuusssss",
      "sssXXXXXXXXXXXXXTss..ssssssssssssssssssuuuuuuuuussss",
      "sssXXXXXXXXXXXXXTs....ssssssTrssssssssssssuuuuuuuuss",
      "sssXXXXXXXXXXXXXT.....ssssssssssssssssssssuuuuuuuuss",
      "sssXXXXXXXXXXXXXT.ss..ssssssssssssTTTTTTsssuuuuuuuss",
      "sssXXXXXX:XXXXXXTssss..ssssssssssssTwwwwTTTbuuuuuuus",
      "ssssssss........sssss..sssssssssssTTwwwwTTuuuuuuuuuu",
      "sssssssu.....uuTssssss..ssssssssssTTwwwwrsuuuuruuuuu",
      "ssssssuuuuuuuuusssssss...sssssrssssTTTTTTuuuruuuuuuu",
      "ssssssuuuuuuuuussssssss...sssssssssssTTTsuuuuuuuuuuu",
      "ssssssuuuuuuuuusssssssss...ssssssssssssssuuubuuuuuuu",
      "ssssuuuuuuuuuuussssTsssss..sssssssssssssuuuuuuuuuuuu",
      "sssuuuuuuuuuuuusssssssssss..ssssssssssuuuuuuuuuuuuuu",
      "ssuuubuuuuuuubusssssssssss..sssssuuuubuuuuuuuuuuuuus",
      "ssuuuuuuuuuuuuusssssssssss..sssssTuuuuuuruuuuuuuusss",
      "uuubuuuuuuuuuuusssssssssss..ssssuuuuuuuuuuuuuuuuusss",
      "uuuuuruuuuuuuuusssssssssss..ssssbuuuuuuuuuuuuuuussss",
      "uuuuuuuuuuuurusssssssssssss..sssssTusuuuuuuuuuusssss",
      "uuuuuuuuuuuuuusssssssssssss..sssssuusuuuuuuuuussssss",
      "uuuuuuuuuuuuuussssssssssrss..sssssTussuuuuuuuussssss",
      "uuuuuuuuuuuuuusssssssssssss..ssssssssssssbuuuuusssss",
      "uuuuuuuuuuuuusssssssssssss...sssssssssssssuuuuuuuuus",
    ],
    objects: [
      {"type":"sign","x":27,"y":8,"text":R.T('map.field_desert_pass.d_pass.objects.0.text')},
      {"type":"sign","x":12,"y":26,"text":R.T('map.field_desert_pass.d_pass.objects.1.text')},
      {"type":"sign","x":44,"y":13,"text":R.T('map.field_desert_pass.d_pass.objects.2.text')},
      {"type":"waylamp","id":"wl_d_pass_1","x":24,"y":15,"lit":true},
      {"type":"waylamp","id":"wl_d_pass_2","x":28,"y":31,"lit":true},
      {"type":"prop","id":"cart_barrels","x":13,"y":26},
      {"type":"prop","id":"copper_brazier","x":7,"y":25},
    ],
    npcs: [
      {"id":"pilgrim","look":"npc_desert_old_f","name":R.T('map.field_desert_pass.d_pass.pilgrim.name'),"x":30,"y":28,"dir":"s","move":"still","talk":"desert_world_pilgrim","reward":"news","key":"world_pilgrim"},
    ],
    spawns: {"north":{"x":25,"y":1,"dir":"s"},"south":{"x":27,"y":38,"dir":"n"},"sandedge":{"x":9,"y":25,"dir":"s"},"rocks":{"x":46,"y":6,"dir":"s"}},
    exits: [{"x":24,"y":0,"w":3,"h":1,"to":{"map":"f_south","spawn":"south"}},{"x":27,"y":39,"w":2,"h":1,"to":{"map":"d_west","spawn":"north"}},{"x":9,"y":23,"w":1,"h":1,"to":{"map":"sandedge","spawn":"gate"}},{"x":46,"y":5,"w":1,"h":1,"to":{"map":"desert_rocks","spawn":"mouth"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_desert_road"}],
    art: {"image":"field/under/d_pass","painted":[],"overlay":"field/under/d_pass_over"},
    meta: {"sub":R.T('map.field_desert_pass.d_pass.meta.sub'),"worldRect":[70,358,110,64]},
    links: {"sandedge":{"map":"d_pass","spawn":"sandedge"},"rocks":{"map":"d_pass","spawn":"rocks"}},
  });
})(window.RPG);
