// 生成物（design/art_ref/gen/env/_tools/under/field_ash/ の areas_ash.py → fit.py → tomap.py）。手で直さない: 配置は areas_ash.py、当たりは fit.py で作り直す。
// エリア a_spa「湯けむりの谷」（溶岩洞の湯の郷、48×40）。エリア切り替えのフィールド（maps/field_00_kit.js、灰の荒野の凡例は field_ash_00_kit.js）。
//   出口: s → a_lava.north
//   絵: field/under/a_spa（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("a_spa", {
    name: R.T('map.field_ash_spa.a_spa.name'), region: "r_ash", outside: "rock",
    legend: R.FieldArea.ASH_LEGEND, theme: 'ash', bgm: 'ash', bbg: 'ash', propSet: 'ash', propSetBase: 'village',
    light: R.FieldArea.ASH_LIGHT,
    rows: [
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRR,,,XXXssssRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRR,,sss,,,cwwwwsssssssRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRR,sssss,,wwwwwwwsssss,,,RRRRRRRRRRRR",
      "RRRRRRRRRRRR;ssssss,cwwwwwwcsssssssssRRRRRRRRRRR",
      "RRRRRRRRRRsssssssss,c,wwwwwwsssssssssssRRRRRRRRR",
      "RRRRRRRRRsrsssssss,,c,,,,,,,cssssrrssssRRRRRRRRR",
      "RRRRRRRRssssssssssww,c,,,,,csssss,,sssssRRRRRRRR",
      "RRRRRRRRs,sssssscwwwwwcc:ccssssss,,sssssRRRRRRRR",
      "RRRRRRRRssssssccwwwwwwc::sssssssssssssssRRRRRRRR",
      "RRRRRRRRssssssc,wwwwwwc::sscwwww,sssssssRRRRRRRR",
      "RRRRRRRRssssssc,,w,,,,c:sscwwwwwwcssssssRRRRRRRR",
      "RRRRRRRRssssrscc,,,,,cc:scwwwwwwwwssssssRRRRRRRR",
      "RRRRRRRRss,,,,ssccccc,,::c,wwwwwwcsssssssRRRRRRR",
      "RRRRRRRsss,,,rr,,,,,,,,::c,,www,,c,s,,ss,RRRRRRR",
      "RRRRRRRsss,,,rr,,,,wwwww:,c,,,,ccc,,,,,,rRRRRRRR",
      "RRRRRRRsss,,,,,,,,wwwwww:,,ccccc,,,,rr,r,RRRRRRR",
      "RRRRRRRsss,,,,,,cwwwwwww::,,,,,,,,,,,,,,,RRRRRRR",
      "RRRRRRRsss,,,,,,c,wwwwww::c,,,,,,,,,,,,,,RRRRRRR",
      "RRRRRRRsss,,,,,,c,,wwww,::c,,,w,w,,,,,,,RRRRRRRR",
      "RRRRRRRRsss,,,,,,c,,,,,,::,,wwwwww,,,,ssRRRRRRRR",
      "RRRRRRRRsssss,,,ssccccccc:scwwwwwww,,sssRRRRRRRR",
      "RRRRRRRRRsssssrrssssscsss:c,,wwwwwc,,sssRRRRRRRR",
      "RRRRRRRRRsssssrrsssssssss::,,,,ww,c,,,,sRRRRRRRR",
      "RRRRRRRRRsssss,,sssssssss::c,,,,,c,,,,,sRRRRRRRR",
      "RRRRRRRRRRssss,,sssssssss::sccccc,,,,,ssRRRRRRRR",
      "RRRRRRRRRRssrssssssssssss::ss;,ssssssssRRRRRRRRR",
      "RRRRRRRRRRR,ssssssssssss::sss;;ssssssrRRRRRRRRRR",
      "RRRRRRRRRRRsssssssssssss::s;;;;;sssssRRRRRRRRRRR",
      "RRRRRRRRRRRRsssssssssss::ss;;,,;sss,sRRRRRRRRRRR",
      "RRRRRRRRRRRRRssssssssss::ss;;,,;ssssRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRsssssssss::ssss,;;;sssRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRsssssssss:;sssss,;;;sRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRsssssssss:;ssss;,,;;RRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRR,,,,,,sss:ssssss,sssRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRR,,,,,,,,ss:ssss;;,,,,RRRRRRRRRRRRRR",
    ],
    objects: [
      {"type":"examine","x":23,"y":22,"event":"ash_spa_pool"},
      {"type":"sign","x":21,"y":33,"text":R.T('map.field_ash_spa.a_spa.objects.1.text')},
      {"type":"prop","id":"steam_vent","x":12,"y":25},
      {"type":"prop","id":"steam_vent","x":33,"y":20},
      {"type":"prop","id":"steam_vent","x":28,"y":8},
      {"type":"chest","id":"a_spa_c1","x":35,"y":27,"item":"i_ether","n":1},
      {"type":"waylamp","id":"wl_a_spa_1","x":26,"y":33,"lit":true},
    ],
    npcs: [

    ],
    spawns: {"south":{"x":23,"y":38,"dir":"n"}},
    exits: [{"x":23,"y":39,"w":2,"h":1,"to":{"map":"a_lava","spawn":"north"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_ash_spa"}],
    art: {"image":"field/under/a_spa","painted":[],"overlay":"field/under/a_spa_over"},
    meta: {"sub":R.T('map.field_ash_spa.a_spa.meta.sub'),"worldRect":[360,354,84,42]},
    links: {},
  });
})(window.RPG);
