// 生成物（design/art_ref/gen/env/_tools/under/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// エリア f_cross「北の野」（三つの道の分かれ道、60×40）。エリア切り替えのフィールド（maps/field_00_kit.js）。
//   出口: s → f_lookout.bridge, w → f_hut.east, e → world.f_cross_e
//   絵: field/under/f_cross（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("f_cross", {
    name: R.T('map.field_cross.f_cross.name'), region: "r_forest", outside: "forest_dark",
    rows: [
      ",,,,,,FFFFFFFFFFRRRRRFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFRR,,,",
      ",,,,,RFFFFFFFFFFRRRRRFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFR,,,",
      ",,,,,FFFFFFFFFFFFRRRFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFRR,,",
      ",,,,,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFRRRFFFFFRRRRFFFFFFFFFR,,",
      ",,,,RFFRRRRFFFFFFFFFFFFFFFFFFFRRRRRR,,,RRRRRR,,RRFFFFFFFFR,,",
      ",,,,RRRT,,,RRRRRFFFFRFFFRRRRRRT,,,,,,,,,,,,R,,,,RRRRRRRRR,,,",
      ",,,,,,,,,,,,,,,,RRRRRRRR,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,XXXXXXXX,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,XccccccX,,,,,,,,,,,,,,,,,wwwww,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,XccccccX,,,,,,,,,,,,,,rwwwwwwww,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,XccccccX,,,,,,,,,,,,,,wwwwwwwwwww,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,XXXXccXX,,,,,,,,,,X,,,wwww==wwwww,,,,,,,",
      ",,,,,,,TTT,,,,,,,,,,,,,,,:,,,,,,,,,,,,r,,,wwww==wwww,,,,,,,,",
      ",,,,,,,TTTT,,,,,,,,,,,,,,::,,,,,,,,,,,,,,,,rww==wwww,,,,,,,,",
      ",,,,,,,,T,,,,,,,,,,,,,,,,,::,,,,,,,,,,,,,,,,,,==,,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,::,,,,,,,,,,,,XX:r:,:=,,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,,::,,,,,,,,,,,::r::::,,,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,,::,,,,,,,,,,,:::::::,,,,,,,,,,,,.",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,,,:,,,,,,,,,,,,,,,::,,,...........",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,,,::..............::..............",
      ",,,,,,,,,,,,,,,,,,,,,,.......:....................,,,,,,,,,,",
      ".....,,,,,,,,,,,,,............r,,,,,,,,,,,,..,,,,,,,,,,,,,,,",
      "............,.........,,,,,,..X,,,,,,,,,,,,,XXX,,,,,,,,,,,,,",
      ",,,,..............,,,,,,,,,,..,,,,,,,,,,,,,,XXX,,,,,,,,,,,,,",
      ",,,,,,,,,,,..,,,,,,,,,,,,,,,..,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,T,,,,,,,,,,,,,,,,,,,",
      ",,,,,,,,,TTT,,,,,,,,,,,,,,,..,,,,,,,,,TTTTT,,,,,,,,,,,,,,,,,",
      ",,,,,,,,TTTTT,,,,,,,,,,,,,,..,,,,,,,,,TTTTTT,,,,,,,,,,TT,,,,",
      ",,,,,,,,TTTTT,,,,,,,,,,,,,,...,,,,,,,TTTTTTT,,,,,,,,,TTT,,,,",
      ",,,,,,,,TTTTT,,,,,,,,,,,,,,...,,,,,,,,TTTT,,,,,,,,,,,TTTT,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,XXccXX,,,,,,,,,,,,,,,,,,,,,,TTT,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,cccccXc,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,cccccXc,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,XXccXXc,,,,,,,,,,,,,,,,,,,sssssssss",
      "sssss,ssssssssssssssssssssT==~ssssssssssssssssssss~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    ],
    objects: [
      {"type":"sign","x":31,"y":19,"text":R.T('map.field_cross.f_cross.objects.0.text')},
      {"type":"examine","x":24,"y":10,"event":"world_poi_plains_found"},
      {"type":"examine","x":25,"y":10,"event":"world_poi_cache","item":"i_potion","key":"world_poi_plains_found"},
      {"type":"examine","x":38,"y":11,"event":"world_poi_stones"},
      {"type":"prop","id":"lantern","x":44,"y":16},
      {"type":"waylamp","id":"wl_rest_3","x":49,"y":22,"lit":true},
      {"type":"prop","id":"lamp_post","x":25,"y":28},
      {"type":"prop","id":"lamp_post","x":29,"y":27},
      {"type":"chest","id":"f_cross_c1","x":46,"y":11,"item":"i_potion","n":2},
    ],
    npcs: [
      {"id":"traveler_plains","look":"npc_merchant_2","name":R.T('map.field_cross.f_cross.traveler_plains.name'),"x":43,"y":17,"dir":"s","move":"still","talk":"world_traveler_plains","reward":"news","key":"world_traveler_plains"},
      {"id":"guard_east","look":"npc_guard_1","name":R.T('map.field_cross.f_cross.guard_east.name'),"x":54,"y":18,"dir":"w","move":"still","pushable":false,"cond":{"slice":true},"talk":{"lines":[{"text":R.T('map.field_cross.f_cross.lines.0.text')}]},"reward":"news","key":"world_guard_east"},
    ],
    spawns: {"bridge":{"x":27,"y":38,"dir":"n"},"west":{"x":1,"y":22,"dir":"e"},"east":{"x":58,"y":18,"dir":"w"}},
    exits: [{"x":27,"y":39,"w":2,"h":1,"to":{"map":"f_lookout","spawn":"bridge"}},{"x":0,"y":22,"w":1,"h":2,"to":{"map":"f_hut","spawn":"east"}},{"x":59,"y":18,"w":1,"h":2,"to":{"map":"world","spawn":"f_cross_e"},"cond":{"not":{"slice":true}}}],
    triggers: [],
    tilePatches: [{"cond":{"slice":true},"rect":[55,17,3,4],"rows":["rrr","rrr","rrr","rrr"]}],
    zones: [{"rect":null,"zone":"zw_forest"}],
    art: {"image":"field/under/f_cross","painted":[],"overlay":"field/under/f_cross_over","closed":"field/under/f_cross_closed"},
    meta: {"sub":R.T('map.field_cross.f_cross.meta.sub'),"worldRect":[232,124,120,96]},
    links: {},
  });
})(window.RPG);
