// 生成物（design/art_ref/gen/env/_tools/under/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// エリア f_cape「灯台の岬」（ファロス街道と灯台、56×44）。エリア切り替えのフィールド（maps/field_00_kit.js）。
//   出口: w → f_roa.east
//   絵: field/under/f_cape（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("f_cape", {
    name: "灯台の岬", region: "prologue", outside: "sea",
    rows: [
      "FFFFFFFFFFFFFFFFFFFFFT,,,,,,,,,;;;;;,;;;,;TTTXXrrrTTXXXX",
      "FFFFFFFFFFFFFTTTTTTTTT,,,,,,,,,;;;;;,,,,,TTTTXXXXXrXXXXX",
      "FTTTTTTTTTTTTTTTrTTTTT,,,,,,,,,;;T;;,,,,,,TTTTXXXXrXXXXX",
      "TTT,,TTTTTT,,,,,,;;TT,,,,,,,,,;;;;,,,,,,,,,TTTXXrrrTXXXX",
      "TT,,,TTTTTT,,,,TTTrT,,,,,,,,,,,,,,,,,rrr\",;TTTXXrrrrXXXX",
      "\"\",,,TTTTTT;;;,TTTT,,,,,,,,,,,,,T,,,XXXr;,;,,TXrrrrrXXXX",
      "\"\",,,,TTTrT;;;;TTTT,,,,T,r,,,,,,,,::::::;,,,,,XrccrXXXXX",
      "\",,,,,,,,,;;;;;;TT,,,,,,,,,,,,,,,,::::::,,,,,r.....,,,,,",
      "..........,;;,,;\",,,,,,,,,,,,,,,\",.....................X",
      ".................,,,,;,;;,.............................X",
      ",,,,,,,,,,...............::.......,,,,,,,,,,,,,,;,,,,,,,",
      ",,,,,TT,,,,,,,,,,;.......::\",,\",,,,,,,,r,,,,,,,,,T;,,T,,",
      ",,r,,,,,,r,,,,,,,;;;;;;;;::,,,\",,,,XXX,,,,,T,,,,,,;T,,,,",
      ",Tr,,T,,,,,,,,,,;;;;r;;;\"\":,,,\",,,,XXX,,,,T,,,,,,,;,,,,,",
      ",,,,,,,TTT,,,,,,;;;;;;;;\"\":\",,,,,,,XXX,,TTTT,r,,,,,,,,T,",
      ",,,,,,TTTTT,,,,b;;;TTT,;\"\"::,;;;,;,,,,,,TTTTT,,,,,,,,,,,",
      ",,,,,,TTTTTr,,,,;;TTTTT,,,::,;T;;;;;;;;;TTTT,,,\"\",,,RRXX",
      ",,,,,,,,,,,,;;;;;;;TTTT,,,,::,;,TTT;;rT;;,\";;,,,\",,RR~~~",
      ",,,,,,,,,,,;;TTr;;;;TTTr,,,::,;;TTT;;;;;;;;;T,,,,,RR~~~~",
      "RRRR,,,,,,,;;,;;\";;;;,,T,,,;::;TTTTrrr;;;;;;T,,,,RR~~~~~",
      "ssrRRR,,,;TrTTT;;;;;;,T,T,,,::,,,,,;;;;;;;;;;,,,,~~~~~~~",
      "sssrrRR;;;;;TTT;;;;,,,,,,,,,,:,,,,\"T;;,b;;;,,,,,~~~~~~~~",
      "~~_sssRR;;\"TTTT;;;;,,,,,,,,,,:,,,,,,,,,,,,,r,,R~~~~~~~~~",
      "~~~__srRR;;\"TT;;;;;,::,,,,,,::,,,,,,,,,,,,,,RR~~~~~~~~~~",
      "~~~~~_ssRrT;;;T;;;,,::,,\"\"\",::,,,,,,,,,,,,,R~~~~~~~~~~~~",
      "~~~~~_ssR\",\";;;;;;;:::,\",,,,::,,,,,,,,,,,,,~~~~~~~~~~~~~",
      "~~~~~_ssR;\";;;;;;;;:::,,,,,T:,,,T,,T,,,,,R~~~~~~~~R~~~~~",
      "~~~~~_ssRRr;;;;;;;::::,,,,,:,XXXX,,,T,,,,R~~~~~~~RRR~~~~",
      "~~~~~~_ssRRrr;;;;;::::,;;;::,XXXX,r,,,\",R~~~~~~~~~R~~~~~",
      "~~~~~~~ssssRr;;;;;::::Xrr;::,XXXX,,,T,,RR~~~~~~~~~~~~~~~",
      "~~~~~~~_ssssRRRRRrrs::;Xrr::,XXXX,,,,,R~~~~~~~~~~~~~~~~~",
      "~~~~~~~~__ssssrrrrss::,;r:::,XXXX,,,,,R~~~~~~~R~~~~~~~~~",
      "~~~~~~~~~~_sssssss__sRR,\":::,XXXX,,,,R~~~~~~~RRR~~~~~~~~",
      "~~~~~~~~~~~_______ss_~~RR:::,XXXX,,RR~~~~~~~~RR~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~s~~~~~RR:::,XXXX,,R~~~~~~~~~~~~~~~~~~~~",
      "~~~R~~~~~~~~~~~~~~~~~~~~R:::,XXXX,,R~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~:::,XXXXRR~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~R~~~~~~~~R:ccccccc~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~RRR~~~~~~~RRccccccc~~~~~~RRR~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~R~~~~~~~~R,,,ccccR~~~~~~RRR~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~RRRRRRRRR~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~RRRRR~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    ],
    objects: [
      {"type":"door","x":31,"y":36,"w":1,"look":"none","to":{"map":"lighthouse_1","spawn":"entrance"}},
      {"type":"sign","x":28,"y":38,"text":"ファロス灯台"},
      {"type":"sign","x":50,"y":11,"text":"港町ファロス"},
      {"type":"sign","x":26,"y":13,"text":"南 → ファロス灯台"},
      {"type":"examine","x":36,"y":14,"event":"world_poi_pen_wall"},
      {"type":"waylamp","id":"wl_rest_2","x":42,"y":7,"lit":true},
      {"type":"prop","id":"tent","x":43,"y":6},
      {"type":"prop","id":"lantern","x":44,"y":6},
      {"type":"chest","id":"f_cape_c1","x":12,"y":31,"item":"i_salve","n":2},
      {"type":"prop","id":"lighthouse_glow","x":31,"y":28,"cond":"prologue_boss"},
      {"type":"door","x":55,"y":8,"look":"none","locked":"ファロスの町へは、北の門から入ろう。"},
      {"type":"door","x":55,"y":9,"look":"none","locked":"ファロスの町へは、北の門から入ろう。"},
    ],
    npcs: [

    ],
    spawns: {"west":{"x":1,"y":8,"dir":"e"},"pharos":{"x":48,"y":7,"dir":"s"},"lighthouse":{"x":31,"y":37,"dir":"s"}},
    exits: [{"x":0,"y":8,"w":1,"h":2,"to":{"map":"f_roa","spawn":"east"}},{"x":48,"y":6,"w":2,"h":1,"to":{"map":"pharos","spawn":"gate_w"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":[0,0,56,16],"zone":"zw_prologue"},{"rect":null,"zone":"zw_peninsula"}],
    art: {"image":"field/under/f_cape","painted":["lighthouse_glow@31,28"],"overlay":"field/under/f_cape_over"},
    meta: {"sub":"ファロス街道と灯台","worldRect":[272,300,72,92]},
    links: {"pharos":{"map":"f_cape","spawn":"pharos"},"lighthouse":{"map":"f_cape","spawn":"lighthouse"}},
  });
})(window.RPG);
