// 生成物（design/art_ref/gen/env/_tools/under/field_ash/ の areas_ash.py → fit.py → tomap.py）。手で直さない: 配置は areas_ash.py、当たりは fit.py で作り直す。
// エリア a_beach「火山ガメの浜」（黒い砂浜、60×36）。エリア切り替えのフィールド（maps/field_00_kit.js、灰の荒野の凡例は field_ash_00_kit.js）。
//   出口: n → a_lava.south, n → a_foot.south
//   絵: field/under/a_beach（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("a_beach", {
    name: R.T('map.field_ash_beach.a_beach.name'), region: "r_ash", outside: "sea",
    legend: R.FieldArea.ASH_LEGEND, theme: 'ash', bgm: 'ash', bbg: 'ash', propSet: 'ash', propSetBase: 'village',
    light: R.FieldArea.ASH_LIGHT,
    rows: [
      "RRRRRRR:sRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR:sRRRRRRRRRR",
      "RRRRRRR:sRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR:sRRRRRRRRRR",
      "RRRRRRR:sRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR:sRRRRRRlllR",
      "RRRRsss:sRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR::RRRRRRlllR",
      "RRrssss:ssssRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRuu::uussRRlllR",
      "sssssss::sssssssRRRRRRRRRRRRRRsssssssRRRRRRRssuu::uussssllRR",
      "sssssss::ssssssrssssssRRRRssssrsssssssssssssuuuu:uusssslllRR",
      "ssssssss:sssssrrsssssssssssssssssssssssssssssuuu:uusssslllRR",
      "ssssssss::sssssssssssssssssssssssssrsrssssuuuuuu:ussssslllRR",
      "sssssssss:::sssssrrrssssssssssssssssssssssurrru::ussssslllRR",
      "sssssrrrss::sssssrrrrsssssssssssssssssrrssuurss:sussssslllRR",
      "ssssssrsss::::sssrrrsssssssrrssssssssrrrrsuuss::ssssssslllRR",
      "sssssssssss::::suuuussssssrrrsssssssrrrrrsssss::ssssssssllRR",
      "sssssssssssss:::uuuusssssssrssssssssrrrrrssss::sssssssssllRR",
      "ssssssssssssss:::uuusssssssssssssssssrssssss::sssssssssslllR",
      "sssssssssssssss::::usssssssssssssssssssssss::ssssssssssslllR",
      "ssssssssssssssss::::ssssssXXssssrssssss:::::sssssssssssslllR",
      "ssssssssssssssrrss:::sssssssssss:::::::::sssssrrssssrssslllR",
      "usssssssssssssssssss::::::::::::::::ssssssssrrrrrssssssslllR",
      "usssrsrssssssssssssssss::::::sssssssssssssssrrrrrssssssslllR",
      "sssssrruusssssssssssssssssrrrsssssssssssssssrrrrssssssssllRR",
      "ssssssruuuwwrssssssssssssssrrsssssssssssssssssssssssssssllRR",
      "ssssuuuuuuwwrssssssssrrrrsssssssrrsssssssrrrssssssssssslllRR",
      "sssuuuuuuuuussssssssrrrrrssssssrwwwsssssssssssssssssssslllRR",
      "uuuuuuuuuusussssssssrrrrrssssssrwwwsssssssssssssssssssslllRR",
      "_____u__________________________www____________________lllRR",
      "_____________________~~~~~~~~__________________________lllRR",
      "~~_______________~~~~~~~~~~~~~~~~~~___________~~~~~~~~~lll~~",
      "~~~~~~~~~~_~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ll~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ll~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ll~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    ],
    objects: [
      {"type":"examine","x":26,"y":16,"event":"ash_beach_rock"},
      {"type":"sign","x":9,"y":8,"text":R.T('map.field_ash_beach.a_beach.objects.1.text')},
      {"type":"chest","id":"a_beach_c1","x":47,"y":23,"item":"i_panacea","n":1},
      {"type":"waylamp","id":"wl_a_beach_1","x":31,"y":19,"lit":true},
      {"type":"prop","id":"steam_vent","x":53,"y":26},
      {"type":"prop","id":"steam_vent","x":53,"y":12},
      {"type":"prop","id":"lava_glow","x":57,"y":10},
      {"type":"prop","id":"lava_glow","x":56,"y":22},
    ],
    npcs: [

    ],
    spawns: {"lava":{"x":7,"y":1,"dir":"s"},"foot":{"x":48,"y":1,"dir":"s"}},
    exits: [{"x":7,"y":0,"w":2,"h":1,"to":{"map":"a_lava","spawn":"south"}},{"x":48,"y":0,"w":2,"h":1,"to":{"map":"a_foot","spawn":"south"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_ash_beach"}],
    art: {"image":"field/under/a_beach","painted":["lava_glow"],"emit":"field/under/a_beach_emit"},
    meta: {"sub":R.T('map.field_ash_beach.a_beach.meta.sub'),"worldRect":[435,444,105,42]},
    links: {},
  });
})(window.RPG);
