// 生成物（design/art_ref/gen/env/_tools/under/field_desert/ の areas_desert.py → fit.py → tomap.py）。手で直さない: 配置は areas_desert.py、当たりは fit.py で作り直す。
// エリア d_east「東の街道」（灰の荒野への古い道、56×36）。エリア切り替えのフィールド（maps/field_00_kit.js、砂漠の凡例は field_desert_00_kit.js）。
//   出口: w → kasim.gate_e, e → world.d_east_e, s → d_south.north
//   絵: field/under/d_east（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("d_east", {
    name: "東の街道", region: "r_desert", outside: "dune_sand",
    legend: R.FieldArea.DESERT_LEGEND, theme: 'desert', bgm: 'desert', bbg: 'desert',
    rows: [
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~RR~~~~~~~~~~~~~~~~~~~~~~",
      "~u~busssssss~~~~~~~~~~~~~~~~~~~~RRuuuuuuuu~~~~~~~~~~RRRR",
      "uuuuuussssssssssssssss~~~~~~uubuRRRrssssssuuuuuuRRRRRRRR",
      "XXXXXssssssssssssssssrssssuuuuuuRRRssssbsssuuuuusRRRRRRR",
      "XXXXXssssssrbsssssssssssuuuuuuuuRRRssssssskuuuussRRRRRRR",
      "XXXXXssssssssssssssssbuuuuuuuuussRRsssssssuuuuuuuRRRRRRR",
      "XXXXXssssssssssssssrssuuuuuuuusssRRssssssuuuuuuuuRRRRRRR",
      "XXXXXssssssssssssssssuuuuuuuuusssRRssssssuuuuuuuuRRRRRRR",
      "XXXXXssssssssssssssssuuuuuuuuussRRRsssssskuuuuuuuuRRRRRR",
      "XXXXXsssssssssssssssssuuuuuuuussRRRssssbskkuuuusssRRRRRR",
      "XXXXXssssssssssssssssuuuuuuuuuusRRRssssskkkkksssssRRRRRR",
      "XXXXXsssssssssssbssssuXXXuuuubuuRRRsssssssskss..........",
      "XXXXXssssssssssssssssuuuuuuuuuu=====....................",
      "XXXXXsssssssssssss...suuuuuuu..=====............sssRRR..",
      "XXXXXssssss....................=====kssssssssssssssRRRRR",
      "...................s.........ussRRRkksbssssssssssssRRRRR",
      "...........s:ssssssssuuuuuuuusssRRRskssssssssssssssRRRRR",
      "XXXXXsssssss:sssssssssuuuuuuuusssRRsksssssssssssssRRRRRR",
      "XXXXXssssrss:sssssssssuuuuuuuubusRRukssssssssssssRRRRRRR",
      "XXXXXsssssss:sssssssssuuuuuuuuuuuRRuuusssssssssssRRRRRRR",
      "XXXXXsssbsss:ssssskkkkkkuuuuuuuuuRRuuuusssssssssuRRRRRRR",
      "XXXXXssssssk:kkkkkkkkkkkkuuuuuuuRRRuuuuusssssssuuRRRRRRR",
      "XXXXXsssskkk:kkkkkkkkkkkkkuuuuuuRRRuuuuuuuuuuuuuuRRRRRRR",
      "XXXXXssssskk:kkkkkkkkkkkkkkuuuuuRRuuuusuuuuuuuuuuRRRRRRR",
      "XXXXXsssskkk:kkkkkkkkkkkkkkkuuruRRussssruuuuuuuuuRRRRRRR",
      "XXXXXssskskk:kkkkkkkkkkkkkkuuuuuRRussssuuuuuuuuuuRRRRRRR",
      "XXXXXssssssk:kkkkkkkkkkkkkuuuuuuRRRuuuuuuuuuuuuuuuRRRRRR",
      "XXXXXsssssss:kkkkkkkkkkkkuuuuuuuRRRuuuuuuuuuuuuuuuRRRRRR",
      "XXXXXsssssss:uukkkkkkkkkuuuuuuuuuRRuuuuuuuuuuuuuuuRRRRRR",
      "XXXXXsuuuuuu:uuuuuuskssskssssuuuuRRRuubusssruuuuuRRRRRRR",
      "XXXXXuuuuuuu:uuuussssssskssssuuuuuRRuuuusssssssssRRRRRRR",
      "XXXXXuuuuuuu:uuussssssssssssssssssRRuuussssssssssRRRRRRR",
      "uuuuuuuuuuuu:ssssssssssssssrsssrssRRssssssssssssRRRRRRRR",
      "uuuuuuuuuuus:bssssssssssssssssssssRRRsssssssssssRRRRRRRR",
    ],
    objects: [
      {"type":"sign","x":46,"y":17,"text":"東 → 灰の荒野・カルデラ"},
      {"type":"sign","x":8,"y":15,"text":"オアシスの町カシム\n東の門"},
      {"type":"waylamp","id":"wl_d_east_1","x":9,"y":16,"lit":true},
      {"type":"waylamp","id":"wl_d_east_2","x":25,"y":19,"lit":true},
      {"type":"waylamp","id":"wl_d_east_3","x":41,"y":17,"lit":true},
      {"type":"prop","id":"cart_barrels","x":21,"y":13},
    ],
    npcs: [
      {"id":"oil_caravan","look":"npc_oil_carrier","name":"油運び","x":25,"y":14,"dir":"w","move":"still","talk":"desert_world_oil","reward":"hint","key":"world_oil_caravan"},
      {"id":"oil_camel","look":"ani_camel","name":"ラクダ","x":26,"y":13,"dir":"w","move":"still","talk":{"lines":[{"text":"ラクダは、油のつぼを背に\nのんびり砂をかんでいる。"}]},"reward":null},
      {"id":"guard_ash","look":"npc_guard_1","name":"番人","x":50,"y":16,"dir":"e","move":"still","pushable":false,"cond":{"slice":true},"talk":{"lines":[{"text":["灰の荒野へ抜ける峠は、\n灰の崩れでふさがってるんだ。","カルデラへ行くなら、\n片づくまで待ってくれ。"]}]},"reward":"news","key":"world_guard_ash"},
    ],
    spawns: {"kasim":{"x":1,"y":17,"dir":"e"},"pass":{"x":54,"y":14,"dir":"w"},"south":{"x":12,"y":34,"dir":"n"}},
    exits: [{"x":0,"y":17,"w":1,"h":2,"to":{"map":"kasim","spawn":"gate_e"}},{"x":55,"y":14,"w":1,"h":2,"to":{"map":"world","spawn":"d_east_e"},"cond":{"not":{"slice":true}}},{"x":12,"y":35,"w":2,"h":1,"to":{"map":"d_south","spawn":"north"}}],
    triggers: [],
    tilePatches: [{"cond":{"slice":true},"rect":[52,13,3,3],"rows":["rrr","rrr","rrr"]}],
    zones: [{"rect":[0,10,56,12],"zone":"zw_desert_road"},{"rect":null,"zone":"zw_desert"}],
    art: {"image":"field/under/d_east","painted":[]},
    meta: {"sub":"灰の荒野への古い道","worldRect":[165,395,125,50]},
    links: {"kasim_e":{"map":"d_east","spawn":"kasim"}},
  });
})(window.RPG);
