// 生成物（design/art_ref/gen/env/_tools/under/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// エリア f_fern「森の街道」（フェルンへの森の道、56×44）。エリア切り替えのフィールド（maps/field_00_kit.js）。
//   出口: e → f_hut.west, n → fern.gate_s, w → f_windhill.east, s → f_south.north
//   絵: field/under/f_fern（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("f_fern", {
    name: "森の街道", region: "r_forest", outside: "forest_dark",
    rows: [
      ",,;TFFF;;;,,FFFFFFFFFFFFFFXX..XX;;;;;;;;;;;;,,TTF,,FFFFF",
      ",,,TFFFFr;,,TFFFFFFFFFFFT,X;..TX;;;;;;;;;;;;,,,TFFFFFFFF",
      ",,,TFFF;;,,,,TT;;;FFFFT,,,X;..FXF;;;;;;;;;;;,,rFFFFFF,,,",
      ",,TTFFF;,,,,,,T,;;;FFFT,,,,,..FFFF;FTTT;;;;;;,TFFFFFF,,,",
      ",,,TFFF,,;;;;;T;;;;FFFT,,,,...TTFFFFFF;T;;;;,,TFFFFFT,,,",
      ",,,TFFFT,;;;;;;;;,,FFF;;,,,...;,FFFFFF,,,,b;TTFFFFFF,,,,",
      ",,,TFFFFT,;;;;;T;,TFFFT;,,,..TFFFFFFF,,,,,,,;TTFFFFF,,,,",
      ",,TFFTFT,;;;;;;;;,TFFT,,;,,..,,,,FFFF,,,,,,,;TTTFFFF,,,,",
      ",TFFTTT,,,;;;;T;;,TTT,,;;;,..,,,,,FF,,,,,,,bTTTTFFFF,,,,",
      ",,FFT,,,,,,,,,,;;,,,;;;;;;,..,,r,,FF,,,,,,,FFTTTFTF,,,,;",
      ",,FF,,,,,,,,,,bF;;;;;;;;;;;..,,,,,TFFb,,b,FF,FTTT;;;;;;;",
      "FFFF,T,,,,,,,,,T;;;;;;;;;;...,,,,,TXFFFFFFFF,,,TTT;;;;..",
      "FFFFTTTT,,,b,,,,,;;;;T;TFF...,,,,TFTF,TFFFFT,,..........",
      "FFFFFTTTr,,,,,,,,FT;;TTTFF...,,,,TFFF,,,,,..............",
      "T,FFT,;T,,...,,,,TT;;;TTFF,..,,,TFFFF,,,......,;;;;;FF;;",
      "..................;;;T;FF,,..,,,,,,FF......TTTT,;,TTFFT;",
      ".......................FX,,..,,,,,......;;,TTT,,,,TFFFTT",
      ".....,,FF,,,,,,FF.....................TT;;;;;TXFFFFFFFFF",
      ",,,;T;FFFTTT;T;TFFFFFFF............,,;;T;;;;;,,FFFFFFFFF",
      ",,,;;;FFTT;FFFFFFFFFFFF,,,,...,,,,,,,;;TTT;;;,,TFFFFFFFF",
      ",,,;;;;;TX;;FFFFFFFFFFF,,,,,..,,,,,,,;;TFT;T;,,,FFFFFFFF",
      ",,;;;;;TT;;;FFFFFFFFXFFF,,,,,..,,,,;;;TTFF;;;b,,;FFFFFFF",
      ",;;;;;;TT;;;FF;;FFFFFFFFFF,,,..,,,,,,;;;,,,,;;;;;;;;;FFF",
      "FT;;;;;;;;;;;;;;TFFFFFFFFF,r,,..,,,,,,,,,,,,,,,b,;;;;T;;",
      "FF;;;;;;;;;b;;;;;;TFFFFF,,,T,,..,,,,,,,,,,,,,,,,;;;;;;;;",
      "RR;;;;;;;T;;;;;;;;;FFFFF,,,TT,..,,,,T,,,,,,,,,,,;;;;;T;;",
      "wRRRRRR;;;;;;;;;;;;FFFFF,,,T,,..,,,,,,,,,,,,,,,,;;;;;;;;",
      "wwwwwRRRRRR;;;FFFFFFFFF;;,,,,,..,,,,,,,,,r,,,,,,,;;;;;;;",
      "RRwwwwwwwwRRRRRFFFFFFFFF;;;T,..T,,,TF,,,,,,,,,,,,;;;;;;;",
      "FRRRRRwwwwwwwwRRRRFFFFFFFFTT,..,,,,FF,,,,,,,,,,,,;;;;;;;",
      "FFFT;RRRRRRwwwwwwRRRRFFFFFF,,..,,,,FFb,,,,,,,,FF,,;;;;;;",
      "FFFT;;;;;RRRRRRwwwwwRRRRRFF,,..,,,,FF,,,,,,FFFFFT;;;;;;;",
      ";,TT;;;;;;;;;RRRRRwwwwwRRRRRR==RR,,FF,,,,,FFFFFT;;;;;;;;",
      ",TTT,r;;,,;;;;T;TRRRRwwwwwwww==wRRRRF,,,,,FFFFFT;;;;;,,,",
      ",,,TFF;T,,;;;;;;;FFFRRRRRwwww==wwwwRRRFFFFFFFFF;;;;;,r,,",
      ",,,TFFFFT,;;;;,,,TFFFFFRRRRRR==RRwwwwRRRFFFFFFFFT;;;,,,,",
      ",,,TFFFTT,;;;;,:::::FF;;;;:::..FRRRwwwwRRFFFFFFF;;;,,,,,",
      ",,FFFFFF,,,T;;T;:::::::::::::..;TRRRRwwwRRRFFFFT;;;,,,,,",
      ",,FFFFFFFFFF;TFFFFF,,,,,,,;;TF..Tr;;RRRwwwRRFFFT;;;;,,,,",
      ",,FFFFFFFFFFFFFFFFT,,;,,,,;,FF..T,;;;;RRwwwRRTT;;;;;;TFF",
      "FFFFFFFTFFFFFFFFFFF;,;,,,,,,FF..T,;;;;;,RRwwRR;,,;;;;FFF",
      "FFFFFFFFFFFFFFFFFF;;;;,,,,,,TF..T,;;;;;,,RRwwwRR,;;;TFFF",
      "TT,,FFFFFFFFFF;TF;;;;,,,TFTTF...Tb;;;;;,,,RRwwwRR;;TFFTT",
      "T,,,FFFFFFFFF;;;T;;;;;,,FFFFF...T,;;;;;,,,,RRwwwRTFFFF;;",
    ],
    objects: [
      {"type":"waylamp","id":"wl_forest_2","x":38,"y":14,"lit":"q_forest_fireflies_2","event":"forest_waylamp"},
      {"type":"waylamp","id":"wl_forest_3","x":26,"y":23,"lit":"q_forest_fireflies_3","event":"forest_waylamp"},
      {"type":"examine","x":24,"y":16,"event":"world_poi_shrine"},
      {"type":"sign","x":30,"y":4,"text":"森の村フェルン"},
      {"type":"sign","x":33,"y":21,"text":"北 → フェルン\n西 → 風鳴りの丘\n南 → 森の南"},
      {"type":"prop","id":"mushroom_glow","x":13,"y":36},
      {"type":"prop","id":"mushroom_glow","x":44,"y":24},
      {"type":"chest","id":"f_fern_c1","x":15,"y":35,"item":"i_ether","n":1},
    ],
    npcs: [

    ],
    spawns: {"east":{"x":54,"y":12,"dir":"w"},"fern":{"x":28,"y":2,"dir":"s"},"west":{"x":1,"y":16,"dir":"e"},"south":{"x":30,"y":42,"dir":"n"}},
    exits: [{"x":55,"y":12,"w":1,"h":2,"to":{"map":"f_hut","spawn":"west"}},{"x":28,"y":0,"w":2,"h":1,"to":{"map":"fern","spawn":"gate_s"}},{"x":0,"y":16,"w":1,"h":2,"to":{"map":"f_windhill","spawn":"east"}},{"x":30,"y":43,"w":2,"h":1,"to":{"map":"f_south","spawn":"north"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_forest_road"}],
    art: {"image":"field/under/f_fern","painted":[]},
    meta: {"sub":"フェルンへの森の道","worldRect":[112,188,90,74]},
    links: {"fern":{"map":"f_fern","spawn":"fern"}},
  });
})(window.RPG);
