// 生成物（design/art_ref/gen/env/_tools/under/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// エリア f_roa「ロアの丘」（羊の丘と古井戸、52×40）。エリア切り替えのフィールド（maps/field_00_kit.js）。
//   出口: w → roa.gate, n → f_lookout.south, e → f_cape.west
//   絵: field/under/f_roa（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("f_roa", {
    name: "ロアの丘", region: "prologue", outside: "forest_dark",
    rows: [
      "FFFFFFFFFFFFFFFFFFFFF,,;;;;;;;;..;;;;;,,ww,rrrrrrrrr",
      "FFFFFFFFFFFFFFFFFFFFF,,,,;;;;;...;;;;;,,wwwrrrrrrrrr",
      "FFFFFFFFFFFFFFFFFFFF,,,,,,,;;;..;;;;;;,,wwwrrrrrrrrr",
      "FFFFFFFFFFF,,,,TTTT,,,,,,,,,;...,,,,;;;,www,rrrrrrrr",
      "FFFFFFFF,,,,,,;TTT,,,,,,,,,,;..,,,,,,;,,,ww,rrrrrrrr",
      "FFFFFFFF,,,,,;\"\"\"\"\",,,,,,,;;...,,,,TTT,,ww,,rrrrrrrr",
      "FFFFFFF,,,,,,;;\"\"\",,,,,,,,;...,,,,,TTT,,ww,,RRrrrrrr",
      "FFFFFF;;;,,,,,,,;\"\",b,,r,,...,,,,,,TTT,,ww,,RRRRrrrr",
      "FFFFF,;;;,,X,X,,,\"\",,,,,,...,,,,,,,,,,,ww,,,,\"RRRRRR",
      "FFFFF,,;,,,,,,,X,,\",\",,,...,,,\",,,,,,,,ww,,,,,,,,RRR",
      "FFFFF,,,,,X,,c,,,,\"\"\",,\"..,,,\"\"\",,,,,,,ww,,,,,,,,,,,",
      "FFFFF,,,,,,,,,,,X,,,,,,..,\"\"\"\"\"\",,,,;;,w,,,,,,,,,,,,",
      "FFFFF,,,,,,X,,X,,,,,,,...,,\"\",,,,,,,;;,ww,,,,,,\",,,,",
      "FFFFF,,TT,,,,,,,,,,,,,..,,,TTTr,,,,T,;,ww,,\",,,,,,,,",
      "FFFFFF,TTRRRRcRRRR,,,..,,,TTTTT,;TTTT;,ww,,\"\",\",,,,,",
      "FFFFFF,TT,,,,,,,,TT,,..,\"\"TTTT,,;TTTT,,ww,\"\"\"\",,,,,,",
      "FFFFFF;;;,,,,,,,,TT,..cXc\"\",,,,,,,,T,,,www\"\"\"\",,,,,,",
      "FFFFF;;;;r,,,,;,,,,...ccc,,,,,,,,,,,,,,www\"\",,,,,,,,",
      "F.X....;;;,,;;;........,,,,,,,,,,,,,,,,www,,,,,,,,,,",
      "....................;....,,,,,,,,,,,,,,ww,,,,T,,,,,,",
      "FFFF........:...;;;;;;.....,,,,,,,,,,,,ww,,,TTTT\",,,",
      "FFXF,,,,;;;;:;;;;;;;;;;;.....X,,,,,r,,www,,,TTTTT,,,",
      "FFFF;,;;;;;;:;;;;;;;;;;;,,.....,,,,,,,www,,,TTTTT,,,",
      "FFFFF;;;;;;;:,;;;;;;;;;;,,,,.....,,,,,,ww,,,;TTT,,,,",
      "FFFFF;;;;,,,:,,,,,,,,r,,,,,,,,....,,,,,ww,,,;;;,,,,,",
      "FFFFF,;;,,,,:,XX,,,,,,,,,,,,,,,,....,,,ww,,,;;,,,,,\"",
      "FFFFF,,,,,XX,,,,XX,,,,,,,,,,,,,,,......==...,;,,,,b,",
      "FFFFF,,,XX,,,,,,,,X,,,,,,,,,,,,,,;;....==.....,,,,,,",
      "FFFF,,,X,XX,,,,,,,,X,,,,\"\"\",,,,,,;;;;;;ww,,,.....,,,",
      "FFFF,,,X,XX,,,,,,,,X,,,,\"ww,,,,,b;b;;;;ww,,,,,......",
      "FFFF,,,X,,,,,,,,,,,X,,,wwwwww,,,,;;;;;;ww,,,,,,,....",
      "FFFF,,,,X,,,,,,,,,,X,,wwwwwww,,TTT;;;;;www,,,,,,,,,,",
      "FFFF,,b,X,,,,,,,,,X,,,wwwwww,,,TTTT;;;;;ww;;,,,,,,,,",
      "FFFF,,,,,XX,,,,,XX,,,,,,ww,,,,,TTT,;,;;;\"ww,,,TTT,,,",
      "FFFF,,,r,,,XXXXX,,,,,,,,,,,,,,,,T,,b,,\";;ww,,TTTTT;;",
      "FFFF,,,,,,,,,;;;,,,,,,,,,,,,,,,,,,,,\"\"\"\"\"ww,,TTTTT;;",
      "FFFFF,,,,,,,,,;;,,,,,,,,,,,,,,,,,,FFF\"\"\",ww,FFFF;;;;",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,,wwwFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwwFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwwFFFFFFFF",
    ],
    objects: [
      {"type":"stairs","x":23,"y":16,"to":{"map":"well","spawn":"entrance"}},
      {"type":"sign","x":21,"y":15,"text":"旅人の古井戸\n枯れ井戸。底へ下りる縄ばしごがある。"},
      {"type":"examine","x":13,"y":10,"event":"world_poi_stones"},
      {"type":"examine","x":29,"y":21,"event":"world_poi_shrine"},
      {"type":"waylamp","id":"wl_pen_road","x":34,"y":23,"lit":"prologue_lamp_road","event":"world_pen_lamp"},
      {"type":"sign","x":5,"y":17,"text":"ロアの里\n語り部の里。"},
      {"type":"sign","x":43,"y":27,"text":"東 → 港町ファロス・灯台の岬\n北 → 見晴らし台・跳ね橋"},
      {"type":"chest","id":"f_roa_c1","x":49,"y":11,"item":"i_potion","n":1},
    ],
    npcs: [
      {"id":"shepherd","look":"npc_old_m_2","name":"羊飼いの年寄り","x":14,"y":31,"dir":"w","move":"still","cond":"prologue_done","talk":"world_shepherd","reward":"news","key":"world_shepherd"},
    ],
    spawns: {"roa":{"x":1,"y":19,"dir":"e"},"north":{"x":31,"y":1,"dir":"s"},"east":{"x":50,"y":29,"dir":"w"},"well":{"x":22,"y":17,"dir":"s"}},
    exits: [{"x":0,"y":19,"w":1,"h":2,"to":{"map":"roa","spawn":"gate"}},{"x":31,"y":0,"w":2,"h":1,"to":{"map":"f_lookout","spawn":"south"}},{"x":51,"y":29,"w":1,"h":2,"to":{"map":"f_cape","spawn":"west"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_prologue"}],
    art: {"image":"field/under/f_roa","painted":["stairs_down@23,16"]},
    meta: {"sub":"羊の丘と古井戸","worldRect":[222,246,70,60]},
    links: {"roa":{"map":"f_roa","spawn":"roa"},"well":{"map":"f_roa","spawn":"well"}},
  });
})(window.RPG);
