// 生成物（design/art_ref/gen/env/_tools/under/field_mine/ の areas_mine.py → fit.py → tomap.py）。手で直さない: 配置は areas_mine.py、当たりは fit.py で作り直す。
// エリア g_valley「鉱石の谷」（鉱山都市ドヴァンの門の谷、54×40）。エリア切り替えのフィールド（maps/field_00_kit.js、山地の凡例は field_mine_00_kit.js）。
//   出口: w → g_pass.east, e → g_rail.west
//   絵: field/under/g_valley（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("g_valley", {
    name: "鉱石の谷", region: "r_mine", outside: "rock",
    legend: R.FieldArea.MINE_LEGEND, theme: 'field', bgm: 'overworld', bbg: 'mine', propSet: 'mine', propSetBase: 'village',
    light: R.FieldArea.MINE_LIGHT,
    rows: [
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRXXXXXRRRRRRRRRRRRRRRRRRRRRRRR",
      ",,RRRRRRRRRRRRR,,,RRRRRRRXXXXXRRRRR,r;;;;,,,RRRRR,RRRR",
      ",,,,,,,,,,,,,,,;;,,,RRXXRXXXXXRXXR,,;r;;;;;;;,,,,,,,,,",
      ",,,,,,,,,,,,,,;;;;,,,,XX,,R.R,:XX,,,;;;;;;;;;,,,,,wwww",
      ",,,,,\",,,,,,,,,;;;,,\",,\"\"\"c..,,,,,,rrrrrrr;;;,,,wwwwww",
      ",,,,\"\"\",,,,,,,,;;;;,\",,\"\"\"c..,,,r,,TXXXXXX\"\",,wwwwwwww",
      ",,,,\"\"\",,,,,,,;;;TTTT,,,,\",..,,,,,,,XXXXXX,,wwwwwww,,,",
      ",,,,,,,,,,w,r,;;;rTTT,,,,,,..,,,,,,\"XXXXXX,wwwww,,,,,,",
      ",,,,,,,,rrrrr,;;;;,,,,,,,,..,,,,,,,\",,,,,,wwww,,,,,,,,",
      ",,;,,,;,rrrr,,;,,,,\",\"\",,...,,,,,,,,,,,,,Trww,,,,,,,,,",
      ";;;,,,;,rrr,,,,,,\"\"\"\"\"\",.....,,,,,,,,,,ww===,,,,,,,,,,",
      ";;;,T,,;;;;,,,,,,,,,,,,...,....,,,,,,,wwww,,,,,,,T,T,,",
      ";;TT,,TT,,,,,,,,,,.......,,,,....,,,,wwww,,,,,,T,,T,,,",
      ";,TTTTTT;,,,,..........,,,,,,,,....====w,,,,,,,TTTTTT,",
      ".......;...........,,,,,,,,,,,,,,..====.,,,,\",,TTTTT,,",
      "..............,,,,,,,,,,,,,,,,,,,,wwww=..,\"\"\"\",,....,,",
      ".......T;;;,,,,,,,,,,,,,,,,,,,,,,wwww.................",
      ";;;TTTTT;;;,,,,,,,,,,,,,,,,,,,,,wwww,,,,,........T....",
      ";;;TTTTT;;;,,,,,,,,,,,,,,,,,,,,wwww,,,,,,,;;;\";;,TT,,.",
      ";;;;;;;;;;;;,,wr,,,,,,,,,,,,,,wwww,,,,,,,,;;;\"\";;,,,,,",
      ";;;;;;;;;;;;,rrrrr,,,,,,,,,wwwwww,,,,,,,,r;rrrr\";,,,,,",
      ";;;;;;;;;;;;,rrrr,,,,,,,,,wwwwww,,,,,,;;,;rrrrrr;,,,,,",
      ",,;;;;;;;;;;;;,,,,,,,,,,wwwwww,,,,,,,,;;;;rrrrrr;;,,,,",
      ",,,;;;;;;;;;;;;,,,,wwwwwwwww,,,,,,,,,,;;;;rrrr,;;;,,,,",
      ",,,,;;;;;;;;;;;,wwwwwwwwww,,,,,,,,,,,;;;;;;\",,;r;T;,,,",
      ",,,,,,,;;;;,,wwwwwwwwww,;;;,,,,,,,,,,;;;;;;\"\";r;;;;;;;",
      ",,,,,,,;;wwwwwwwwww,\";;;;;;;;,,,,,,,,;;;;;;\";;TTTTT;;;",
      ",,,,,,,wwwwwwww,,;;;;;;;;;;;;,,,,,,,;;;;;;;;\"\"TTTTT;;r",
      "rrrrrrwRwwwww,,,;;;;;;;;;;rrr,,,,,,,,;;;;;;;\"\"\",TTrrrR",
      "RRRRRRwwwwwRRrrrrrrrrrrrrrRRRrrrrrrrrrrrr;;;rrrrRRRRRR",
      "RRRRRwwwwRRRRRRRRRRRrRRRRRRRRRRRRRRRRRRRRr;rRRRRRRRRRR",
      "RRRRwwwRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRwwRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRwwRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRwwRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    ],
    objects: [
      {"type":"door","x":27,"y":8,"to":{"map":"dovan","spawn":"gate"}},
      {"type":"sign","x":24,"y":12,"text":"鉱山都市ドヴァン\n地の底の町。門の奥へ。"},
      {"type":"examine","x":38,"y":13,"event":"mine_sorting_shed"},
      {"type":"chest","id":"g_valley_c1","x":8,"y":16,"item":"i_ether","n":1},
      {"type":"waylamp","id":"wl_g_valley_1","x":14,"y":21,"lit":true},
      {"type":"waylamp","id":"wl_g_valley_2","x":23,"y":12,"lit":true},
      {"type":"waylamp","id":"wl_g_valley_3","x":44,"y":20,"lit":true},
    ],
    npcs: [

    ],
    spawns: {"west":{"x":1,"y":20,"dir":"e"},"east":{"x":52,"y":22,"dir":"w"},"gate":{"x":27,"y":9,"dir":"s"}},
    exits: [{"x":0,"y":20,"w":1,"h":2,"to":{"map":"g_pass","spawn":"east"}},{"x":53,"y":22,"w":1,"h":2,"to":{"map":"g_rail","spawn":"west"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_mine"}],
    art: {"image":"field/under/g_valley","painted":[],"overlay":"field/under/g_valley_over"},
    meta: {"sub":"鉱山都市ドヴァンの門の谷","worldRect":[334,76,54,40]},
    links: {"dovan":{"map":"g_valley","spawn":"gate"}},
  });
})(window.RPG);
