// 生成物（design/art_ref/gen/env/_tools/under/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// エリア f_windhill「風鳴りの丘」（ユーラと北の峠への道、52×44）。エリア切り替えのフィールド（maps/field_00_kit.js）。
//   出口: e → f_fern.west, n → yura.gate, n → world.f_windhill_n
//   絵: field/under/f_windhill（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("f_windhill", {
    name: "風鳴りの丘", region: "r_forest", outside: "forest_dark",
    rows: [
      "FTFFFFFTT;;...;;;;;;;;;,T;;;;;;;;;RRRRT..RRRRRRRRRRR",
      "FTFFFFFTT;;..,;;;;;;;;;;;;;;;;;;;;RRRRr..RRRRRRRRRRR",
      "FFFFFFFFTT;..,,;;;;;bT;;;,,,;;;;;;RRRRr..RRRRRRRRRRR",
      "FFFFFFFTTTT..,,;;;;;;;;;,,,,,;;;;;RRRRr..RRRRRRRRRRR",
      "FFFFFFFFTTT...,;;TT;;;;;,,,,;;,;;;;;;;,..;;rrbTrrrrr",
      "FFFFFFFFFTT...,;;;;;;;;;,,,;;;,;;;;;;;,..;;;;TTTTTTT",
      "FFFFFFFFFTT...,;;;;bT;;,,,,,;;;;;;,,;;,...;;;rTFFTTT",
      "FFFFFFFF,,,...,;;;T;;;;,,,,,;;;;;;;;,;,,..;;rwwwwTTT",
      "FFFFFFFFTTTT..,,TTT;;;,,,,,,;;;;RRRR,;;;..;;rwwwwwrT",
      "FFFFFFFTTTT...,,,;;;;,,,,,,,,RRrrrr;RRR;...rrwwwwwrT",
      "FFFFFFFTTTTT.,,,TT,TT,,,,,,RRrr;,,,,;rRR,..,,rwwwwrT",
      "FFFFFFFFTFFTT,.FFT,,,b,,,,,Rr;;;,,,X,,,RR..,,,rwwrFF",
      "FFFFFFFFFFFTT..FFT,,,,,,;TR,,,;rXr;r,,,,R..,XXXrrrFF",
      "FFFFFFFFFFFFT..FFT,,,,,,,RRr,,;r,;X,,Xr,RR.,XXX,TTTF",
      "FFFFFFT,,,FFT..FF,,,,,,,,,R,,;;r,X,,,,,,RR.,,;;,,,TF",
      "FFFFFT,,,,,FFr.FFTT,,,,,,,R,,;;::,,,,,,,Rr.,;;;;;;;F",
      "FFFFF,,,,,,FFT..FF,,T,,,,,.R,;;:r,,,,,,RR.,,;;r;;;;;",
      "FFFFT,,,,,,TT...FFFTT;TT,,,R,,:r,,,,,,RR..,,;;;;;;;;",
      "FFFFT,,,,,;;;TT..TFTT,;T,,,,ccR;,,,,RRRr..,,;;;;;;;;",
      "FFFF,,,,,,r;FT....FT,,;;;;;;ccRRRRRRRR,..,,,;;;;;;;;",
      "FFFFFrr,,,,FFF;...TT,,;;;;;:::;;,,,,;;;..,,,;;;;;,;;",
      "FFFFFT,;;,,FFFFT.::,,TT;;;;::;;;;;;;;;..;,;;;;;,,,,,",
      "FFFFFT;;;;FFFFT,,::..,;;;;;:;;;;;;;;;...;,;;;,,,,,,,",
      "FFFFT;b;;;;,FTT;::;......;;:;;;;;;;;;..;;;;;,,,,,,,,",
      "FFFF;;,;;;;;;;;::;;;;.....::....;;;;..;;;;;;,,,,,,,,",
      "FFFF;;T;brr;;;::;;;,TT;;..::..........;;;;;;,,,,,,,,",
      "FFFFF;;;rTr;;::;;;;;T;;;;;;;;;;;........;;;;;;,,,,,;",
      "FFFFFF;,,rrr;::;;;;;;;;;;;;;;;;;;;;;;.....;;;;;,,,;;",
      "FFFFFFT,,,,,::,;;;;;,;;;;;;;;;;;;;;;;;;.....;;;;;;TT",
      "FFFFFFT,,X,::,,,;;;,;;;;;;;;;;;;;;;;;;;.............",
      "FFFFFF,,XXX::,,,;;;TT;;;;;;;;;T;;;;T;;TTTF..........",
      "FFFFFF,,,,::,,,;;;;;;;;;;;;,;;T;;;TT,;TTTFF;.;;;;;;;",
      "FFFFFF;,,,,,,,;;;;;;;;;;;;;TT,;;;;;TFT;;TbTTT,;;;;;T",
      "FFFFFTT;;,,,,;;;;;;;;;;;;;T,,,,T,,,,;;;;;,,TTT;;;;;F",
      "FFFFFTT,;;;;;;;;;;;;;;,,TFFTF,,T,,;TT;;;;,,,;;;;;;;F",
      "FFFFFF,,,,,,T;;FFFFFTTTFFFFFF,FFFFFT,;;;;,T,,;;;;;FF",
      "FFFFFFF,,,FFFFFFFFFFFFFFFFFFFFFFFFF,;;;TTFF,,,;FFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFTFFFFTT,FFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
    ],
    objects: [
      {"type":"examine","x":34,"y":13,"event":"windhill_notes"},
      {"type":"sign","x":30,"y":19,"text":"風鳴りの丘\n風が歌のように鳴るという。"},
      {"type":"examine","x":10,"y":31,"event":"world_poi_forest_statue"},
      {"type":"prop","id":"tent","x":20,"y":13},
      {"type":"prop","id":"lantern","x":22,"y":13},
      {"type":"sign","x":15,"y":6,"text":"北 → 苔の村ユーラ"},
      {"type":"sign","x":42,"y":6,"text":"北の峠を越えて\n↑ 雪の村ユール"},
      {"type":"prop","id":"beacon","x":3,"y":40,"cond":"cleared_r_forest"},
      {"type":"waylamp","id":"wl_15","x":17,"y":25,"lit":true},
      {"type":"chest","id":"f_windhill_c1","x":47,"y":15,"item":"i_ether","n":1},
    ],
    npcs: [
      {"id":"guard_north","look":"npc_guard_1","name":"番人","x":41,"y":4,"dir":"s","move":"still","pushable":false,"cond":{"slice":true},"talk":{"lines":[{"text":["北の峠は、雪崩で\nふさがってしまったんだ。","雪原へ行くのは、\n雪が落ちつくまで待ってくれ。"]}]},"reward":"news","key":"world_guard_north"},
    ],
    spawns: {"east":{"x":50,"y":30,"dir":"w"},"yura":{"x":12,"y":2,"dir":"s"},"pass":{"x":39,"y":1,"dir":"s"}},
    exits: [{"x":51,"y":30,"w":1,"h":2,"to":{"map":"f_fern","spawn":"west"}},{"x":12,"y":0,"w":2,"h":1,"to":{"map":"yura","spawn":"gate"}},{"x":39,"y":0,"w":2,"h":1,"to":{"map":"world","spawn":"f_windhill_n"},"cond":{"not":{"slice":true}}}],
    triggers: [],
    tilePatches: [{"cond":{"slice":true},"rect":[38,1,4,2],"rows":["rrrr","rrrr"]}],
    zones: [{"rect":null,"zone":"zw_forest"}],
    art: {"image":"field/under/f_windhill","painted":[],"overlay":"field/under/f_windhill_over","closed":"field/under/f_windhill_closed"},
    meta: {"sub":"ユーラと北の峠への道","worldRect":[40,128,92,124]},
    links: {"yura":{"map":"f_windhill","spawn":"yura"}},
  });
})(window.RPG);
