// 生成物（design/art_ref/gen/env/_tools/under/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// エリア f_cross「北の野」（三つの道の分かれ道、60×40）。エリア切り替えのフィールド（maps/field_00_kit.js）。
//   出口: s → f_lookout.bridge, w → f_hut.east, e → world.f_cross_e
//   絵: field/under/f_cross（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("f_cross", {
    name: "北の野", region: "r_forest", outside: "forest_dark",
    rows: [
      "rrrFFrrrFFFFFFFFrrrrrrrrrrFrFFrFFFFrFrrrrrrrFFFrrrrrrFFFrrrr",
      "rrFFFrrrFFFFFFrrrrrrrrrrrrrFrFrFFFFFrrrrrrrrrFFrrrrrrFFFrrrr",
      "rFFFFrrrrrFFFFrrFrrrrrrrrrrrrrrFrrrFrFrFrrrrrFFrrrrrrrFrFrrr",
      "rFFFFFrrrrFFFFFrFrrrrrrrr,r,,,FrrrrFRRRFrrrrFFrFrFrrrrrrrFFr",
      "FFFFFrrRRRRFFrFrrrrrr,,,,,,,,rRRRRRRT\";RRRRrFFrrrrrrrrrrrRRR",
      "RRRRRRRr;;,RRRRRrrrrRr,,RR,,,,r,,;,,\";;;,;,RRRrRRRRRRRRRRrrb",
      ";;;r;;,r,,,,,rrrRRRRRRRRrrrrr\",,,;,,\",,,,,;rrrrrrrrrrr;;;;;,",
      ";r;;;;,,,,,,,,,,,,;;XXXcccXX\",,,,;,,,,,,,,,,,,,rbrr;;;;;;;,,",
      "r;;;;,,,,,,,,,,,,,;;XccccccX,,,,,;,,,r,,,,,,rwwwwwTr,;;r;,,,",
      ";;,,,,,r,,,,rr,,,,,;XccccccXr,,,,,,,,;;;;,,wwwwwwww~rr,,,,,,",
      ";;,,,,;;,,,,r,,,,,,,cccccccXrr,,,,;;;XXXXbwwwwwwwwwww~,,,,\",",
      ",,,,r,,r,,,,,,,,,,,,ccccccccrr,,,,;;;XXXXbwwwww==wwwwwb,\",,,",
      ",,,,\",,TTTr,,,,,\",\",,,\"\",::\"r\",,\";;;;XXXXrwwwww==www~br,\"\"\",",
      ",,,,,,,TTTr,,,,,,,,,,,,,,::,,,,,;;;;,;r;;,,bwww==www~,,\"\",,,",
      ",,,,,,,,Tr,,,,,,,,,,\",,,,,::,,,,,;;;;;;;;;,,bww==~r,,,,\"\",,,",
      ",,,,,,,,,,,,,,,,,,,,\",,,r,::,,,,;;;;;;;;:::::,:==r,,,,,,,,,,",
      ",,,,,,,,,,,,,b,,,,,,\"b,,,,,::,,,;;;;;;;;:::::::,,,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,,::,,,;;;;;;;;:::::::,,,,,,;,,,,,.",
      ",,;,,,,,,,,,,,,,,,,,,,,,,,,,:,,,;,;;;;;;;;;;::;,,...........",
      "r;;;,,,,,,,,,,,,,,,,,,,,,,,,::..............::..............",
      ";;;;,,,,,,,,,;;,,,,,,,.......:....................,,;;;;;;;\"",
      ".....,,,,,,,;;;;,,............,r,;;;;;;;;;;..;,,,,,,;;;;;;;;",
      "............,.........,,,,,,..rX,;;;;;;;;;;;;;,,,,,,;;;;;;;;",
      ",;;;..............,,,,,,,,;;..;;;;;;;;;;;;;;XX,,,,,,;;;,,,,r",
      ",,,,,,,,,,,..;;;;;\"\",,\"\"\",;;..;;;;;;;\";;;;;;;;;,,,,,;;;,,,,,",
      ",,,,,,,,,,;;;;;;;;;;,,,,,,;;..;;;;;;;;;;;;r;;;;,,,,,,,,,,,,,",
      ",,,,,,,,,,;;;r;;;;;;,,,,,,,..;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,",
      ",,,,,,,,,;;;;;;;;;;;;,,,,,;..;;;,;;;;;;rr;r;;;;;;;;,,,,,,r,,",
      ",,,,,,,,,rrr;;;;;;;;;,,,,;;..,,;\"\";;;rrTTTT;;;;;;;;,,,,,,,,,",
      "b,,,,,,,,TTTr;;;;;;;,,,;;;;...,;\";;;;;TTTTT;;;;;;;;\",,br,,,,",
      ",,,,r;;,TTTTr;;;;;;;,,;;;;;...;;;;;;;rTTTTr;;;;;;;;,,,TTr,,,",
      ",,,,\"\";;TTTTr;r\";;;;;;;;;;;...;;;;;;;;,;;r;;;;;;;;;;\"TTTr,,,",
      ",,,,\"rr;;;rr\"\"\"\"\";;;;;;;;rcc.ccc;;;;;;,;;;;;;;;;;;;;\"TTTr,;;",
      ",,,,\";;;;;;\";;;\";;;;;;;;;rcccccc;;;;;;;;;;;;r;;;;;;r\";;;;;;;",
      ",,,;;;;;;;;;;;;;r;;;;;;;;rcccccc,;;;;;;;;;;;;;;;;;;rrrrrrrrr",
      "rrrrrrrrrrrrrrrrrrrrrrrrrrrr==rrrrrrrrrrrrrrrrrrrrr~~~~~~~~~",
      "~~~~~r~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    ],
    objects: [
      {"type":"sign","x":31,"y":19,"text":"北の野の分かれ道\n西 → ヴェルダの森・フェルン\n東 → ガルド山地\n南 → 跳ね橋・ファロス半島"},
      {"type":"examine","x":24,"y":10,"event":"world_poi_plains_found"},
      {"type":"examine","x":25,"y":10,"event":"world_poi_cache","item":"i_potion","key":"world_poi_plains_found"},
      {"type":"examine","x":44,"y":23,"event":"world_poi_stones"},
      {"type":"prop","id":"tent","x":41,"y":15},
      {"type":"prop","id":"lantern","x":43,"y":16},
      {"type":"waylamp","id":"wl_rest_3","x":47,"y":23,"lit":true},
      {"type":"prop","id":"lamp_post","x":27,"y":32},
      {"type":"prop","id":"lamp_post","x":31,"y":32},
      {"type":"chest","id":"f_cross_c1","x":47,"y":11,"item":"i_potion","n":2},
    ],
    npcs: [
      {"id":"traveler_plains","look":"npc_merchant_2","name":"旅の行商人","x":42,"y":17,"dir":"s","move":"still","talk":"world_traveler_plains","reward":"news","key":"world_traveler_plains"},
      {"id":"guard_east","look":"npc_guard_1","name":"番人","x":54,"y":18,"dir":"w","move":"still","pushable":false,"cond":{"slice":true},"talk":{"lines":[{"text":["東の峠は、ゆうべの\n崖崩れで通れないんだ。","山地の鉱山町へ行くなら、\nしばらく待ってくれ。"]}]},"reward":"news","key":"world_guard_east"},
    ],
    spawns: {"bridge":{"x":28,"y":38,"dir":"n"},"west":{"x":1,"y":22,"dir":"e"},"east":{"x":58,"y":18,"dir":"w"}},
    exits: [{"x":28,"y":39,"w":2,"h":1,"to":{"map":"f_lookout","spawn":"bridge"}},{"x":0,"y":22,"w":1,"h":2,"to":{"map":"f_hut","spawn":"east"}},{"x":59,"y":18,"w":1,"h":2,"to":{"map":"world","spawn":"f_cross_e"}}],
    triggers: [],
    tilePatches: [{"cond":{"slice":true},"rect":[55,17,3,4],"rows":["rrr","rrr","rrr","rrr"]}],
    zones: [{"rect":null,"zone":"zw_forest"}],
    art: {"image":"field/under/f_cross","painted":[],"overlay":"field/under/f_cross_over","closed":"field/under/f_cross_closed"},
    meta: {"sub":"三つの道の分かれ道","worldRect":[232,124,120,96]},
    links: {},
  });
})(window.RPG);
