// 生成物（design/art_ref/gen/env/_tools/under/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// エリア f_lookout「見晴らし台」（跳ね橋と北の海、48×40）。エリア切り替えのフィールド（maps/field_00_kit.js）。
//   出口: s → f_roa.north, n → f_cross.bridge
//   絵: field/under/f_lookout（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("f_lookout", {
    name: "見晴らし台", region: "prologue", outside: "sea",
    rows: [
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~~~~RRRR~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~~~RRRRRRRRRRRRR",
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~~~~~~RRRRR,,;rRRRRRR",
      "~~~~~~~~~~~~~~~~~~~~~~==~~~~~~RRRRR,,,,,;;;,,,,R",
      "~~~~~~~~~~~~~~~~~~~~cccccc~~RRRRR,,,,,,,,,,,,,,R",
      "~~~~~rr~~~~~~~~~~~rrccccccRRRR,,,,,,,,,,,XX;;;,R",
      "rrrrrrrrrrrr~~~rrrr\"ccccccRR,,,,,,,r,,,,,XX;;;,R",
      ",,,,\"\"r,;,,rrrrr;;;\"cccccc;;;;,,,,,,,,,,,,;;,,,R",
      "\",\"\"\"\"\";;,,,;;;;;;,,,..;;;;;;;,,,,,,,,,::,;,b,,R",
      "b\"\"\"\"\"\"\";,,,;;;;;;,,\"..;;;;;;;,,,,,,,,::,,r,,,,R",
      "\"\"\"\"\"\"\";\"T,;;;;;;;,,,,..;;;;;;\";;,,,:::,,,,,,,,R",
      "\"\"\"\",\"TTTTT;;;;;;;,,,,..,,;;\";\",,,,:::,,,,,,,,,R",
      "TTTTTTTTTTT;;;;;;,,,,,..,,,,\"\",,,,:::,,,,,,,,,,R",
      "TTTTTTTTTTTT;;;,\",,,,,..,,,\"\"\",,,:::,,,,,,,,;,,R",
      "TTTTTTTTTTTTTT,,\",,,,,..,,,\"\"\",:::,,,,,,,,,;;;RR",
      "TTTTTTTTTTTTTTT,\",,,,,,..,,\"\"::::,,,,,,,,,,;;;r\"",
      "TTTTTTTTTTTTTTT,;,,,,,..,,,::::,,,,,,,,;;;;;;;;;",
      "TTTTTTTTTTTTTTT;;;;;r,..,::::,,,,,,,,,,,\";;;;;;,",
      "TTTTTTTTTTTTTTT;;b;;;;.::::,,,,,,,,,,,r\"\"r\";;;;,",
      "TTTTTTTTTTTTTT;;;;;;;;.::\",\",\",,\"\",,,,\";;\";;;;;,",
      "TTTTTTTTTTTTTT;;;;;;;..,,,\"\"\"\"\"\"\"\"\"b\",;;;;;;;;;,",
      "TTTTTTTTTTTTT;;;;;;;;..,,\"\"\"\"\"b\"\"\"\"\"\"\";;;;;,;;;,",
      "TTTTTTTTTTTTT;;;,,,;;..\"\"\"\"\"\"\"\"\"\"\"\"\"\"\";;;;,,,,,,",
      "TTTTTTTTTTTTT,,,,b,;,..,,,,\"\"\"\"TTTT\"\";;;;;,,,,,\"",
      "TTTTTTTTTTT;;\",,,,;,,..,,,,\"\"\"\"TTTTT;;;;;;,,,,,,",
      "TTTTTTT,;;;;,,,,,,,,,;..,,,,\"\",TTTT;;;;TTT,,,,,,",
      "TTTTT,,,,;;;,,;;;;;,,,...,,,\",,;;;;;;;,TTTT,,,,,",
      ",,,,,,,,,;;;,,;;;;;,,,,..,,,\";;;;;,,,,TTTTT;,,,,",
      ",b,,,,,,;;;;;;;;;;;;,,,..,,\"\"\";;;,,,,,TTTTT;;;;;",
      ",,,,,,,,,;b;TTTr;;;;;,\"\"..\"\"\";;;;;,,,,,T\"\"\";;;;\"",
      ",,,,,,,,,,,TTTTT\";,,;,,\"..\"\"\"\";;;,,,,,r\"\"\"\";;;;\"",
      ",,,,,,,,,,,,TTT;;FF,;;,\"..\"b\"\",;;,,,,,,,\"\";;;;;\"",
      "FFFFFFFFFF,FFFFFFFFFFFFF..\"FFFFFFFF,,FFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFFFF",
    ],
    objects: [
      {"type":"waylamp","id":"wl_pen_lookout","x":40,"y":12,"lit":"prologue_lamp_lookout","event":"world_pen_lamp"},
      {"type":"examine","x":41,"y":12,"event":"world_poi_pen_lookout"},
      {"type":"sign","x":38,"y":15,"text":"見晴らし台\n半島の北の海を見わたす。"},
      {"type":"prop","id":"bench","x":43,"y":14},
      {"type":"prop","id":"lamp_post","x":20,"y":13},
      {"type":"prop","id":"lamp_post","x":25,"y":10},
      {"type":"prop","id":"bollard","x":21,"y":10},
      {"type":"sign","x":26,"y":13,"text":"跳ね橋\n北 → 北の野"},
      {"type":"chest","id":"f_lookout_c1","x":45,"y":9,"item":"i_ether","n":1},
    ],
    npcs: [
      {"id":"bridge_guard","look":"npc_guard_2","name":"橋番","x":24,"y":11,"dir":"w","move":"still","pushable":false,"talk":"world_bridge_guard","reward":"news","key":"world_bridge_guard"},
    ],
    spawns: {"south":{"x":24,"y":38,"dir":"n"},"bridge":{"x":22,"y":1,"dir":"s"}},
    exits: [{"x":24,"y":39,"w":2,"h":1,"to":{"map":"f_roa","spawn":"north"}},{"x":22,"y":0,"w":2,"h":1,"to":{"map":"f_cross","spawn":"bridge"}}],
    triggers: [],
    tilePatches: [{"cond":"!prologue_done","rect":[22,1,2,8],"rows":["~~","~~","~~","~~","~~","~~","~~","~~"]}],
    zones: [{"rect":null,"zone":"zw_peninsula"}],
    art: {"image":"field/under/f_lookout","painted":[]},
    meta: {"sub":"跳ね橋と北の海","worldRect":[238,214,70,46]},
    links: {},
  });
})(window.RPG);
