// 生成物（design/art_ref/gen/env/_tools/under/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// エリア f_south「森の南」（きこりの野営地と古い塔、56×48）。エリア切り替えのフィールド（maps/field_00_kit.js）。
//   出口: n → f_fern.south, s → world.f_south_s
//   絵: field/under/f_south（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("f_south", {
    name: "森の南", region: "r_forest", outside: "forest_dark",
    rows: [
      "TTTTTTFTTTFFFFFTTTTTTTTTTTT;;...;;TTTFFFTTTTTTTTTTTTTTTT",
      "TTTTTTTTTTFFFFTTTTTTTTTTTTTT;...;;TTTTTTTTwTTTTTTTTTrTTb",
      "TTTTTTTTTTTFFFTTTTTTTTTTTTTTT...T;T;TTTTTTTTTTTTTTTTTTTT",
      "TTTTTTTTTTTTTFFTTTTTTTTFFF,,,...X;;,,;TTTTTTTTTTTTTFFTTT",
      "FFTTTTTT,;TFFFFTFFTTTFFFFF,,X..TXT,;;;;TTTFTTTTTTTTFFTTT",
      "FFFTT,,,,TTFFFFFFFFFFFFFFFX,,,.TXT,,;FFFFFFFTTTTTTTFFTTT",
      "FFFT,,,,,T;TFFFFTFFFFFFFFT,,,,..,T,rFFFFFFFFTTTTTTTFFFFT",
      "FFFT,,,,,;,FFFFTFFFFFFFFFT,,,,...,,TTTFFFFFFTTTTrTTTTTTF",
      "FFF,,XXXXX,FFFFTTTTTTTFFT,,,,,,...,,TTFFFFFFTTTTTTTTTTTT",
      "FFF,sXXXXX,,TTTTrTTTTTTTT,,,,,,,..XTTTFFFFFFFTTTTTTTTTTT",
      "FFFFFXXXXXT,,,,TT;T;;;T;;;X,,,,,...TTTFFFFFFFFFFFFFFTTTT",
      "FFFFFXXXXXTT,,,,,;;T;;;;;;,,,,,,,..,FFFFFFFFFFFFFFFFTTTT",
      "FFFFFXXXXXXX,,,,,;;;;;;;;,,,,,,,FF..FFFFFFFFFFFFFFFFTTTT",
      "FFFFFF::TTXX,,,,,;;;;;TTTTFFFFFFFF.TFFFFFFFFFFFFFFFFTTTT",
      "FFFFF,:,,,,::,,,,;;;;;TTFFFFFFFFFF...FFFFFFFFFFFFFFTTTTT",
      "FFFFFF,,,,,::,,,,;;;;;TFFFFFFFFFFF..T,TFFFTFFFFFFFTTTTTT",
      "FFFFFF,,,,,,T,,,,;;;;TTFFFTFFFFFFT,...,,,TTTFFFFFFFTTTTT",
      "FFFFFF,,,,,,::,,;;;;;TTFFFTbTTTTTT,,.XXX,,,TFFFFFFFFTTTT",
      "FFFFFFF,,,,,,:,,T;F,;TTFFFTTTTTT,,,,TXXX,X,,,FFFFFFFTTTT",
      "FFFFFFFF,,;;,::;;TTT;TTFFFFTTTT;,,,:TXXX,X,T,,FFFFFFTTTT",
      "FFFFFFFFT;;;;;:TTTFTTTTTTFFTTbT;,,,:::,,,,,r,,FFFFFFTTTT",
      "FFFFFFTTTT;;;;::TTTTTTTTTTFT,TT,,,,XXX:,X,,,,,FFFFFFTTTT",
      "FFFFTTTTTT;;,.,:TTTTT,TTTTT,,,,,,..XXX:,,,,,T,,FFFFFbTTT",
      "FFFFTTTrT;,,,s.::TT,,,,,TTTT,,,,...XXX::,,,T,,,FFFFFTTTT",
      "FFFFTT;;;;,,,,,,,::,,,,,,TTT,,....,XXX,:,,,,,,,FFFFFTTTT",
      "FFFFTT;;;;TFFF,,,,::,,,,,,......,,,,r,,::,,,,;FFFFFFTTTT",
      "FFFT;;,;;;TTFF,,,,,:::........,,,,,,,,,T:,,,,;TTTTTFTTTT",
      "FFFTT,;;;TTTTTT,,,,,:::...,,,,,,,,,,,,,,::,,,,TTTTTFTTTT",
      "FFFTT,,F,FFFFFT,,,,,.::,,,,,,,,,,,,,,TT,::,,,,,wwwwwwwTT",
      "FFFTFFFF,,FFFFFT,,,...,,,,,,,,,,,,T,,,,,T:,T,,,,,,wwwwww",
      "FFFTFFFFFFFFFFFT;,,..,,,,,,,,,Tw,,,,,,,,::,,,,TTTTTTTTww",
      "TFFTFFFFFFwwwwwww,,__,,,,,,,,,,,,,,wwww,__,wwTwwwwbwwwFF",
      "wFFFFTTTwwwwwwwww,___.,wwwwwwwwTwwwwwwwTT.TwwwwwwwwwwwwT",
      "wwwwwwwwwwFFFwTwwTww;wwwwwwwTwwwwwwwwwwww,wwww,,;;;;,,TT",
      "wwwwwwwwTwwwTwwwwTww;wTwwwTTwwTw,,,w,,,:w,,,w,,FF,;;,,TT",
      "wwwwwwwwwwwTTTTT;FT.,wwwwwwTwFFFF,,,,,T::,,,,,,FFF,,,,,,",
      ",wwwwwwwwwTTTT;;,FT.,,;;;;,FFFFFFFFT,,T,,,,,,,,FFFFF,,,,",
      ",,,,T,,,,,,;;;;;,F..,,;;;;TTTFFFFFFTT,,,,,,,,,FFFFFTT,,,",
      ",,,,,,,,,,,;;;;;TTT..,,,,,XXTTFXXTTTT,,,,,,,,,TTTTTTT,,F",
      ",T,,,,;;;;,;;;;,,TT..,,,,,XX,TTXXTTTTT,,,,,;;TTTTTTT;,,,",
      "TT,,,,;rr;,;;TT,,,,..,,,,,,,,,,,TTTTT;,,,,,,,,TT,TT;,;TF",
      ",,,,,,;TT,,FFFTT,,,..,,,T,,,,,,,,,;;TTT,,,,,,,,,,;;;T;;T",
      ",,,,,,;;;,TFFFFTF,,,..,,,,,,,,,,,,;TTFFT,,,,,,,;,;;;T;TT",
      ",,,,,RR,,RRRFFTTTF,,..,,,,,,,,,,,,,RRRRRRR,,,,,RRRR,,,RR",
      "R,R,,RRRRRRRRRRRRTT;...,RRRRR,RR,,RRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRTrTr..RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRFT...RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRFF...RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    ],
    objects: [
      {"type":"examine","x":42,"y":21,"event":"world_poi_forest_ring"},
      {"type":"sign","x":40,"y":24,"text":"森の南の広場"},
      {"type":"sign","x":34,"y":26,"text":"双子の見張り塔\n修理中につき、立ち入り禁止。"},
      {"type":"examine","x":6,"y":12,"event":"world_poi_forest_tower"},
      {"type":"examine","x":7,"y":12,"event":"world_poi_cache","item":"i_ether","key":"world_poi_forest_tower"},
      {"type":"examine","x":30,"y":30,"event":"world_poi_stones"},
      {"type":"examine","x":32,"y":5,"event":"world_poi_shrine"},
      {"type":"prop","id":"tent","x":19,"y":24},
      {"type":"prop","id":"lantern","x":20,"y":24},
      {"type":"waylamp","id":"wl_17","x":31,"y":9,"lit":true},
      {"type":"waylamp","id":"wl_18","x":21,"y":39,"lit":true},
      {"type":"sign","x":23,"y":42,"text":"南の峠\n南 → ザハラ砂漠"},
    ],
    npcs: [
      {"id":"woodcutter_road","look":"npc_woodcutter_1","name":"きこり","x":21,"y":25,"dir":"w","move":"still","talk":"world_woodcutter","reward":"hint","key":"world_woodcutter"},
      {"id":"guard_south","look":"npc_guard_1","name":"番人","x":21,"y":42,"dir":"n","move":"still","pushable":false,"cond":{"slice":true},"talk":{"lines":[{"text":["南の峠は、砂嵐で\n道が埋まってしまったんだ。","砂漠へ行くのは、\n嵐がやむまで待ってくれ。"]}]},"reward":"news","key":"world_guard_south"},
    ],
    spawns: {"north":{"x":30,"y":1,"dir":"s"},"south":{"x":20,"y":46,"dir":"n"}},
    exits: [{"x":30,"y":0,"w":2,"h":1,"to":{"map":"f_fern","spawn":"south"}},{"x":20,"y":47,"w":2,"h":1,"to":{"map":"world","spawn":"f_south_s"},"cond":{"not":{"slice":true}}}],
    triggers: [],
    tilePatches: [{"cond":{"slice":true},"rect":[19,44,4,2],"rows":["rrrr","rrrr"]}],
    zones: [{"rect":null,"zone":"zw_forest"}],
    art: {"image":"field/under/f_south","painted":[],"overlay":"field/under/f_south_over","closed":"field/under/f_south_closed"},
    meta: {"sub":"きこりの野営地と古い塔","worldRect":[84,262,110,100]},
    links: {},
  });
})(window.RPG);
