// 生成物（design/art_ref/gen/env/_tools/under/field_ash/ の areas_ash.py → fit.py → tomap.py）。手で直さない: 配置は areas_ash.py、当たりは fit.py で作り直す。
// エリア a_bridge「潮見橋のたもと」（湿原と灰をつなぐ橋、48×40）。エリア切り替えのフィールド（maps/field_00_kit.js、灰の荒野の凡例は field_ash_00_kit.js）。
//   出口: n → m_bog.south, s → a_foot.north, 門 → haimi_inn.door
//   絵: field/under/a_bridge（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("a_bridge", {
    name: R.T('map.field_ash_bridge.a_bridge.name'), region: "r_ash", outside: "sea",
    legend: R.FieldArea.ASH_LEGEND, theme: 'ash', bgm: 'overworld', bbg: 'ash', propSet: 'ash', propSetBase: 'village',
    light: R.FieldArea.ASH_LIGHT,
    rows: [
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~X==X~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~kk~~~~X==X~~~~kk~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~kkkkkkkkkX==X~kkkkkkkk~~~~~~~~~~~~kk",
      "RRRR~~~~wwkkkkkkkkkkkk.=kkkkkkkkkkkkkkkkkkkkkkkk",
      "RRRRRRkkkkkkkkkkkkkkkk..kkkkkkkkwwwkkkkkkkkkkkkk",
      "RRRRRRRkkkkkkkkkkkkkkk..kkkkkkkkwwwkkkkkkRRRRRRR",
      "RRRRRRRsssssXXXXXXXsss..kkkkksssskssskkkRRRRRRRR",
      "RRRRRRRRssssXXXXXXXsss..ssssssssssssssssRRRRRRRR",
      "RRRRRRRRRsssXXXXXXXsss..sssssssssssssssRRRRRRRRR",
      "RRRRRRRRRsssXXXXXXXsss..sssssssssssssssRRRRRRRRR",
      "RRRRRRRRRsssXXX:XXXsss..sssssssssssssssRRRRRRRRR",
      "RRRRRRRRRssssrr::::rr::.ssssssssssssssRRRRRRRRRR",
      "RRRRRRRRRssssc:::::::::.ssssssssssssssRRRRRRRRRR",
      "RRRRRRRRRsssssssssssss..ssssssssssssssRRRRRRRRRR",
      "RRRRRRRRRuussssssssss..ssssssssssssssssRRRRRRRRR",
      "RRRRRRRRuuussssssssss..ssssssssssssssssRRRRRRRRR",
      "RRRRRRRRuuussssssssss..ssrsssrsssssssrsRRRRRRRRR",
      "RRRRRRRRuussrssssrsss..sssssssssssssrsssRRRRRRRR",
      "RRRRRRRRuusssssssssss..sssssrssrssssssssRRRRRRRR",
      "RRRRRRRRsssssssssssss..sssssssssssssssuuRRRRRRRR",
      "RRRRRRRRsssssssssssss..ssssssssrsssssuuuRRRRRRRR",
      "RRRRRRRRRssuuusssssss..sssssrssrsssssuuuRRRRRRRR",
      "RRRRRRRRRuuuuuurssss..ssssssssssssssuruuRRRRRRRR",
      "RRRRRRRRRuuuuuuuusss..sssssssrssssssuuuRRRRRRRRR",
      "RRRRRRRRRuuuuuuuusss..sssssssssssssuuuuRRRRRRRRR",
      "RRRRRRRRRRuuuuuuusss..ssssssssssrsssuuuRRRRRRRRR",
      "RRRRRRRRRRuuuuusssss..ssssssssssrsssuuRRRRRRRRRR",
      "RRRRRRRRRRuuusssssss...sssssssssssssssRRRRRRRRRR",
    ],
    objects: [
      {"type":"examine","x":24,"y":15,"event":"ash_bridge_sign"},
      {"type":"examine","x":21,"y":3,"event":"ash_bridge_sign"},
      {"type":"sign","x":26,"y":19,"text":R.T('map.field_ash_bridge.a_bridge.objects.2.text')},
      {"type":"sign","x":19,"y":25,"text":R.T('map.field_ash_bridge.a_bridge.objects.3.text')},
      {"type":"waylamp","id":"wl_a_bridge_inn","x":27,"y":21,"lit":true},
      {"type":"waylamp","id":"wl_a_bridge_1","x":26,"y":32,"lit":true},
    ],
    npcs: [

    ],
    spawns: {"north":{"x":22,"y":1,"dir":"s"},"south":{"x":21,"y":38,"dir":"n"},"haimi":{"x":15,"y":23,"dir":"s"}},
    exits: [{"x":22,"y":0,"w":2,"h":1,"to":{"map":"m_bog","spawn":"south"}},{"x":21,"y":39,"w":2,"h":1,"to":{"map":"a_foot","spawn":"north"}},{"x":15,"y":22,"w":1,"h":1,"to":{"map":"haimi_inn","spawn":"door"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":[19,14,7,29],"zone":"zw_ash_road"},{"rect":null,"zone":"zw_ash_plain"}],
    art: {"image":"field/under/a_bridge","painted":[]},
    meta: {"sub":R.T('map.field_ash_bridge.a_bridge.meta.sub'),"worldRect":[528,336,90,48]},
    links: {"haimi":{"map":"a_bridge","spawn":"haimi"},"ash_bridge":{"map":"a_bridge","spawn":"north"}},
  });
})(window.RPG);
