// 生成物（design/art_ref/gen/env/_tools/under/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// エリア f_fern「森の街道」（フェルンへの森の道、56×44）。エリア切り替えのフィールド（maps/field_00_kit.js）。
//   出口: e → f_hut.west, n → fern.gate_s, w → f_windhill.east, s → f_south.north
//   絵: field/under/f_fern（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("f_fern", {
    name: R.T('map.field_fern.f_fern.name'), region: "r_forest", outside: "forest_dark",
    rows: [
      "TTTFFFFFTTTT,,FFFFFFFFFFFFXX...XFTTTTTTTTTTFTTFFFFFFFFFF",
      "TTTFFFFFTTTT,,FFFFFFFFFFFFXT...XFTTTrTTTTTTTTTTFFFFFFFFF",
      "TTTFFFFFTTTT,,FFFFFFFFFTTTXr...XFFTTTTTTTTTTTTTFFFFFFFFF",
      "TTFFFFFFTTT,,,FFTFFFFFFTTTrrr..FFFFFFFFTTTTTTTFFFFFFFTTT",
      "TTTFFFFFTTT,;,FFFFFFFFFTTTrrr..FFFFFFFFFTTTTTTFFFFFFFTTT",
      "TTTFFFFFTTT,;;;FFFFFFFFTTTrrT..FFFFFFFFTTTTT,FFFFFFFTTTT",
      "TTTFFFFFFTT,;;;FTTFFFFFTTTTT...FFFFFFFrrrrT;,FFFFFFFTTTT",
      "TFFFFFFFTTT,,,FTTTFFFFTTTT,....,FFFFFFrrT,T;,FFFFFFFTTTT",
      "TFFFFFFTTTT,;,FTTTFFFTTTTT,....,,FFF,,,,,,,,,,FFFFFFTTTT",
      "FFFFFTTbTT,,,FFFFTrTTTTTTTT..,,,,FFFFF,,T,,,,FFFFFFFTTT;",
      "FFFFTTTTTT,,rTFFFrrXXTTTTT...,,,rFFFFFF,,,FF,,,FFFFFTTT;",
      "FFFFTFTTTTr,,,,FFrrXXXXXFFTT.,r,TTFXFFF,,,F,,,,,,FFFT;..",
      "FFFFFFFFT,,,,,,,FFFFFFXXFFTT..,TTFFFFFFFF,,,,,.T........",
      "FFFFFFFFT,,,,,,,FFFFFXXXFFTT.,,TTFFFFFFFFFTTT...........",
      "FFFFFT,,T,...,,T,FFrrXXFFFFTr;.,FFFFFFFFTTT...,,,....,,T",
      "TTTT..............;TrXXFFFFTT,,,FFFFFTTTTTTFFF,,;,.,,F,,",
      ".......................FXFTTT,,,TTTTTTTTTTTFFF,...,,,,,,",
      "..........F,,FFFF........TrTT..TTTTTTTFFTFTTT,X..,,,,,FF",
      ",,,;rFFFFFFFFFFFFFFFF.............TTFTTFTFT;.,..,,,,,,,,",
      ",,T;;FFFFFFFFFFFFFFFFFF,,,,...,,,,,.......;;;,,,FF,,,,,F",
      ",,,;FFFFFXFFFFFFFFFFFFFF,,,,..,,,,.........;;,,FFFFF,FFF",
      ",,;TFFTFFFFFFFFFFFFFXFFF,,,,,..,,TTFTTFFF,,;;,TTFFFFFFFF",
      "FTrTTbTFFTTTFFFFFFFFFFFF,,,r,..,,,TbTTFFFFT,T,TTXXFFFFFF",
      "FFwTTTTTTTTTFFFFFFFFFFFFF,,,r,..,TTTTTTFFTT,,,rTXXTTTFFF",
      "FFFrTTTTrTTTTTFFTTFFFFFFFFT,,,..,TFTTTTTTTT,,,rrrrTTTTTT",
      "RRFwwwwTTFTTTTTFFTFFFFFFTTTF,,..,TFFTTTTTTr,,,TrrrrTTFTT",
      "wRRRRRRrRRRrTTTFFFFFFFFFTTTFTr..,XXT,,TT,,r,r,,TrrTTTTTb",
      "wwwwwRRRRRRRRRFFFFFFFFFFTTTTT,..,XXTT,,,,,,r,,,,;rTTTTTT",
      "RRwwwwwwwwRRRRRFFFFFFFFFFFTFF...FFFFFT,,,,,,r,,,TTTTTTTT",
      "FRRRRRwwwwwwwwRRRRFFFFFFFFFFF...FFFFFF,,TT,,,,,FTTrTTTTT",
      "FFFFFRRRRRRwwwwwwRRRRFFFFFFFF..FFFFFFFT,,,TFFFFFTTrTTrTr",
      "FFFFTRRTTRRRRRRwwwwwRRRRRFFFF..FFFFFFFT,,,TFFFFFFTrrTTTT",
      "FFFFFFRTTrTrTRRRRRwwwwwRRRRRR==RRFFFFFT,,,FFFFFFTTTTTTTT",
      "TFFFFFFrTTTTTRRTFRRRRwwwwwwww==wRRRRFF,,,FFFFFFFTTTTTTTT",
      "TTTFFFFFTTTTTRRRrFFFRRRRRwwww==wwwwRRRFFFFFFFFFFTTTTTTTT",
      "TTTFFFFFFTTTbRRRRFFFFFFRRRRRR==RRwwwwRRRFFFFFFFFFTTTTTTT",
      "TTTFFFFFFTTTTRRRRTTTFFFrTTrrrr.FRRRwwwwwFFFFFFFFTTTTTrTT",
      "TTFFFFFFFFFFFFRrRRRRRRrrrrrrrr.FFFRRRwwwRRRFFFFFTTrTTTTT",
      "FFFFFFFFFFFFFFFFFFFFTTTTTrrFF...FTrrRRRwwwRRFFFFTTTTTTTF",
      "FFFFFFFFFFFFFFFFFFFTTTTTTTrFFF..FTrrrTRRwwwRRFFTTTTTTFFF",
      "FFFFFFFFFFFFFFFFFFFTTTTTTTTFFF..FTTTTTTrRRwwRRTTTTTTFFFF",
      "FFFFFFFFFFFFFFFFFFFTTTTrFFFFFF..FbTTTTTrrRRwwwwRRRTTFFFF",
      "FFFFFFFFFFFFFFFFFFTTTTrrFFFFFT..FTTTTTTTTRRRwwwRRRTFFFFF",
      "FTFFFFFFFFFFFFTTFTTTTTTTFFFFF...FTTTTTTTTFRRRwwwRFFFFFFT",
    ],
    objects: [
      {"type":"waylamp","id":"wl_forest_2","x":40,"y":18,"lit":"q_forest_fireflies_2","event":"forest_waylamp"},
      {"type":"waylamp","id":"wl_forest_3","x":30,"y":20,"lit":"q_forest_fireflies_3","event":"forest_waylamp"},
      {"type":"examine","x":21,"y":15,"event":"world_poi_shrine"},
      {"type":"sign","x":30,"y":4,"text":R.T('map.field_fern.f_fern.objects.3.text')},
      {"type":"sign","x":33,"y":21,"text":R.T('map.field_fern.f_fern.objects.4.text')},
      {"type":"prop","id":"mushroom_glow","x":43,"y":27},
      {"type":"prop","id":"mushroom_glow","x":44,"y":24},
      {"type":"chest","id":"f_fern_c1","x":46,"y":26,"item":"i_ether","n":1},
    ],
    npcs: [

    ],
    spawns: {"east":{"x":54,"y":12,"dir":"w"},"fern":{"x":28,"y":2,"dir":"s"},"west":{"x":1,"y":16,"dir":"e"},"south":{"x":30,"y":42,"dir":"n"}},
    exits: [{"x":55,"y":12,"w":1,"h":2,"to":{"map":"f_hut","spawn":"west"}},{"x":28,"y":0,"w":2,"h":1,"to":{"map":"fern","spawn":"gate_s"}},{"x":0,"y":16,"w":1,"h":2,"to":{"map":"f_windhill","spawn":"east"}},{"x":30,"y":43,"w":2,"h":1,"to":{"map":"f_south","spawn":"north"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_forest_road"}],
    art: {"image":"field/under/f_fern","painted":[],"overlay":"field/under/f_fern_over"},
    meta: {"sub":R.T('map.field_fern.f_fern.meta.sub'),"worldRect":[112,188,90,74]},
    links: {"fern":{"map":"f_fern","spawn":"fern"}},
  });
})(window.RPG);
