// 生成物（design/art_ref/gen/env/_tools/under/field_star/ の areas_star.py → fit.py → tomap.py）。手で直さない: 配置は areas_star.py、当たりは fit.py で作り直す。
// エリア s_road「山あいの街道」（北の野と湿原をつなぐ道、60×40）。エリア切り替えのフィールド（maps/field_00_kit.js、高原の凡例は field_star_00_kit.js）。
//   出口: w → f_cross.east, n → s_steps.west, s → m_north.north
//   絵: field/under/s_road（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("s_road", {
    name: R.T('map.field_star_road.s_road.name'), region: "r_forest", outside: "rock",
    legend: R.FieldArea.STAR_LEGEND, theme: 'field', bgm: 'overworld', bbg: 'star', propSet: 'star', propSetBase: 'village',
    light: R.FieldArea.STAR_LIGHT,
    rows: [
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRcc,RRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRccRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRccRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRccRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRccRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRccRRRRRRRRRRR",
      "RRRRRRRR,RRRRRRRRRRRRR,,,,rRRRRRRRRRRRRRRRRRRRRccRRRRRRRRRRR",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Rr,,cc,rRRRRRRRRR",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,cc,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,TT,,,,,,,,,,,,,,cc,,,,,,,,,,,",
      ",,,,,,,,,,,,,,www,,,,,,,,,,,,,TTTTT,,,,,,,,,,,,cc,,,,,,,,,,,",
      ",,,,TTTTTT,,,wwwww,,,,,,,,,,,TTTTTT,,,,,,,,,,,,..,,,,,,,,,,,",
      ",,,,TTTTT,,,wwwwwww,,,,,;;,,,TTTTT,,,,,,,,,,,,,..,,,,,,,,,,,",
      ",,,,,,,,,,,,,wwwwww,,;;;;;;;,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,ww,,;;;;;;;;;;;;;;,,,,,,,,,,,,,..,,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;,,,,,,,,,,,,...,,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;,,,,,,,,,,,,..,,,,,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;,,,,,,,,,,,,,..,,,,,,,,T,T,T,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,,;,,,,,,,,:,,,,,,..,,,,,,,,,,TTTTT",
      "..................,,,,,,,,,,,,,,,,,,:...,...,,,,,,,,,,TTTTTT",
      "...................................::.......,,,,,,,,,TTTTTTT",
      ",,,,,,,,,,,,,,,,,,.................,,,,,,....,,,,,,,,,TTTTTT",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,....,,,,,,,,,TTTT,",
      ",,,,,,,,;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,...,,,,,,,,TTT,,",
      ",,,,,,,;;;;;;;;;;;,,,,,,T,,,,,,,,,,,,,,,,,,,,....,,,,,,,,,,,",
      ",,,,,,,T;;;;;;;;;;;,,,TTTT,,,,,,,,,,,,,,,,,,,,....,,,,,,,,,,",
      ",,,,,T,;T;;;;;;;;;,TTTTTTTTT,,,,,,,,,,,,,,,,,,,....,,,,,,,,,",
      ",,,,,,TTTTT;;;;,;,,,TTTTTTT,,,,,,,,,,,,,,,,,,,,,...,,,,,,,,,",
      ",,,,,,TTTTT,,,,,,,,,,TTTTTT,,,,,,,,,,,,,,,,,,,,,,...,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,rrrr,...,rrrrrr",
      ",,,,,,,,,,T,,,,,,,,,,,,,,,,,,T,,,,,,,,,,,,rrrrRRR,...,RRRRRR",
      ",,,,FFFFFF,,,,,,TT,,,,,,FFFFF,,,,,,,,T,,,rRRRRRRRr...,RRRRRR",
      "FFFFFFFFFFFFFFFF,,,,,FFFFFFFFFFFFFFFF,,,RRRRRRRRRr...,RRRRRR",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFRRRRRRRRRr...,RRRRRR",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFRRRRRRRRRr...,RRRRRR",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFRRRRRRRRRr...,RRRRRR",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFRRRRRRRRRr...,RRRRRR",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFRRRRRRRRRr...,RRRRRR",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFRRRRRRRRr,...,RRRRRR",
    ],
    objects: [
      {"type":"sign","x":40,"y":18,"text":R.T('map.field_star_road.s_road.objects.0.text')},
      {"type":"prop","id":"tent","x":37,"y":16},
      {"type":"waylamp","id":"wl_s_road_1","x":11,"y":17,"lit":true},
      {"type":"waylamp","id":"wl_s_road_2","x":43,"y":24,"lit":true},
      {"type":"waylamp","id":"wl_s_road_3","x":48,"y":14,"lit":true},
    ],
    npcs: [
      {"id":"marsh_traveler","look":"npc_traveler","name":R.T('map.field_star_road.s_road.marsh_traveler.name'),"x":36,"y":18,"dir":"s","move":"still","talk":"marsh_world_traveler","reward":"news","key":"world_marsh_traveler"},
    ],
    spawns: {"west":{"x":1,"y":19,"dir":"e"},"star":{"x":47,"y":1,"dir":"s"},"south":{"x":51,"y":38,"dir":"n"}},
    exits: [{"x":0,"y":19,"w":1,"h":2,"to":{"map":"f_cross","spawn":"east"}},{"x":47,"y":0,"w":2,"h":1,"to":{"map":"s_steps","spawn":"west"},"cond":{"not":{"slice":true}}},{"x":50,"y":39,"w":3,"h":1,"to":{"map":"m_north","spawn":"north"},"cond":{"not":{"slice":true}}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_marsh_road"}],
    bbg: "marsh",
    art: {"image":"field/under/s_road","painted":[],"overlay":"field/under/s_road_over"},
    meta: {"sub":R.T('map.field_star_road.s_road.meta.sub'),"worldRect":[338,128,140,48]},
    links: {},
  });
})(window.RPG);
