// 生成物（design/art_ref/gen/env/_tools/under/field_desert/ の areas_desert.py → fit.py → tomap.py）。手で直さない: 配置は areas_desert.py、当たりは fit.py で作り直す。
// エリア d_east「東の街道」（灰の荒野への古い道、56×36）。エリア切り替えのフィールド（maps/field_00_kit.js、砂漠の凡例は field_desert_00_kit.js）。
//   出口: w → kasim.gate_e, e → world.d_east_e, s → d_south.north
//   絵: field/under/d_east（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("d_east", {
    name: R.T('map.field_desert_east.d_east.name'), region: "r_desert", outside: "dune_sand",
    legend: R.FieldArea.DESERT_LEGEND, theme: 'desert', bgm: 'desert', bbg: 'desert',
    rows: [
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~RR~~~~~~~~~~~~~~~~~~~~~~",
      "~~~russsssss~~~~~~~~~~~~~~~~~~~~RRuuuuuuu~~~~~~~~~~~RRRR",
      "XXXXXTsssssssssssssss~~~~~~.uuuTRRRssTbTrsuuuuuuRRRRRRRR",
      "XXXXXrssssssssssssssssssssruuuuTRRRssssssssTbuuurRRRRRRR",
      "XXXXXssssssssssTrbssssssuuuuuuuTRRRssssssssuuuusrRRRRRRR",
      "XXXXXsssssssssssssssssuuTbuuuuusTRRsssssssuuuuuuTRRRRRRR",
      "XXXXXsssssssssssssssssTTruuuuussTRRssssssuuuuuuuTRRRRRRR",
      "XXXXXssssssssssssssssuuuuuuuuussTRRssssssuuuuuuuTRRRRRRR",
      "XXXXXssssssssssssssssuuuuuuuuusTRRRsssssssuuuuuuuTRRRRRR",
      "XXXXXsssssssssssssssssuuuuuuuusTRRRssssssTbuuuussrRRRRRR",
      "XXXXXssssssssssssssssuuuuuuuuuuTRRRssssssssssssssrRRRRRR",
      "XXXXXsssssssbssssssssusssuuuuuuTRRRsssssssssss..........",
      "XXXXXssssssssssssssssuuTuuuuuuu=====....................",
      "XXXXXTssssssssssss...suuuuuuu..=====............ssrRRR..",
      "XXXXXrsssss....................=====ssssssssssssTbrRRRRR",
      "...................s.........usTRRRsssssssssssssssTRRRRR",
      "...........s:ssssssssuuuuuuuussTRRRsssssssssssssssrRRRRR",
      "XXXXXrssssss:sssssssssuuuuuuuussTRRssssssssssssssTRRRRRR",
      "XXXXXsssssss:srsssssTbuuuuuuuuuuTRRussssssssssssTRRRRRRR",
      "XXXXXsssssss:sssssssssuuuuuuuuuuTRRuuusssTbsssssrRRRRRRR",
      "XXXXXsssssss:ssssskkkkkkuuuuuuuuTRRuuuusssssssssTRRRRRRR",
      "XXXXXsssTTrk:kkkkkkkkkkkkuuuuuuTRRRuuuuusssssssuTRRRRRRR",
      "XXXXXsssTrrk:kkkkkkkkkkkkkuuuuuTRRRuuuuuuuuuuuuuTRRRRRRR",
      "XXXXXssssskk:kkkkkkkkkkkkkkuuuuTRRuuuusuuuuuuuuuTRRRRRRR",
      "XXXXXsssskkk:kkkkkkkkkkkkkkkuuuTRRusTrsuuuurruuuTRRRRRRR",
      "XXXXXssskskk:kkkkkkkkkkkkkkuuuuTRRussssuuuuuuuuuTRRRRRRR",
      "XXXXXssssssk:kkkkkkkkkkkkkuuuuuTRRRuuuuuuuuuuuuuuTRRRRRR",
      "XXXXXsssssss:kkkkkkkkkkkkuuuuuuTRRRuuuuuuuuuuuuuuTRRRRRR",
      "XXXXXsssssss:uukkkkkkkkkuuuuuuuuTRRuuuuuuuuuuuuuuTRRRRRR",
      "XXXXXsuuuuuu:uuuuuuskssTbssssuuuTRRRuuuussssuuuTrRRRRRRR",
      "XXXXXuuuuuuu:uuuussssssssssssuuuuTRRuuuussssssssTRRRRRRR",
      "XXXXXuuuuuuu:uuusssssssssssssssssTRRuuusssssssssTRRRRRRR",
      "XXXXXuuuuuuu:ssssssssssssssssssssTRRssTrssTrsssTRRRRRRRR",
      "XXXXXuuuuuTb:ssssssssssssssssssssTRRRssssssssssTRRRRRRRR",
    ],
    objects: [
      {"type":"sign","x":46,"y":17,"text":R.T('map.field_desert_east.d_east.objects.0.text')},
      {"type":"sign","x":8,"y":15,"text":R.T('map.field_desert_east.d_east.objects.1.text')},
      {"type":"waylamp","id":"wl_d_east_1","x":8,"y":20,"lit":true},
      {"type":"waylamp","id":"wl_d_east_2","x":25,"y":19,"lit":true},
      {"type":"waylamp","id":"wl_d_east_3","x":41,"y":17,"lit":true},
      {"type":"prop","id":"cart_barrels","x":7,"y":25},
    ],
    npcs: [
      {"id":"oil_caravan","look":"npc_oil_carrier","name":R.T('map.field_desert_east.d_east.oil_caravan.name'),"x":12,"y":22,"dir":"w","move":"still","talk":"desert_world_oil","reward":"hint","key":"world_oil_caravan"},
      {"id":"oil_camel","look":"ani_camel","name":R.T('map.field_desert_east.d_east.oil_camel.name'),"x":11,"y":25,"dir":"w","move":"still","talk":{"lines":[{"text":R.T('map.field_desert_east.d_east.lines.0.text')}]},"reward":null},
      {"id":"guard_ash","look":"npc_guard_1","name":R.T('map.field_desert_east.d_east.guard_ash.name'),"x":50,"y":16,"dir":"e","move":"still","pushable":false,"cond":{"slice":true},"talk":{"lines":[{"text":R.T('map.field_desert_east.d_east.lines.0.text_2')}]},"reward":"news","key":"world_guard_ash"},
    ],
    spawns: {"kasim":{"x":1,"y":17,"dir":"e"},"pass":{"x":54,"y":14,"dir":"w"},"south":{"x":12,"y":34,"dir":"n"}},
    exits: [{"x":0,"y":17,"w":1,"h":2,"to":{"map":"kasim","spawn":"gate_e"}},{"x":55,"y":14,"w":1,"h":2,"to":{"map":"world","spawn":"d_east_e"},"cond":{"not":{"slice":true}}},{"x":12,"y":35,"w":2,"h":1,"to":{"map":"d_south","spawn":"north"}}],
    triggers: [],
    tilePatches: [{"cond":{"slice":true},"rect":[52,13,3,3],"rows":["rrr","rrr","rrr"]}],
    zones: [{"rect":[0,10,56,12],"zone":"zw_desert_road"},{"rect":null,"zone":"zw_desert"}],
    art: {"image":"field/under/d_east","painted":[],"overlay":"field/under/d_east_over","closed":"field/under/d_east_closed"},
    meta: {"sub":R.T('map.field_desert_east.d_east.meta.sub'),"worldRect":[165,395,125,50]},
    links: {"kasim_e":{"map":"d_east","spawn":"kasim"}},
  });
})(window.RPG);
