// 生成物（design/art_ref/gen/env/_tools/under/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// エリア f_windhill「風鳴りの丘」（ユーラと北の峠への道、52×44）。エリア切り替えのフィールド（maps/field_00_kit.js）。
//   出口: e → f_fern.west, n → yura.gate, n → world.f_windhill_n
//   絵: field/under/f_windhill（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("f_windhill", {
    name: "風鳴りの丘", region: "r_forest", outside: "forest_dark",
    rows: [
      "FTFFFFF;;;;...;;;;;;;;;,,;;;;;;;;;RRRRT..RRRRRRRRRRR",
      "FTFFFFF;;;;..,;;;;;;;;;;;;;;;;;;;;RRRR;..RRRRRRRRRRR",
      "FFFFFFFF;;;..,,;;;;;b;;;;,,,;;;;;;RRRR;..RRRRRRRRRRR",
      "FFFFFFFT;;,..,,;;;T;;;T;,,,,,;;;;;RRRR;..RRRRRRRRRRR",
      "FFFFFFFFT;,...,;;TTTT;T;,,,,;;,;;;;;;;,..;;;;;;;;;b,",
      "FFFFFFFFF;,...,;;TTTTT;;T,,,;;,;;;;;;;,..;;;;;T;TT;,",
      "FFFFFFFFF;,...,;;;;;;;;,TT,,;;;;T;,b;;,...;;;TFFFT;;",
      "FFFFFFFF,,,...,;;T;;;;;TT,,,;;;;;;;;,;,,..;;rwwwwT,,",
      "FFFFFFFFTT,...,,TT;;;;TTT,,,;;;;;;;;,;;;..;;rwwwwwr,",
      "FFFFFFFTTT,...,,,;;;;TTTT,,,,;;;;;;;;;;;...,rwwwwwr,",
      "FFFFFFFTTT,..,,FT,,T,TTTT,,,;;;;,,,,;;;;,..,,rwwwwr,",
      "FFFFFFFFTFF..FFFF,,,,,,,,,,;;;;;,,,X,,,,;..,,,TwwrFF",
      "FFFFFFFFFFF..FFFFF,,,,,,;,,,b,;;X;;,,,,,,..,TT,rrFFF",
      "FFFFFFFFFFFF..FFFF,,,,,,,,,;,,;;,;X,,X,,,..,,,,,TTFF",
      "FFFFFFT,,FFF..FFFF,,,,,,,,,,,;;;,X,,,,,,,..,,;;,TTTF",
      "FFFFFr,,,,,F..FFFF,,,,,,,,,,,;;::,,,,,,,...,;;;;T;;F",
      "FFFFF,,,,T,FF..FFF,,,,,,,,,,,;;::,,,,,,,..,,;;;b;;;;",
      "FFFF,,,,,,TTT..FFFFFT;;,,,,;;;::,,,,,,,,..,,;;;;;;;;",
      "FFFFr,,,,,;TTT..FFFFT,;,,,,;:::;,,,,,,,...,,;;;;;;;;",
      "FFFF,,,,,,;;FT...FFF,,;;;;;;:::;,,,,,,...,,,;;;;;;;;",
      "FFFFF,,,,TFFFF;...,,,,;;;;;::;;;;;;;;;;..,,,;;;;;,;;",
      "FFFFF,,;;FFFFFFF.::TTFTr;T;::;;;;;;;;;..;,;;;TT,,,b,",
      "FFFFF;;;;;FFFFTTT::..FFTTTT:;;;;;;;;;...;,;;;T,,,,,,",
      "FFFF,;;;;;;FFF;T::T......T;:;;;;;;;;;..;;;;;,,,,,,,r",
      "FFFF;;,;;;;;FF;::;;;;.....::....;;;;..;;;;;;b,,,,,,,",
      "FFFF;;T;;;;;FF::;;;TTF....::..........;;;;;T,,,,,,,,",
      "FFFFF;;;;T;;;::;;;;TTT;;;;;;;;;;........;;;;;;,T,,,;",
      "FFFFFF;,,,r;;::;;;T;;;TbTT;;;;;;;T;;;.....;;TT;TT,;;",
      "FFFFFFF,,,,,::,;;;;T;;;TT;;;T;;;;FF;TTT.....FFTTTFFF",
      "FFFFFFF,,X,::,,,;;;T;;;TT;FFFFFF;FFFFFFFF...........",
      "FFFFFF,,XXX::,,,;;;;;;;FFFFFFFFFFFFFFFFFFFFF........",
      "FFFFFF,,,,::,,,;;;;;;;;FFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFF,,,,,,,T;;FFF;;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFF,,,,;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFTFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
    ],
    objects: [
      {"type":"examine","x":34,"y":13,"event":"windhill_notes"},
      {"type":"sign","x":30,"y":19,"text":"風鳴りの丘\n風が歌のように鳴るという。"},
      {"type":"examine","x":10,"y":31,"event":"world_poi_forest_statue"},
      {"type":"prop","id":"tent","x":20,"y":13},
      {"type":"prop","id":"lantern","x":22,"y":13},
      {"type":"sign","x":15,"y":6,"text":"北 → 苔の村ユーラ"},
      {"type":"sign","x":42,"y":6,"text":"北の峠を越えて\n↑ 雪の村ユール"},
      {"type":"prop","id":"beacon","x":3,"y":40,"cond":"cleared_r_forest"},
      {"type":"waylamp","id":"wl_15","x":15,"y":19,"lit":true},
    ],
    npcs: [
      {"id":"guard_north","look":"npc_guard_1","name":"番人","x":41,"y":4,"dir":"s","move":"still","pushable":false,"cond":{"slice":true},"talk":{"lines":[{"text":["北の峠は、雪崩で\nふさがってしまったんだ。","雪原へ行くのは、\n雪が落ちつくまで待ってくれ。"]}]},"reward":"news","key":"world_guard_north"},
    ],
    spawns: {"east":{"x":50,"y":30,"dir":"w"},"yura":{"x":12,"y":2,"dir":"s"},"pass":{"x":39,"y":1,"dir":"s"}},
    exits: [{"x":51,"y":30,"w":1,"h":2,"to":{"map":"f_fern","spawn":"west"}},{"x":12,"y":0,"w":2,"h":1,"to":{"map":"yura","spawn":"gate"}},{"x":39,"y":0,"w":2,"h":1,"to":{"map":"world","spawn":"f_windhill_n"}}],
    triggers: [],
    tilePatches: [{"cond":{"slice":true},"rect":[38,1,4,2],"rows":["rrrr","rrrr"]}],
    zones: [{"rect":null,"zone":"zw_forest"}],
    art: {"image":"field/under/f_windhill","painted":[]},
    meta: {"sub":"ユーラと北の峠への道","worldRect":[40,128,92,124]},
    links: {"yura":{"map":"f_windhill","spawn":"yura"}},
  });
})(window.RPG);
