// 生成物（design/art_ref/gen/env/_tools/under/field_ash/ の areas_ash.py → fit.py → tomap.py）。手で直さない: 配置は areas_ash.py、当たりは fit.py で作り直す。
// エリア a_pass「灰かぶりの峠」（砂漠から灰の荒野へ抜ける峠、52×40）。エリア切り替えのフィールド（maps/field_00_kit.js、灰の荒野の凡例は field_ash_00_kit.js）。
//   出口: w → d_east.pass, e → a_lava.west, s → a_battle.north
//   絵: field/under/a_pass（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("a_pass", {
    name: "灰かぶりの峠", region: "r_ash", outside: "rock",
    legend: R.FieldArea.ASH_LEGEND, theme: 'ash', bgm: 'overworld', bbg: 'ash', propSet: 'ash', propSetBase: 'village',
    light: R.FieldArea.ASH_LIGHT,
    rows: [
      "TTTTTRRRRRRRRRRRRRRRRRRRRRRRRuuuuuuusRRRRRRRRRRRRRRR",
      "TTTTTRRRRRRRRRRRRRRRRRRRRRRRRuuuuuuusRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRuuuuusursRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRsssuuuuuuuusRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRsssssssuuuuuuuusRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRssssssssssuuuuuuuuusRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRsssssssssssrsusruuuuuuussRRRRRRRRRR",
      "RRRRRRRRRRRRRRRsssssssssssssrsuuuuuuuuussssRRRRRRRRR",
      "RRRRRRRRRRRRRRssssssssssssssssuuuuuuuuusssssrssRssss",
      "RRRRRRRRRRRssssssssssssssssssssruruuuuusssssssssssuu",
      "RRRRRRRRRRssssssssrrrrrsssssrsrrrruuuuussssssrssssss",
      "RRRRRRRRRRsssssssrrrrrrsssssssrrruuuuuuusssssssrrsss",
      "RRRRRRRRRssssssssrrrrrrsssssssssuuurrrrurrssssrrrsss",
      "RRRRRRRRsssssssssssrrrsssssssssssuuXXXrusuusssssssss",
      "RRRRRRRssssssssrssssssssssssssssssuXrXruuuuussssssss",
      "RRRssssssssssskrrrrrrssssssssssssssssssuuuuussssssss",
      "ssssssssssssssskr::rssssssssssss....ssssuuuuuuusssss",
      "ssssssssssssss...s:ssssssss.........................",
      ".ssssss...........:.................................",
      "...........................ssssssssssrsuuuuuuurrssss",
      ".......ssssssssssssssssss..sssssssssbssrssuuuuruuuss",
      "sssrrsssssssusssssssrrrsss..ssssssrssssrrruuuuuuuuss",
      "rrrrsssssssssusussrrsrrsss..sssssssssssrrssuuuuuuuss",
      "RRRRRRssuuuuuuuussssssssss..sssssrrssssssssuuuuuuuus",
      "RRRRRRRsuuuuuuuusssssssssss.sssssrssssssssuuuuuuuuur",
      "RRRRRRRRuuuuuuussssssssssss.sssssssrrsssssuuuuuuuuus",
      "RRRRRRRRRsuuuuussssssssssss.sssssssssssssuuusrruuuuu",
      "RRRRRRRRRRuuuuusssssssssss..sssssssssssssrrrrrruuuuu",
      "RRRRRRRRRuuuuuussssssssrss..ssssssssssrssrrrrrrruuuu",
      "RRRRRRRRRuuuuuusrsssssssss.sssssssrrssssurrrrrrruuuu",
      "RRRRRRRRRuuuuuusrrsssssss..ssssssssssssuussrrrrsuuuu",
      "RRRRRRRRRuuuuuussssssssss..ssssssssssuuuuuussrsuuuus",
      "RRRRRRRRRuuuuuussssssssss.ssssrrrurrruuuuuuuusuuusss",
      "RRRRRRRRRuuuuuusssssrssss.ssssrrrsrrrruuuuuuuuurrsss",
      "RRRRRRRRRuuuuuussssssssss.ssssssurrrrruuuuuuuuurrrss",
      "RRRRRRRRRuuuuussssssssss..sssssssssssuuuuuuuuurrrrss",
      "RRRRRRRRRRuuuussssssssss..ssssssssuussuuuuuuuussssss",
      "RRRRRRRRRRRuuusssssssssss.ssssrsssussssuuuuuuusrrsss",
      "RRRRRRRRRRRuussssssssssss.ssssssssssssssssuuuuusssss",
      "RRRRRRRRRRRRussssssssssss.sssssssssssssssssuuuuuuuus",
    ],
    objects: [
      {"type":"sign","x":6,"y":22,"text":"灰の荒野\n東 → 炎の町カルデラ"},
      {"type":"sign","x":29,"y":22,"text":"南 → 灰の古戦場\n折れた剣の碑"},
      {"type":"waylamp","id":"wl_a_pass_1","x":12,"y":21,"lit":true},
      {"type":"waylamp","id":"wl_a_pass_2","x":31,"y":20,"lit":true},
      {"type":"prop","id":"tent","x":14,"y":10},
      {"type":"prop","id":"lantern","x":12,"y":11},
    ],
    npcs: [
      {"id":"ash_traveler","look":"npc_traveler","name":"灰の荒野の旅人","x":14,"y":12,"dir":"s","move":"still","talk":"ash_world_traveler","reward":"news","key":"world_ash_traveler"},
    ],
    spawns: {"west":{"x":1,"y":19,"dir":"e"},"east":{"x":50,"y":18,"dir":"w"},"south":{"x":25,"y":38,"dir":"n"}},
    exits: [{"x":0,"y":19,"w":1,"h":2,"to":{"map":"d_east","spawn":"pass"}},{"x":51,"y":18,"w":1,"h":2,"to":{"map":"a_lava","spawn":"west"}},{"x":25,"y":39,"w":2,"h":1,"to":{"map":"a_battle","spawn":"north"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":[0,15,55,7],"zone":"zw_ash_road"},{"rect":null,"zone":"zw_ash_plain"}],
    art: {"image":"field/under/a_pass","painted":[],"overlay":"field/under/a_pass_over"},
    meta: {"sub":"砂漠から灰の荒野へ抜ける峠","worldRect":[285,393,96,48]},
    links: {},
  });
})(window.RPG);
