// 生成物（design/art_ref/gen/env/_tools/under/field_desert/ の areas_desert.py → fit.py → tomap.py）。手で直さない: 配置は areas_desert.py、当たりは fit.py で作り直す。
// エリア d_coast「西の浜」（遠回りの浜の道と王墓のオアシス、44×52）。エリア切り替えのフィールド（maps/field_00_kit.js、砂漠の凡例は field_desert_00_kit.js）。
//   出口: n → desert_camp3.road, e → d_hollow.coast, e → d_caravan.coast, 門 → desert_wellroom.road
//   絵: field/under/d_coast（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("d_coast", {
    name: R.T('map.field_desert_coast.d_coast.name'), region: "r_desert", outside: "sea",
    legend: R.FieldArea.DESERT_LEGEND, theme: 'desert', bgm: 'desert', bbg: 'desert',
    rows: [
      "~~~~~~~sRRRRRRRRRRR..ssRRRRRRRRRRRRRRRRRRRRR",
      "~~~~~~~ssRRRRRRRRRR..ssRRRRRRRRRRRRRRRRRRRRR",
      "~~~~~~sssRRRRRRRRRs..ssRRRRRRRRRRRRRRRRRRRRR",
      "~~~~~~sssRRRRRRRRRs..ssRRRRRRRRRRRRRRRRRRRRR",
      "~~~~~~ssss.RRRRRRsss.ss.RRRRRRRRRRRRRRRRRRRR",
      "~~~~~sssrssssuusssus..ssssssssssssssrRRRRRRR",
      "~~~~~~ssrsss,,,,,,,,,.ssssssssssssssRRRRRRRR",
      "~~~~~~ssssss,,,,,,XX,.ssXsssssssssssRRRRRRRR",
      "~~~~~~ssssss,,,T,,XX,.ssXXsssssssssssRRRRRRR",
      "~~~~~~ssssss,,,,,,,,,.sssssssssssssssRRRRRRR",
      "~~~~~~ssssss,T,,,,,,,.sssssTsssssssssRRRRRRR",
      "~~~~~~ssssss,,,,,,,,,.ssssssssssssssssrRRRRR",
      "~~~~~~ssssssT,,,T,,,,.sssTssssssssssssrrrrRR",
      "~~~~~~ssssss,,,,,,,,,.sssssssssssssssssssssr",
      "~~~~~~sssssusssssssss..sssssssss::::::::::::",
      "~~~~~~ssssrTsssssssss..ssss::::::::::::sssss",
      "~~~~~~sssssusssssssss..s:::::sssssssssssssss",
      "~~~~~~~ssssTuusssssss::::sssssssssssssssssss",
      "~~~~~~~ssssTursssssss::sssssssssssssss.RRRRR",
      "~~~~~~~~sssTrrsssssss..sssssssssssssssRRRRRR",
      "~~~~~~~~ssssrsssssss...suuusssssssssssRRRRRR",
      "~~~~~~~~ssssssssssss..ssuuuusssssssss.RRRRRR",
      "~~~~~~~~ssssssssssss..ssuuuuusssssrrsRRRRRRR",
      "~~~~~~~~ssssssssssss..ssuuuuussurTssssRRRRRR",
      "~~~~~~~~sssssssssss..sssssssuuuuuuurTu.RRRRR",
      "~~~~~~~ssssssssssss..ssssssssuuuuuuuuuuRRRRR",
      "~~~~~~~ssssssssssss..ssssssssuuusuuuuuuRRRRR",
      "~~~~~~~ssssusssssss..ssssssssuuuTTsusuuuRRRR",
      "~~~~~~~ssssussssss..ssssssssssuuuuTTTTuurRRR",
      "~~~~~~~sssuussssss..ssssrssssssuuurrTTuusRRR",
      "~~~~~~ssssTurTusss..ssXXXXuuussuuuuuuuuussRR",
      "~~~~~~ssssTTuuuuus..ssXXXXusTuuuuuu.uuuuusrr",
      "~~~~~~ssssuuuuuusu..uuX:XXuXTuuuuuuuuuuuuuuu",
      "~~~~~~ssssuuuuuuTT..::::uuurruuuuuuuuuuuuuuu",
      "~~~~~~sssssuuuusru..:uuuruuuuusuuuuuuuuuuuuu",
      "~~~~~~sssssuuuuuuu...uuuuuuuuuuuuuuuuuuusuuu",
      "~~~~~~~ssssuuuurrTu..uuuuuuuuuuTuuuuuuuuTTuu",
      "~~~~~~~sssssuuuuuuuu..uuuuuuuuuuuuuuuuuuTuuu",
      "~~~~~~~sssssuuuuuuuu...uuuuuusssuuuuuuuuuuuu",
      "~~~~~~~~ssssuuuuuuuuu...uuuussssuuusuuuuuuuu",
      "~~~~~~~~ssssssuusuuuuu....ssssssuusuuuuuuuuu",
      "~~~~~~~~~ssssuuuuuuuuuuu....ssssssuTTsssssss",
      "~~~~~~~~~ssssrTuTTuuuuuuus......ssTTssssssss",
      "~~~~~~~~~sssssssuuuuuuuuusss......T.........",
      "~~~~~~~~~ssssssssuuuuussssssssss............",
      "~~~~~~~~~ssssssssssuuussssssssssssssssssssss",
      "~~~~~~~~~ssssssssuuusuusssssssssssssssssssss",
      "~~~~~~~~~ssssssssuuusuuuuussssssssssssssssss",
      "~~~~~~~~sssssssssuuuuuuuuuuuuuuuusssssssrTss",
      "~~~~~~~~~ssssssssssuuuuuuuuuuuuuuussssssssss",
      "~~~~~~~~~ssrTsssssssuuuuuuuubuuuuussssssssss",
      "~~~~~~~~~ssrsssssssssuuuuuuuuuuuuuusssssssss",
    ],
    objects: [
      {"type":"sign","x":22,"y":5,"text":R.T('map.field_desert_coast.d_coast.objects.0.text')},
      {"type":"sign","x":26,"y":35,"text":R.T('map.field_desert_coast.d_coast.objects.1.text')},
      {"type":"waylamp","id":"wl_desert_beacon_3","x":23,"y":21,"lit":"q_kasim_beacon_3","event":"desert_beacon"},
      {"type":"prop","id":"bones","x":14,"y":26},
      {"type":"prop","id":"clay_jars","x":21,"y":31},
    ],
    npcs: [

    ],
    spawns: {"camp3":{"x":20,"y":1,"dir":"s"},"hollow":{"x":42,"y":14,"dir":"w"},"caravan":{"x":42,"y":44,"dir":"w"},"wellroom":{"x":23,"y":33,"dir":"s"}},
    exits: [{"x":20,"y":0,"w":2,"h":1,"to":{"map":"desert_camp3","spawn":"road"}},{"x":43,"y":14,"w":1,"h":2,"to":{"map":"d_hollow","spawn":"coast"}},{"x":43,"y":44,"w":1,"h":2,"to":{"map":"d_caravan","spawn":"coast"}},{"x":23,"y":32,"w":1,"h":1,"to":{"map":"desert_wellroom","spawn":"road"}}],
    triggers: [{"id":"desert_ambush_3","x":17,"y":36,"w":6,"h":4,"on":"step","event":"desert_ambush_3","cond":["desert_caravan_on","!desert_ambush_3_done"]}],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_desert_caravan","cond":"desert_caravan_on"},{"rect":null,"zone":"zw_desert"}],
    art: {"image":"field/under/d_coast","painted":[],"overlay":"field/under/d_coast_over"},
    meta: {"sub":R.T('map.field_desert_coast.d_coast.meta.sub'),"worldRect":[24,400,40,101]},
    links: {"camp3":{"map":"d_coast","spawn":"camp3"},"wellroom":{"map":"d_coast","spawn":"wellroom"}},
  });
})(window.RPG);
