// 生成物（design/art_ref/gen/env/_tools/under/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// エリア f_south「森の南」（きこりの野営地と古い塔、56×48）。エリア切り替えのフィールド（maps/field_00_kit.js）。
//   出口: n → f_fern.south, s → world.f_south_s
//   絵: field/under/f_south（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("f_south", {
    name: "森の南", region: "r_forest", outside: "forest_dark",
    rows: [
      ",,;TTTF;;;FFFFF;;;T;;;,,,,;;;...;;;;;FFF;;;;,,,,,,,,,,,,",
      ",,,T;;;T;;FFFFT;;;;;;;,,,,,;;...;;;;;TTT;;;;,,,,,,,,r,,b",
      ",,,;;;;;;,TFFFT;;;;;;;,,,,,;;...;;;;T;;;;;;;,,,,,,,TT,,,",
      ",,,;;;;;,,TTTFF,;;;;;TTFFF,,,...;;;TT;;;;;;;;,,,,,,FF,,,",
      "FFT,,,;,,;TFFFF;FF;;,FFFFFF,XT...TT;;;;T;TFT,,,,,TTFFTT,",
      "FFF,,,,,,;TFFFF;FF,,FFFFFFX,,,..,,,,;FFFFFFFT,;,,;TFFTT,",
      "FFF,,,,,,,;TFFFFTFFFFFFFF,,,,,..,,,rFFFFFFFFT,,,,,;FFFFT",
      "FFF,,,,,,;TFFFFTFFTFFFFFF,,,,,...,,,,TFFFFFFT;;;r;;TTTTF",
      "FFF,,,,,,,FFFFFFTT,TTTFF,,,,,,,...,,TTFFFFFFTT;;;;;,,,,,",
      "FFF,TTTTTFFr,,,;;,,,;;;;,,,,,,,,..XTTTFFFFFFFT;T;;;,,,,;",
      "FFFFFTTFFF,,,,,,;;;;;;;;;;X,,,,,...TTTFFFFFFFFFFFFF;;;;;",
      "FFFFFFFFF,,,,,,,,;;;;;;;;;,,,,,,,..FFFFFFFFFFFFFFFFF;;;;",
      "FFFFFFFF,,XX,,,,,;;;;;;;;TFFFFFFFF..FFFFFFFFFFFFFFFF;;;;",
      "FFFFFFT,,,XX,,,,,;;;;;;TTTFFFFFFFF..FFFFFFFFFFFFFFFF;;;;",
      "FFFFFFT,,,,::,,,,;;;;;;TFFFFFFFFFFF..FFFFFFFFFFFFFFT;;;;",
      "FFFFFFF,,,,::,,,,;;;;;;FFFFFFFFFFFF..,,FFF,FFFFFFFTT;;,;",
      "FFFFFFF,,,,,:,,,,;;;;;;FFF;FFFFFF,,...,,,,,TFFFFFFFT,;;;",
      "FFFFFFF,,,,,::,,;;;;;;,FFF;bTT;;,,,,..,X,,,,FFFFFFFF,;;;",
      "FFFFFFFF,,,,,:,,;;FT;,,FFF;;;;TT,,,,..,,,X,,,FFFFFFF,;;;",
      "FFFFFFFFFT;;,::;;TTT;;TFFFF;TT;;,,,X::c,,X,,,,FFFFFF,;;;",
      "FFFFFFFFT;;;;;::T;FT;;,,,FF,Tb;;,,,X::,,,,,,,,FFFFFF,;;;",
      "FFFFFFTTT;;;;;::;;,,,,,,,,FT,,,,,,,..X:,X,,,,,FFFFF,;;;;",
      "FFFF;;;;;;;;bTF:::,,,,,,,,,,,,,,,....,:,,,,,,FFFFFFFb;;;",
      "FFFF;;;;;;FFFFF:::,,,,,,,,,,,,,,...,,,::,,,,,FFFFFFF;;;;",
      "FFFF;;;;;;TFFF,,,::,,,,,,,,,,,....,,,,,:,,,,,,FFFFF;;;;;",
      "FFFF;;;;;;TFFF,,,,::,,,,,,......,,,,,,,::,,,,;FFFFFFT;;;",
      "FFFT;;r;;;;;FF,,r,,:::........,,,,,,,,,,:,,,,;;;;;TFT;;;",
      "FFFTTT;;;T;;;TT,,,,,:::...,,,,,,,b,,,,,,::,,,,;;;;TFT;;;",
      "FFFTTFFFFFFF;FT,,,,,.::,,,,,,,b,,,,,,,,,::,,,,wwwwwwww;;",
      "FFFTFFFFFFFFFFFT,,,...,,,,,,,,,,,,,,,,,,::,,wwwwwwwwwwww",
      "FFFTFFFFFFFFFFF;;,,..,,,,,,,,,,wwwwwwww,::wwww,;,,;;;;ww",
      "TFFTFFFFFFwwwwwwwww__,,FFFFFwwwwwwwwwwww__www,,;;;b;;;FF",
      "wwFFF;;;wwwwwwwwww___wwwwwwwwww,,,,,,,,,:w,,,,,;;;;;;;;T",
      "wwwwwwwwwwFFF;T;;T..;wwwwwww;,,,,,,,,,,,:,,,,,TT;;;;bT,,",
      ",wwwwwww,,;;T;;;;T..;;T;;;;;;,T,,,,,,,,::,,,,,TFFF;;,,,T",
      ",,,,,,,,,,;;;;;;;F..,,;;;;;T;FFFFFF,,,,::,,,,,,FFFFT,,,,",
      ",,,,,,,,,,;;;;;;FF..,,;;;;TFFFFFFFF,,,,,,,,,r,,FFFFF,,,,",
      ",,,,,,,,,,,;;;;;TF..,,;;;;;;;FFFFFF;,,,,,,,,,,FFFFF,,,,T",
      "r,,,,,,,,,,;;;;;;,...,,,,,XX,TFXXT;;,,,,,,,,,TTTTT;;,,,F",
      ",,,,,,;;;;,;;;;,,,,..,,,,,XX,TTXX,;;;,,,,,,;;;;;;;;;;T,,",
      ",,,,,,;r;;,;;TTT,,,..,,b,,,,,,,,,,;;;;,,,,,,,,;,,;;;b;;F",
      ",,,,,,;;;b,FFFTTT,,..,,,,,,,,,,,,,;;;TT,,,,,,,,,b;;;;;;T",
      ",,,,b,;;;,,FFFFTF,,,..,,,,,,,,,,,,;;;FF,,,,,,,,;r;;;;;TT",
      ",,,,,RR,,RRRFF;;TF,,..,,,,,,,,,,,,RRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRT;;..RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRT;T..RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRFT..RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRFF..RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    ],
    objects: [
      {"type":"examine","x":38,"y":19,"event":"world_poi_forest_ring"},
      {"type":"sign","x":35,"y":23,"text":"森の南の広場"},
      {"type":"sign","x":29,"y":41,"text":"双子の見張り塔\n修理中につき、立ち入り禁止。"},
      {"type":"prop","id":"fence","x":28,"y":40},
      {"type":"prop","id":"fence","x":29,"y":40},
      {"type":"prop","id":"fence","x":30,"y":40},
      {"type":"examine","x":12,"y":14,"event":"world_poi_forest_tower"},
      {"type":"examine","x":13,"y":14,"event":"world_poi_cache","item":"i_ether","key":"world_poi_forest_tower"},
      {"type":"examine","x":27,"y":6,"event":"world_poi_stones"},
      {"type":"examine","x":34,"y":9,"event":"world_poi_shrine"},
      {"type":"prop","id":"tent","x":19,"y":24},
      {"type":"prop","id":"lantern","x":20,"y":24},
      {"type":"waylamp","id":"wl_17","x":33,"y":12,"lit":true},
      {"type":"waylamp","id":"wl_18","x":19,"y":37,"lit":true},
      {"type":"sign","x":23,"y":42,"text":"南の峠\n南 → ザハラ砂漠"},
    ],
    npcs: [
      {"id":"woodcutter_road","look":"npc_woodcutter_1","name":"きこり","x":21,"y":25,"dir":"w","move":"still","talk":"world_woodcutter","reward":"hint","key":"world_woodcutter"},
      {"id":"guard_south","look":"npc_guard_1","name":"番人","x":21,"y":42,"dir":"n","move":"still","pushable":false,"cond":{"slice":true},"talk":{"lines":[{"text":["南の峠は、砂嵐で\n道が埋まってしまったんだ。","砂漠へ行くのは、\n嵐がやむまで待ってくれ。"]}]},"reward":"news","key":"world_guard_south"},
    ],
    spawns: {"north":{"x":30,"y":1,"dir":"s"},"south":{"x":20,"y":46,"dir":"n"}},
    exits: [{"x":30,"y":0,"w":2,"h":1,"to":{"map":"f_fern","spawn":"south"}},{"x":20,"y":47,"w":2,"h":1,"to":{"map":"world","spawn":"f_south_s"}}],
    triggers: [],
    tilePatches: [{"cond":{"slice":true},"rect":[19,44,4,2],"rows":["rrrr","rrrr"]}],
    zones: [{"rect":null,"zone":"zw_forest"}],
    art: {"image":"field/under/f_south","painted":[]},
    meta: {"sub":"きこりの野営地と古い塔","worldRect":[84,262,110,100]},
    links: {},
  });
})(window.RPG);
