// 生成物（design/art_ref/gen/env/_tools/under/field_ash/ の areas_ash.py → fit.py → tomap.py）。手で直さない: 配置は areas_ash.py、当たりは fit.py で作り直す。
// エリア a_lava「溶岩の原」（カルデラの西の黒い原、60×44）。エリア切り替えのフィールド（maps/field_00_kit.js、灰の荒野の凡例は field_ash_00_kit.js）。
//   出口: w → a_pass.east, e → caldera.gate_w, n → a_spa.south, s → a_beach.lava
//   絵: field/under/a_lava（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("a_lava", {
    name: R.T('map.field_ash_lava.a_lava.name'), region: "r_ash", outside: "rock",
    legend: R.FieldArea.ASH_LEGEND, theme: 'ash', bgm: 'overworld', bbg: 'ash', propSet: 'ash', propSetBase: 'village',
    light: R.FieldArea.ASH_LIGHT,
    rows: [
      "kkkkkkkkkkkkkkk::kkkklllsuuussssrruuuuussssssssssssssssRRRRR",
      "kkkkkkkkkkkkkkk::kkkkllluuusssrrssuuuuussssssssssssssssRRRRR",
      "kkkkkkkkkRRRRRR::kkrullsuuussssssssssssssssssssssssssssRRRRR",
      "kkkkkkkRRRRRRRR::ssrlllsuuussssssssssssssssssssssssssssRRRRR",
      "kkkksRRRRRRrkrr::RRRRllluuussssssssssssssssssssssssssssRRRRR",
      "kkkRRRRRkkkkkkk:krRRRlllssssssssussssssrrssssssssssssTsRRRRR",
      "kkkRRRkkkkkkkkk:kssrllllssssuuuuussssuurrrRRsssssssssrsRRRRR",
      "kkkkkkkkkkkkkks:sssslllssssuuuuuuuuuuuuuuuRRRRssssssrRRRRRRR",
      "kkkkkkkkkkkskss:sssssllllssuuuuuuuuuuuuuuuuRRRRrsssssRRRRRRR",
      "kkkkkkkkkkkkkss:sssssllllrssuuuuuuuuuuuuuuuuuRRRrsssssRRRRRR",
      "kksrkkkkkkkkks::ssssssllllssuuuuuuuuuulurrruuuRRRsssssRRRRRR",
      "kkkkkkkkkkkkrk::ssssssllllssuuuuuuuuulllllluuusRRsssssRRRRRR",
      "kkkkkkkkkkkkkk:rssssssslllssuuuuuuuuulllllluuusRRRsssssRRRRR",
      "kkkkkkkkkkkkkk:rrsssssslllssuuuuuuuuuulllluuusssRRsssssRRRRR",
      "kkkkkkkkkkkkkk:krrssssslllrsuuuuuusssssuuuuussssRRrssssRRRRR",
      "kkkkkkrskkkkkk:kkkksssllllrsuuuuuusssssuuuuussssRRrsssRRRRRR",
      "kkkkkkkkkkkksk:kkkksssllllsuuuuuuussssssuuuussssRRrsssRRRRRR",
      "kkkkkkkkkkkkkk:kkkkssslllssuuuuuuursssssssuuuussssssssRRRRRR",
      "kkkkkkkkkrkkk::kkkkssrrRRrsuuuuuuusssssssssuuuussuuuussRXXRR",
      ".............::..rksrcccccc.......sssssssssuuu..............",
      ".............::......cccccc................::...............",
      "kkkkkkkkkkkkrrk.....rccccccuuusuus.........::.uuuuuu....lll.",
      "kkkkkkkkkkkkkkkkrsssrrRRrruuuusuuuuuusssssu::uuuuusssssRRRRR",
      "kkkkkkkkkkkkkkkkssssrlllrsuuuusuuuuuuuussuu::uuuussssssRXXRR",
      "kkkkkkkkkkkkkkkrrskrlllrsuuuuuuuuulllruuuuur:ruusssssssRRRRR",
      "kkkkkkkkkkkkkkkkkkkrlllrkuruuurlllllsuuuuukr:krrsssssssRRRRR",
      "kkkkkkkrkkkkkkkkkkkllllkkkkrurllllRRRRRRRRRr:kkssssssssRRRRR",
      "kkkkkkkrrkkkkkkkkkllllkkkkrlllllsRsRRRRRRRRR:kkrsssssssRRRRR",
      "kkkkkkkkkkkkkkkkkkllllkkklllllsssssruukksRRR::krsssssssRRRRR",
      "kkkkkkkkkkkkkkkkkllllkkkllllksssskkkrkkkkkkk::krsssssssRRRRR",
      "kkkkkkkklllkkkrrlllllrkllllkkssskkkkkkkkkkkkk:krsssssssRRRRR",
      "kkkkkkkllllllklllllllllllkkkkkkkkkkkkkkkkkkkk::ssssssssRRRRR",
      "kkkkrllllllllllllllllllkkkkkkkkkkkkkkkkkkkkkkk:ssssssssRRRRR",
      "kkkkkllllllllllllllllkkkkkkkkkkkkkkkkkkkkkkkkkr:ssssssRRRRRR",
      "kkkkrlllllllllllllllkkkkkkkkkkkkkkkkkkkkkkkkkkkrsrsssRRRRRRR",
      "kkkkklllllllllllllllkkkkkrskkkkkkkkkkkkkkkkkrrk::rsssRRRRRRR",
      "kkkkrlllllllllllllllkkkkkkkkkkkkkkkkkkkkkkkrrsk::rssssRRRRRR",
      "kkkkklllllllllllllllkkkkkkkkkkkkkkrskkkkkkkksssk:ssssssRRRRR",
      "kkkkkkllllllllllllllkkkkkkkkkkkkkkkkkkrkkkkkssss:ssssssRRRRR",
      "kkkkkkkllllllllllllkkkkkkkkkkkkkkkkkkkkkkkkkksss:ssssssRRRRR",
      "kkkkkkkkllllllkkkkkkkskkkkkkkkkkkkkkkkkkkkkkkkssrssssssRRRRR",
      "kkkkkkrkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk:ssssssRRRRR",
      "kkkkkkkskkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk:ssssssRRRRR",
      "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk:ssssssRRRRR",
    ],
    objects: [
      {"type":"sign","x":10,"y":23,"text":R.T('map.field_ash_lava.a_lava.objects.0.text')},
      {"type":"sign","x":46,"y":23,"text":R.T('map.field_ash_lava.a_lava.objects.1.text')},
      {"type":"sign","x":51,"y":18,"text":R.T('map.field_ash_lava.a_lava.objects.2.text')},
      {"type":"waylamp","id":"wl_a_lava_1","x":30,"y":22,"lit":true},
      {"type":"waylamp","id":"wl_a_lava_gate","x":50,"y":23,"lit":true},
      {"type":"prop","id":"lava_glow","x":12,"y":36},
      {"type":"prop","id":"lava_glow","x":8,"y":34},
      {"type":"prop","id":"lava_glow","x":16,"y":38},
      {"type":"prop","id":"lava_glow","x":23,"y":9},
      {"type":"prop","id":"lava_glow","x":24,"y":16},
      {"type":"prop","id":"lava_glow","x":33,"y":26},
      {"type":"prop","id":"lava_glow","x":22,"y":29},
      {"type":"prop","id":"lava_glow","x":40,"y":12},
    ],
    npcs: [

    ],
    spawns: {"west":{"x":1,"y":20,"dir":"e"},"caldera":{"x":58,"y":20,"dir":"w"},"north":{"x":15,"y":1,"dir":"s"},"south":{"x":48,"y":42,"dir":"n"}},
    exits: [{"x":0,"y":20,"w":1,"h":2,"to":{"map":"a_pass","spawn":"east"}},{"x":59,"y":20,"w":1,"h":2,"to":{"map":"caldera","spawn":"gate_w"}},{"x":15,"y":0,"w":2,"h":1,"to":{"map":"a_spa","spawn":"south"}},{"x":48,"y":43,"w":2,"h":1,"to":{"map":"a_beach","spawn":"lava"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":[0,18,63,6],"zone":"zw_ash_road"},{"rect":null,"zone":"zw_ash_plain"}],
    art: {"image":"field/under/a_lava","painted":["lava_glow"],"emit":"field/under/a_lava_emit"},
    meta: {"sub":R.T('map.field_ash_lava.a_lava.meta.sub'),"worldRect":[381,393,105,93]},
    links: {"caldera":{"map":"a_lava","spawn":"caldera"}},
  });
})(window.RPG);
