// 生成物（design/art_ref/gen/env/_tools/under/field_ash/ の areas_ash.py → fit.py → tomap.py）。手で直さない: 配置は areas_ash.py、当たりは fit.py で作り直す。
// エリア a_battle「灰の古戦場」（折れた剣の眠る窪地、52×40）。エリア切り替えのフィールド（maps/field_00_kit.js、灰の荒野の凡例は field_ash_00_kit.js）。
//   出口: n → a_pass.south
//   絵: field/under/a_battle（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("a_battle", {
    name: R.T('map.field_ash_battle.a_battle.name'), region: "r_ash", outside: "rock",
    legend: R.FieldArea.ASH_LEGEND, theme: 'ash', bgm: 'overworld', bbg: 'ash', propSet: 'ash', propSetBase: 'village',
    light: R.FieldArea.ASH_LIGHT,
    rows: [
      "RRRRRRRRRRRRRRRRRRRRssuuu:uuuuuRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRsssu::uuuuuRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRssss::uuuuuRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRssssss::uuuursssssrrrrRRRRRRRRRRRR",
      "RRRRRRRRRRRsssssssssssss::uuuussssssrrrrrsRRRRRRRRRR",
      "RRRRRRRRsssssssrssssssss::urusssssssssssssRRRRRRRRRR",
      "RRRRRRRRssssssrrsrssssss::uuusssssssssssssskRRRRRRRR",
      "RRRRRRssssssssssssssssss::sssssssssssssssskkkRRRRRRR",
      "RRRRRRssssssssssssssssss::uuurrssssssssssskkkRRRRRRR",
      "RRRRRRssXXXXXXXXXXXsssss::uuuuuussssrsssskkkssssRRRR",
      "RRRRRssssccccccccrXrssss::uuuurrussssssskkkrssssRRRR",
      "RRRRssssXcscccccccXrsssr:ruuuuuuussssssskkkrrssRRRRR",
      "RRRRssssXcccccccccXrsss:::ssuuuuusssssskkksssssRRRRR",
      "RRRRssssXcccccccccr::rrsr:ssssuuusssssskkksssrrrRRRR",
      "RRRRssssscccccccccs::sssu::ssssuussrsskkksssrrrrRRRR",
      "RRRRssssXcccccccccr::ssss::sssrrussrsskkksssssssRRRR",
      "RRRRssssXcccccccccXssssss::usssssrrruukkksssssssRRRR",
      "RRRRssssXccrccccscXrsssss::uuusrsssuuukkksssssssRRRR",
      "RRRRssssXcccccccccXrssssss:uuuusssssukkkkrsssssssRRR",
      "RRRRssssXXXXssXXXXXrssssss:uuusssssuukkkkssssssssRRR",
      "RRRRssssssssssssssussssssu::susssssuukkkkssssssssRRR",
      "RRRRrrrrrsssssssssssssrsss::ssrrsssuukkkkssssssssRRR",
      "RRRRssrrssssssssssssrrrrrs::susssssuuukkkssssssssRRR",
      "RRRRssrrssssssssssssssrrss::suusssuuuukkkssssssssRRR",
      "RRRssssssssssssssssrssssrs::uuuuusuuuurkkssssssssRRR",
      "RRRssssssssssssssssssssssr::uuuuuuuuuukkkusssssssRRR",
      "RRRssssssssssrrssssssssssu::uuuuuusurrukkkssssssRRRR",
      "RRRRsssssssssssrrssssssscccccccuuururrskkkssssssRRRR",
      "RRRRssrssssssssrrssssssscccXcccuuuuuuuskkkssrsssRRRR",
      "RRRRRsrrrsssssssssssssscccccccccuuuuuuskkkksrrssRRRR",
      "RRRRRsrrrssssssssssssssscccccccsssssssskkkksssssRRRR",
      "RRRRRssssssssssssssrssssuccccccssssssssskkssssssRRRR",
      "RRRRRRsssssssrssssssrrsrssscssssssssssssuusssssRRRRR",
      "RRRRRRssssssrrrsssrrrrssssssssrsssssssssssssssRRRRRR",
      "RRRRRRuusssssssssssssssssssssrrrsssrrrssssssssRRRRRR",
      "RRRRRRuuusuuuursssssssssssssssssssssrssssssRRRRRRRRR",
      "RRRRRRssRsRRsusssssssssssuuusssssssRRRRRRsRRRRRRRRRR",
      "RRRRRRRRRRRRRsRssssssssRRRssssRsRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
    ],
    objects: [
      {"type":"examine","x":27,"y":28,"event":"ash_battlefield_stone"},
      {"type":"sign","x":23,"y":4,"text":R.T('map.field_ash_battle.a_battle.objects.1.text')},
      {"type":"chest","id":"a_battle_c1","x":10,"y":17,"item":"i_revive","n":1},
      {"type":"waylamp","id":"wl_a_battle_1","x":28,"y":6,"lit":true},
    ],
    npcs: [

    ],
    spawns: {"north":{"x":25,"y":1,"dir":"s"}},
    exits: [{"x":25,"y":0,"w":2,"h":1,"to":{"map":"a_pass","spawn":"south"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_ash_plain"}],
    art: {"image":"field/under/a_battle","painted":[]},
    meta: {"sub":R.T('map.field_ash_battle.a_battle.meta.sub'),"worldRect":[285,441,96,45]},
    links: {},
  });
})(window.RPG);
