// 生成物（design/art_ref/gen/env/_tools/under/field_desert/ の areas_desert.py → fit.py → tomap.py）。手で直さない: 配置は areas_desert.py、当たりは fit.py で作り直す。
// エリア d_caravan「隊商路」（野営地をつなぐ砂の道、60×40）。エリア切り替えのフィールド（maps/field_00_kit.js、砂漠の凡例は field_desert_00_kit.js）。
//   出口: n → d_west.south, e → d_south.west, w → d_hollow.caravan, w → d_coast.caravan, 門 → desert_camp1.road, 門 → desert_camp2.road
//   絵: field/under/d_caravan（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("d_caravan", {
    name: "隊商路", region: "r_desert", outside: "dune_sand",
    legend: R.FieldArea.DESERT_LEGEND, theme: 'desert', bgm: 'desert', bbg: 'desert',
    rows: [
      "RRRRRRRRRRRRRRRRRRRssssssuuuuu..uuuuuuuuuuuuuuuuuussssssssss",
      "RRRRRRRRRRRRRRRRRRRssksssuuuuu..uuuuuuuuuuuuuuuuuussssrsssss",
      "RRRRRRRRRRRRRRRRRRssssssuuuuuu..uuuuuuuuuuuuuuuuusssssssssss",
      "RRRRRRRRRRRRRRRRRssssuuuuuuuuu..uuuuuuuuuuuuuuuuussssssssssk",
      "RRRRRRRRRRRRRRRsrsssuuuuuuuuuu..uuuuuuuuuuuuuuuksussRRRRRsss",
      "RRRRRRRRRRRRRRssssssuuruuuuRRR....sssuuuuuuuuuukkrssRRRRRsss",
      "uussRRRRRsssssssssussuuuuuuRRR.....sssssuuuuuuuuukkuuRRRRkss",
      "ussssssssssssssuuuuussuuuuuRR..uss...sssuuuuuuuuuksuuuuussss",
      ":::::::::::::::::uuuusuuuuuuu..ussss....uuuuuuuuurssssusssss",
      "ksssss:::::::::::::::::::uuu..uusuusss.....uuuuuussssssssrss",
      "ssssssssssssssuuuuuuuu::::::::usssssssuu.........ussssssssss",
      "RRRssssssssssssuussuussssuuu::ussssssssssuuuu.............ss",
      "RRRRRRRsssssssssssssuuuuuubu..kssssssssssssusssssuu.........",
      "RRRRRRRRRRssssssssssuuuuuuuuu..ussssssssssssssssssuuuusssuuu",
      "RRRRRRRRRRsssssssssssuuuuuuuu..usssssssssssssssssssuuussuuuu",
      "RRRRRRRRRRssuuusssssssuuuuuuu..ssssssssssssrsssssssuuuuuuuuu",
      "RRRRRRRRRssssuussssssbsuuuuuuu:.sssssssssssssssssssuuuuuuuuu",
      "RRRRRRRRssssssssssssssssuuuuu.::sssssssuuRRRRRRRsssuuuuuubuu",
      "uusuuuuusssssssksskssssssuuuu..:::ssssuuRRRRRRRRRssuuuuuuuuu",
      "uusuuuuuussssssssssssssssuuuu..us::ssssuRRRRRRRRRRsuuuuuuuuu",
      "ssuuuuuuubsssuussssssssuuuuu..uuus:::ssRRRRRRRRRRRsssuuuuuuu",
      "ksssssssssssuuuussssrsuuuuu...uuuusu::sRRRRRRRRRRRsssuuuuuuu",
      "sssssssssussuuuuuuuuuuuuuu...uuuuuuuu:::RRRRRRRRRssuussuuuuu",
      "sssssssssussuuuuuuuuuuuu....uuuuuuuuuuu::::RRRRRbuuuuusuuuuu",
      "ssssssssssrsuuuuuuuuuu.....uuuuuuuuuuuuuu::sRRuuuuuuuuuuuuus",
      "ssssssssssssuuuuuuu......uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuss",
      "ssssssssssssuuu...::..uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuss",
      "sssssssss........::uuuuubuuuuuuuuuuuuuuuuuuuuuuuuubuuuuuuuus",
      "...............u::uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuus",
      ".........ssssuuu:uuuuuuuubuuuuuuuuuuruuuuuuuuuuuuuuuuuuuuuus",
      "suuuuuuusssssuuX:XuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuRRRRuuuus",
      "uuuuuuuusssuuuRRRRRRuuuuuuuuuuuuuuuuuuuuuuuuuuruuRRRRRRRuuss",
      "uuuuuuuusssuRRRRRRRRRusssuuuuuuuuuuuuuuuuuuuuuuuuRRRRRRRssss",
      "uuuuuuuusssRRRRRRRRRRsssssssssuuuuuuuuuuuuuuuuuuuRRRRRRRssss",
      "uuuuuuRRsssRRRRRRRRRRssssssssssssssuuuuuuuuuuuuuuuuRRRssssss",
      "uuuuuRRRRssRRRRRRRRRRssssrsssssssssuuuuuuuuuuuuuuuusssssssss",
      "uuuuRRRRRsssRRRRRRRRRssbsssssssssssuuubuuuuuuuuuuuuskksssssb",
      "uuuuRRRRRssssRRRRRRRssssssssssssssssuuuuuuuuuuuuuuusskksssss",
      "uuuuuuuuuuuuusssssusssssssssssssssssssuuuubuuuuussssssssssss",
      "uuuuuuuuuuuuuussssssssssssssssssssssssuuuuusuuusssssssssssss",
    ],
    objects: [
      {"type":"sign","x":39,"y":25,"text":"野営地「岩の井戸」"},
      {"type":"sign","x":19,"y":29,"text":"野営地「星の石」"},
      {"type":"sign","x":8,"y":10,"text":"砂嵐のくぼ地\n――風のやまない近道。"},
      {"type":"sign","x":27,"y":13,"text":"西 → 西の浜（遠回り）\n北西 → 砂嵐のくぼ地（近道）"},
      {"type":"waylamp","id":"wl_desert_beacon_2","x":21,"y":27,"lit":"q_kasim_beacon_2","event":"desert_beacon"},
      {"type":"prop","id":"tent","x":39,"y":22},
      {"type":"prop","id":"copper_brazier","x":44,"y":25},
      {"type":"prop","id":"clay_jars","x":13,"y":29},
      {"type":"prop","id":"bones","x":33,"y":34},
      {"type":"prop","id":"cactus","x":47,"y":15},
    ],
    npcs: [

    ],
    spawns: {"north":{"x":30,"y":1,"dir":"s"},"east":{"x":58,"y":12,"dir":"w"},"hollow":{"x":1,"y":8,"dir":"e"},"coast":{"x":1,"y":29,"dir":"e"},"camp1":{"x":42,"y":24,"dir":"s"},"camp2":{"x":16,"y":29,"dir":"n"}},
    exits: [{"x":30,"y":0,"w":2,"h":1,"to":{"map":"d_west","spawn":"south"}},{"x":59,"y":12,"w":1,"h":2,"to":{"map":"d_south","spawn":"west"}},{"x":0,"y":8,"w":1,"h":2,"to":{"map":"d_hollow","spawn":"caravan"}},{"x":0,"y":29,"w":1,"h":2,"to":{"map":"d_coast","spawn":"caravan"}},{"x":42,"y":23,"w":1,"h":1,"to":{"map":"desert_camp1","spawn":"road"}},{"x":16,"y":30,"w":1,"h":1,"to":{"map":"desert_camp2","spawn":"road"}}],
    triggers: [{"id":"desert_ambush_2","x":24,"y":22,"w":5,"h":4,"on":"step","event":"desert_ambush_2","cond":["desert_caravan_on","!desert_ambush_2_done"]}],
    tilePatches: [{"cond":{"not":{"any":[{"choice":"ch_desert_route","is":"short"},"cleared_r_desert"]}},"rect":[0,7,2,4],"rows":["RR","RR","RR","RR"]}],
    zones: [{"rect":null,"zone":"zw_desert_caravan","cond":"desert_caravan_on"},{"rect":null,"zone":"zw_desert"}],
    art: {"image":"field/under/d_caravan","painted":[]},
    meta: {"sub":"野営地をつなぐ砂の道","worldRect":[60,440,100,61]},
    links: {"camp1":{"map":"d_caravan","spawn":"camp1"},"camp2":{"map":"d_caravan","spawn":"camp2"}},
  });
})(window.RPG);
