// 生成物（design/art_ref/gen/env/_tools/under/field_desert/ の areas_desert.py → fit.py → tomap.py）。手で直さない: 配置は areas_desert.py、当たりは fit.py で作り直す。
// エリア d_west「鷹の台地」（カシムの西の野、60×44）。エリア切り替えのフィールド（maps/field_00_kit.js、砂漠の凡例は field_desert_00_kit.js）。
//   出口: n → d_pass.south, e → kasim.gate_w, s → d_caravan.north, 門 → desert_hawks_1.mouth, 門 → desert_mirage.road
//   絵: field/under/d_west（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("d_west", {
    name: "鷹の台地", region: "r_desert", outside: "dune_sand",
    legend: R.FieldArea.DESERT_LEGEND, theme: 'desert', bgm: 'desert', bbg: 'desert',
    rows: [
      "uubuuuuuuuuuuuuusssssssssuuuu...uuuuuuuuuuuuuuuuuussssssssss",
      "uuuuuuuuuuuuuuussssssksssuuuu...uuuuuuuuuuuuuuuuusssssssssss",
      "uussuuuuuuuuuuussssssssssuuuu...uuuuuubuuuuuuuuuusssssssssss",
      "uusssssuuuuusssssssssuuuuuuuuu..uuuuuuuuuuuuuuuuussssssXXXXX",
      "uussssssuuuussssssssuuuuuuuuuu..uusuuuuuuuuuuuuksssssssXXXXX",
      "uusssssssuusssssssssuuuuuuuuuu..ssssssuuuuruuuukkksssuuXXXXX",
      "ubbssssssssssssssssssuuuuuuuuuu..ssbssssuuuuuuuukkkkTuuXXXXX",
      "usssssRRRRRRRRRRRRRRssuuuuuuuru..sssssssuuuuuuuukksTTTuXXXXX",
      "kssRRRRRRRRRRRRRRRRRRsssuuuuuuus..ssssssuuuuuuuuusTTTTTXXXXX",
      "kssRRRRRRRRRRRRRRRRRRRsssuuuuuus...sssuuuuuuuuuuusTTTTTXXXXX",
      "sssRRRRRRRRRRRRRRRRRRRRssuuuuuuss...sssuuuuuuuuuusTTTTTXXXXX",
      "ssRRRRRRRRRRRRRRRRRRRRRssuuuuussss...sssssuuuuussuuTTTsXXXXX",
      "ssRRRRRRRRRRRRRRRRRRRRRuuuuuuukssss...sssssssssssuuuussXXXXX",
      "ssRRRRRRRRRRRRRRRRRRRRRuuuuuuussssss...ssssssssssssuussXXXXX",
      "ssRRRRRRRRRRRRRRRRRRRRRuuuuuuuussssss....ssssssssssuuTTXXXXX",
      "ssRRRRRRRRRRRRRRRRRRRRRuuuuuuussrssssss...sssssssssuTTTXXXXX",
      "ssRRRRRRRRRRRRRRRRRRRRRsuuuuuussssssssss....sssssssuuTuXXXXX",
      "ssRRRRRRRRRRRRRRRRRRRRRsbuuuukksssssssssus....sssssuuuuXXXXX",
      "uusRRRRRRRRRRRRRRRRRRRsskkkkkkkkkkssssuuuuu.....sssuuuuXXXXX",
      "usssRRRRRRRRRRRRRRRRRsskkkkkkkkkkkkksssusssss...............",
      "sssssRRRRRRRRRRRRRRRsskkkkkkkkkkkkkkkssssssssus.............",
      "kssssRRRRRRRRRRRRRRssskkkkkkkckkkkkkksssssssuuu..ssssu......",
      "ssssssRRRRRRRRRRRRuusskkkkkkkkkrkkkkuuuuuuusuuu..ssuussXXXXX",
      "sssssssssRRRRRRRuuuuuuukkkkkkkkkkkkkuuburuuuru..ussuuusXXXXX",
      "srssssssssss::uuuuuuuuukkkkkkkkkkkkuuuuuuuuuuu..uuuuuuuXXXXX",
      "ssssssssssrs::uuuuuuuruubuuuuuuuuuuuuuuuuuuuuu..uuuuuuuXXXXX",
      "sssrbssbssssu:::::uuuuuuuuuuuuuuuubuuuuuuuuuu..uuuuuuuuXXXXX",
      "RRRRsssssssuuuuu:::::uuuuuuuuuuubuuuuuuuuuuu...uuuuuuuuXXXXX",
      "RRRRssssssssuuuuuuu::::::uuuuuuuuuuuuuuuuuu...uuuuuuruuXXXXX",
      "RRRRRusssssssuuuubuuuuu::::::uuuuuuuuuuuuu...uuuuuuuTTuXXXXX",
      "RRRRRuussssssuuuuuuuuuuuuuu::::::uuuuuuuu...uuuuuuTTTTTXXXXX",
      "RRRRRuuussssssuuuuuuuuuuuuuuuuu:::::::::::.uuruuusTTTTTXXXXX",
      "RRRRRRuusssssssuuuuuuussssuuuuuuuuuuuu::::uuuuuussTTTTTXXXXX",
      "RRRRRRussssssssuuuuussrssssssssuuusuuu...uuuuuuuussTTTTXXXXX",
      "RRRRRuusssssssssuuuusssssssssssssssssu..uuuuuuuuuusTTTsXXXXX",
      "RRRRuuussssssssssuuussssssssssssssssu..uuuuuuuuuuuuTTTsXXXXX",
      "RRRRuuuusssssrsssuuussssssssssssssss...uuuuuuuuuurusTksXXXXX",
      "RRRuuuuusssssssssuuussssssssssssssss..uuuuuuuuuuuussskkXXXXX",
      "Ruuuuuuuuuuuusssssussssssssssssssss..suuuuuuuuussssssssXXXXX",
      "uuuuuuuuuuuuussssssssssrsssssssssss..suuuussuurssssssssXXXXX",
      "uuuuusuuuuuuusssssssssssssssssssss...sssuussssssssssssssssss",
      "uuuuuuuuuuuuusssssssssssssssssssss..ssssuussssssssssssssssss",
      "uuuuuuuuuuuuuuussssssssssssrsssrss..ussssssssssssssssssssssb",
      "uuuuuuuuubuuuuussssssbssssssssssss..ubssssssssssssssssssssss",
    ],
    objects: [
      {"type":"examine","x":29,"y":21,"event":"desert_mirage_empty","cond":{"not":"desert_night"}},
      {"type":"prop","id":"lantern","x":25,"y":19,"cond":"desert_night"},
      {"type":"prop","id":"lantern","x":33,"y":19,"cond":"desert_night"},
      {"type":"prop","id":"lantern","x":25,"y":23,"cond":"desert_night"},
      {"type":"prop","id":"lantern","x":33,"y":23,"cond":"desert_night"},
      {"type":"prop","id":"lantern","x":29,"y":18,"cond":"desert_night"},
      {"type":"sign","x":35,"y":24,"text":"砂の真ん中の平地\n消灯の刻に、灯りの列が揺れるという。"},
      {"type":"sign","x":15,"y":27,"text":"岩の台地\n夜、鷹の笛が聞こえるという。"},
      {"type":"sign","x":50,"y":23,"text":"オアシスの町カシム\n――泉を囲む市場"},
      {"type":"waylamp","id":"wl_desert_beacon_1","x":42,"y":32,"lit":"q_kasim_beacon_1","event":"desert_beacon"},
      {"type":"waylamp","id":"wl_d_west_gate_n","x":50,"y":18,"lit":true},
      {"type":"waylamp","id":"wl_d_west_gate_s","x":49,"y":24,"lit":true},
      {"type":"waylamp","id":"wl_d_west_road","x":34,"y":12,"lit":true},
      {"type":"prop","id":"bones","x":9,"y":26},
      {"type":"prop","id":"thorn_bush","x":16,"y":29},
      {"type":"prop","id":"copper_brazier","x":53,"y":19},
      {"type":"prop","id":"copper_brazier","x":53,"y":22},
    ],
    npcs: [

    ],
    spawns: {"north":{"x":30,"y":1,"dir":"s"},"kasim":{"x":58,"y":20,"dir":"w"},"south":{"x":34,"y":42,"dir":"n"},"hawks":{"x":12,"y":25,"dir":"s"},"mirage":{"x":29,"y":22,"dir":"s"}},
    exits: [{"x":30,"y":0,"w":2,"h":1,"to":{"map":"d_pass","spawn":"south"}},{"x":59,"y":20,"w":1,"h":2,"to":{"map":"kasim","spawn":"gate_w"}},{"x":34,"y":43,"w":2,"h":1,"to":{"map":"d_caravan","spawn":"north"}},{"x":12,"y":24,"w":1,"h":1,"to":{"map":"desert_hawks_1","spawn":"mouth"}},{"x":29,"y":21,"w":1,"h":1,"to":{"map":"desert_mirage","spawn":"road"},"cond":"desert_night"}],
    triggers: [{"id":"desert_ambush_1","x":39,"y":32,"w":5,"h":3,"on":"step","event":"desert_ambush_1","cond":["desert_caravan_on","!desert_ambush_1_done"]}],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_desert_caravan","cond":"desert_caravan_on"},{"rect":null,"zone":"zw_desert"}],
    art: {"image":"field/under/d_west","painted":[]},
    meta: {"sub":"カシムの西の野","worldRect":[40,400,116,70]},
    links: {"kasim":{"map":"d_west","spawn":"kasim"},"hawks":{"map":"d_west","spawn":"hawks"},"mirage":{"map":"d_west","spawn":"mirage"}},
  });
})(window.RPG);
