// 生成物（design/art_ref/gen/env/_tools/under/field_marsh/ の areas_marsh.py → fit.py → tomap.py）。手で直さない: 配置は areas_marsh.py、当たりは fit.py で作り直す。
// エリア m_north「霧の入口」（山あいの街道から湿原へ下りる所、52×40）。エリア切り替えのフィールド（maps/field_00_kit.js、湿原の凡例は marsh_field_00_kit.js）。
//   出口: n → world.marsh_n, s → m_west.north
//   絵: field/under/m_north（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("m_north", {
    name: R.T('map.marsh_field_north.m_north.name'), region: "r_marsh", outside: "marsh_water",
    legend: R.FieldArea.MARSH_LEGEND, theme: 'moss_village', propSet: 'marsh', bbg: 'marsh',
    light: { ambient: '#667aa6', k: 0.64, mood: 'night' },   // 湿原: 泥炭と葦の絵は砂より暗いので、夜の明るさを少し上げる（霧の青み）
    rows: [
      "RRRRRRRRRRRRRRRRRRRRRRR;...;rRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRR,,..;rRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRR,,..rrRRRRRRRRRRRRRRRRRRRRRRR",
      "RRRRRRRRRRRRRRRRRRRRRRwb,..rrrRRRRRRRRRRRRRRRRRRRRRR",
      ",R,,RRRRRRR,R,RRRRRRRwrr..rrr;,,,,,RRRRRR,,RRRRRRRR,",
      ",,,,,,,,,,,,,,,,,,,,rrrr..;;b;,,rr,,,,,,,,,RR,,RRR,,",
      ",,,,,R,,,,,R,,,TT,,,,rrr..;bwb,,rr,b,,,RR,,,,,RRRR,,",
      ",bb,,,;rr,,,r;;;;rr,,rr...bwww,rr,,wrbbwwb,,,,RRRRR,",
      ",wwr,rr;;,,,w;rrTr,,,,,..,bwww,,,r,rwwwbr,,,,,rrrr,,",
      "rbb,,rr;,,,rr,,,r,,,,,,..,,bbr,,rrrrrrr,,,,,r,,,,,,,",
      ",,,rr,r,,,,,r,,,,,,,,,..,r,,,r,,rrrr,,,b,,,,,,,,,,,,",
      "r,,rr,T\"rr,,b,,bbb,,,,.:,,,,,,,\"rXXX;;bw,,rTb,,,,r,,",
      ",,,,,,r\"\"\",ww,bwwwb,,..:::::::,\"rXXX;bwwwwwbwb,,,,,,",
      ",,,,,,,\",XXXXwbbwwbb,..,,,,,::::rXXX,bwwwwwbwb,,,,,,",
      ",,,,,,,,,XXXXwbbwwww...,,,,,,,,,::,,,;bwww,,b,,,T,,,",
      ",,\",,\"\",,rrrrrr:::::::,,,bb,,,,,;rs,,,,bb,,,,,,,bbb,",
      ",bbbbbb;;,,:,bwr,,,,.:.,bwwb,bb,,,,,,,,,,,,,,,,bbbbb",
      ",bbbbbb;;,,,,,b,,,,,,..,bbbbbwwb,,,,,,,,,,,,,,bbbbbb",
      ",bbbbbb;;b,,;;;;;;,,b..bwwwwwwwwwww,,,,bb,,,wwwwbbbb",
      "bbbbbwwwwwbbbb;;;;;bw==wwwwwwwwwwwwwwwwwwwwwwwwwwwww",
      "wwwwwwwwwwwwwwwwwwwwww==wwbbbbbbbwwwwwwwwwwwwwwwwwww",
      "wwwwwwwwwwwwwwwwwwwwwb..r,,,,,,,,bbsrwwwwwbbbbbrrrww",
      "wwbbbbrwbbbbbwwwwbbbb;;..,,,,\",,,,\",\"b,,bbTr,,,,,,,b",
      "bbbbbbrwwwrbwbrbb;;;;;;;..,,b,,\"\"\"\"\",,,,,,r,;;;,\"\",,",
      "bbbbbbrwwwwwwwww,,,,,,,,...\"\"\",b\"\"\"\"\",,,,,,,;;;,\",,,",
      "bbbbbbbbbbbbbbbb,,,,,,,,,..,\",bwb\"\",\",,,,,,bbb,,,,,,",
      "bbbbbbbbbbbbbbbbb,,,,,,,,...\",\"b,,;;;;,,,,bbbbbb,,,,",
      "bbbbbbbbbbbbbbbbwb,,,,,,,,..\",,,,;;;;;;,,bbbbbbbbbw,",
      "bbbbbwwwwbbbbbbbwb,,,\",,,,..\",,,,;;;;;;,,bbwbbwbbbb,",
      "bbbbwwwwwwbbbb,,wwb,,,,,,,,..,,,,;;;;;;bbwwwwwwwbbbb",
      "bbbbwwwwwwbbbb,,bb,,,,,,,,,..\",,b;;;;;bbbwwwwwwwbbbb",
      "bbbbwwwwwwbbbb,T,,,,,,,,,,,..,,bw;;;;bbbbwwwwwwwbbbb",
      "bbbbbbbwwbbbbb,,,,,,,,,,,\"\"..,bww;;;;bbbbbwwwwbbbrbb",
      "bbbbbbbbbbbbbwr,,,,bb,,,,,..,,,bw,,;,;bbbbbbbbbbb,,,",
      "bwwbbbbbwwbwwww;,,bwwb\",,,..,,,,,,,,,,wwbbbbbbbbb;;;",
      "bwwwwwbrwwwbbww;,,,bb\",,,,..,,,,,,\",,,bwwwrrr,,,,;;;",
      "rrwwwwbwbbwbbbb;r\",\"\"\",,,..,,,,,,,\",,,bwbwwwb,,,s;;;",
      "rrwwwwwwwbbwbb,,;,\"\"r\",,,..,,,,,,,,,,,,bbwrb\",,,;;;;",
      "bbwwwwwwwbbwwwb,\"rwb\"\",,,..,,,,,,,,,,,,,,brTr\",\"\",,,",
      "wbwwwwwwwbbwwwwwwwb\"\"\",,,..\"\",bw,,,,,,,,,,,,\"\"\",\",,,",
    ],
    objects: [
      {"type":"sign","x":27,"y":6,"text":R.T('map.marsh_field_north.m_north.objects.0.text')},
      {"type":"examine","x":34,"y":14,"event":"marsh_field_tower"},
      {"type":"examine","x":35,"y":14,"event":"world_poi_cache","item":"i_ether","key":"marsh_tower"},
      {"type":"waylamp","id":"wl_m_north_1","x":27,"y":15,"lit":true},
      {"type":"waylamp","id":"wl_m_north_2","x":24,"y":32,"lit":true},
      {"type":"prop","id":"log","x":13,"y":16},
    ],
    npcs: [
      {"id":"peat_cutter","look":"npc_marsh_woman","name":R.T('map.marsh_field_north.m_north.peat_cutter.name'),"x":14,"y":17,"dir":"s","move":"still","talk":{"lines":[{"text":R.T('map.marsh_field_north.m_north.lines.0.text')}]},"reward":null},
    ],
    spawns: {"north":{"x":25,"y":1,"dir":"s"},"south":{"x":26,"y":38,"dir":"n"}},
    exits: [{"x":24,"y":0,"w":3,"h":1,"to":{"map":"world","spawn":"marsh_n"}},{"x":25,"y":39,"w":3,"h":1,"to":{"map":"m_west","spawn":"north"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_marsh_road"}],
    art: {"image":"field/under/m_north","painted":[],"overlay":"field/under/m_north_over"},
    meta: {"sub":R.T('map.marsh_field_north.m_north.meta.sub'),"worldRect":[475,166,54,33]},
    links: {},
  });
})(window.RPG);
