// 生成物（design/art_ref/gen/env/_tools/under/field_marsh/ の areas_marsh.py → fit.py → tomap.py）。手で直さない: 配置は areas_marsh.py、当たりは fit.py で作り直す。
// エリア m_bog「鐘沈みの沼の縁」（霧の来る所、52×44）。エリア切り替えのフィールド（maps/field_00_kit.js、湿原の凡例は marsh_field_00_kit.js）。
//   出口: n → m_fen.south, s → world.marsh_s, 門 → marsh_bog.entrance
//   絵: field/under/m_bog（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("m_bog", {
    name: R.T('map.marsh_field_bog.m_bog.name'), region: "r_marsh", outside: "marsh_water",
    legend: R.FieldArea.MARSH_LEGEND, theme: 'moss_village', propSet: 'marsh', bbg: 'marsh',
    light: { ambient: '#667aa6', k: 0.64, mood: 'night' },   // 湿原: 泥炭と葦の絵は砂より暗いので、夜の明るさを少し上げる（霧の青み）
    rows: [
      ",,,,sssss\"rr,,,ss,sswww;;..;;;.wbss;;;,,,,FFFFFFFFFF",
      "w.,,,s.s,;;,,,,,sssssw,,,..;;;;.sss;;;,,,,FFFFFFFFFF",
      "w.,,,,ss,,,,,,,,,sssss,,,..;;;;;;ss;;;,r,,FFFFFFFFFF",
      "w.,,,,,s,,,,,,,,,sssss,,,..,;;,,,,,,;;;.,.FFFFFFFFFF",
      "Fw.,,,,,,,,,,,,;rsssss,,,..,;;,,,,,,,;,.wwwFFFFFFFFF",
      "FFFFF,,,,,,,,,;;ssss.s,,,..;r;,,,,,,,,,,.,,,FFFFFFFF",
      "FFFFFFF,,,,,,..ws.ss..,,..;;;;,,,,,,,,,,,,,,s,FFFFFF",
      "FFFFFFFwb.b...wwwwbs.s,,..,rr,,.,,,,,,,,,,,,,FFFFFFF",
      "FFFFFFFFwwb.wwwwwwww,,,..,,;..ww,,,,,,,,,,,,,,FFFFFF",
      "FFFFFFFFFwbwwwwwwwwwb,...,,,ww..,,,,,,,,.,,,,,,,,,,,",
      "FFFFFFFFFwwbwwwwwwwwb,..,,,,,.sss,.w..,.wb,,,,,,,,,,",
      "FFFFFFFFFb,,,,wwwww,,,..,,,,,ssss.wwwww,,,,,,,,,,,..",
      "FFFFFFFFFFT,,,...,,,,..,,,,,,sss..wwwww.,,,,,,,,,,ww",
      "FFFFFFFFFFT,,,,,,www,,..,,,,,ssss.www.,,,,,,,,,,,,..",
      "FFFFFFFFFFww,,,,wwwb,,..,,,,,,ssss...sss,,,,,,,,,,,r",
      "FFFFFFFFFFb,,,,,wb.,,,..,,,,,,,,ssssssss,,,,,,,,,,,,",
      "FFFFFFFFFF,,,,,,,b,,,,..,,,,,,,,sssssss,,,,,,,,,,,ss",
      "FFFFFFFFFFb,,,;,.w,,,,,..,,,,,s,,,,ssss,...w,,,,,sss",
      "FFFFFFFFFFwwws;,.;,,.,,..,,,rr,,,s,ssss.wwwwwwss,,ss",
      "FFFFFFFFFFwwww;;;;;.wb:::.,,,ss,,,ssssssswwwwww.,,,s",
      "FFFFFFFFFwwwwwb;;;:::::::.s::::==========wXXwwww.,,,",
      "FFFFFF:T:::::::::::::;.ss..::::==========wXXwww.,,,,",
      "FFFFFF::::::::::;;;;;.w;s..,,,s,,ssss.wwwwwwwww,,,,,",
      "FFFFFF,,,,,sssss;;;;.wwb,,..,,,,\"sssss..wwwwwww.,,,,",
      "FFFFFFFFFTsssssss,Xb.wwwb,..,,,,\"rsssss...wwww;,,,,,",
      "FFFFFFFFFTssssss,,Xwwww:::...,,sssssss,,,,,,;;,,,,,,",
      "FFFFFFFFFssssss,,,:w::::,,,..sss,,;sss,w,,.,,;,b,,,,",
      "FFFFFFFFFFTssss,,,::wwb,,,,..ss,,;ssss.w,swbswww..,,",
      "FFFFFFFFFFsssws,ss.wwwb,,,,..sss,;ssss...wwwwwwwww.s",
      "FFFFFFFFFFFbwwbsss..w.,,,,,..ssssssssss..wwwwwwwwwws",
      "FFFFFFFFFFFwwwbs.ss..,,,ss,..sssssssssss.wwwwwwwwwws",
      "FFFFFFFFFFFwwww..bss,,,,s,,..,,ss;sssss.bbwwwwwwwwss",
      "FFFFFFFFFFFwwww.bw.s,,,,,,..,,,r,,;;;;.wwb.wwww.wwss",
      "FFFFFFFFFFwwwwbwwbs,,,,,,,..,,,,,,,..b.www..w...wssb",
      "FFFFFFFFFFw..wwwwww,,,,,,,..b,,,,,,.ww..ww.,...sss..",
      "FFFFFFFFFF..wwwwwwwwrr,,,,..w,,,,,,,.,,,.,r,,,,sssss",
      "FFFFFFFFFF,wwwwwwwww\",,,,...,,,,,,,.,,,,,,;,,,,sssss",
      "FFFFFFFFFT,,.wwwwww,b,,,,..,,,,,,,,,,,,,,,,,,,,ssss;",
      "FFFFFFFFF,,,,..w..,\"wb,,,..,,,,,,,,,,,,bbwwb,,,,,,,,",
      "FFFFF,,,,,,,ss,...,.w.,rr..,r,,,,,,,,,bwwwww.,,,,,,,",
      "FFF,,,,,,,,,ssssssss,,;\"\"..,\",,,,,,,,b,wwwww.,,,,,,,",
      ",,,,,,,,,,,sssssssss,;;;,..,,sss,,,,,,,,www.,,,,,,,,",
      ",,,,,,,,,,;sssssss,;;;;;,..,,ssss,,r,,,,...,,,,,T,,,",
      ",,,,,,,,,;;ssssssss,;;;;,..,,ssss,,,,,,,...,,,,,\",,,",
    ],
    objects: [
      {"type":"examine","x":6,"y":22,"event":"marsh_mistwall","cond":{"not":"marsh_assembly_done"}},
      {"type":"examine","x":18,"y":25,"event":"marsh_songstone"},
      {"type":"examine","x":41,"y":21,"event":"world_poi_marsh_bell"},
      {"type":"sign","x":15,"y":20,"text":R.T('map.marsh_field_bog.m_bog.objects.3.text')},
      {"type":"sign","x":29,"y":40,"text":R.T('map.marsh_field_bog.m_bog.objects.4.text')},
      {"type":"prop","id":"bell_frame","x":35,"y":12},
      {"type":"prop","id":"bell_frame","x":14,"y":36},
      {"type":"prop","id":"bell_frame","x":46,"y":31},
      {"type":"waylamp","id":"wl_m_bog_1","x":23,"y":7,"lit":true},
      {"type":"waylamp","id":"wl_m_bog_2","x":33,"y":36,"lit":true},
    ],
    npcs: [

    ],
    spawns: {"north":{"x":26,"y":1,"dir":"s"},"south":{"x":26,"y":42,"dir":"n"},"bog":{"x":7,"y":22,"dir":"e"}},
    exits: [{"x":25,"y":0,"w":3,"h":1,"to":{"map":"m_fen","spawn":"south"}},{"x":25,"y":43,"w":3,"h":1,"to":{"map":"world","spawn":"marsh_s"},"cond":{"not":{"slice":true}}},{"x":6,"y":22,"w":1,"h":1,"to":{"map":"marsh_bog","spawn":"entrance"},"cond":"marsh_assembly_done"}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_marsh"}],
    art: {"image":"field/under/m_bog","painted":[],"overlay":"field/under/m_bog_over"},
    meta: {"sub":R.T('map.marsh_field_bog.m_bog.meta.sub'),"worldRect":[523,283,56,59]},
    links: {"bog":{"map":"m_bog","spawn":"bog"}},
  });
})(window.RPG);
