// 生成物（design/art_ref/gen/env/_tools/under/field_marsh/ の areas_marsh.py → fit.py → tomap.py）。手で直さない: 配置は areas_marsh.py、当たりは fit.py で作り直す。
// エリア m_west「ロッホの西の岸」（湖の町へ渡る桟橋、56×44）。エリア切り替えのフィールド（maps/field_00_kit.js、湿原の凡例は marsh_field_00_kit.js）。
//   出口: n → m_north.south, e → loch.gate_w, s → m_fen.north
//   絵: field/under/m_west（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("m_west", {
    name: R.T('map.marsh_field_west.m_west.name'), region: "r_marsh", outside: "marsh_water",
    legend: R.FieldArea.MARSH_LEGEND, theme: 'moss_village', propSet: 'marsh', bbg: 'marsh',
    light: { ambient: '#667aa6', k: 0.64, mood: 'night' },   // 湿原: 泥炭と葦の絵は砂より暗いので、夜の明るさを少し上げる（霧の青み）
    rows: [
      "ww,,,,;;;\";,,,,,,,,,..,;;;;wbw~~~~~~~~~~~~~~~~~~~~~~~bbb",
      "bbT,,;;;;;;,,,,,,,,,..,;;;;;;b~~~~~~~~~~~~~~~~~~~~~~~bbb",
      ",T,,,;;;;;;;,TTT\",,,..\"\"\";,,bb~~~~~~~~~~~~~~~~~~~~~~~bbb",
      ",,,,,;;;;;;,,TTT\"\",,..,\"\",,bb~~~~~~~~~~~~~~~~~~~~~~~~~bb",
      ",,,TT;;;;;;,,TTT\"\"\",..,,\",,bb~~~~~~~~~~~~~~~~~~~~~~~~bbb",
      "TTTTTTT;;;;,,,,\"\"\"\",..\",,,,bb~~~~~~~~~~~~~~~~~~~~~~~~~bb",
      "TTTTTTT;;;;,,,,,,r,..,,,,,,Tbb~~~~~~~~~~~~~~~~~~~~~~~bbb",
      "TTTTTTT;;;,,,,,,,,,..,,,,,;,b~~~~~~~~~~~~~~~~~~~~~~~~bbb",
      "TT,,,,,,,,,,,,,,,,,..,,,,,;;,~~~~~~~~~~~~~~XX~~~~~~~~~bb",
      "TT,r,,,,,,,r,,,,,,..,,,;;,;;;;~~~~~~~~~~~~~XX~~~~~~~~bbb",
      "TT,,,,,,b,,,\",,,,,..,,,;;TTTT;~~~~~~~~~~~~~~~~~~~~~~~~bb",
      "TTT,,,,bw~,,,,,,,...,,,r;XXXX,,b~~~~~~~~~~~~~~~~~~~~~bbb",
      "TTT,,,www~,,,,,,,...;,r;;XXXX,,b~~~~~~~~~~~~~~~~~~~~~bbb",
      ",T,,,bbbbb,,,,,,,...;;;r:::::,,bb~~~~~~~~~~~~~~~~~~~~bbb",
      ",,,,,wwwwwb,,,,,,s..:::::::::=====~~~~~~~~~~~~~~~~~~~bbb",
      ",,,,,wwwwwwb,,,,bb..;;;;;;,,,,bb~~~~~~~~~~~~~~~~~~~~~~bb",
      ";,,,,wwwww~,,,,www..;;;,,,,,,,bb~~~~~~~~~~~~~~~~~~~~~bbb",
      "T,,bwbTb,b,,,,,,~ss..;;;,,,,,,b~~~~~~~~~~~~~~~~~~~~~~bbb",
      "TbwwwbT,,,,,r,,,,ss...;;,,,,,,,~~~~~~~~~~~~~~~~~~~~~~~bb",
      "TTbwwbT,,,,,,,,,\"\";;...;,,....b~~~~~~~~~~~~~~~~~~~~~~~ss",
      "TTwwwbT,,,,,,,,\"\"\"\"\";.......============================",
      "TTbwwb,\",,,,,,,,\"\",,,.....;,============================",
      "TTbbTTTT,\"\",,rr,,,,,;..,,,;,,,b~~~~~~~~~~~~~~~~~~~~~~~~~",
      "TTbbTTT\"\"\",,,,r,,,,,;..,,,,,,,b~~~~~~~~~~~~~~~~~~~~~~~bb",
      "TTbbTTT\"\"\",,,,,,,,,;;..\"\",,,,,,s~~~~~~~~~~~~~~~~~~~~~bbb",
      "TTb~b,,,\",;,,;;,,,,;..,,r,,,,,,,~~~~~~~~~~~~~~~~~~~~~bbb",
      "Tbwwb,,;;T~b,,;,,,,,..,,,,,,,,,,b~~~~~~~~~~~~~~~~~~~~bbb",
      "TTw~;;;b~wwwbb\"s\",,,..,,,,,,,,,,b~~~~~~~~~~~~~~~~~~~~bbb",
      "TTw;;;,wwwwwwwbT\"\"s..,,,,,,,,,T,bb~~~~~~~~~~~~~~~~~~~~bb",
      "TTb;;;,wwwwwwwb\"\"ss..:,,,,,,,XXX,bb~~~~~~~~~~~~~~~~~~bbb",
      "TT,;;;;,wwwwwwTs\"s..T~:::::::XXX,,b~~~~~~~~~~~~~~~~~~~bb",
      "TT,,,,,,,bwb,,;rrs..ww~Ts,,,,,,,,,b~~~~~~~~~~~~~~~~~~bbb",
      "TT,,,,,,;;,;s;ssss..www,,,,;;;;bwb~~~~~~~~~~~~~~~~~~~bbb",
      "TT,,,;;;;;;sssrss...wwb,,,,;;;,,bb~~~~~~~~~~~~XX~~~~~bbb",
      ",,,,b;;;;;;;s;;;;;..w,;,;;,,,,,bb~~~~~~~~~~~~~XX~~~~~bbb",
      ",,,,wb;;;;;;TTT;;;..;;;;;;;,,,,bb~~~~~~~~~~~~~~~~~~~~~bb",
      ",,,,,wb;;;;TTTTT;;..;;;;;;;,,,bb~~~~~~~~~~~~~~~~~~~~~bbb",
      ",,,,;,;;;;;TTTTT;;;..,;;;;;,,,bb~~~~~~~~~~~~~~~~~~~~~bbb",
      ",Tbbbbb;;;\";;;;;;\",..,,;;;;,,;bb~~~~~~~~~~~~~~~~~~~~~bbb",
      ",,bwwwwb\"\"\",;;;;;,,..,,,;;;;b;bb~~~~~~~~~~~~~~~~~~~~~bbb",
      ",bwwwwwb\"\"\",;;;;;,,..,,,,,;,wb,bb~~~~~~~~~~~~~~~~~~~~~bb",
      ",,bwwwwb\"\"\",;;~;;,,..,,T,,,,,,,,b~~~~~~~~~~~~~~~~~~~~bbb",
      ",,,\"\"\",,\"\"\",;;;ssss,..,,,,,,,,,bb~~~~~~~~~~~~~~~~~~~~bbb",
      ",,\"\",\",,\"\"\",;;;;ssrs..,,,,,,;,,,bb~~~~~~~~~~~~~~~~~~~~bb",
    ],
    objects: [
      {"type":"sign","x":26,"y":18,"text":R.T('map.marsh_field_west.m_west.objects.0.text')},
      {"type":"examine","x":28,"y":30,"event":"world_poi_marsh_stilt"},
      {"type":"prop","id":"mud_boat","x":34,"y":15},
      {"type":"waylamp","id":"wl_m_west_pier","x":25,"y":22,"lit":true},
      {"type":"waylamp","id":"wl_m_west_road","x":18,"y":38,"lit":true},
      {"type":"waylamp","id":"wl_m_west_north","x":17,"y":9,"lit":true},
    ],
    npcs: [
      {"id":"shore_fisher","look":"npc_marsh_old_m","name":R.T('map.marsh_field_west.m_west.shore_fisher.name'),"x":31,"y":13,"dir":"s","move":"still","talk":{"lines":[{"text":R.T('map.marsh_field_west.m_west.lines.0.text')},{"cond":"cleared_r_marsh","text":R.T('map.marsh_field_west.m_west.lines.1.text')}]},"reward":null},
    ],
    spawns: {"north":{"x":20,"y":1,"dir":"s"},"loch":{"x":54,"y":20,"dir":"w"},"south":{"x":21,"y":42,"dir":"n"}},
    exits: [{"x":19,"y":0,"w":3,"h":1,"to":{"map":"m_north","spawn":"south"}},{"x":55,"y":20,"w":1,"h":2,"to":{"map":"loch","spawn":"gate_w"}},{"x":20,"y":43,"w":3,"h":1,"to":{"map":"m_fen","spawn":"north"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_marsh_road"}],
    art: {"image":"field/under/m_west","painted":[],"overlay":"field/under/m_west_over"},
    meta: {"sub":R.T('map.marsh_field_west.m_west.meta.sub'),"worldRect":[481,193,51,54]},
    links: {"loch":{"map":"m_west","spawn":"loch"}},
  });
})(window.RPG);
