// 生成物（design/art_ref/gen/env/_tools/under/field_marsh/ の areas_marsh.py → fit.py → tomap.py）。手で直さない: 配置は areas_marsh.py、当たりは fit.py で作り直す。
// エリア m_bog「鐘沈みの沼の縁」（霧の来る所、52×44）。エリア切り替えのフィールド（maps/field_00_kit.js、湿原の凡例は marsh_field_00_kit.js）。
//   出口: n → m_fen.south, s → world.marsh_s
//   絵: field/under/m_bog（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("m_bog", {
    name: R.T('map.marsh_field_bog.m_bog.name'), region: "r_marsh", outside: "marsh_water",
    legend: R.FieldArea.MARSH_LEGEND, theme: 'moss_village', propSet: 'marsh', bbg: 'marsh',
    light: { ambient: '#667aa6', k: 0.64, mood: 'night' },   // 湿原: 泥炭と葦の絵は砂より暗いので、夜の明るさを少し上げる（霧の青み）
    rows: [
      ",,,,,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,,,,wFFFFFFFFFF",
      ",,,,,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,,,,TFFFFFFFFFF",
      ",,,,,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,,,,wFFFFFFFFFF",
      "w,,,,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,,,,,FFFFFFFFFF",
      "Fwwwww,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,,,,,,FFFFFFFFF",
      "FFFFFF,,,,,,,wbw,,,,,,,,,..,,,,,,,,,,,,,,,,,,FFFFFFF",
      "FFFFFFFT,,,,wbwbbbw,,,,,..,,,,,,,,,,,,,,,,,,,FFFFFFF",
      "FFFFFFFFw,,bbwwwwwbw,,,,..,,,,,,,,,,,,,,,,,,,FFFFFFF",
      "FFFFFFFFFw,wwwwwwwwbw,,..,,,,,,,,,,,,,,,,,,,,,,,,,,,",
      "FFFFFFFFFT,wwwwwwwwwb,...,,,,,,,,,wbw,,,,,,,,,,,,,,,",
      "FFFFFFFFFT,,wwwwwwwwb,..,,,,,,,,,wbwbbw,,,,,,,,,,,,,",
      "FFFFFFFFFFT,,wwwwwwb,,..,,,,,,,,,bwwwwb,,,,,,,,,,,,,",
      "FFFFFFFFFFT,,,,,,,,,,..,,,,,,,,,,,wwwww,,,,,,,,,,,,,",
      "FFFFFFFFFFT,,,,,,,,,,,..,,,,,,,,,,,w,,,,,,,,,,,,,,,,",
      "FFFFFFFFFFT,,,,,,,,,,,..,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
      "FFFFFFFFFFT,,,,,,,,,,,..,,,,,,,,,,,,,,,,,,,,,,,,,,,,",
      "FFFFFFFFFFT,,,,,,,,,,,..,,,,,,,,,,,,,,,,,wwwww,,,,,,",
      "FFFFFFFFFFT,,,,,,,,,,,,..,,,,,,,,,,,,,,,bbbbbww,,,,,",
      "FFFFFFFFFFT,,,,,,,,,,,,..,,,,,,,,,,,,,,bwwwwwbww,,,,",
      "FFFFFFFFFF,,,,,,,,,,,,:::.,,,,,,,,,,,,..wwwwwwbbw,,,",
      "FFFFFFF::,,,,,,,,,:::::::.,::::==========wXXwwww,,,,",
      "FFFFFF:::::::::::::::,,,,..::::==========wXXwwwb,,,,",
      "FFFFFFFFF:::::::,,,,,,,,,..,,,,,,,,,,,wwwwwwwwwb,,,,",
      "FFFFFF,,,T,,,,,,,,,,,,,,,,..,,,,,,,,,,,.wwwwwww,,,,,",
      "FFFFFFFFFT,,,,,,,,X,,,,,,,..,,,,,,,,,,,,,.wwwwb,,,,,",
      "FFFFFFFFFT,,,,,,,,X,,,,:::...,,,,,,,,,,,,,.bbbwww,,,",
      "FFFFFFFFFFT,,,,,,,:,::::,,,..,,,,,,,,,,,,,bwwbbbww,,",
      "FFFFFFFFFFTw,,,,,,:::,,,,,,..,,,,,,,,,,,wbwbbwwwbbw,",
      "FFFFFFFFFFFT,,,,,,,,,,,,,,,..,,,,,,,,,,,bwwwwwwwwwbw",
      "FFFFFFFFFFFT,,,,,,,,,,,,,,,..,,,,,,,,,,,,wwwwwwwwwwb",
      "FFFFFFFFFFFT,,,,,,,,,,,,,,,..,,,,,,,,,,,,,wwwwwwwww,",
      "FFFFFFFFFFFw,,,,,,,,,,,,,,,..,,,,,,,,,,,,,wwwwwwww,,",
      "FFFFFFFFFFF,,,wwb,,,,,,,,,..,,,,,,,,,,,,,,,wwww,,,,,",
      "FFFFFFFFFFT,wwwwwww,,,,,,,..,,,,,,,,,,,,,,,,,,,,,,,,",
      "FFFFFFFFFFTbwwwwwwww,,,,,,..,,,,,,,,,,,,,,,,,,,,,,,,",
      "FFFFFFFFFFwbwwwwwwww,,,,,,..,,,,,,,,,,,,,,,,,,,,,,,,",
      "FFFFFFFFFF,wwwwwwww,,,,,,..,,,,,,,,,,,,,,,ww,,,,,,,,",
      "FFFFFFFFF,,,,wwwwww,,,,,,..,,,,,,,,,,,,wwwwww,,,,,,,",
      "FFFFFFF,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,wwwbbbw,,,,,,,",
      "FFFF,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,wwwwwwb,,,,,,,",
      "FFF,,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,,wwwwwb,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,,.wwww,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,,,...,,,,,,,,,",
      ",,,,,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,,,,,,,,,,,,,,,",
    ],
    objects: [
      {"type":"door","x":6,"y":21,"w":1,"look":"none","to":{"map":"marsh_bog","spawn":"entrance"},"cond":"marsh_assembly_done"},
      {"type":"examine","x":6,"y":21,"event":"marsh_mistwall","cond":{"not":"marsh_assembly_done"}},
      {"type":"examine","x":18,"y":25,"event":"marsh_songstone"},
      {"type":"examine","x":41,"y":21,"event":"world_poi_marsh_bell"},
      {"type":"sign","x":15,"y":20,"text":R.T('map.marsh_field_bog.m_bog.objects.4.text_2')},
      {"type":"sign","x":29,"y":40,"text":R.T('map.marsh_field_bog.m_bog.objects.5.text')},
      {"type":"prop","id":"bell_frame","x":35,"y":12},
      {"type":"prop","id":"bell_frame","x":14,"y":36},
      {"type":"prop","id":"bell_frame","x":46,"y":31},
      {"type":"waylamp","id":"wl_m_bog_1","x":23,"y":7,"lit":true},
      {"type":"waylamp","id":"wl_m_bog_2","x":28,"y":36,"lit":true},
    ],
    npcs: [

    ],
    spawns: {"north":{"x":26,"y":1,"dir":"s"},"south":{"x":26,"y":42,"dir":"n"},"bog":{"x":7,"y":21,"dir":"e"}},
    exits: [{"x":25,"y":0,"w":3,"h":1,"to":{"map":"m_fen","spawn":"south"}},{"x":25,"y":43,"w":3,"h":1,"to":{"map":"world","spawn":"marsh_s"},"cond":{"not":{"slice":true}}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_marsh"}],
    art: {"image":"field/under/m_bog","painted":[],"overlay":"field/under/m_bog_over"},
    meta: {"sub":R.T('map.marsh_field_bog.m_bog.meta.sub'),"worldRect":[523,283,56,59]},
    links: {"bog":{"map":"m_bog","spawn":"bog"}},
  });
})(window.RPG);
