// 生成物（design/art_ref/gen/env/_tools/under/field_marsh/ の areas_marsh.py → fit.py → tomap.py）。手で直さない: 配置は areas_marsh.py、当たりは fit.py で作り直す。
// エリア m_fen「沈んだ礼拝堂の原」（ロッホの南の泥炭の原、56×44）。エリア切り替えのフィールド（maps/field_00_kit.js、湿原の凡例は marsh_field_00_kit.js）。
//   出口: n → m_west.south, s → m_bog.north, e → m_lotus.west
//   絵: field/under/m_fen（v2/assets/env/field/under/。無ければマスから焼く）
(function (R) {
  'use strict';
  R.FieldArea.def("m_fen", {
    name: R.T('map.marsh_field_fen.m_fen.name'), region: "r_marsh", outside: "marsh_water",
    legend: R.FieldArea.MARSH_LEGEND, theme: 'moss_village', propSet: 'marsh', bbg: 'marsh', bgm: 'marsh',
    light: { ambient: '#667aa6', k: 0.64, mood: 'night' },   // 湿原: 泥炭と葦の絵は砂より暗いので、夜の明るさを少し上げる（霧の青み）
    rows: [
      "TT,,,,;;;\";,wb~,,,.w..w.wwbT,ww~bbbbbbbbbbbbbbbbbbbwwwwb",
      ",,,,,;;;;;;,b,,,,,,b....wb;;;bwwbTbbbrbbbbbbbbbbbbbbwwbb",
      ",,,,,;,.;;;;b,,\"\",,,...bbTT,,wwbbTbbbbbbbbbbbbbbbbbbbbbw",
      ",,,,,w.w~ww~,,,b\"\",..,,\"\",,,;,bbbTbbbbbbbbbbbbbbbbbbbbbw",
      ",,,,bbwwwww~,,,b\"\"...,,,\",,rbbbbbTbbbbbbbbbwwwbbbwwwwbbb",
      ",,,,,bbbbwb~,,,\"\"...,,\",,,,bbbb~~~bbbbbbbbbwwwbbwwwwwbbb",
      ",,,,,wwwbbTT,,,,....bbbT,bbbb~~~~~~~bbbbbbw~bbwbwwwwbbbw",
      ",,,bwwwwwb~T,,,...bbb,.,,,,~~~~~~~~~~~bbbwbbbbwbbbwbbbbb",
      ",,bwwwwwwb~b,,...bb~~~~~~~~~~~~~~~~~~~~~bbbTbrrbbbwbbbww",
      ",,,,,.wwwb,bbT..,,b~~~~~~~~~~~~~~~~~~~~~~~~~bbbbbbwbTbww",
      ",,,,b,bw.~,w,~.,,bb~~~~~~~~~~~~~~~~~~~~~~~~~rbbbbbbbb,bw",
      ",,,,w,,b,,,,...,,bb~~~~~~~~~XXX~~~~~~~~~~~~~~bbbbbbbb,;b",
      ",,,,,,,,wT,,..,,bb~~~~~~~~~~XXX~~~~~~~~~~~~~~bbbbbbb;;;;",
      ",,bw,~~,wb~,...,,b~~~~~~~~~~~XX~~~~~~~~~~~~~~bbbbbb.;;;;",
      ",,,b,.,,wbb,..,,b,~~~~~~~X~~~~~~~X~~~~~~~~~~~bbb.b.;;;;;",
      ",,,,b,T.,b~,..,,,,~~~~~~~~ccccccc~~~~~~~~~~~~bbT;;;;;;;;",
      ";,,,bwwwbbT..=============ccccccc.~~~~~~~~~~~bbT;;;;,,,;",
      ";,,bwbbbTb,..==============cccccc.~X~~~~~~~~~~b;,,,,,,,,",
      ";;,bbbTT,,,..,============ccccccc.~~~~~~~~~~~bb,,,,,,,,,",
      ";;,,bbb,,,,..,,,\"...~~~~~~ccccccc,~~~~~~~~~~~bb,,,,,,,,,",
      ";;,,bbbTT,,..,,,\",b~~~~~~X~~~~~~~X~~~~~~~~~~~.b,,,,,,,,,",
      ",,,bbbbTT,,,.c,r\"bb~~~~~~~~~~~~~~~~~~~~~~~~~~,T,,,,,,,,,",
      ",,b,bbbTT\"\",.c,r,,,b~~~~~~~~~~~~~~~~~~~~~~~~,,,,\",,,bb,,",
      ",,,,bbbTT\",,..,,,,b,,~~~~~~~~~~~~~~~~~~~~~~bb,,,\"\",bbwb,",
      ",,,,bbbTbb,T...,,,,;;,~~~~~~~~~~~~~~~~~~~~bbT,,\"s,bbbbwb",
      ",,,,b,Tbbwb~,..,,,,;,~~~~~~~~~~~~~~~~~~~~~,b,,,,s\"bbbbbb",
      ",,,,,,,bbwb~T,..,,bwbww~~~~~~~~~~~~~~~~~,,,,,T,,,\"bbbbb,",
      ",\",;;;bwwwb~T\"..c,,wwbbbbbb~~~~~~~~bb,,,,,,,,,,ww,bbbb,,",
      "\"\";;;,,wwwb~T,\"..c..wwb,bb.,b~~~bbbbbbb,,,,,,,,ww,bbbb,,",
      ",,,;;;bbwwb~;;,\"..c\"\",,,,,,,bbbbbbbT,,,,,,,,,,,,,,,.b,,,",
      ",,,;;;;bww~;;;;s\"....,,,,,,,,bbbwwb,,,,:::::::::::::::::",
      "w~~,,,,,,;;;;;;ssss....,,,,,,,,,.w~::::::::::,,,,\"\",,,,b",
      "wwb,,,,,;;;;;;;s,,ss..:::::::::::::::,,,,,,,,,,b..b\",\",w",
      "wb~,,;;;;;;;s;;;,;T,,,::::::::,,,,,,,,,,,,,,,,wwwww\",,,w",
      ",,,,,;,b...;T;;,,.;b;;;....,,,,,,,,,,,,,,,,,,wwwwwww,,,,",
      ",~,,;bwwwwwb~T,,wwb~T,;;;...,b,,,,,,,,,,,,,,,wwwwwwwwb,,",
      ",b,,;;wwwwwb;T,wwwwbbTT;;;....bT\"\",,,b..,,\",,,.wwwww.,,,",
      ",,,,;bbwwwb;;;;;w,~;T,;;;;;...T,,,,,b,wwbT\"\",\"bb.bb,,\"T,",
      ",,\",;,bbbbbb;;;;;\",,,,,;TT;..;,,,TT,,,wwbb,,,,,,,,,,;;;;",
      "bT,,,,bbwb~,;;;;;,,,,,,,;;;..;,,,,,,,,w.b,,;,,,,,,,,;;;;",
      "b,,,,,bbwwb~;;;;;,,,,,,T,,;..;,,,,,,,,..,,,;;,,,,,,,,,;;",
      "wb~,,,bwww~,;;TT;,b,,,,,,,,..,,,,,,,,,,,,,,,;,,,,,,,,,,,",
      "ww~\"\"\",bbbT,;T;;ssbb,,,,,,,..,,,,,,,,,,,,,,,,;,,,,,,,,,,",
      "wb~b,\",,bbT,;;;;sbb,,,,,,,,..,,,,,,,,,,,\"\",;;,,T,,,,,,,,",
    ],
    objects: [
      {"type":"sign","x":11,"y":14,"text":R.T('map.marsh_field_fen.m_fen.objects.0.text')},
      {"type":"examine","x":29,"y":14,"event":"marsh_field_chapel"},
      {"type":"waylamp","id":"wl_m_fen_1","x":17,"y":7,"lit":true},
      {"type":"waylamp","id":"wl_m_fen_2","x":24,"y":31,"lit":true},
      {"type":"prop","id":"rotten_stump","x":9,"y":27},
    ],
    npcs: [

    ],
    spawns: {"north":{"x":21,"y":1,"dir":"s"},"south":{"x":27,"y":42,"dir":"n"},"east":{"x":54,"y":30,"dir":"w"}},
    exits: [{"x":20,"y":0,"w":3,"h":1,"to":{"map":"m_west","spawn":"south"}},{"x":26,"y":43,"w":3,"h":1,"to":{"map":"m_bog","spawn":"north"}},{"x":55,"y":30,"w":1,"h":2,"to":{"map":"m_lotus","spawn":"west"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_marsh"}],
    art: {"image":"field/under/m_fen","painted":[],"overlay":"field/under/m_fen_over"},
    meta: {"sub":R.T('map.marsh_field_fen.m_fen.meta.sub'),"worldRect":[499,241,60,48]},
    links: {},
  });
})(window.RPG);
