// 生成物（design/art_ref/gen/env/_tools/under/field_mine/ の areas_mine.py・dng_mine.py → fit.py → put_rows.py）。手で直さない。
// 描いた下絵に合わせた鉱山都市ドヴァンと深き坑道の当たり（rows、字は field_mine/lib.py と同じ）・絵（art）・建物の敷地と戸口（blds）。
// mine_dovan.js・mine_deep.js が R.Mine.PAINTED[id] を読む。
(function (R) {
  'use strict';
  const I = (R.Mine = R.Mine || {});
  I.PAINTED = /*DATA*/{
 "dovan": {
  "rows": [
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXXXRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXXXRRRRRRRRRRRRRRRRRRXR",
   "RRRRRXXXXXXXXXXXXkkkkksRRRRRsRRkkkkkkkkkkkkkkkkkkkRRRR",
   "RRRrkXXXXXXXXXXXXkkcXXXXckkkkkkkkkkkkkkkkkkkkkkkkkRRRR",
   "RRRrkXXXXXXXXXXXXkkcXXXXckkkkkkkkkkksskkkkkwwwwwrkrRRR",
   "RRRrkXXXXXXXXXXXXkkcXXXXckkkkkkkkkkkkkkkkkrwwwwwwwRRRR",
   "RRRrkXXXXXXXXXXXXrkcccccckkkkkkkkkkkkkkkkkkwwwwwwwRRRR",
   "RRXrkXXXXXXXXXXXXrkcccccckkkkkkkkkkkkkkkkkkkwwwwwwRRRR",
   "RRRrkXXXXXXXXXXXXrkkkkkkkkkkkkkkkkkkkkkkkkkkkwwwwkRRRR",
   "RRRkkXXXXXXcXXXXXkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkRRRR",
   "RRRkkkcccccccccccccccccccccccccccccccccccccccccckkRRRR",
   "RRRrkkcccccccccccccccccccccccccccccccccccccccccckrRRRR",
   "RRRRRrrrrrrcccRRRRRRRrRRRRRRRRkrRRRRRrrkkkkkkkkkrRRRRR",
   "RRRRRRRRRRRcccRRRRRRRRRRRRRRRRRRRRRRRRRRkkkRRRRRRRRRRR",
   "RRRRRRRRRRRcccRRRRRRRRRRRRRRRRRRRRRRRRRRkkkRRRRRRRRRRR",
   "RRRRRRRRRRRcccRRRRRRRRRRRRRRRRRRRRRRRRRRkkrRRRRRRRRRRR",
   "RRRRRRRsssRcccRsssRRRRRRRRXXXXXXXXXXXRRRkkkRRRRRllllll",
   "RRRRRsskkkkccckkkkrrrrRssRXXXXXXXXXXXkkkkkkkkkkRllllll",
   "RRRRkkXXXXXXXXkkkXXXXXXkkkXXXXXXXXXXXkkkkkkkkkkRllllll",
   "RRXRkkXXXXXXXXkkkXXXXXXkkkXXXXXXXXXXXrkkkkkkkkkRllllll",
   "RRRRkrXXXXXXXXrkkXXXXXXkkkXXXXXXXXXXXrkkkkkkkkkRllllll",
   "RRRRkkXXXXXXXXrkkXXXXXXkkkXXXXXXXXXXXrkkkkkkkkkRllllll",
   "RRRRkrXXXXXXXXrkkXXXcXXkkkXXXXcXXXXXXkkkkkkkkkkRllllll",
   "RRRRkkXXXXcXXXkkccccccccccccccccccccccckkkkkkkkkllllll",
   "RRRRkkccccccccccccccccccccccccccccccccckkkkkkkkrllllll",
   "RRRRkkccccccccccccccccccccccccccccccccckkkkkkkkrllllll",
   "RRRRkkkkkkkkkkkkccccccccccccccccccccccck====kkkRllllll",
   "RRRRRkkkkkkkkkkkccccccccccccccccccccccckkkkXXXkRllllll",
   "RRRRRkkkksskkkkkccccccccccccccccccccccckkkkXXXrRRlllll",
   "RRRRRkkkkkkkkkkkkkkkkkkkkcccckkkkkkkkkkkkRRXXXRRRlllll",
   "RRRRRRRRRkkkkkkkkkkRRRRRsccccRRRRRRRRRRkrRRXXXRRRlllll",
   "RRRRRRRRRRRRRRRRRRRRRRRRsccccRRRRRRRRRRRRRRXXXRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRsccccRRRRRRRRRRRRRRXXXRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRsccccRRRRRRRRRRRRRRXXXRRRRRRRR",
   "RRRRRRRRRRRRRRRssssssssssccccsRRRRRRRRRRRsRXXXssRRRRRR",
   "RRRRRkXXXXXXXXXkXXXXXXXkkcccckXXXXXXXXXXkkkkkkkkkRRRRR",
   "RRRRRkXXXXXXXXXkXXXXXXXkkcccckXXXXXXXXXXrkkkkXXXXRRRRR",
   "RRRRRkXXXXXXXXXkXXXXXXXkkccccrXXXXXXXXXXrkkkkXXXXRRRRR",
   "RRRRRkXXXXXXXXXkXXXXXXXrkcccckXXXXXXXXXXrkkkrXXXXRRRRR",
   "RRRRRkXXXXXXXXXkXXXXXXXrkcccckXXXXXXXXXXrkkkkXXXXRRXRR",
   "RRRRRkXXXXcXXXXkXXXcXXXkkcccckXXXXcXXXXXkkkkkXcXXRRRRR",
   "RRRRRkcccccccccccccccccccccccccccccccccccccccccckRRRRR",
   "RRRRRkcccccccccccccccccccccccccccccccccccccccccckRRRRR",
   "RRRRrkkkkkrkkkkkkkkkkkkkkcccckkkkkkkkkkkkkkkkkrkrRRRRR",
   "RRRRRRRRRRRRRRRRRRrkkkkkkcccckkkkkkkkkkkkrkkkrRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRsccccRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRsccccRRRRRRRRRRRRRRRRRRRRRRRRR"
  ],
  "art": {
   "image": "mine/under/dovan",
   "painted": []
  },
  "blds": [
   {
    "id": "dovan_hall",
    "x": 5,
    "y": 3,
    "w": 12,
    "h": 8,
    "door": [
     11,
     10
    ]
   },
   {
    "id": "dovan_guild",
    "x": 26,
    "y": 17,
    "w": 11,
    "h": 7,
    "door": [
     30,
     23
    ]
   },
   {
    "id": "dovan_tavern",
    "x": 6,
    "y": 19,
    "w": 8,
    "h": 6,
    "door": [
     10,
     24
    ]
   },
   {
    "id": "dovan_house",
    "x": 17,
    "y": 19,
    "w": 6,
    "h": 5,
    "door": [
     20,
     23
    ]
   },
   {
    "id": "dovan_items",
    "x": 6,
    "y": 36,
    "w": 9,
    "h": 6,
    "door": [
     10,
     41
    ]
   },
   {
    "id": "dovan_inn",
    "x": 16,
    "y": 36,
    "w": 7,
    "h": 6,
    "door": [
     19,
     41
    ]
   },
   {
    "id": "dovan_forge",
    "x": 30,
    "y": 36,
    "w": 10,
    "h": 6,
    "door": [
     34,
     41
    ]
   },
   {
    "id": "dovan_house2",
    "x": 45,
    "y": 37,
    "w": 4,
    "h": 5,
    "door": [
     46,
     41
    ]
   }
  ]
 },
 "mine_1": {
  "rows": [
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrkkkkkkRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRsRRRRRRRRRRRRRRRkkkkkkkrRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRskkkksRRRRRRRRRRRRRrkkkkkkRRR",
   "RRRRRRsRRRRRRRRRRRRRRRsRkkkkkkkksRRRRRRRRRRRRrkkkkkRRR",
   "RRRRRsssssRRRRRRRRRRRRskkkkkkkkksRRRRRRRRRRRRRrkkkRRRR",
   "RRRRskkkssRRRRRRRRRRRkkkkkkkkkkkkRRRRRRRRRRllRRkkkRRRR",
   "RRRrkkkkkksRRRRRRRRRRkkkkkkkkkkkksRRRRRRRRRllRRkkkRRRR",
   "RRRrkkkkkksRRRRRRRRRRkkskkkkkkkkkkRRRRRRRRRllRRkkkRRRR",
   "RRRrkkkkkkRRRRRRRRRRRRkkkkkkkkkkkRRRRRRRRRRllRRkkkRRRR",
   "RRRRrkkkkRRRRRRRRRRRRRRRRkkksRRRRRRRRRRRRRRlllRkkkRRRR",
   "RRRRRrkksRRRRRRRRRRRRRRRRRkkRRRRRRRRRRRRRRllllRkkkRRRR",
   "RRRRRrkksRRRRRRRRRRRRRRRRRkkRRRRRRRRRRRRRRllllRkkkRRRR",
   "RRRRRRrkssRRRRRRRRRRRRRRRRkkRRRRRRRRRRRRRRllllRkkkRRRR",
   "RRRRRRrkkksRkkRRRRRRRRRRsRkksRsRRRRRRRRRRRllllRkkkRRRR",
   "RRRRRRRrkkkkkksRRRRRRRRkkkkkkkksRRRRRRRRRRllllRkkkRRRR",
   "RRRRRRRRrkkkkksRRRRRRRkkkkkkkkkkkkRRRRRRssllllRkkksRRR",
   "RRRRRRRRRrkkkkkkkkksRkkkkkkkkkkkkkkkkkkkkklllllkkkkRRR",
   "RRRRRRRRRRRRrkkkkkkkkkkkkkkkkkkkkkkkkkkkkklllllkkkkRRR",
   "RRRRRRRRRRRRRRRrkkkkkkkkkkkkkkkkkkkkkkkkkkXXXXXkkkkRRR",
   "RRRRRRRRRRRRRRRRRRRRRkkkkkkkkkkkkkkkkkkkkkllllRkkkkRRR",
   "RRRRRRRRRRRRRRRRRRRRRRrkkkkkkkkkkRRRRRRkkkllllRkkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRkkkkkkkkRRRRRRRRrRllllRkkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkkRRRRRRRRRRRRRllllRkkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkkRRRRRRRRRRRRRllllRRkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkkRRRRRRRRRRRRRllllRRkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkkRRRRRRRRRRRRRllllRRkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkkRRRRRRRRRRRRRllllRskkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkkRRRRRRRRRRRRRllllRskkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkkRRRRRRRRRRRRRllllRkkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkkRRRRRRRRRRRRRRRRRkkkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkksRRRRRRRRRRRRRRRkkkkRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRkkkkkkkksRRRRRRRRRRkkkkkRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRkkkkkkkkkkkkRRRRRRkkkkkkkRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRkkkkkkkkkkkkkkkkkkkkkkkkkRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRkkkkkkkkkkkkkkkkkkkkkkRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRkkkkkkkkkkkkkkkkkRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRkkkkkkkkkkkkkkkkRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRkkkkkkkkkkkkkRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRkkkkkkkRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkRRRRRRRRRRRRRRRRRRRRRRRRRR"
  ],
  "art": {
   "image": "mine/under/mine_1",
   "painted": []
  },
  "blds": []
 },
 "mine_2": {
  "rows": [
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkkkkRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkkkkksRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkkkkkkkRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkkkkkkrRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkkkrrrRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRskkkrRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkkrRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkkrRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkkrRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRskkkkkrRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRssRRRsskkkkkrrRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRsskkksRskkkkkrrRRRRRRRRRRRRRRR",
   "RRRRRRRRwwwwwwwwwwwwkRRRRkkkkkksskkkkkrRRRRRRRRRRRRRRRRR",
   "RRRRsssswwwwwwwwwwwwkssskkskkkkkkkkkkkRRRRRRRRRRRRRRRRRR",
   "RRRskkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkRRRRRRRRRRRRRRRRRR",
   "RRskkkkk=============kkkkkkkkkkkkkkkkksssRRRRRRRRRRRRRRR",
   "RRkkkkkk=============kkkkkkkkkkkkkkkkkkkkkkssRRRRRRRRRRR",
   "RRrkkkkkwwwwwwwwwwww=kkkkkkkkkkkkkkkrrrrkkkkksRRRRRRRRRR",
   "RRRrkkkkwwwwwwwwwwwwkkkkkkkkkkkkkrrRRRRRRkkkkksRRRRRRRRR",
   "RRRRrrrrRRRRRRRRRRRRkkkrrrkkkkrrrRRRRRRRRRRkrkksRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRkkrrRRrrkkRRRRRRRRRRRRRRRRrkksRRRRRRR",
   "RRRRRRRRRRRRRRRRRskkrRRRRRRkkRRRRRRRRRRRRRRRRRkkkRRRRRRR",
   "RRRRRRRRRRRRRRRRkkkrRRRRRRRkkRRRRRRRRRRRRRRRRRrkksRRRRRR",
   "RRRRRRRRRRRRRRRkkkrRRRRRRRRkksRRRRRRRRRRRRRRRRRkkkRRRRRR",
   "RRRRRRRRRRRRRRkkkrRRRRRRRRRkksRXRRRRRRRRRRRRRRRkkkRRRRRR",
   "RRRRRRRRRRRRRRkkkRRRRRRRRRkkkksXXRRRRRRRRRRRRRRrkkRRRRRR",
   "RRRRRRRRRRRRRkkkrRRRRRRRsskkkkkkkRRRRRRRRRRRRRRRkksRRRRR",
   "RRRRRRRRRRRRkkkrRRRRRRRsXXkkkkkkksRRRRRRRRRRRRRskkksRRRR",
   "RRRRRRRRRRRkkkrRRRRRRsskkkkkkkkkkkRRRRRRRRRRRRRkkkkksRRR",
   "RRRRRRRRRRkkkrRRRRRRRrkkkkkkkkkkskkRRRRRRRRRRRRkkkkkkRRR",
   "RRRRRRRRRRkkkRRRRRRRRRrkkkkkkkkkkwkRRRRRRRRRRRRkkkkkkRRR",
   "RRRRRRRRRskskRRRRRRRRRRkkkkkkkkkwwRRRRRRRRRRRRRrkkkkrRRR",
   "RRRRRRRkkkkkkkRRRRRRRRRRRrkkkkrrwwRRRRRRRRRRRRRRrrrrRRRR",
   "RRRRRRrkkkkkkkRRRRRRRRRRRRrrrRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRkkkkkkkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRrkkkkkkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRrkkkkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRkkkkrRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"
  ],
  "art": {
   "image": "mine/under/mine_2",
   "painted": []
  },
  "blds": []
 },
 "mine_3": {
  "rows": [
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRllkkkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRkkkkkkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRkkkkkkksRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRkkkkkksRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRkkkksRRRRRRRRRRRlXXXXXXXXXlRRRRRRRRRRRRRRRRR",
   "RRRRRRRlkksRRRRRRRRRRRlXXXXXXXXXlRRRRRRRRRRRRRRRRR",
   "RRRRRRRlkksRRRRRRRRRRRRXXXXXXXXXRRRRRRRRRRRRRRRRRR",
   "RRRRRRRlkksRRRRRRRRRRRRXXXXXXXXXRRRRRRRRRRRRRRRRRR",
   "RRRRRRRkkksRRRRRRRRRRRkkkkkkkkkkkkkRRRRRRRRRRRRRRR",
   "RRRkkkkkkksRRRRRRRRRRlkkkXXXXXXkkkksRRRRRRRRRRRRRR",
   "RRkkkkkkksRRRRRRRRRRRkkkkXXXXXXkkksksRRRRRRRRRRRRR",
   "RRrkkkkkksRRRRRRRRRRRkkkkXXXXXXkkkkksRRRRRRRRRRRRR",
   "RRRrkkkkksRRRRRRRRRRkkkkkXXXXXXkkkkksRRRRRRRRRRRRR",
   "RRRRRrkkksRRRRRRRRRRkkkkkkkkkkkkkkkksRRRRRRRRRRRRR",
   "RRRRRrkksRRRRRRRRRRRkkkkkkkkkkkkkkkksRRRRRRRRRRRRR",
   "RRRRRrkksRRRRRRRRRRRlkkkkkkkkkkkkkkksRRRRRRRRRRRRR",
   "RRRRrkksRRRRRRRRRRRRlkkkkkkkkkkkkkkksRRRRRRRRRRRRR",
   "RRRRlkksRRRRRRRRRRRRRkkkkkkkkkkkkkkksRRRRRRRRRRRRR",
   "RRRRrkkkkkkkkkkkRRRRRrkkkkkkkkkkkkssRRRRRRRRRRRRRR",
   "RRRRrkkkkkkkkkkkksRRRRRkkkkkkkkkkkksRRRRRRRRRRRRRR",
   "RRRRRlkkkssRkkkksRRRRRRRlkkkkkkksssRRRRRRRRRRRRRRR",
   "RRRRRrkkksRRRrksRRRRRRRRRRkkkssRRRRRRRRRRRRRRRRRRR",
   "RRRRRRrkkksRRRRRRRRRRRRRRRkkksRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRrkkkksRRRRRRRRRRRRRRkkksRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRrkkkksRRRRRRRRRRRRRlkksRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRlkkkkkRRRRRRRRRRRXXXXXXRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRrkkkkkksRRRRRRRRXXXXXXsRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRlkkkkkRRRRRRRRXXXXXXsRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRkkkkkkRRRRrlXXkXXXkRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRlkkkkkkRRlkkkkkkkksRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRkkkkkkklkkkkkkkkkRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRskkkkkkkkkkkkkkklRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRskkkkkkkkkkkkksRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRkkkkkkkkkkkkksRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRlkkkkkkkkkssssRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRskkkkkksssRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRssssssRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"
  ],
  "art": {
   "image": "mine/under/mine_3",
   "painted": []
  },
  "blds": []
 }
}/*END*/;
})(window.RPG);
