// 生成物（design/art_ref/gen/env/_tools/under/field_mine/ の areas_mine.py・dng_mine.py → fit.py → put_rows.py）。手で直さない。
// 描いた下絵に合わせた鉱山都市ドヴァンと深き坑道の当たり（rows、字は field_mine/lib.py と同じ）・絵（art）・建物の敷地と戸口（blds）。
// mine_dovan.js・mine_deep.js が R.Mine.PAINTED[id] を読む。
(function (R) {
  'use strict';
  const I = (R.Mine = R.Mine || {});
  I.PAINTED = /*DATA*/{
 "dovan": {
  "rows": [
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXXXRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXXXXRRRRRRRRRRRRRRRRRRXR",
   "RRRRRXXXXXXXXXXXXkkkkksRRRRRsRRkkkkkkkkkkkkkkkkkkkRRRR",
   "RRRrkXXXXXXXXXXXXkkcXXXXckkkkkkkkkkkkkkkkkkkkkkkkkRRRR",
   "RRRrkXXXXXXXXXXXXkkcXXXXckkkkkkkkkkksskkkkkwwwwwrkrRRR",
   "RRRrkXXXXXXXXXXXXkkcXXXXckkkkkkkkkkkkkkkkkrwwwwwwwRRRR",
   "RRRrkXXXXXXXXXXXXrkcccccckkkkkkkkkkkkkkkkkkwwwwwwwRRRR",
   "RRXrkXXXXXXXXXXXXrkcccccckkkkkkkkkkkkkkkkkkkwwwwwwRRRR",
   "RRRrkXXXXXXXXXXXXrkkkkkkkkkkkkkkkkkkkkkkkkkkkwwwwkRRRR",
   "RRRkkXXXXXXcXXXXXkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkRRRR",
   "RRRkkkcccccccccccccccccccccccccccccccccccccccccckkRRRR",
   "RRRrkkcccccccccccccccccccccccccccccccccccccccccckrRRRR",
   "RRRRRrrrrrrcccRRRRRRRrRRRRRRRRkrRRRRRrrkkkkkkkkkrRRRRR",
   "RRRRRRRRRRRcccRRRRRRRRRRRRRRRRRRRRRRRRRRkkkRRRRRRRRRRR",
   "RRRRRRRRRRRcccRRRRRRRRRRRRRRRRRRRRRRRRRRkkkRRRRRRRRRRR",
   "RRRRRRRRRRRcccRRRRRRRRRRRRRRRRRRRRRRRRRRkkrRRRRRRRRRRR",
   "RRRRRRRsssRcccRsssRRRRRRRRXXXXXXXXXXXRRRkkkRRRRRllllll",
   "RRRRRsskkkkccckkkkrrrrRssRXXXXXXXXXXXkkkkkkkkkkRllllll",
   "RRRRkkXXXXXXXXkkkXXXXXXkkkXXXXXXXXXXXkkkkkkkkkkRllllll",
   "RRXRkkXXXXXXXXkkkXXXXXXkkkXXXXXXXXXXXrkkkkkkkkkRllllll",
   "RRRRkrXXXXXXXXrkkXXXXXXkkkXXXXXXXXXXXrkkkkkkkkkRllllll",
   "RRRRkkXXXXXXXXrkkXXXXXXkkkXXXXXXXXXXXrkkkkkkkkkRllllll",
   "RRRRkrXXXXXXXXrkkXXXcXXkkkXXXXcXXXXXXkkkkkkkkkkRllllll",
   "RRRRkkXXXXcXXXkkccccccccccccccccccccccckkkkkkkkkllllll",
   "RRRRkkccccccccccccccccccccccccccccccccckkkkkkkkrllllll",
   "RRRRkkccccccccccccccccccccccccccccccccckkkkkkkkrllllll",
   "RRRRkkkkkkkkkkkkccccccccccccccccccccccck====kkkRllllll",
   "RRRRRkkkkkkkkkkkccccccccccccccccccccccckkkkXXXkRllllll",
   "RRRRRkkkksskkkkkccccccccccccccccccccccckkkkXXXrRRlllll",
   "RRRRRkkkkkkkkkkkkkkkkkkkkcccckkkkkkkkkkkkRRXXXRRRlllll",
   "RRRRRRRRRkkkkkkkkkkRRRRRsccccRRRRRRRRRRkrRRXXXRRRlllll",
   "RRRRRRRRRRRRRRRRRRRRRRRRsccccRRRRRRRRRRRRRRXXXRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRsccccRRRRRRRRRRRRRRXXXRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRsccccRRRRRRRRRRRRRRXXXRRRRRRRR",
   "RRRRRRRRRRRRRRRssssssssssccccsRRRRRRRRRRRsRXXXssRRRRRR",
   "RRRRRkXXXXXXXXXkXXXXXXXkkcccckXXXXXXXXXXkkkkkkkkkRRRRR",
   "RRRRRkXXXXXXXXXkXXXXXXXkkcccckXXXXXXXXXXrkkkkXXXXRRRRR",
   "RRRRRkXXXXXXXXXkXXXXXXXkkccccrXXXXXXXXXXrkkkkXXXXRRRRR",
   "RRRRRkXXXXXXXXXkXXXXXXXrkcccckXXXXXXXXXXrkkkrXXXXRRRRR",
   "RRRRRkXXXXXXXXXkXXXXXXXrkcccckXXXXXXXXXXrkkkkXXXXRRXRR",
   "RRRRRkXXXXcXXXXkXXXcXXXkkcccckXXXXcXXXXXkkkkkXcXXRRRRR",
   "RRRRRkcccccccccccccccccccccccccccccccccccccccccckRRRRR",
   "RRRRRkcccccccccccccccccccccccccccccccccccccccccckRRRRR",
   "RRRRrkkkkkrkkkkkkkkkkkkkkcccckkkkkkkkkkkkkkkkkrkrRRRRR",
   "RRRRRRRRRRRRRRRRRRrkkkkkkcccckkkkkkkkkkkkrkkkrRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRsccccRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRsccccRRRRRRRRRRRRRRRRRRRRRRRRR"
  ],
  "art": {
   "image": "mine/under/dovan",
   "painted": [],
   "emit": "mine/under/dovan_emit"
  },
  "blds": [
   {
    "id": "dovan_hall",
    "x": 5,
    "y": 3,
    "w": 12,
    "h": 8,
    "door": [
     11,
     10
    ]
   },
   {
    "id": "dovan_guild",
    "x": 26,
    "y": 17,
    "w": 11,
    "h": 7,
    "door": [
     30,
     23
    ]
   },
   {
    "id": "dovan_tavern",
    "x": 6,
    "y": 19,
    "w": 8,
    "h": 6,
    "door": [
     10,
     24
    ]
   },
   {
    "id": "dovan_house",
    "x": 17,
    "y": 19,
    "w": 6,
    "h": 5,
    "door": [
     20,
     23
    ]
   },
   {
    "id": "dovan_items",
    "x": 6,
    "y": 36,
    "w": 9,
    "h": 6,
    "door": [
     10,
     41
    ]
   },
   {
    "id": "dovan_inn",
    "x": 16,
    "y": 36,
    "w": 7,
    "h": 6,
    "door": [
     19,
     41
    ]
   },
   {
    "id": "dovan_forge",
    "x": 30,
    "y": 36,
    "w": 10,
    "h": 6,
    "door": [
     34,
     41
    ]
   },
   {
    "id": "dovan_house2",
    "x": 45,
    "y": 37,
    "w": 4,
    "h": 5,
    "door": [
     46,
     41
    ]
   }
  ]
 },
 "mine_1": {
  "rows": [
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRsRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkksRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrrkkkkkXRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRsssRRRRRRRRRRRRRRRrrkkkkkrRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRsskkkksRRRRRRRRRRRRRrkkkkkkRRR",
   "RRRRRssssRRRRRRRRRRRsssskkkkkkkksRRRRRRRRRRRRkkkkkkRRR",
   "RRRRRssssssRRRRRRRRRRXskkkkkkkkksRRRRRRRRRRRRRkkkkRRRR",
   "RRRXXkkksXsRRRRRRRRRskkkkkkkkkkkkXRRRRRRRRRRRRskkkRRRR",
   "RRXXkkkkkksRRRRRRRRRXkkkkkkkkkkkkXXRRRRRRRRllRXkkkRRRR",
   "RRXkkkkkkksRRRRRRRRRRkkskkkkkkkkkkXRRRRRRRRllRXkkkRRRR",
   "RRXkkkkkkkRRRRRRRRRRRRkkkkkkkkkkkRRRRRRRRRRllRskkkRRRR",
   "RRRRrkkkkRRRRRRRRRRRRRRXXkkkRRRRRRRRRRRRRRRllRRkkkRRRR",
   "RRRRRkkksRRRRRRRRRRRRRRRRskkRRRRRRRRRRRRRRlllRRkkkRRRR",
   "RRRRRrkksssRRRRRRRRRRRRRRRkkRRRRRRRRRRRRRRllllRkkkRRRR",
   "RRRRRRkkXXsRRRRRRRRRRRRRRRkkRRRRRRRRRRRRRRllllRkkksRRR",
   "RRRRRRkkkksRkkRRRRRRRRRXXRkkRRRRRRRRRRRRRRllllRkkkXRRR",
   "RRRRRRRkkkkkkksRRRRRRRRkkkkkkkkRRRRRRRRRRRllllRkkkXRRR",
   "RRRRRRRRkkkkkksRRRRRRRkkkkkkkkkkkkXsRXRRRRllllRkkksRRR",
   "RRRRRRRRRrkkkkkkkkkRRkkkkkkkkkkkkkkkkkkkkrllllRkkkkRRR",
   "RRRRRRRRRRRRkkkkkkkkkkkkkkkkkkkkkkkkkkkkkklllllkkkkXRR",
   "RRRRRRRRRRRRRXXkkkkkkkkkkkkkkkkkkkkkkkkkkklllllkkkkXRR",
   "RRRRRRRRRRRRRRRRsssXXkkkkkkkkkkkkkkkkkkkkklllllkkkkRRR",
   "RRRRRRRRRRRRRRRRRRRssskkkkkkkkkkkXXsssskkkllllRkkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRskkkkkkkkssRRRRRRkRllllRkkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkkssRRRRRRRRRRRllllRkkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkksRRRRRRRRRRRRllllRRkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkksRRRRRRRRRRRRllllRRkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkkXRRRRRRRRRRRRllllRRkkXRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRskkkkXRRRRRRRRRRRRllllRRkkXRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRXkkkksRRRRRRRRRRRRllllRRkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRXkkkksRRRRRRRRRRRRllllRrkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkkRRRRRRRRRRRRRsssRrkkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkkRRRRRRRRRRRRRssRrkkkRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRrkkkkkkkRRRRRRRRRXXkrkkksRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRkkkkkkkkkkkkRXXRRRrkkkkkksRRRRRR",
   "RRRRRRRRRRRRRRRRRRRXkrkkkkkkkkkkkkkkkkkkkkkkksRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRrkkkkkkkkkkkkkkkkkkkkksRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRkkkkkkkkkkkkkkkkkRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRkkkkkkkkkkkkkkkrRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRkkkkkkkkkkkkkRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRXXkkkkkkksXXRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRkkkRRRRRRRRRRRRRRRRRRRRRRRRRR"
  ],
  "art": {
   "image": "mine/under/mine_1",
   "painted": [],
   "emit": "mine/under/mine_1_emit"
  },
  "blds": []
 },
 "mine_2": {
  "rows": [
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXkRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrwkkkwXRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRwkkkkkwRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRwkkkkkkkkRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrkkkkkkkkRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRwkkkkkkkRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXkkkkRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRwkkkksRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRwkkkksRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRwkkkksRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrwkkkksRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRXXwkkkkkksRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRwkwRRRwkkkkkksRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRkRRRRwkkkkkrskkkkkkXXRRRRRRRRRRRRRRR",
   "RRRRRRRRwwwwwwwwwwwwkRXXwkskkkkkwkkkkksRRRRRRRRRRRRRRRRR",
   "RRRRrrrwwwwwwwwwwwwwkkkwkkkkkkkkkkkkkkRRRRRRRRRRRRRRRRRR",
   "RRXrkkkkkwwwwwwwwwwwkkkkkkkkkkkkkkkkkkRRRRRRRRRRRRRRRRRR",
   "RRwkkkkk=============kkkkkkkkkkkkkkkkkkkkkkXXRRRRRRRRRRR",
   "RRrkkkkk=============kkkkkkkkkkkkkkkkkkkkkkkkRRRRRRRRRRR",
   "RRRkkkkkwwwwwwwwwwwwkkkkkkkkkkkkkkkXXRssskkkkkXRRRRRRRRR",
   "RRRRkkkkwwwwwwwwwwwwkkkkkkkkkkkkkssRRRRRRRskkkwRRRRRRRRR",
   "RRRRRRsRRRRRRRRRRRRwkkkXXkkkksXXRRRRRRRRRRRRskkkRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRrkkXXXXXXkksRRRRRRRRRRRRRRRRkkkRRRRRRR",
   "RRRRRRRRRRRRRRRRrkkkXRRRRRRkkRRRRRRRRRRRRRRRRRkkksRRRRRR",
   "RRRRRRRRRRRRRRRrkkksRRRRRRRkkRRRRRRRRRRRRRRRRRRkkkRRRRRR",
   "RRRRRRRRRRRRRRrwkksRRRRRRRRkkRRRRRRRRRRRRRRRRRXkkkRRRRRR",
   "RRRRRRRRRRRRRRrkksRRRRRRRRwkkkRRRRRRRRRRRRRRRRXkkkRRRRRR",
   "RRRRRRRRRRRRRwkkkRRRRRRRRRkkkkRXXRRRRRRRRRRRRRRRkkRRRRRR",
   "RRRRRRRRRRRRrkkksRRRRRRRrkkkkkkkXRRRRRRRRRRRRRRRkkkRRRRR",
   "RRRRRRRRRRRwkkkXRRRRRRRkXXkkkkkkkkRRRRRRRRRRRRRrkkkkrRRR",
   "RRRRRRRRRRrkkksRRRRRRwXkXXkkXXkkskkRRRRRRRRRRRRrkkkkkRRR",
   "RRRRRRRRRRrkkXRRRRRRRXXkkkkkXXkkkkkRRRRRRRRRRRRwkkkkkXRR",
   "RRRRRRRRRRwskXRRRRRRRRRkkkkkkkkkswRRRRRRRRRRRRRrkkkkkXRR",
   "RRRRRRRrrrkkkkRRRRRRRRRRRkkkkkkkwwRRRRRRRRRRRRRXkkkksRRR",
   "RRRRRRrwkkkkkkRRRRRRRRRRRRkkksXXRRRRRRRRRRRRRRRRRRsRRRRR",
   "RRRRRXwkkkkkkkRRRRRRRRRRRRRssRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRXwkkkkkkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRkkkkkksRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRkkkkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"
  ],
  "art": {
   "image": "mine/under/mine_2",
   "painted": [],
   "emit": "mine/under/mine_2_emit"
  },
  "blds": []
 },
 "mine_3": {
  "rows": [
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRssRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRXkkkkkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRXkkkkkkkRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRkkkkkkkXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRkkkkkkXRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRrkkkRRRRRRRRRRRRlXXXXXXXXXlRRRRRRRRRRRRRRRRR",
   "RRRRRRRrkkRRRRRRRRRRRRlXXXXXXXXXlRRRRRRRRRRRRRRRRR",
   "RRRRRRRrkkXRRRRRRRRRRRRXXXXXXXXXRRRRRRRRRRRRRRRRRR",
   "RRRRRRRlkkXRRRRRRRRRRRRXXXXXXXXXRRRRRRRRRRRRRRRRRR",
   "RRRRRXXkkkRRRRRRRRRRRRkkkkkkkkkkkkkRRRRRRRRRRRRRRR",
   "RRRkkkkkkkRRRRRRRRRRRkkkkXXXXXXkkkksRRRRRRRRRRRRRR",
   "RRRkkkkkksRRRRRRRRRRRkkkkXXXXXXkkkskRRRRRRRRRRRRRR",
   "RRkkkkkkkRRRRRRRRRRRRkkkkXXXXXXkkkkkRRRRRRRRRRRRRR",
   "RRRkkkkkkRRRRRRRRRRXkkkkkXXXXXXkkkkksRRRRRRRRRRRRR",
   "RRRRRkkkkRRRRRRRRRRXkkkkkrkkklrkkkkksRRRRRRRRRRRRR",
   "RRRRRkkkXRRRRRRRRRRRkkkkkkkkkkkkkkkkXRRRRRRRRRRRRR",
   "RRRRRkkkXRRRRRRRRRRRkkkkkkkkkkkkkkkkXRRRRRRRRRRRRR",
   "RRRXlkksRRRRRRRRRRRRkkkkkkkkkkkkkkkksRRRRRRRRRRRRR",
   "RRRXkkkRRRRRRRRRRRRRXkkkkkkkkkkkkkkksRRRRRRRRRRRRR",
   "RRRXkkkkrrrrrkkrRRRRsskkkkkkkkkkkksXsRRRRRRRRRRRRR",
   "RRRXkkkkkkkkkkkkrRRRRRskkkkkkkkkkkkXsRRRRRRRRRRRRR",
   "RRRRRkkkkssRkkkksRRRRRRRkkkkkkkkssRRRRRRRRRRRRRRRR",
   "RRRRRkkkkRRRRkksRRRRRRRRRskkksRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRkkkkRRRRRRRRRRRRRRRRkkkRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRrkkkkXRRRRRRRRRRRRRRkkkRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRkkkkkRRRRRRRRRRRRRRrkkRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRkkkkkrXXRRRRRRRRRXXXXXXRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRkkkkkklRRRRRRRRRXXXXXXRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRkkkkkkRRRRRRRRXXXXXXRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRkkkkkrRRRRlrXXkXXXrXRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRkkkkkkrRRrkkkkkkkkXRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRkkkkkkkkkkkkkkkklRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRXXkkkkkkkkkkkkkkkrRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRskkkkkkkkkkkkkXRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRXkkkkkkkkkkkkkXRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRXkkkkkkkkkkssXXRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRXXkkkkkkssRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRssssssRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"
  ],
  "art": {
   "image": "mine/under/mine_3",
   "painted": [],
   "emit": "mine/under/mine_3_emit"
  },
  "blds": []
 },
 "volk": {
  "rows": [
   "RRRRRRXRRRRRRRRRRRRRRRRXXXXRRRRR",
   "RRRRRRXRRRRRRRRRRRRRRRRXXXXRRRRR",
   "RRRRRRXRRRRRRRRRRRRRRRRXXXXRRRRR",
   "RRRRRRc,,,,,,,,,,,,,,,RXXXXRRRRR",
   "RR,XXXXXXXX,,,,,,,,,,,wwwwwwRRRR",
   "RR,XXXXXXXX,,,,,,,,,,,wwwwwwRRRR",
   "RR,XXXXXXXX,,,,,,,,,,,wwwwwwTRRR",
   "RR,XXXXXXXX,XXXXXXXXX,wwwwwwTRRR",
   "RR,XXXXXXXX,XXXXXXXXX,wwwwwwTRRR",
   "RR,XXXXXXXX,XXXXXXXXXwwwr,,,TTRR",
   "RR,XXXXXXXX,XXXXXXXXXwwwr,,,,,RR",
   "RR,XXXcXXXX,XXXXXXXXXwwwr,,XX,RR",
   "RR,,,,,,,,,,XXXXXXXXXwwwr,,,,,RR",
   "RR,r,,,,,,r,XXXXXcXXXwww,,,,,,RR",
   "RR,,,,,,,,,,,,cccccc====,,,,,,RR",
   "RR,,,,,,,,,,,,ccccccXwww,,,,,,RR",
   "RR,,,,,,,,,,,,cXccccXwwXXXXXX,RR",
   "RR,XXXXXX,,,,,cccccccwwXXXXXX,RR",
   "RR,XXXXXX,,,,,cccccccwwXXXXXX,RR",
   "RR,XXXXXX,,,,,,,,,,,wwwXXXXXX,RR",
   "RR,XXXXXX,,,,,,,,,wwww,XXXcXX,RR",
   "RR,XXcXXX,,,,,,,,,wwww,,,,,,,,RR",
   "RR,,,,,,,,,,,,,,wwwww,,,,,,TTTRR",
   "RR,,,TTTT,,,,,,,wwwww,,,,,,TTTRR",
   "RR,,,TTTT,,,,,wwww,,,,,,,,,TTTRR",
   "RRRRRRRRR==RRwwwRRRRRRRRRRRRRRRR",
   "RRRRRRRRR==RRwwwRRRRRRRRRRRRRRRR",
   "RRRRRRRRR==RRwwwRRRRRRRRRRRRRRRR"
  ],
  "art": {
   "image": "mine/under/volk",
   "painted": [],
   "overlay": "mine/under/volk_over"
  },
  "blds": [
   {
    "id": "volk_inn",
    "x": 3,
    "y": 4,
    "w": 8,
    "h": 8,
    "door": [
     6,
     11
    ]
   },
   {
    "id": "volk_forge",
    "x": 12,
    "y": 7,
    "w": 9,
    "h": 7,
    "door": [
     17,
     13
    ]
   },
   {
    "id": "volk_house",
    "x": 3,
    "y": 17,
    "w": 6,
    "h": 5,
    "door": [
     5,
     21
    ]
   },
   {
    "id": "volk_elder",
    "x": 23,
    "y": 16,
    "w": 6,
    "h": 5,
    "door": [
     26,
     20
    ]
   }
  ]
 },
 "vein_1": {
  "rows": [
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRksRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRsssRRR",
   "RRRRkkkkkkXRRRRRRRRRRRRRRRRRllllRRRRRkkkkXRR",
   "RRXkkkkkkkXRRRRRRRRRRRRRRRRRllllRRRRkkkkkksR",
   "RRXkkkkkkksRRRRRRRRRRRRRRRRRllllRRRRkkkkkkRR",
   "RRRRrkkkkXRRRRRRRRRRRRRRRRRRllllRRRrkkkkrRRR",
   "RRRRRrkkRRRRRRRRRRRRRRRRRRRRllllRRRkkkRXXRRR",
   "RRRRRrkkRRRRRRRRRRRRRRRRRRRRllllRRrkkRRRRRRR",
   "RRRRRrkkRRRRRRRRRRRRRRRRRRRRllllRRrkkRRRRRRR",
   "RRRRXrkksRRRRRRRRRRRRRRRRRRRllllRRrkkRRRRRRR",
   "RRRRXrkksRRRRRRRRRRRRRRRRRRRllllRRkskXRRRRRR",
   "RRRRRRkkkXXRRRRssRRRRRRRRRRRllllRRkkkXRRRRRR",
   "RRRRRRrkkkkssskkkksXXRRRRXXRllllRRkksRRRRRRR",
   "RRRRRRRrkkkkkkkkkkkkkXXsskksllllRRkksRRRRRRR",
   "RRRRRRRRRrkkkkkkkkkkkkkkkkkkllllRRkkkkRRRRRR",
   "RRRRRRRRRRrkkkkkkkkkkkkkkkkkllllRkkkkkRRRRRR",
   "RRRRRRRRRRrkkkkkkkkkkkkkkkkkXXXXXkkkkkRRRRRR",
   "RRRRRRRRRRrkkkkkkkkkkkkkkkkkllllRrkkkkRRRRRR",
   "RRRRRRRRRRRrkkkkkkkkkkrXkkkkllllRrkkkRRRRRRR",
   "RRRRRRRRRRRkkkkkkkkkkkXXrrRRllllRRkkkRRRRRRR",
   "RRRRRRRRRRrkkkkkkkkXXRRRRRRRllllRXkkkRRRRRRR",
   "RRRRRRRRRkkkXRRRRRRRRRRRRRRRllllRXkkkRRRRRRR",
   "RRRRRRRRrkksRRRRRRRRRRRRRRRRllllRRkkkRRRRRRR",
   "RRRRRRRrkkkRRRRRRRRRRRRRRRRRllllRXrkkRRRRRRR",
   "RRRRRRRkkkRRRRRRRRRRRRRRRRRRllllRXrkkRRRRRRR",
   "RRRRRRRkkRRRRRRRRRRRRRRRRRRRllllRRRkkkRRRRRR",
   "RRRRRRXkkRRRRRRRRRRRRRRRRRRllllllRRrkksRRRRR",
   "RRRRRRXkksRRRRRRRRRRRRRRRRRllllllRRRkkkXXRRR",
   "RRRRRRRkkkksRRRRRRRRRRRRRRRlllllRRRRkkkkkRRR",
   "RRRRRRRkkkkksRRRRRRRRRRRRRRRllllRRRrkkkkkkRR",
   "RRRRRRRkkkkkkXRRRRRRRRRRRRRRllllRRRkkkkkkkRR",
   "RRRRRRrkkkkkkXRRRRRRRRRRRRRlllllRRRrkkkkkkRR",
   "RRRRRRRkkkkkRRRRRRRRRRRRRRRRRRRRRRRXkkkkkRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"
  ],
  "art": {
   "image": "mine/under/vein_1",
   "painted": [],
   "emit": "mine/under/vein_1_emit"
  },
  "blds": []
 },
 "vein_2": {
  "rows": [
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrssRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrkkkkXRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrkkkkkkRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrkkkkkkRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkkkkrRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRrkkkRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRkkkkRRRRRR",
   "RRRXkkXRRRRRRRRRRRRRRRRRRRRXXRRRRkkkkRRRRRRR",
   "RRRkkkkRRRRRRRRXXRrkkkkkRRRkkkkkkkkkXRRRRRRR",
   "RRrkkkkRRRrkkkkkkkkkkkkkkkkkkkkkkkkRRRRRRRRR",
   "RRrkkkkkRrkkkkkkkkkk=kkkkkkkkkkkkRRRRRRRRRRR",
   "RRkkkkkkskkkkwwwwwww=wwwwwwwkkkksRRRRRRRRRRR",
   "RRrkkkkkkkkkwwwwwwww=wwwwwwwwkkkXRRRRRRRRRRR",
   "RRkkkkkkkkkkwwwwwwww=wwwwwwwwkkkXRRRRRRRRRRR",
   "RRXkkkkkkkkwwwwwwwww=wwwwwwwwkkkkRRRRRRRRRRR",
   "RRXkkkkkkkkwk=======kk=======kkkkRRRRRRRRRRR",
   "RRRRXXXXkkkwwwwwwwwkXXwwwwwwwkkkRRRRRRRRRRRR",
   "RRRRRRRRRkkswwwwwwwwwwwwwwwwwkkkRRRRRRRRRRRR",
   "RRRRRRRRRRrkswwwwwwwwwwwwwwwkkkkssRRRRRRRRRR",
   "RRRRRRRRRRrkkwwwwwwwwwwwwwwwkkkkXXRRRRRRRRRR",
   "RRRRRRRRRRRkkswwwwwwwwwwwwwwkkkkkkRRRRRRRRRR",
   "RRRRRRRRRRRkkkkkkkkkkkkkkkkkkkkkkkkRRRRRRRRR",
   "RRRRRRRRRRRkkkkrkrkkkkkkkkkkkrRRkkkkRRRRRRRR",
   "RRRRRRRRRRrkkkRRRRRkkRRRRRRRRRRRRkkkksRRRRRR",
   "RRRRRRRRRrkkkXRRRRRkkRRRRRRRRRRRRRrkkkkksRRR",
   "RRRRRRRRkkkksRRRRRXkksRRRRRRRRRRRRRRkkkkkRRR",
   "RRRRRRRkkkkXsRRRRRXkkksRRRRRRRRRRRRRkkkkksRR",
   "RRRRRkkkkkRRRRRRRRRkkkkkkRRRRRRRRRRRkkkkkXRR",
   "RRskskkkksRRRRRRRXkkkkkkkksRRRRRRRRRrkkkrXRR",
   "RRXwkkkkksRRRRRRRXkkkkkkkwXRRRRRRRRRRrrRRRRR",
   "RRXkkkkkkRRRRRRRRRrkkkkkrXRRRRRRRRRRRRRRRRRR",
   "RRRrkkrrRRRRRRRRRRRrrrrRRRRRRRRRRRRRRRRRRRRR",
   "RRRRrRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"
  ],
  "art": {
   "image": "mine/under/vein_2",
   "painted": [],
   "emit": "mine/under/vein_2_emit"
  },
  "blds": []
 },
 "vein_3": {
  "rows": [
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRXXXXXRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRXXXXXXXXXXRRRRRRRRXXRR",
   "RRRRRRRRRRRXRXXXXXXXXXXXRRRRRRRkkkRR",
   "RRRRRRRRRRRXXXXXXXXXXXXXXXRRRkkkkkRR",
   "RRRRRRRRRRRRRRskkkkkksRRRRRkkkkkkrRR",
   "RRRRRRRRRRRRkkkkkkkkkksRRkkkkkrrrRRR",
   "RRRRRRRRRRRrkkkkkkkkkkkkkrkkRRRRRRRR",
   "RRRRRRRRRRkXkkkkkkkkkkkkkXkkRRRRRRRR",
   "RRRRRRRRRkkkkkkkkkkkkkkkkkkksRRRRRRR",
   "RRRRRRRRRkkkkkkkkkkkkkkkkkkkkXRRRRRR",
   "RRRRRRRRXkkkkkkkkkkkkkkkkkkkkXRRRRRR",
   "RRRRRRRRXkkkkkkkkkkkkkkkkkkkRRRRRRRR",
   "RRRRRRRRRrkkkkkkkkkkkkkkkkkkRRRRRRRR",
   "RRRRRRRRRXkkrkkkkkkkkkkkrkkkRRRRRRRR",
   "RRRRRRRRRXrkXkkkkkkkkkkkXkkrRRRRRRRR",
   "RRRRRRRRRRRrkkkkkkkkkkkkkkrXRRRRRRRR",
   "RRRRRRRRRRRRRrrkkkkkkkkkkrRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRkkkrrRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRXkkRXXRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRXkkRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRXkkRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRXkksRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRskkksRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRkkkkkkRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRXkkkkkkRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRXrkkkkkXRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRkrrRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"
  ],
  "art": {
   "image": "mine/under/vein_3",
   "painted": [],
   "emit": "mine/under/vein_3_emit"
  },
  "blds": []
 }
}/*END*/;
})(window.RPG);
