// 生成物（design/art_ref/gen/env/_tools/under/oblivion/ の dng_oblivion.py → gen.sh → fit.py → process.py → put_rows.py）。手で直さない。
// 忘却の底（クリア後のダンジョン oblivion_1〜5）の描いた下絵に合わせた当たり（rows、字は dng_oblivion.py と同じ）と絵（art）。
// maps/oblivion.js が R.Oblivion.PAINTED[id] を読む。
(function (R) {
  'use strict';
  const O = (R.Oblivion = R.Oblivion || {});
  O.PAINTED = /*DATA*/{
 "oblivion_1": {
  "rows": [
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~ss~~~~~~~~~~~~~~~~~~~~~",
   "~~~~ssccss~sssssssssssssss~~~~~~~~~~~~~~",
   "~~ssssssssXsssssssssssssssssssssX~sX~~~~",
   "~~ssssssssssssssssssssssssssssssssssX~~~",
   "~ssssssssssss~~XX~~~~~~~~~sssssssssss~~~",
   "~sssssssssss~~~~~~~~~~~~~~~~~~~~ssssX~~~",
   "~~ssssssssss~~~~~~~~~~~~~~~~~~~~~sX~~~~~",
   "~~~ssssssss~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~sssss~~~~~~~~~~~~~sss~~~~~~~~~~~~~~~",
   "~~~~ssss~~~~~~~~~~ssssXsss~~~~~~~~~~~~~~",
   "~~~~ssss~~~~~~~~~ssXsssssXs~~~~~~~~~~~~~",
   "~~~Xssss~~~~~~~~~sssssssssss~~~~~~~~~~~~",
   "~~~~ssss~~~~~~~~~sXsssssssXs~~~~~~~~~~~~",
   "~~~~sssss~~~~~~~~sssssssssss~~~~~~~~~~~~",
   "~~~~ssssX~~~~~~~~XsXsssssXsX~~~~~~~~~~~~",
   "~~~~~sssX~~~~~~~~~~sssssss~~~~~~~~~~~~~~",
   "~~~~~ssss~~~~~~~~~~~ssss~~~~~~~~~~~~~~~~",
   "~~~~~sssss~~~~~~~~~~sss~~~~~~~~~~~~~~~~~",
   "~~~~~~ssss~~~~~~~~~~ss~~~~~~~~~~~~~~~~~~",
   "~~~sssssssss~~~~~~~~ss~~~~~~~~~~~~~~~~~~",
   "~~ssssssssssX~~~~~~~ss~~~~~~~~~~~~~~~~~~",
   "~~ssssssssssss~~~~~~ss~~~~~~~~ssssssX~~~",
   "~~sssss~sssssssssss~ss~~~sssssXsssssss~~",
   "~~~sss~~~~ssssssssssssssssssssssssssss~~",
   "~~~~~~~~~~~sssssssssssssssssssssssssss~~",
   "~~~~~~~~~~~~~sssssssssssssssssssssssss~~",
   "~~~~~~~~~~~~~~~~sssssssssss~~~ssssccsX~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~sssXXX~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
  ],
  "art": {
   "image": "oblivion/under/oblivion_1",
   "painted": []
  }
 },
 "oblivion_2": {
  "rows": [
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~,cc,,,~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~TT,,,,,,,,T~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~TTTT,,,,,,TTTT~~~~~~~~~~~~~~~____~~~~~~~~",
   "~~~TTTT,,,,,,TTTT~~~~~~~~~~~~~~______F~~~~~~",
   "~~~TTTT,,,,,,,TTT========~~~~~_______F~~~~~~",
   "~~~TTT,,,,,,,,,T,=========~~~_______FFF~~~~~",
   "~~~,,,,,,,,,,,,,,,========~~_______FFFF~~~~~",
   "~~X,,,,,,,,,,,,,,,~~~~~~~~~________FFFFF~~~~",
   "~~X,TTT,,,,,,,,,,,~~~~~~~~__F_______FFF_~~~~",
   "~~~TTTT,,,,,,TTTT,~~~~~~~~_FFF__________~~~~",
   "~~~~~TT,,,,,TTTTT~~~~~~~~~_FFF___________~~~",
   "~~~~~~~,==,,TTTT~~~~~~~~~__FFF___________~~~",
   "~~~~~~~====~~~~~~~~~~~~~~___F____________~~~",
   "~~~~~~~====~~~~~~~~~~~~~~_________________~~",
   "~~~~~~~====~~~~~~~~~~~~~~_________________~~",
   "~~~~~~~====~~~~~~~~~~~~~~__________________~",
   "~~~~~~~====~~~~~~~~~~~~~~__________________~",
   "~~~~~~~====~~~~~~~~~~~~~~____________F____~~",
   "~~~~~~~~==::~~~~~~~~~~~~~~___________FFF__~~",
   "~~~~~~X::::::r~~~~~~~~~~~~__________FFFFF_~~",
   "~~~~~::::::::rr:::~~~~====___________FFFF~~~",
   "~~~~:r:::::::r::::========__FFF______FFF~~~~",
   "~~~r:rr:::::::::::=======~~_FFF________~~~~~",
   "~~~::r::::::::::::====~~~~~_FFF________~~~~~",
   "~~~:::::::::::::::::~~~~~~~~__________~~~~~~",
   "~~~X::::::::::::r::~~~~~~~~~~~___cc_~~~~~~~~",
   "~~~~X::::::::::rrr:~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~X::::::::::r~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~X:::::::~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
  ],
  "art": {
   "image": "oblivion/under/oblivion_2",
   "painted": [],
   "overlay": "oblivion/under/oblivion_2_over"
  }
 },
 "oblivion_3": {
  "rows": [
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX~~",
   "~~XXXXXccccccccccXXccccccccccXccXX~~",
   "~~XXXXXccccccccckXXkccccccccccccXX~~",
   "~~XXXXXccccccccckkkkccccccccccccXX~~",
   "~~XXXXXccccccccckkkkccccccccccXXXX~~",
   "~~XXXXXccccccccckkkkccccccccccXXXX~~",
   "~~XXXXXccccccccckkkkcccccccccXXXXX~~",
   "~~XXXXXccccccccckkkkcccccccccXXXXX~~",
   "~~XXXXXXXXXXXXXXccccXXXXXXXXXXXXXX~~",
   "~~XXXXXXXXXXXXXXccccXXXXXXXXXXXXXX~~",
   "~~XXXXXXXXXXXXccccccccXXXXXXXXXXXX~~",
   "~~XXXXXXXXXXXXccccccccXXXXXXXXXXXX~~",
   "~~XXXXXXXXXXXXXXccccXXXXXXXXXXXXXX~~",
   "~~XXXXXXXXccccccccccccccccXXXXXXXX~~",
   "~~XXXXXXXcccccccccccccccccXXXXXXXX~~",
   "~~XXXXXXXccXccccccccccccXcXXXXXXXX~~",
   "~~XXXXXXXccXccccccccccccXcXXXXXXXX~~",
   "~~XccccXXcccccccccccccccccXXXccccX~~",
   "~~XccccXXcccccXXccccXXccccXXXccccX~~",
   "~~XcccccccccccXXccccXXcccccccccccX~~",
   "~~XccccccccccccccccccccccccccccccX~~",
   "~~XcccccXccccccccccccccccccXcccccX~~",
   "~~XccccXXcccccXXccccXXccccXXXccccX~~",
   "~~XccccXXccXccXXccccXXccXcXXXccccX~~",
   "~~XXXXXXXccXccccccccccccXcXXXXXXXX~~",
   "~~XXXXXXXcccccccccccccccccXXXXXXXX~~",
   "~~XXXXXXXcccccccccccccccccXXXXXXXX~~",
   "~~XXXXXXXXXXXXXXccccXXXXXXXXXXXXXX~~",
   "~~XXXXXXXXXXXXXXccccXXXXXXXXXXXXXX~~",
   "~~XXXXXXXXXXXXXXccccXXXXXXXXXXXXXX~~",
   "~~XXXXXXXXXXXXXXXccXXXXXXXXXXXXXXX~~",
   "~~XXXXXXXXXXXXXXXccXXXXXXXXXXXXXXX~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
  ],
  "art": {
   "image": "oblivion/under/oblivion_3",
   "painted": []
  }
 },
 "oblivion_4": {
  "rows": [
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX~",
   "~XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX~",
   "~XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXccX~",
   "~XXcccccccccccccccccccccccccccccccccccccccccccX~",
   "~XXccccccccccccccccccccccccccccccccccccccccXccX~",
   "~XXccccccccccXXXXXccccccccXXXXXXccccccccXXXXccX~",
   "~XXccccccccccXXXXXccccccccXXXXXXccccccccXXXXccX~",
   "~XXccccccccccXXXXXccccccccXXXXXXccccccccXXXXccX~",
   "~XXccccXXccccXXXXXcccXXcccXXXXXXcccXXcccXXXXccX~",
   "~XcccccXXccccXXXXXcccXXcccXXXXXXcccXXcccXXXXccX~",
   "~XcccccccccccXXXXXccccccccXXXXXXccccccccXXXXccX~",
   "~XXccccccccccXXXXXccccccccXXXXXXccccccccXXXXccX~",
   "~XXccccccccccXXXXXccccccccXXXXXXccccccccXXXXccX~",
   "~XXccccccccccXXXXXccccccccXXXXXXccccccccXXXXccX~",
   "~XXcccccccccccccccccccccccccccccccccccccccccccX~",
   "~XXccccccccccccccccccccccccccccccccccccccccXccX~",
   "~XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXccX~",
   "~XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
  ],
  "art": {
   "image": "oblivion/under/oblivion_4",
   "painted": []
  }
 },
 "oblivion_5": {
  "rows": [
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~cccccccc~~~~~~~~~~~~~~",
   "~~~~~~~~~~~cccccccccccccc~~~~~~~~~~~",
   "~~~~~~~~~cccccccccccccccccc~~~~~~~~~",
   "~~~~~~~~cccccccccccccccccccc~~~~~~~~",
   "~~~~~~~cccccccXXXccXXXccccccc~~~~~~~",
   "~~~~~~ccccccXXXXXccXXXXXcccccc~~~~~~",
   "~~~~~ccccccXXXcccccccccXXcccccc~~~~~",
   "~~~~~cccccXXXcccccccccccXXccccc~~~~~",
   "~~~~cccccXXXcccccccccccccXXccccc~~~~",
   "~~~~ccccXXXcccccccccccccccXXcccc~~~~",
   "~~~cccccXXcccccccccccccccccXccccc~~~",
   "~~~ccccXXccccccccccccccccccXXcccc~~~",
   "~~~ccccXXcccccccccccccccccccXcccc~~~",
   "~~~ccccXXcccccccccccccccccccXcccc~~~",
   "~~~ccccXXcccccccccccccccccccXcccc~~~",
   "~~~ccccXXcccccccccccccccccccXcccc~~~",
   "~~~ccccXXcccccccccccccccccccXcccc~~~",
   "~~~ccccXXccccccccccccccccccXXcccc~~~",
   "~~~ccccXXXcccccccccccccccccXXcccc~~~",
   "~~~cccccXXccccccccccccccccXXccccc~~~",
   "~~~~ccccXXXccccccccccccccXXXcccc~~~~",
   "~~~~cccccXXXccccccccccccXXXccccc~~~~",
   "~~~~~cccccXXXccccccccccXXXccccc~~~~~",
   "~~~~~XcccccXXXXXXccXXXXXXcccccX~~~~~",
   "~~~~~~XcccccXXXXXXXXXXXXcccccX~~~~~~",
   "~~~~~~~XccccccXXXXXXXXccccccX~~~~~~~",
   "~~~~~~~~XccccccccccccccccccX~~~~~~~~",
   "~~~~~~~~~XccccccccccccccccX~~~~~~~~~",
   "~~~~~~~~~~~XccccccccccccX~~~~~~~~~~~",
   "~~~~~~~~~~~~~~XccccccX~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~XccX~~~~~~~~~~~~~~~~",
   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
  ],
  "art": {
   "image": "oblivion/under/oblivion_5",
   "painted": []
  }
 }
}/*END*/;
})(window.RPG);
