// 生成物（design/art_ref/gen/env/_tools/under/snow/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// 雪原のエリア f_passinn「湯けむりの峠」（峠の宿と、湯の湧く谷、52×42）。エリア切り替えのフィールド（maps/field_00_kit.js・snow_field_00_kit.js）。
//   出口: w → f_eastroad.east, n → pass_inn.gate, e → world.snow_east
//   絵: field/under/f_passinn（v2/assets/env/field/under/。無ければマスから焼く）。文は src/i18n/ja/maps_snow.js（map.snow_field.passinn.*）
(function (R) {
  'use strict';
  R.Snow.fieldArea("f_passinn", {
    name: R.T('map.snow_field.passinn.name'), region: "r_snow", outside: "wall_snow",
    rows: [
      "FFFFFFF,,XXXXXXXXXX,..rXXXXXXXXXX\"\"wwrrrrrrrrrrrrrrr",
      "FFFFFFF,,,,,,,,,rrX,.rrXrrr;;r;;r;\"rwrrrrrrrrrrrrrrr",
      "FFFFFFFr,,,,,,,,,,,...,;;;;r;Tr;;,,Twrrrrrrrrrrrrrrr",
      "FFFFFFFT,,,,,,,,,,,...,;;;;T;;;;;,,rwrrrrrrrrrrrrrrr",
      "FFFFFFFT\",,,,,,,,,,...,;;;;;;;;;;,,rwrrrrrrrrrrrrrrr",
      "FFFrr,,,,TT,,,,,,,,...,,;rr,,,,;;,,rwrrrrrrrrrrrrrrr",
      ";r,,,,,,,,,,,,,,,,,...,,rTT;,,,,,,,rwwrrrrrrrrrrrrrr",
      ";;r,,,,,,,,,,,,,,,,...,,,r,,,,;,,,,rwwrrrrrrrrrrrrrr",
      ";;T;;,,,,,,,,,,,,,,...,,rT,,,,;;;;;rwwrrrrrrrrrrrrrr",
      ";;;;,,,,,,,,,,,,,,,...,,,,,,r,rrr;;,wwrrrrrrrrrrrrrr",
      ";;;,,,,,,,,,,,,,,,,...,,,,,rTTTTT;;rwwrrrrrrrrrrrrrr",
      ";;;,,,;,,,,,,,,,,,,...,,,,,rTTTTT,,rwwrrrrrrrrrrrrrr",
      ";;,,,;;Trr,,,,,,\"\",...,r,,,rTTTTT,,rwrrrrrrrrrrrrrrr",
      ";;,,r,rTTTTr,,,,\";;...,Tr,,,;;;;;,,wwrrrrrrrrrrrrrrr",
      ",,,,,,TTTTTT,,,;;;;...,,,,,,,;;;;;rwTrrrrrrrrrrrrrrr",
      ",,,,,,TTTTT,,,;;;;;..,,,,,,,,,;;;,;wwrrrrrrrrrrrrrrr",
      ",,,,,,,;;;;;,;;;;;;..,,,,,,,,;;;;;rwrrrrrrrrrrrrrrrr",
      ",,,,,,,,;;;;TT;;;;,..,,,,,,,,;;;;;rwwrrrrrrrrrrrrrrr",
      ",,,,,,,,;;;;\";;;,,,..,,,,,,,,;,;;;rwwrrrrrrrrrrrrrrr",
      ",,r,,,,,;;;;;;;;,,,......,,,,,,;;;;rwTTrrrrrrrrrrrrr",
      ",rTr,,,,;;;;;;..................,;;;wrrrrrrrrrrrrrrr",
      ",,,,,,,,;;;..........,,............wwrr;rrrrrrrrrrrr",
      ",,,,,,,,......;;;;;;,,,,,,,,,,,,...=wrr;;rrrrrrrrrrr",
      "............;;;;;;;;,,,,,,,,,,,,,,==..,,;;rrrrrrrrrr",
      "........;;;;;;;;;;;;,,,r,,,,,,r,rww....,;;;rrrrrrrrr",
      ",,,,,,,;;;;;;;;;;;:rr,,TT,,,:::rwwwT;....;;;rrrrrrrr",
      "\",,,,,;;rr;;;;;;::::rr,,,,,rr::wwwTr;;;....;;rrrrrrr",
      ",\",,,,;,,,;;;;;:r:ww::r;;,r:.wwwwr,;;;;;;........rr.",
      ",,,,,;rr,,;;;;r:.wwww::r:r::wwwwwr,;\";;;;;;.........",
      ",,,,;TTT,;;;;r:.wwwwww::::::::::rr;;;;;;;,,,,.......",
      ",,,,TTTTr;r;r:::wwwwww::.ww:::rr,,;;;;;;,,,,,rrrrrrr",
      ",,,,rTTTT,;:::::::ww:::wwwww:r,r,,;;;rXr,,,,,rrrrrrr",
      ",,,r,,,,,,::.w:::::::::.wwww:r,,\",;;;;,,,,,rrrrrrrrr",
      ";,rT,,r,,rr.www::r,,,,:::ww::r,,,,;;,,,,,,,rrrrrrrrr",
      ";;;;;;T;;rr:www::r,,,,,r::::rr,,,,,,,,,,,rrrrrrrrrrr",
      "rrrrr;rr;r;:::w:r,,rr,,,r:rTTr,,,,,,,,,,,rrrrrrrrrrr",
      "FFFFFFFFrrrrr::r,,,TT,rrr,,TTTr,rr,,,,,rrrrrrrrrrrrr",
      "FFFFFFFFFFFFFFFrrrTrr,,,Tr,,Tr,,,T,,,r,rrrrrrrrrrrrr",
      "FFFFFFFFFFFFFFFFFFFFrrrrrrrrrrrrrrrrFFrrrrrrrrrrrrrr",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFrrrrrrrrrrrrr",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFrrrrrrrrrrrrr",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFrrrrrrrrrrrr",
    ],
    objects: [
      {"type":"sign","x":18,"y":5,"text":R.T('map.snow_field.passinn.objects.0.text')},
      {"type":"sign","x":36,"y":24,"text":R.T('map.snow_field.passinn.objects.1.text')},
      {"type":"examine","x":21,"y":31,"event":"snow_pass_springs"},
      {"type":"waylamp","id":"wl_snow_80_35","x":9,"y":21,"lit":true},
      {"type":"prop","id":"snow_lamp","x":18,"y":4},
      {"type":"prop","id":"snow_lamp","x":17,"y":4},
      {"type":"chest","id":"f_passinn_c1","x":11,"y":31,"item":"i_incense","n":1},
      {"type":"examine","x":12,"y":15,"event":"snow_mat","mat":"snow_mat_berry"},
    ],
    npcs: [
      {"id":"guard_snow_east","look":"npc_guard_1","name":R.T('map.snow_field.passinn.guard_snow_east.name'),"x":47,"y":28,"dir":"w","move":"still","pushable":false,"cond":{"slice":true},"talk":{"lines":[{"text":R.T('map.snow_field.passinn.guard_snow_east.lines.0')}]},"reward":"news","key":"world_guard_snow_east"},
    ],
    spawns: {"west":{"x":1,"y":23,"dir":"e"},"inn":{"x":20,"y":1,"dir":"s"},"east":{"x":50,"y":28,"dir":"w"}},
    exits: [{"x":0,"y":23,"w":1,"h":2,"to":{"map":"f_eastroad","spawn":"east"}},{"x":20,"y":0,"w":2,"h":1,"to":{"map":"pass_inn","spawn":"gate"}},{"x":51,"y":28,"w":1,"h":2,"to":{"map":"world","spawn":"snow_east"},"cond":{"not":{"slice":true}}}],
    triggers: [],
    tilePatches: [{"cond":{"slice":true},"rect":[48,27,3,3],"rows":["rrr","rrr","rrr"]}],
    zones: [{"rect":[18,0,5,16],"zone":"zw_snow_road"},{"rect":[18,16,4,7],"zone":"zw_snow_road"},{"rect":[22,18,4,5],"zone":"zw_snow_road"},{"rect":[13,19,5,4],"zone":"zw_snow_road"},{"rect":[26,19,7,4],"zone":"zw_snow_road"},{"rect":[10,20,3,5],"zone":"zw_snow_road"},{"rect":[33,20,3,5],"zone":"zw_snow_road"},{"rect":[7,21,3,4],"zone":"zw_snow_road"},{"rect":[36,21,1,6],"zone":"zw_snow_road"},{"rect":[0,22,7,4],"zone":"zw_snow_road"},{"rect":[37,22,2,5],"zone":"zw_snow_road"},{"rect":[13,23,2,1],"zone":"zw_snow_road"},{"rect":[31,23,2,1],"zone":"zw_snow_road"},{"rect":[39,23,1,5],"zone":"zw_snow_road"},{"rect":[17,24,3,5],"zone":"zw_snow_road"},{"rect":[27,24,5,8],"zone":"zw_snow_road"},{"rect":[40,24,2,5],"zone":"zw_snow_road"},{"rect":[7,25,2,1],"zone":"zw_snow_road"},{"rect":[15,25,2,12],"zone":"zw_snow_road"},{"rect":[20,25,2,9],"zone":"zw_snow_road"},{"rect":[26,25,1,12],"zone":"zw_snow_road"},{"rect":[34,25,2,1],"zone":"zw_snow_road"},{"rect":[42,25,2,5],"zone":"zw_snow_road"},{"rect":[14,26,1,12],"zone":"zw_snow_road"},{"rect":[22,26,1,10],"zone":"zw_snow_road"},{"rect":[25,26,1,5],"zone":"zw_snow_road"},{"rect":[32,26,2,4],"zone":"zw_snow_road"},{"rect":[44,26,8,5],"zone":"zw_snow_road"},{"rect":[13,27,1,11],"zone":"zw_snow_road"},{"rect":[23,27,2,9],"zone":"zw_snow_road"},{"rect":[38,27,1,1],"zone":"zw_snow_road"},{"rect":[12,28,1,10],"zone":"zw_snow_road"},{"rect":[11,29,1,9],"zone":"zw_snow_road"},{"rect":[10,30,1,7],"zone":"zw_snow_road"},{"rect":[17,30,3,4],"zone":"zw_snow_road"},{"rect":[32,30,1,1],"zone":"zw_snow_road"},{"rect":[9,31,1,5],"zone":"zw_snow_road"},{"rect":[8,32,1,3],"zone":"zw_snow_road"},{"rect":[25,32,1,5],"zone":"zw_snow_road"},{"rect":[27,32,4,2],"zone":"zw_snow_road"},{"rect":[17,34,1,2],"zone":"zw_snow_road"},{"rect":[21,34,1,1],"zone":"zw_snow_road"},{"rect":[27,34,3,1],"zone":"zw_snow_road"},{"rect":[27,35,2,1],"zone":"zw_snow_road"},{"rect":[24,36,1,1],"zone":"zw_snow_road"},{"rect":[15,37,1,1],"zone":"zw_snow_road"},{"rect":null,"zone":"zw_snow"}],
    weather: "snow",
    weatherCond: "!cleared_r_snow",
    art: {"image":"field/under/f_passinn","painted":[],"overlay":"field/under/f_passinn_over","closed":"field/under/f_passinn_closed"},
    meta: {"sub":R.T('map.snow_field.passinn.meta.sub'),"worldRect":[240,70,44,44]},
    links: {"pass_inn":{"map":"f_passinn","spawn":"inn"}},
  });
})(window.RPG);
