// 生成物（design/art_ref/gen/env/_tools/under/snow/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// 雪原のエリア f_eastroad「灯守りの街道」（ユールと峠の宿をむすぶ森の道、56×40）。エリア切り替えのフィールド（maps/field_00_kit.js・snow_field_00_kit.js）。
//   出口: w → yule.gate_e, e → f_passinn.west, s → snow_woods.south
//   絵: field/under/f_eastroad（v2/assets/env/field/under/。無ければマスから焼く）。文は src/i18n/ja/maps_snow.js（map.snow_field.eastroad.*）
(function (R) {
  'use strict';
  R.Snow.fieldArea("f_eastroad", {
    name: R.T('map.snow_field.eastroad.name'), region: "r_snow", outside: "forest_dark",
    rows: [
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwwFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwwFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwwFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwwFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwwFFFFFFFFFFFFFFFF",
      "XXFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFwwFFFFFFFFFFFFFFFF",
      "XX,r,,,rrrwFFFFFFFFFFFFFFFFFFr;r,FFFFFFwFFFFFFFFFFFFFFFF",
      "XX;;,,,,,,,TwrrrrrFFFFFFwr\"rr;;,,,,r;rwwwFFFFFFFFFFFFFFF",
      "XX;b,,,,,,,r,,,br;wr;rrw;;;;;,,,,,,,,,,,wFFFFFTwwwr,rrrw",
      "XX;;;;;;,,,,,,,,;;;;;;;;;;r,,,Tr,,,,,,,,wwwrrww,,,,,,,,,",
      "XX;;;;;;;,,,\",,,,;;;;;;;rrTr,,,,,,,,,,,,,ww,,,,,rr,,,,,,",
      "XX;;;;;;;,,,,,,,,,;;;;;;TTTT,,XXXXXXX,,,,ww\"\",,,,r,,\",,,",
      "XX;;;;;\"\"\",,,,,,,,,;;;;;rTT,,,XXXXXXX,,,,ww,,,,,Tr,,,,Tr",
      "XX;;;,\"\"\"\",,,Tr,,rr;;;;;;rr;brXXXXXXX,,,ww\"\",,,,Tw,TTTTw",
      ";;;;,,,\"\"\",,,,,,;;;;;r;;;;\"\"\";XXXXXXXw;,wwr,,,,,,,TTTTw,",
      "..........,,,,;;;r;;;;rb\"\"\"\"\";XXXXXXXw,,wwr,\";;;,,,TTTw,",
      ".............,,,;Tr;;;;;;\";...........,,ww,\"\";;;;;,,r,,,",
      "r,,,,,,,,,......;;;;;;;;................=w,\"\"\";;r;;;,,,,",
      "XX,,,,,,,,,,...........::...;;;;,;,;;;..==.,\"\";Tr;;,rr,,",
      "XX,,\",,,,,,,,\"\"\"........::;;\";\"\"\",,,,,,,w=....;;;;,,,,,,",
      "XX;\"\",,,,,,,r\",\"\",\",rr;;::;,,,;,,,,,,,,,wwr.........,,,.",
      "XX;;\",,,,,,,,,,,;;\"\"TTr;;::,,,,,r,,,,,,,wwwr,,..........",
      "XX;;,,,,TTr,,,,,,;;rTTw,;,::,,,,Tr,,rrTr,www,,,,,,,,....",
      "XX\";,bTTTTTr,Tr,,,;rrwwr;,::,,,,r,,TTTrr,rww,,,,;;,,,,,,",
      "XX\"\",bTTTTT,,r,,,,,TwwwTr,,::,Tr,,,TTTr,,,ww,,,,;;;,,,,,",
      "XX;\"\",r,,,,,,,,rT,rTTTww;,,::,r,,,TTTTw,,rww,,,XXXr,,,,,",
      "XX,\"\",,,,;;;;;TTTT,wwwww,,,,::,,,,rTw,,,,www,,,,,,,,Tr,,",
      "XX,,,,,,,;;;;;rwTT,,,w,,,,,,::,,,,,r,,\",,wwr,,,,,,,;rbr\"",
      "XXFFr,,,,,;r;;r\"\"\";,,,,,,,T,::,,,,,,,,,r,wwr,Tr,r,,,;r;;",
      "XXFFFFFFFFFFFFFFFFr,,,,,,,r,,:,,,,,,r,FFFwFFFFrTTr,,;;;;",
      "XXFFFFFFFFFFFFFFFFFr,,,br,r,,::,Tr,,,FFFFwFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFrbbrr,,::,r,,,FFFFFwFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFrrrT,::,,;,FFFFFFwwFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFwwrrr,,:,,,FFFFFFFwwFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFwrrr,,:,rFFFFFFFFwwFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFrFFF:FFFFFFFFFFwwFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:.FFFFFFFFFFwFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFwFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFwwFFFFFFFFFFFF",
    ],
    objects: [
      {"type":"sign","x":23,"y":17,"text":R.T('map.snow_field.eastroad.objects.0.text')},
      {"type":"sign","x":28,"y":33,"text":R.T('map.snow_field.eastroad.objects.1.text')},
      {"type":"examine","x":5,"y":25,"event":"world_snow_fox"},
      {"type":"waylamp","id":"wl_snow_1","x":15,"y":21,"lit":"q_snow_lamps_1","event":"snow_waylamp"},
      {"type":"waylamp","id":"wl_snow_2","x":33,"y":19,"lit":"q_snow_lamps_2","event":"snow_waylamp"},
      {"type":"waylamp","id":"wl_snow_3","x":50,"y":23,"lit":"q_snow_lamps_3","event":"snow_waylamp"},
      {"type":"waylamp","id":"wl_snow_67_35","x":27,"y":22,"lit":true},
      {"type":"prop","id":"tent","x":13,"y":12},
      {"type":"prop","id":"firewood","x":15,"y":13},
      {"type":"prop","id":"lantern","x":11,"y":12},
      {"type":"examine","x":48,"y":27,"event":"snow_mat","mat":"snow_mat_coal"},
      {"type":"examine","x":33,"y":16,"event":"snow_road_hut"},
    ],
    npcs: [
      {"id":"snow_pilgrim","look":"npc_snow_old_m","name":R.T('map.snow_field.eastroad.snow_pilgrim.name'),"x":16,"y":14,"dir":"s","move":"still","talk":"world_snow_pilgrim","reward":"news","key":"world_snow_pilgrim"},
    ],
    spawns: {"yule":{"x":1,"y":16,"dir":"e"},"east":{"x":54,"y":22,"dir":"w"},"woods":{"x":30,"y":38,"dir":"n"}},
    exits: [{"x":0,"y":16,"w":1,"h":2,"to":{"map":"yule","spawn":"gate_e"}},{"x":55,"y":22,"w":1,"h":2,"to":{"map":"f_passinn","spawn":"west"}},{"x":30,"y":39,"w":2,"h":1,"to":{"map":"snow_woods","spawn":"south"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_snow"}],
    weather: "snow",
    weatherCond: "!cleared_r_snow",
    art: {"image":"field/under/f_eastroad","painted":[],"overlay":"field/under/f_eastroad_over"},
    meta: {"sub":R.T('map.snow_field.eastroad.meta.sub'),"worldRect":[156,64,96,60]},
    links: {"yule_e":{"map":"f_eastroad","spawn":"yule"},"snow_woods":{"map":"f_eastroad","spawn":"woods"}},
  });
})(window.RPG);
