// 生成物（design/art_ref/gen/env/_tools/under/snow/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// 雪原のエリア f_snowpass「凍て風の峠」（森から雪原へ越える峠、48×44）。エリア切り替えのフィールド（maps/field_00_kit.js・snow_field_00_kit.js）。
//   出口: s → f_windhill.pass, n → f_lake.south
//   絵: field/under/f_snowpass（v2/assets/env/field/under/。無ければマスから焼く）。文は src/i18n/ja/maps_snow.js（map.snow_field.snowpass.*）
(function (R) {
  'use strict';
  R.Snow.fieldArea("f_snowpass", {
    name: R.T('map.snow_field.snowpass.name'), region: "r_snow", outside: "wall_snow",
    rows: [
      "rrrrrrrrrrrrrrrR,;;;;;;;..;T;;;;;;;Rrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR;;;;;r;..;;;r;;;;;Rrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR,;;;;;,..;;;;;;T;;Rrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR,,,,;,,..,,,,;;,,,Rrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR\",,,,,,..,,r,,,,,,Rrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR,,,,,,,,..,,,,,,,,,Rrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR,,,,,,,,..,,,,,,,,,Rrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,,\",,,,..,,,,,,,,\"Rrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,,,,,,,...,,,,,,,\"\"Rrrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,,\"\",,,,..,,,,\",,,,Rrrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,r,,,,,..;;;;;T;T,,Rrrrrrrrrrr",
      "rrrrrrrrrrrrrrR,\",,,,,,,...;;;;;;;;,,Rrrrrrrrrrr",
      "rrrrrrrrrrrrrR,,\",,,,,;...r;;;;;;;r,,XXrrrrrrrrr",
      "rrrrrrrrrrrrrrR,\",,,,,..;;;;;;;;;;r,RXXrrrrrrrrr",
      "rrrrrrrrrrrrrrR,,,,,,..;;;;r;;;;;;,,RXXrrrrrrrrr",
      "rrrrrrrrrrrrrrR,,,,,...;;r;;;r;r;;,XXXXrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,,..r;rr;;;r;r;;,,XXrrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,..r;;;;;;;;;;;;,rRrrrrrrrrrrr",
      "rrrrrrrrrrrrrrR,,,,..,;;;;;;;;;;;;,,Rrrrrrrrrrrr",
      "rrrrrrrrrrrrrR,,,,r..,;;\"rr;;;;;;;;,TRrrrrrrrrrr",
      "rrrrrrrrrrrrrXXXXX,.:,,r\";;;;r;;,,,,,,Rrrrrrrrrr",
      "rrrrrrrrrrrrRXccc::::.r;r;;;r;;;,,,,,,Rrrrrrrrrr",
      "rrrrrrrrrrrrRXccc::,...;;;;;;;;,,,,,,,,Rrrrrrrrr",
      "rrrrrrrrrrRR,XXXXX;,,....,;;;;,,,,,,,,,,Rrrrrrrr",
      "rrrrrrrrRR,,,,,,,;;,,,......;;,,,,,,,,,,;Rrrrrrr",
      "rrrrrrrR,,,,,,,,,,,,,,,,,....;;;;,,,,,,,,;RrrrrR",
      "rrrrRRR,,,,,T,,,,,,,,,,,;,;...,,,,,,,,,,,;;RRRR;",
      "RRRR,,,,,,,,,,,;,,,,,,,;;;;,..,,,,,,,,,,,;;;,,,;",
      ",;;;;,;,,,,,,,,,,,T,,,,,,;,\"\"..\"\",,,,,,,,,,,,,,r",
      ",;;;;;;;,,,,,,,,,TTT,,,,,,,,,..\"\",;;;,,,,,,,,,,,",
      ",,;;;;;;,,,,,,,r,TTT,,,,,,,,.,,,X,T;,,TTTT,,TT,\"",
      ",,;;;;;;,,,,,,,,,,,,,,,,T,,..,,,,,;;,TTTTT,TTT,,",
      "\"\";;;;;,,,,,,,,,,,,,,,,,;,...,,,,,r,,,,TTT,,T,,,",
      "\";,,,;,,,,,::,,,,,,,,,,,;...,,,,,,,,,,,,,;\"\";,,,",
      ";;,,,;,,,,,::::,,,,,r,,,...,,,,,,,,,,,,,,;;;;,,\"",
      ";,,\",,,,,,,,,,::::,,,,,,..,,,,,TTT,,,,,,,;;;;,,,",
      ",,,\"\"TTT,,,,,,,,:::::,,...,,,,,TTTT,,,,,,,;;;;,,",
      ",,,,\"TTT,,,,,,,,,,,:::::.,,,,,;TTT,,r,,,,;;,;;,,",
      "FFFFFFFFFFF,,,,,,,,,,,,:.,,,T,;;,,,,,,,,,,,,FFFF",
      "FFFFFFFFFFFFF,,,,,,,\",..,,,,;;;;;,,,,FFFFFFFFFFF",
      "FFFFFFFFFFFFFFF,,,FFFF..FF,T;;;FFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFF...FFFFFFFFFFFFFFFFFFFFFFF",
    ],
    objects: [
      {"type":"sign","x":21,"y":39,"text":R.T('map.snow_field.snowpass.objects.0.text')},
      {"type":"examine","x":31,"y":31,"event":"snow_pass_cairn"},
      {"type":"examine","x":18,"y":22,"event":"snow_pass_hut"},
      {"type":"waylamp","id":"wl_snow_39_43","x":25,"y":37,"lit":true},
      {"type":"waylamp","id":"wl_snow_39_38","x":23,"y":8,"lit":true},
      {"type":"prop","id":"tent","x":8,"y":32},
      {"type":"prop","id":"firewood","x":9,"y":34},
      {"type":"prop","id":"snow_lamp","x":9,"y":33},
      {"type":"chest","id":"f_snowpass_c1","x":15,"y":21,"item":"i_ether","n":1},
    ],
    npcs: [
      {"id":"snow_trapper","look":"npc_snow_man","name":R.T('map.snow_field.snowpass.snow_trapper.name'),"x":11,"y":33,"dir":"s","move":"still","talk":"world_snow_trapper","reward":"hint","key":"world_snow_trapper"},
    ],
    spawns: {"south":{"x":23,"y":42,"dir":"n"},"north":{"x":24,"y":1,"dir":"s"}},
    exits: [{"x":23,"y":43,"w":2,"h":1,"to":{"map":"f_windhill","spawn":"pass"}},{"x":24,"y":0,"w":2,"h":1,"to":{"map":"f_lake","spawn":"south"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_snow"}],
    weather: "blizzard",
    art: {"image":"field/under/f_snowpass","painted":[]},
    meta: {"sub":R.T('map.snow_field.snowpass.meta.sub'),"worldRect":[98,104,44,40]},
    links: {},
  });
})(window.RPG);
