// 生成物（design/art_ref/gen/env/_tools/under/snow/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// 雪原のエリア f_floe「北の流氷原」（オーロラの海、52×40）。エリア切り替えのフィールド（maps/field_00_kit.js・snow_field_00_kit.js）。
//   出口: s → f_lake.north
//   絵: field/under/f_floe（v2/assets/env/field/under/。無ければマスから焼く）。文は src/i18n/ja/maps_snow.js（map.snow_field.floe.*）
(function (R) {
  'use strict';
  R.Snow.fieldArea("f_floe", {
    name: R.T('map.snow_field.floe.name'), region: "r_snow", outside: "sea",
    rows: [
      "rrrrrrrrrrrR~~~~~~~~~~~~~~~~~~~~XXXXXXXXXXXX~~~~~~~~",
      "rrrrrrrrrrrR~~~~~~~~~~~~~~~~~~~~XXXXXXXXXXXX~~~~~~~~",
      "rrrrrrrrrrrR~~~~~~~~~~~~~~~~~~~rXXXXXXXXXXXXr~~~~~~~",
      "rrrrrrrrrrR~~~~~~~~~~~~~~~~~~sssXXXXXXXXXXXXXX~~~~~~",
      "rrrrrrrrrrR~~~~~~~~~~,,r,,,~~sssXXXXXXXXXXXXXX~~~~~~",
      "rrrrrrrrrrR~~~~~~~rr,,,,,,,rssssXXXXXXXXXXXXXXrr~~~~",
      "rrrrrrrrrrR~~~~~~r,,,,,,,,,sssssXXXXXXXXXXXXXXrsrr~~",
      "rrrrrrrrrrrR~~~~r,,,,,,,,,,sssssXXXXXXXXXXXXXXss,,r~",
      "rrrrrrrrrXXXX~~~r,,,,,,,,,,,ssssXXXXXXXXXXXXXXss,,,r",
      "rrrrrrrrrXXXX~~~r,,,,,,,,,,,,,sssssrrsXsrrsssss,,,,,",
      "rrrrrrrrr,,,,,,~r,,,,,,,,,,,,,,,ssssssssssssss,,,,,,",
      "rrrrrrrrr,,ss,,~~r,,,,,,,,,,,,,,,sssssssssss,,,,,,,,",
      "rrrrrrrrr,,ss,,~~~~r,rrr,,,r,,,,,,,,,,ss,,,,,,,,,,,r",
      "rrrrrrrrr,,,ss,~~~~~~~~~~~~~r,,,,,,,,,ss,,,,,,,,,,r~",
      "rrrrrrRRR~r,sss~~~~~~~~~~~~~~r,,,,,,,,ss,,,,,,,,,,~~",
      "RRRRRR~~~~r,sss~~~~~~~~~~~~~~~,,,,,,,,,ss,,,,,,,,~r~",
      "~~~~~~~~rrrrrrsr,~~~~~~~~~~~~~~~,,,,,,,ss,,,,,,,~~~~",
      "~~~~~~r,,rrrrss,,,~~~~~~~~~~~r~~~~,,,,,ss,,,,,,~~~~~",
      "~~~~~r,,rrr,,,ss,,,~~~~~~~~~~~~~~~~~~,,sss~~~~~~~~~~",
      "~~~~r,,,,,,,,,ss,,,~~~~~~~~~~~~~~~~~~~~sss~~~~~~~~~~",
      "~~~~r,,,,,,,,,,ss,,,~~~~~~~~~~~~r~~~~~~sssr,~~~~~~~~",
      "~~~~r,,,,,,,,,,sss,,~~~~~~~~~~~~~~~~~rr,ss,,r,r~~~~~",
      "~~~~,,,,,,,,,,,,ss,,,~~~~~~~~~~~~~~,,,,,ss,,,,,,~~~~",
      "~~~~r,,,,,,,,,,,sss,,~~~~~~~~~~~~~,,,,,,,,,,,,,,r~~~",
      "~~~~r,,,,,,,,,,,,sss,~~~~~~~~~~~~r,,,ss,,,,,r,,,,~~~",
      "~~~~~r,,,,,,,,,,,,sss~~~~~~~~~r~~r,ssss,,,,,,r,,,~~~",
      "~~~~~~r,,,,,,,,,,,,ss,rrrrrr,r,r,,ssss,,,,,,,,r,,,~~",
      "~~~~~~~~r,,,,,,,,,,,ssrrr,,,,,,sssss,,,,,,,,,,,,,,~~",
      "~~~~~~~~~~~~~r,,,,,rrssrrrrr,sssss,,,,,,,,,,,,,,,~~~",
      "~~~~~~~~~~~~~r,,,rrr,,sss,,sssss,,,,,,,,,,,,,,,,r~~~",
      "~~~~r~~~~~~~~r,,,,,,,,,sss,ss,,,,,,,,,,,,,,,,,,r~~~~",
      "~~~~~~~~~~~~r,,,,,,,,,,,ssss,,,,,,,,,,,,,,,,,,~~~~~~",
      "~~~~~~~~~~~r,,,,,,,,,,ssssss,,,,,,,,,,,r,,~~~~~~~~~~",
      "~~~~~~~~~~~r,,,,,,,,sssssssssss,,,,rrrrr,,~~~~~~~~~~",
      "~~~~~~~~~~~r,,,,,,,,ssssssssssss,,,r,,,,,,~~~~~~~~~~",
      "~~~~~~~~~~~r,,,,,,,sssssssssssss,,,,,,,,,~~~~~~~~~~~",
      "~~~~~~~~~~~~r,,,,,,,ssssssssssss,,,,,,,,,~~~~~~~r~~~",
      "~~~~~~~~~~~~~~r,,,,,,sssssssssss,,,,,,,r~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~r,,,sssssssssss,,,,r,~~~~~~~~~~~~~~",
      "~~~~~~~~~~~~~~~~~~~r,,ssssssss,,,,,r~~~~~~~~~~~~~~~~",
    ],
    objects: [
      {"type":"door","x":11,"y":9,"w":2,"look":"none","to":{"map":"aurora","spawn":"south"}},
      {"type":"door","x":38,"y":9,"look":"none","to":{"map":"frost_ship_1","spawn":"entrance"}},
      {"type":"sign","x":14,"y":12,"text":R.T('map.snow_field.floe.objects.2.text')},
      {"type":"sign","x":36,"y":12,"text":R.T('map.snow_field.floe.objects.3.text')},
      {"type":"examine","x":22,"y":35,"event":"world_snow_floe_sled"},
      {"type":"prop","id":"sled","x":21,"y":35},
      {"type":"prop","id":"snow_lamp","x":27,"y":35},
      {"type":"prop","id":"ice_crystal","x":9,"y":12},
      {"type":"prop","id":"ice_crystal","x":14,"y":10},
    ],
    npcs: [

    ],
    spawns: {"south":{"x":26,"y":38,"dir":"n"},"landing":{"x":24,"y":34,"dir":"n"},"aurora":{"x":12,"y":11,"dir":"s"},"ship":{"x":38,"y":11,"dir":"s"}},
    exits: [{"x":26,"y":39,"w":2,"h":1,"to":{"map":"f_lake","spawn":"north"},"cond":"cleared_r_snow"}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"z_snow_floe"}],
    weather: "snow",
    art: {"image":"field/under/f_floe","painted":[]},
    meta: {"sub":R.T('map.snow_field.floe.meta.sub'),"worldRect":[44,4,100,36]},
    links: {"aurora":{"map":"f_floe","spawn":"aurora"},"frost_ship":{"map":"f_floe","spawn":"ship"},"floe":{"map":"f_floe","spawn":"landing"}},
  });
})(window.RPG);
