// 生成物（design/art_ref/gen/env/_tools/under/snow/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// 雪原のエリア f_peakfoot「白竜の峰のふもと」（竜の骨と冬至の祠、48×42）。エリア切り替えのフィールド（maps/field_00_kit.js・snow_field_00_kit.js）。
//   出口: s → yule.gate_n
//   絵: field/under/f_peakfoot（v2/assets/env/field/under/。無ければマスから焼く）。文は src/i18n/ja/maps_snow.js（map.snow_field.peakfoot.*）
(function (R) {
  'use strict';
  R.Snow.fieldArea("f_peakfoot", {
    name: R.T('map.snow_field.peakfoot.name'), region: "r_snow", outside: "wall_snow",
    rows: [
      "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrRRRRRRRrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrRRRRRRRR;,,,,,RrrrrrrrXXXXRRrRRRrrrrrrRRR",
      "RRRRRRRR,,,,,,r;;,,,,,RRRRRRRXXXXRRR,,,RRRRRRR,,",
      "r,,,,,,,,,,rr,T;;;,,\",,R,,,,RXXXXrrT\",;,,,,,,,,,",
      "r,,,,,,,TTT,,,,;;r;;;,,,,,,,cc.cccr\"\"rTrT;;;;,,,",
      ",,,;;;rrrrrTr,,;,;;;,,,,,,,,cc..cc\"\"\"r;,;;;;;;,,",
      ",,,rT,TTTTTrT,,;;;;;,,,,,,,,cc..cc\"\"rT;rTrrrT,,,",
      ",,,,,,TTTTT,,,,;;;;;;;,,T,,,,..,,,,,,,,TTTTTT,,,",
      "\",,,,,,,,,,,,,,,,;;;;;,,rT,,...,,,,,,,,,TTTTT;;,",
      "\",,,,,,,,,,,,,,,;;;,,,,,,,,...,,,,,,,,,,T,,,,,,,",
      ",,,,,,,,,,,,,,;;;,,,,,,,,,...,,rT,,,,,,rT\",,,,,;",
      ",,,,,,,,,,,,;;;\"\",,,;;,,,...,,,,,,,,,,\",\"\",,rT,;",
      ",,,,,,rT,,,r;r;r\"rr,,,,,...\",,;,T,,,,,\"\"\"\"\"\",,,;",
      ",,,,,,,,,,\",rrXrXrTr,,,,..\",,;;,rT,,\"\"\"\"\"\"\"\"\",,;",
      ",,,,rT,,,r;,X,rrrrX,,;,..,\",,;,;,,,,\"rr,,,\"\",,,,",
      ",,,,,,,rrr,rr,rrrrrr,,...;,,;;;;,,,r,Xrrr,\",,,,r",
      ",,,,,,,,,XXrr,:::rrr,,..;;;;;;,,,r,rcccrrr,,,,,r",
      ",,,,\"\",,\"rrrrT,,,,rrr..,;;;;;;,,:rXcccccXrT,,,,T",
      ",,,,,,,rrrrrXrr,,,Xrr..;:::::::::rcccXcccrT,,,,,",
      ",,,,,,rrrrT;,rXrX,,T::.;:::,,,,,rrXcccccXrr,r,,;",
      ",,,,,;;;,,;;;rrrrr;;.:,;;,rT,,,,,,rrcccrrr,,T,,;",
      ",,,,,,,r,,;;;;rrrr;;..,,,,TT,,,,,,,,rXrr,,,,r,,;",
      ",,,TTrrrT,,;;;;;rr;;..,,,,,,,,,,,,,,,;;,,;;;,;;;",
      ",,,rrrTTTT,T;;;;;;;;..,,,,,,TTTr,,,;;,,,,;Tr;rT;",
      ",,,rTTTTTr,r;;;;;;;;..,,\",,,rrrT,,,,;rT;TrrrTT,,",
      ",,,TTTTTTT\",;;;,\"r,,,..,,,TT,TTTT,,,,,,rrTTTTTT,",
      ",,,,,TTT,,\";;;;,\"r,,,..,,;rT,,,TT,,,,,,,TTTTTTT,",
      "TTT;\",,,,,,;;;,,,,,,,...;;,;;;,T;;;,,,,,TTTTTTT,",
      "TTTTT;;;;T;;;;,,,,,,,,..;;;;;;;TT;;,\"\",,,TTTTT,,",
      "FFTTTTTr;TT;;;,,,,,,,,..;;;;;;;;;;;,\",,,,,,,TTTT",
      "FFFFFrrrT;;;;,,,,,,,r,..;;;r;;;,;;;\"\"\",,,,TTTTTT",
      "FFFFFFFFTT,,,,,,,,,,r,..;;;r;;;;;,,,\"\",,,rrrFFFF",
      "FFFFFFFFFTT,rrrrrrrrrT..;;;rrrrrrrrrr,,,,FFFFFFF",
      "FFFFFFFFFFTrrrrrrrrrXT..r,\"Xrrrrrrrrr,,,,FFFFFFF",
      "FFFFFFFFFFTTXXXXXXXXXT..,,,XXXXXXXXXrT,,,FFFFFFF",
    ],
    objects: [
      {"type":"door","x":30,"y":10,"w":2,"look":"none","to":{"map":"peak_1","spawn":"south"}},
      {"type":"sign","x":27,"y":13,"text":R.T('map.snow_field.peakfoot.objects.1.text')},
      {"type":"examine","x":10,"y":23,"event":"snow_foot_bones"},
      {"type":"examine","x":37,"y":25,"event":"snow_foot_shrine"},
      {"type":"prop","id":"beacon","x":37,"y":25,"cond":"cleared_r_snow"},
      {"type":"waylamp","id":"wl_snow_48_17","x":23,"y":31,"lit":true},
      {"type":"waylamp","id":"wl_snow_55_17","x":33,"y":14,"lit":true},
      {"type":"prop","id":"ice_crystal","x":26,"y":13},
      {"type":"chest","id":"f_peakfoot_c1","x":16,"y":24,"item":"i_revive","n":1},
    ],
    npcs: [
      {"id":"snow_scout","look":"npc_snow_watch","name":R.T('map.snow_field.peakfoot.snow_scout.name'),"x":25,"y":20,"dir":"s","move":"still","talk":"world_snow_scout","reward":"boss","key":"world_snow_scout"},
    ],
    spawns: {"yule":{"x":23,"y":40,"dir":"n"},"peak":{"x":30,"y":11,"dir":"s"}},
    exits: [{"x":23,"y":41,"w":2,"h":1,"to":{"map":"yule","spawn":"gate_n"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":[29,10,3,7],"zone":"zw_snow_road"},{"rect":[32,11,1,4],"zone":"zw_snow_road"},{"rect":[28,13,1,7],"zone":"zw_snow_road"},{"rect":[27,14,1,7],"zone":"zw_snow_road"},{"rect":[26,15,1,7],"zone":"zw_snow_road"},{"rect":[25,16,1,12],"zone":"zw_snow_road"},{"rect":[24,17,1,11],"zone":"zw_snow_road"},{"rect":[29,17,2,1],"zone":"zw_snow_road"},{"rect":[23,18,1,10],"zone":"zw_snow_road"},{"rect":[29,18,1,1],"zone":"zw_snow_road"},{"rect":[22,20,1,22],"zone":"zw_snow_road"},{"rect":[13,21,5,4],"zone":"zw_snow_road"},{"rect":[21,21,1,21],"zone":"zw_snow_road"},{"rect":[18,22,2,5],"zone":"zw_snow_road"},{"rect":[20,23,1,13],"zone":"zw_snow_road"},{"rect":[31,23,4,4],"zone":"zw_snow_road"},{"rect":[26,24,5,3],"zone":"zw_snow_road"},{"rect":[17,25,1,1],"zone":"zw_snow_road"},{"rect":[19,27,1,6],"zone":"zw_snow_road"},{"rect":[26,27,2,1],"zone":"zw_snow_road"},{"rect":[23,31,1,11],"zone":"zw_snow_road"},{"rect":[24,33,1,9],"zone":"zw_snow_road"},{"rect":null,"zone":"zw_snow"}],
    weather: "snow",
    weatherCond: "!cleared_r_snow",
    art: {"image":"field/under/f_peakfoot","painted":[],"overlay":"field/under/f_peakfoot_over"},
    meta: {"sub":R.T('map.snow_field.peakfoot.meta.sub'),"worldRect":[134,16,64,52]},
    links: {"yule_n":{"map":"f_peakfoot","spawn":"yule"},"peak":{"map":"f_peakfoot","spawn":"peak"}},
  });
})(window.RPG);
