// 生成物（design/art_ref/gen/env/_tools/under/snow/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// 雪原のエリア f_lake「凍った湖」（ユールの西の湖と、つららの崖、56×44）。エリア切り替えのフィールド（maps/field_00_kit.js・snow_field_00_kit.js）。
//   出口: s → f_snowpass.north, e → yule.gate_w, n → f_floe.south
//   絵: field/under/f_lake（v2/assets/env/field/under/。無ければマスから焼く）。文は src/i18n/ja/maps_snow.js（map.snow_field.lake.*）
(function (R) {
  'use strict';
  R.Snow.fieldArea("f_lake", {
    name: R.T('map.snow_field.lake.name'), region: "r_snow", outside: "wall_snow",
    rows: [
      "rrrrrrRr,,,\"\"\"swwwwwwwwwwsswwwwwwwwwwww,,,,,,,FFFFFFFFFF",
      "rrrrrrRr,,,,\",swwwwwwwwwwssswwwwwwwwwww,,,,,,,FFFFFFFFFF",
      "rrrrrrRr;,,,,,swwwwwwwwwwssswwwwwwwwwww,,,,,,,rFFFFFFFFF",
      "rrrrrrRrrr,,,rswwwwwwwwwwssswwwwwwwwwww,,,,,,,,FFFFFFFFF",
      "rrrrrrRrTT,,,rswwwwwwwwwwwsswwwwwwwwwww\"\"\",,,TrFFFFFFFFF",
      "rrrrrrR;;;;;,rswwwwwwwwwwwsswwwwwwwwwwwr\"\",,,,rFFFFFFFFF",
      "rrrrrrRr;;,;;;swwwwwwwwwwwsswwwwwwwwwwww\"br,,rrFFFFFFFFF",
      "rrrrrrRr;;,,;;swwwwwwwwwwwsswwwwwwwwwwwwr\",,,,,FFFFFFFFF",
      "rrrrrrRr;;;,;;swwwwwwwwwwwsswwwwwwwwwwwwwrsrr,,rFFFFFFFF",
      "rrrrrrRr;;;;,sswwwwwwwwwwwsswwwwwwwwwwwwww,,,,,,FFFFFFFF",
      "rrrrrrrR;;;;;swwwwwwwwwwwwsswwwwwwwwwwwwwwrbr,,,rFFFFFFF",
      "rrrrrrrRr,;;;swwwwwwwwwwwwsswwwwwwwwwwwwwwwbbr,;;FFFFFFF",
      "rrrrrrrRr,;;;swwwwwwwwwwwwwsswwwrrrwwwwwwwrbbr,,,FFFFFFF",
      "rrrrrrrRrr;;;srwwwwwwwwwwwwsswwrrXrrwwwwwwrbr,,;;FFFFFFF",
      "rrrrrrrRr;;;;;swwwwwwwwwwwwsswwwrrrwwwwwwrbbr,Tr;FFFFFFF",
      "rrrrrrrrRr,,;,swwwwwwwwwwwwsswwwwwwwwwwwwsbr,,;;;rFFFFFF",
      "rrrrrrrrRr,,,,swwwwwwwwwwwwsswwwwwwwwwwww,br,,;;;;;;rrrr",
      "rrrrrrrrR,,,,,swwwwwwwwwwwwsswwwwwwwwwwwr,,,,,,;;;;;;;rr",
      "rrrrrrrrR,,,,,sswwwwwwwwwwwsswwwwwwwwwww,,,,,,;;;;;,;;XX",
      "rrrrrrrrR,,,,,,swwwwwwwwwwwsswwwwwwwwwrrsr,,,,,;;;Tr,rXX",
      "rrrrrrrrRr,,,,,sswwwwwwwwwwsswwwwwwwwrbbr,,,,,,,;TTTr\"XX",
      "rrrrrrrrRr,,,,,rrwwwwwwwwwwsswwwwwwwrrbr,,,;;,Tr;;,,,,XX",
      "rrrrrrrRr,,;;;,TTswwwwwwwwwsswwwwwwrrr\",\";;;;;;,,,,,,,XX",
      "rrrrrrrRrr;;;;,,,ssrwwwwwwwwsswwwwrsr,,\"\";;;\"\"TTT,,,,,XX",
      "rrrrrrrRr;;;;rr,,,,srrwwwwwwrsrrrr,,,,,,r;;\";;TTTr,,,,XX",
      "rrrrrrRr,;;;;;;,,,,,,srrrrrrrs,,,rr,,,,,\"\";;;;TTTr,,,,XX",
      "rrrrrrRr,,;;;;;;,,,,,br,,,,,ss,,brr,,,,;,,;;;;;,,,,,,,XX",
      "rrrrrrRr,,,,,;;;;,,,,,bbbbr,ss,,rr,,,,,;,,;;;;;,,,;,r,XX",
      "rrrrrrRr,,,,\"\"\";;;;;;,,,,,,,ss,,,;,,,,,,,,;;;;;;,;;,\"XXX",
      "rrrrrrXXXX,,;;;;rr;;;,,,,,TTss;,,,,r,,;;;;;;;;;;;;;;rTTT",
      "rrrrrrXXXXr,;;;;;;;;;,,,,,,,ss;;,,TTr,;;;;;;;;;r........",
      "rrrrrrr,,r::::;;;;;;;,,;,,,;,s;;;;r,,,;;;;;;r...........",
      "rrrrrrrR,,,,:::::r;;;,;;;;;;;;;;,;,,\"...........;;,,,,,,",
      "rrrrrrrRr,,,;;;::::;;;,;;;;;;;;,,............,,,,,,,rXXX",
      "rrrrrrrrR;;;;,r;;;:::;;;;;;;;;;........;;;;,,,,,,,,,rTXX",
      "rrrrrrrrR;;;;;r;;;;;:::::;;;;;...,,,,,,,,;,,,,,,,T,rTrXX",
      "rrrrrrrRr;;;;;\";\"\";;;;;::::::..;;,,,,r,,,,,,r,,,rTTr,,XX",
      "rrrrrrrRr;;Tr;;\"TTr;;;;;;;;::.;;\",,,rTTT,,,,r,,,,,,,,TXX",
      "rrrrrrRFFr;;;;r\"TTTrTr;;;;;..;;;,,,,TTTT\",,,,,,rrr,,,TXX",
      "rrrrrRFFFFr;FFFFFFFFFFrrT;;..r;;;,,,rTTT\",,,;;,rrFFF,,XX",
      "rrRRRFFFFFFFFFFFFFFFFFFFr;;..;;;;,,,rTTTrrr;FFFFFFFFFFXX",
      "RRFFFFFFFFFFFFFFFFFFFFFFFFr..;;r;,,rFFFFFFFFFFFFFFFFFFXX",
      "FFFFFFFFFFFFFFFFFFFFFFFFFF...,FFFFFFFFFFFFFFFFFFFFFFFFXX",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFFFFFFFFF",
    ],
    objects: [
      {"type":"door","x":7,"y":30,"w":2,"look":"none","to":{"map":"icicle_1","spawn":"entrance"}},
      {"type":"sign","x":11,"y":33,"text":R.T('map.snow_field.lake.objects.1.text')},
      {"type":"sign","x":32,"y":36,"text":R.T('map.snow_field.lake.objects.2.text')},
      {"type":"examine","x":31,"y":34,"event":"world_snow_lake"},
      {"type":"prop","id":"sled","x":26,"y":34},
      {"type":"prop","id":"ice_hole","x":36,"y":25},
      {"type":"prop","id":"ice_crystal","x":10,"y":27},
      {"type":"prop","id":"ice_crystal","x":12,"y":30},
      {"type":"waylamp","id":"wl_snow_26_37","x":20,"y":33,"lit":true},
      {"type":"waylamp","id":"wl_snow_42_32","x":41,"y":34,"lit":true},
      {"type":"prop","id":"tent","x":10,"y":18},
      {"type":"prop","id":"firewood","x":11,"y":19},
      {"type":"prop","id":"lantern","x":9,"y":18},
      {"type":"examine","x":13,"y":21,"event":"snow_mat","mat":"snow_mat_ice"},
    ],
    npcs: [

    ],
    spawns: {"south":{"x":27,"y":42,"dir":"n"},"yule":{"x":54,"y":30,"dir":"w"},"north":{"x":26,"y":1,"dir":"s"},"icicle":{"x":8,"y":31,"dir":"s"}},
    exits: [{"x":27,"y":43,"w":2,"h":1,"to":{"map":"f_snowpass","spawn":"north"}},{"x":55,"y":30,"w":1,"h":2,"to":{"map":"yule","spawn":"gate_w"}},{"x":26,"y":0,"w":2,"h":1,"to":{"map":"f_floe","spawn":"south"},"cond":"cleared_r_snow"}],
    triggers: [],
    tilePatches: [{"cond":{"not":"cleared_r_snow"},"rect":[25,0,5,24],"rows":["ww   ","ww   ","ww   ","ww   "," ww  "," ww  "," ww  "," ww  "," ww  "," ww  "," ww  "," ww  ","  ww ","  ww ","  ww ","  ww ","  ww ","  ww ","  ww ","  ww ","  ww ","  ww ","  ww ","   ww"]}],
    zones: [{"rect":null,"zone":"zw_snow"}],
    weather: "snow",
    weatherCond: "!cleared_r_snow",
    art: {"image":"field/under/f_lake","painted":[],"overlay":"field/under/f_lake_over","closed":"field/under/f_lake_closed"},
    meta: {"sub":R.T('map.snow_field.lake.meta.sub'),"worldRect":[60,44,84,64]},
    links: {"yule_w":{"map":"f_lake","spawn":"yule"},"icicle":{"map":"f_lake","spawn":"icicle"}},
  });
})(window.RPG);
