// 生成物（design/art_ref/gen/env/_tools/under/snow/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// 雪原のエリア f_peakfoot「白竜の峰のふもと」（竜の骨と冬至の祠、48×42）。エリア切り替えのフィールド（maps/field_00_kit.js・snow_field_00_kit.js）。
//   出口: s → yule.gate_n
//   絵: field/under/f_peakfoot（v2/assets/env/field/under/。無ければマスから焼く）。文は src/i18n/ja/maps_snow.js（map.snow_field.peakfoot.*）
(function (R) {
  'use strict';
  R.Snow.fieldArea("f_peakfoot", {
    name: R.T('map.snow_field.peakfoot.name'), region: "r_snow", outside: "wall_snow",
    rows: [
      "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrRrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrRRRRRRRrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
      "rrrrrrrRRRRRRRR;RRRRRRrrrrrrrXXXXRRrRRRrrrrrrRRR",
      "RRRRRRRRRRRRRr;;;,,,RRRRRRRRRXXXXRRRRRRRRRRRRRRR",
      "RRRRRRR,,,,,,,;;;;,,\",RRRRRRRXXXX,,\"\",;RRRRRR,,,",
      ",,,,,,,,,,,r,T,;;;;;;,T,,,,,cc.ccc;\"\";;;;;;;;,,,",
      "T,,;;;,;;,,,,,,;r;;;,,,,,,,,cc..cc\"\"\"T;r;;;;;;,,",
      ",,,,,,TTTTT,,,,;;;;;,,,,,,,,cc..cc\"\";;;,;;;;,,,,",
      ",,,r,,TTTTTT,,,;;;;;;;,,,,,,,..,,,,,T,,T,TTT,,,,",
      "\",,,,,TTTT,,,,,,,;;;;;,,,,,,...,,,,,,,,TTTTT,;;,",
      "\",,,,,,,,,,,,,,,;;;,,,,,T,,...,,,,,,,,,,TTTT,,,,",
      ",,,,,,,,,,,,,,;;;,,,,,,,,,...,,,,,,,,,,\"\"\",,,,,;",
      ",,,,,,,,,,,,;;;\"\",,,;;,,,...,,,r,,,,,,\"T\"\",,,,,;",
      ",,,,,,,,,,,;;;;\"\",,,,,,,...\",,;,,,,,,,\"\"\"\"\"\"r,,;",
      ",,,,,,r,,,\",,,X,X,,,,,,,..\",,;;,,,,,\"\"\"\"\"\"\"\"\",,;",
      ",,,,,,,,,;;,X,,,,,X,,;,..,\",,;,;T,,,\",,,,,\"\",,,,",
      ",,,,r,,,,,,,,,:::,,,,,...;,,;;;;,,,,,X,,,,\",,,,,",
      ",,,,,,,,,XX,,,:::::,,,..;;;;;;,,,,,,ccc,,,,,,,,\"",
      ",,,,\"\",,\",,,,,,,,,::,..,;;;;;;,,::XcccccX,,,,,,T",
      ",,,,,,,,\",,,X,,,,,X::..;::::::::::cccXccc,,,,,,,",
      ",,,,,,;;,,,;,,X,X,,;::.;:::,,,,,,,XcccccX,,,,,,;",
      ",,,,,;;;,,;;;;,,;;;;.:,;;,,,,,,,,,,,ccc,,,,,,,,;",
      ",,,,,,,,,,;;;;;;;;;;..,,,,T,,,,,,,,,,X,,,,,,,,,;",
      ",,,,,,,,,,,;;;;;;;;;..,,,,,,,,,,,,,,,;;,,;;;T;;;",
      ",,,r,,TT,,,;;;;;;;;;..,,,,,,\",,,,,,;;,,,,;;;;\"\";",
      ",,,,TTTTT,,\";;;;;;;;..,,\",,,,,,,,,,,;,,;;;;;,T,,",
      ",,,TTTTTTT\"T;;;,\",,,,..,,,,,TTT,,,,,,r,;;TTT\",,,",
      ",,,TTTTTTT\";;;;,\",,,,..,,;;,,TTT,,,,,,,TTTTTTT,,",
      ",,,;\"TTT,,,;;;,,,r,,,...;;T;;;TT;;;,,,,TTTTTTT,,",
      ",,,,\";;;;;;;;;,,,,,,,,..;;;;;;;;;;;,\"\",,TTTTTT,,",
      "FFT\"\";;;;;;;;;,,,,,,,,..;;;;;;;;;;;,\",,,,TTTT,,,",
      "FFFFF;;;;;;;;,,,,,,,,,..;;;;;;;T;;;\"\"\",,,,,,,,,,",
      "FFFFFFFF,T,,,,,,,,,,,,..;;;;;;;;;,,,\"\",,,,,,FFFF",
      "FFFFFFFFF,,,,,,,,,,,,,..;;;;;;,;,,,,,,,,,FFFFFFF",
      "FFFFFFFFFF,,,,,,,,,,X,..,,\"X;,,,,,,,,,,,,FFFFFFF",
      "FFFFFFFFFF,,XXXXXXXXX,..,,,XXXXXXXXX,,,,,FFFFFFF",
    ],
    objects: [
      {"type":"door","x":30,"y":10,"w":2,"look":"none","to":{"map":"peak_1","spawn":"south"}},
      {"type":"sign","x":27,"y":13,"text":R.T('map.snow_field.peakfoot.objects.1.text')},
      {"type":"examine","x":10,"y":23,"event":"snow_foot_bones"},
      {"type":"examine","x":37,"y":25,"event":"snow_foot_shrine"},
      {"type":"prop","id":"beacon","x":37,"y":25,"cond":"cleared_r_snow"},
      {"type":"waylamp","id":"wl_snow_48_17","x":24,"y":31,"lit":true},
      {"type":"waylamp","id":"wl_snow_55_17","x":33,"y":15,"lit":true},
      {"type":"prop","id":"ice_crystal","x":26,"y":13},
      {"type":"prop","id":"snow_lamp","x":33,"y":14},
      {"type":"chest","id":"f_peakfoot_c1","x":16,"y":24,"item":"i_revive","n":1},
    ],
    npcs: [
      {"id":"snow_scout","look":"npc_snow_watch","name":R.T('map.snow_field.peakfoot.snow_scout.name'),"x":25,"y":20,"dir":"s","move":"still","talk":"world_snow_scout","reward":"boss","key":"world_snow_scout"},
    ],
    spawns: {"yule":{"x":23,"y":40,"dir":"n"},"peak":{"x":30,"y":11,"dir":"s"}},
    exits: [{"x":23,"y":41,"w":2,"h":1,"to":{"map":"yule","spawn":"gate_n"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_snow"}],
    weather: "snow",
    weatherCond: "!cleared_r_snow",
    art: {"image":"field/under/f_peakfoot","painted":[]},
    meta: {"sub":R.T('map.snow_field.peakfoot.meta.sub'),"worldRect":[134,16,64,52]},
    links: {"yule_n":{"map":"f_peakfoot","spawn":"yule"},"peak":{"map":"f_peakfoot","spawn":"peak"}},
  });
})(window.RPG);
