// 生成物（design/art_ref/gen/env/_tools/under/snow/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// 雪原のエリア f_snowpass「凍て風の峠」（森から雪原へ越える峠、48×44）。エリア切り替えのフィールド（maps/field_00_kit.js・snow_field_00_kit.js）。
//   出口: s → f_windhill.pass, n → f_lake.south
//   絵: field/under/f_snowpass（v2/assets/env/field/under/。無ければマスから焼く）。文は src/i18n/ja/maps_snow.js（map.snow_field.snowpass.*）
(function (R) {
  'use strict';
  R.Snow.fieldArea("f_snowpass", {
    name: R.T('map.snow_field.snowpass.name'), region: "r_snow", outside: "wall_snow",
    rows: [
      "rrrrrrrrrrrrrrrRrr;;;;;;..;T;;;;;;;Rrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrRr;;;;r;..;;;r;;r;;Rrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrr,,;;;;;,..;;;;;;T;;Rrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR,,,,;,,..,,,,;;r,,Rrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR\",,,,,,..,,r,,,,,,Rrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR,,,,,,,,..,,,,,,,,,Rrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrr,,,,,,,,,..,,,,,,,,,Rrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,,\",,,,..,,,,,,,,\"Rrrrrrrrrrrr",
      "rrrrrrrrrrrrrrr,,,,,,,,,,...,,,,r,,\"\"Rrrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,,\"\",,,,..,,,,r,r,,Rrrrrrrrrrr",
      "rrrrrrrrrrrrrrr,,,rr,,,,,..;;;;;T;T,,Rrrrrrrrrrr",
      "rrrrrrrrrrrrrrR,\",,,,,,,...;;;;;;;;,,Rrrrrrrrrrr",
      "rrrrrrrrrrrrrR,,\",,,,,;...r;;;;;;;r,rXXrrrrrrrrr",
      "rrrrrrrrrrrrrrR,\",,,,,..;;;;;;;;;;r,RXXrrrrrrrrr",
      "rrrrrrrrrrrrrrR,,,,,,..;;;;r;;;;;;,rRXXrrrrrrrrr",
      "rrrrrrrrrrrrrrR,,,,,...;rr;;;r;r;;,XXXXrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,,..r;rr;;;rrr;;,rXXrrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,..r;;;;;;;;;;;;,rRrrrrrrrrrrr",
      "rrrrrrrrrrrrrrR,,,,..,;;;;;;;;;;;;,,Rrrrrrrrrrrr",
      "rrrrrrrrrrrrrRrrrrr..,;;\"rr;;;;;;;;,TRrrrrrrrrrr",
      "rrrrrrrrrrrrrXXXXXr.:,,r\";;;;r;;,,,,,rRrrrrrrrrr",
      "rrrrrrrrrrrrRXXcXX:::.rrr;;;r;;;,,,,,,Rrrrrrrrrr",
      "rrrrrrrrrrrrRXXcXX:,...;;;;;;;;,,,,,,,rRrrrrrrrr",
      "rrrrrrrrrrRR,XXcXX;,,....,;;;;,,,,,,,,,,Rrrrrrrr",
      "rrrrrrrrRRr,,,,,,;;,,,......;;,,,,,,,,,,rRrrrrrr",
      "rrrrrrrRr,,,r,,,,,,,,,,,,....;;;;,,,,,,,,rRrrrrR",
      "rrrrRRR,,,,rT,,,,,,,,,,,;,;...,,,,,,,,,,,;rRRRRr",
      "RRRRr,,,,,,,,,,;,rr,,,,;;;;,..,,,,,,,,,,,;;;,,,;",
      ",;;;;,;,,,,,,,,,,rTr,,,,,;,\"\"..\"r,,,,,,,,,,,,,,r",
      ",;;;;;;;,,,,,,,,rTTT,,,,,,,,,..rr,r;;,rrrr,,rr,,",
      ",,;;;;;;,,,,,,rr,TTT,,,,r,,,.,,,XrT;,rTTTTrrTTr\"",
      ",,;;;;;;,,,,,,,,,,,,,,,,T,,..,,,,,;;,TTTTTrTTTr,",
      "\"\";;;;;,,,,r,,,,,,,,,,,,;,...,,,,rr,,,,TTT,,T,,,",
      "\";,,,;,,,,r::,r,,,,,r,,,;...,,,,r,,,,,,,,;\"\";,,,",
      ";;,,,rr,,,,::::,,,,,r,,,...,,,,rrrr,,,,,,;;;;,,\"",
      ";,,\"rrrrr,,,,,::::,,r,,,..,,,,,TTTr,,,,,,;;;;,,,",
      "rrrrTTTTr,,,,,,,:::::,,...,,,,,TTTTrr,,,,,;r;;rr",
      "rrrrrTTTrrrTr,,,,,,:::::.,,,r,;,,,,,r,,r,r;Trrrr",
      "FFFFFFFFFFFrr,r,,,r,r,,:.r,,,,;rrr,rrrrrrrrrFFFF",
      "FFFFFFFFFFFFFrrrrrrrF,..rr,rr;rrrrrrrFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFrrrFFFFr.FF,TrrrFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFr.FFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFT.FFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFFr..FFFFFFFFFFFFFFFFFFFFFFF",
    ],
    objects: [
      {"type":"sign","x":21,"y":39,"text":R.T('map.snow_field.snowpass.objects.0.text')},
      {"type":"examine","x":31,"y":31,"event":"snow_pass_cairn"},
      {"type":"examine","x":18,"y":22,"event":"snow_pass_hut"},
      {"type":"waylamp","id":"wl_snow_39_43","x":27,"y":34,"lit":true},
      {"type":"waylamp","id":"wl_snow_39_38","x":23,"y":8,"lit":true},
      {"type":"prop","id":"tent","x":8,"y":32},
      {"type":"prop","id":"firewood","x":9,"y":34},
      {"type":"prop","id":"lantern","x":7,"y":33},
      {"type":"chest","id":"f_snowpass_c1","x":15,"y":21,"item":"i_ether","n":1},
    ],
    npcs: [
      {"id":"snow_trapper","look":"npc_snow_man","name":R.T('map.snow_field.snowpass.snow_trapper.name'),"x":11,"y":33,"dir":"s","move":"still","talk":"world_snow_trapper","reward":"hint","key":"world_snow_trapper"},
    ],
    spawns: {"south":{"x":23,"y":42,"dir":"n"},"north":{"x":24,"y":1,"dir":"s"}},
    exits: [{"x":23,"y":43,"w":2,"h":1,"to":{"map":"f_windhill","spawn":"pass"}},{"x":24,"y":0,"w":2,"h":1,"to":{"map":"f_lake","spawn":"south"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":[23,0,4,6],"zone":"zw_snow_road"},{"rect":[27,4,1,9],"zone":"zw_snow_road"},{"rect":[24,6,3,8],"zone":"zw_snow_road"},{"rect":[28,7,1,4],"zone":"zw_snow_road"},{"rect":[23,10,1,7],"zone":"zw_snow_road"},{"rect":[22,11,1,7],"zone":"zw_snow_road"},{"rect":[21,12,1,14],"zone":"zw_snow_road"},{"rect":[20,13,1,12],"zone":"zw_snow_road"},{"rect":[19,14,1,10],"zone":"zw_snow_road"},{"rect":[24,14,1,1],"zone":"zw_snow_road"},{"rect":[18,16,1,8],"zone":"zw_snow_road"},{"rect":[16,20,2,4],"zone":"zw_snow_road"},{"rect":[22,20,1,6],"zone":"zw_snow_road"},{"rect":[23,21,1,5],"zone":"zw_snow_road"},{"rect":[24,22,2,5],"zone":"zw_snow_road"},{"rect":[26,23,3,5],"zone":"zw_snow_road"},{"rect":[29,24,1,10],"zone":"zw_snow_road"},{"rect":[30,25,1,6],"zone":"zw_snow_road"},{"rect":[31,27,1,4],"zone":"zw_snow_road"},{"rect":[27,28,2,7],"zone":"zw_snow_road"},{"rect":[26,30,1,8],"zone":"zw_snow_road"},{"rect":[25,31,1,9],"zone":"zw_snow_road"},{"rect":[10,32,4,4],"zone":"zw_snow_road"},{"rect":[24,32,1,12],"zone":"zw_snow_road"},{"rect":[14,33,2,4],"zone":"zw_snow_road"},{"rect":[23,33,1,11],"zone":"zw_snow_road"},{"rect":[16,34,3,4],"zone":"zw_snow_road"},{"rect":[19,35,4,4],"zone":"zw_snow_road"},{"rect":[27,35,1,1],"zone":"zw_snow_road"},{"rect":[13,36,1,1],"zone":"zw_snow_road"},{"rect":[15,37,1,1],"zone":"zw_snow_road"},{"rect":[18,38,1,1],"zone":"zw_snow_road"},{"rect":[21,39,2,5],"zone":"zw_snow_road"},{"rect":[25,42,1,2],"zone":"zw_snow_road"},{"rect":null,"zone":"zw_snow"}],
    weather: "blizzard",
    art: {"image":"field/under/f_snowpass","painted":[],"overlay":"field/under/f_snowpass_over"},
    meta: {"sub":R.T('map.snow_field.snowpass.meta.sub'),"worldRect":[98,104,44,40]},
    links: {},
  });
})(window.RPG);
