// 生成物（design/art_ref/gen/env/_tools/under/snow/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// 雪原のエリア f_passinn「湯けむりの峠」（峠の宿と、湯の湧く谷、52×42）。エリア切り替えのフィールド（maps/field_00_kit.js・snow_field_00_kit.js）。
//   出口: w → f_eastroad.east, n → pass_inn.gate, e → world.snow_east
//   絵: field/under/f_passinn（v2/assets/env/field/under/。無ければマスから焼く）。文は src/i18n/ja/maps_snow.js（map.snow_field.passinn.*）
(function (R) {
  'use strict';
  R.Snow.fieldArea("f_passinn", {
    name: R.T('map.snow_field.passinn.name'), region: "r_snow", outside: "wall_snow",
    rows: [
      "FFFFFFF,,XXXXXXXXXX...,XXXXXXXXXX\"\"wwrrrrrrrrrrrrrrr",
      "FFFFFFF,,,,,,,,,,,X...,X;;;;;;;;;;\",wrrrrrrrrrrrrrrr",
      "FFFFFFF,,,,,,,,,,,,...,;;;;;;T;;;,,,wrrrrrrrrrrrrrrr",
      "FFFFFFF,,,,,,,,,,,,...,;;;;T;;;;;,,,wrrrrrrrrrrrrrrr",
      "FFFFFFF,\",,,,,,,,,,...,;;;;;;;;;;,,,wrrrrrrrrrrrrrrr",
      "FFF,,,,,,T,,,,,,,,,...,,;,,,,,,;;,,,wrrrrrrrrrrrrrrr",
      ";;,,,,,,,,,,,,,,,,,...,,,TT;,,,,,,,,wwrrrrrrrrrrrrrr",
      ";;,,,,,,,,,,,,,,,,,...,,,,,,,,;,,,,\"wwrrrrrrrrrrrrrr",
      ";;T;;,,,,,,,,,,,,,,...,,,T,,,,;;;;;\"wwrrrrrrrrrrrrrr",
      ";;;;,,,,,,,,,,,,,,,...,,,,,,,,,;;;;,wwrrrrrrrrrrrrrr",
      ";;;,,,,,,,,,,,,,,,,...,,,,,,TTTTT;;,wwrrrrrrrrrrrrrr",
      ";;;,,,;,,,,,,,,,,,,...,,,,,,TTTTT,,,wwrrrrrrrrrrrrrr",
      ";;,,,;;T,,,,,,,,\"\",...,,,,,,TTTT,,,,wrrrrrrrrrrrrrrr",
      ";;,,r,;TTTT,,,,,\";;...,T,,,,;;;;;,,wwrrrrrrrrrrrrrrr",
      ",,,,,,TTTTTT,,,;;;;...,,,,,,,;;;;;,w,,rrrrrrrrrrrrrr",
      ",,,,,,TTTTT,,,;;;;;..,,,,,,,,,;;;,;w,,rrrrrrrrrrrrrr",
      ",,,,,,,;;;;;,;;;;;;..,,,,,,,,;;;;;;w;;;rrrrrrrrrrrrr",
      ",,,,,,,,;;;;T;;;;;,..,,,,,,,,;;;;;;ww;;rrrrrrrrrrrrr",
      ",,,,,,,,;;;;\";;;,,,..,,,,,,,,;,;;;;ww;;;rrrrrrrrrrrr",
      ",,,,,,,,;;;;;;;;,,,......,,,,,,;;;;;w;;;rrrrrrrrrrrr",
      ",,,,,,,,;;;;;;..................,;;;w;;;;rrrrrrrrrrr",
      ",,,,,,,,;;;..........,,............ww;;;;rrrrrrrrrrr",
      ",,,,,,,,......;;;;;;,,,,,,,,,,,,...=w;;;;;rrrrrrrrrr",
      "............;;;;;;;;,,,,,,,,,,,,,,==..,,;;;rrrrrrrrr",
      "........;;;;;;;;;;;;,,,,,,,,,,,,,ww....,;;;;rrrrrrrr",
      ",,,,,,,;;;;;;;;;;;:;,,,T,,,,:::,www;;....;;;;rrrrrrr",
      "\",,,,,;;r;;;;;;;:::::;,,,,,::::www,;;;;....;;rrrrrrr",
      ",\",,,,;,,,;;;;;:::w:::;;;,::wwww:,,;;;;;;...........",
      ",,,,,;;,,,;;;;::wwwww::;::::www::,,;\";;;;;;.........",
      ",,,,;TTT,;;;;::wwwwwww::::::::::,,;;;;;;;,,,,.......",
      ",,,,TTTT;;r;::::wwwwww::www::::,,,;;;;;;,,,,,rrrrrrr",
      ",,,,,TTT;,;::::::::::::wwwww::,,,,;;;;X,,,,,,rrrrrrr",
      ",,,,,,,,,,::ww:::::::::wwwww::,,\",;;;;,,,,,rrrrrrrrr",
      ";,,T,,,,,::wwww::,,,,,:::w:::,,,,,;;,,,,,,rrrrrrrrrr",
      ";;;;;;T;;;::www::,,,,,,:::::,,,,,,,,,,,,,rrrrrrrrrrr",
      ";;;;;;,;;;;:::::,,,,,,,,,:,TT,,,,,,,,,,,rrrrrrrrrrrr",
      "FFFFFFFF\";,;:::,,,,T,,r,,,,TTT,,,,,,,,,rrrrrrrrrrrrr",
      "FFFFFFFFFFFFFFF,,,T,,,,,T,,TT,,,,T,,,,,rrrrrrrrrrrrr",
      "FFFFFFFFFFFFFFFFFFFF,,,,,,,,,,,,,,,,FF,rrrrrrrrrrrrr",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFrrrrrrrrrrrrr",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFrrrrrrrrrrrrr",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFrrrrrrrrrrrr",
    ],
    objects: [
      {"type":"sign","x":18,"y":5,"text":R.T('map.snow_field.passinn.objects.0.text')},
      {"type":"sign","x":36,"y":24,"text":R.T('map.snow_field.passinn.objects.1.text')},
      {"type":"examine","x":21,"y":31,"event":"snow_pass_springs"},
      {"type":"waylamp","id":"wl_snow_80_35","x":9,"y":21,"lit":true},
      {"type":"prop","id":"snow_lamp","x":18,"y":4},
      {"type":"prop","id":"snow_lamp","x":22,"y":4},
      {"type":"chest","id":"f_passinn_c1","x":11,"y":31,"item":"i_incense","n":1},
      {"type":"examine","x":12,"y":15,"event":"snow_mat","mat":"snow_mat_berry"},
    ],
    npcs: [
      {"id":"guard_snow_east","look":"npc_guard_1","name":R.T('map.snow_field.passinn.guard_snow_east.name'),"x":47,"y":28,"dir":"w","move":"still","pushable":false,"cond":{"slice":true},"talk":{"lines":[{"text":R.T('map.snow_field.passinn.guard_snow_east.lines.0')}]},"reward":"news","key":"world_guard_snow_east"},
    ],
    spawns: {"west":{"x":1,"y":23,"dir":"e"},"inn":{"x":20,"y":1,"dir":"s"},"east":{"x":50,"y":28,"dir":"w"}},
    exits: [{"x":0,"y":23,"w":1,"h":2,"to":{"map":"f_eastroad","spawn":"east"}},{"x":20,"y":0,"w":2,"h":1,"to":{"map":"pass_inn","spawn":"gate"}},{"x":51,"y":28,"w":1,"h":2,"to":{"map":"world","spawn":"snow_east"},"cond":{"not":{"slice":true}}}],
    triggers: [],
    tilePatches: [{"cond":{"slice":true},"rect":[48,27,3,3],"rows":["rrr","rrr","rrr"]}],
    zones: [{"rect":null,"zone":"zw_snow"}],
    weather: "snow",
    weatherCond: "!cleared_r_snow",
    art: {"image":"field/under/f_passinn","painted":[]},
    meta: {"sub":R.T('map.snow_field.passinn.meta.sub'),"worldRect":[240,70,44,44]},
    links: {"pass_inn":{"map":"f_passinn","spawn":"inn"}},
  });
})(window.RPG);
