// 生成物（design/art_ref/gen/env/_tools/under/snow/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// 雪原のエリア f_snowpass「凍て風の峠」（森から雪原へ越える峠、48×44）。エリア切り替えのフィールド（maps/field_00_kit.js・snow_field_00_kit.js）。
//   出口: s → f_windhill.pass, n → f_lake.south
//   絵: field/under/f_snowpass（v2/assets/env/field/under/。無ければマスから焼く）。文は src/i18n/ja/maps_snow.js（map.snow_field.snowpass.*）
(function (R) {
  'use strict';
  R.Snow.fieldArea("f_snowpass", {
    name: R.T('map.snow_field.snowpass.name'), region: "r_snow", outside: "wall_snow",
    rows: [
      "rrrrrrrrrrrrrrrR,;;;;;;;..;T;;;;;;rrrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR;;;;;r;..;;;r;;;;rRrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR,;;;;;,..;;;;;;T;;Rrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR,,,,;,,..,,,,;;,,rRrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR\",,,,,,..,,r,,,,,,Rrrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR,,,,,,,,..,,,,,,,,rRrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrrR,,,,,,,,..,,,,,,,,,Rrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrRr,,,\",,,,..,,,,,,,,\"Rrrrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,,,,,,,...,,,,,,,\"\"Rrrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,,\"\",,,,..,,,,r,r,,Rrrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,r,,,,,..;;;;rTrT,,Rrrrrrrrrrr",
      "rrrrrrrrrrrrrrRr\",,,,,,,...;;;;;;;;,,Rrrrrrrrrrr",
      "rrrrrrrrrrrrrRr,\",,,,,;...r;;;;;;rr,,XXrrrrrrrrr",
      "rrrrrrrrrrrrrrR,\",,,,,..;;;;;;;;;;r,RXXrrrrrrrrr",
      "rrrrrrrrrrrrrrR,,,,,,..;;;;r;;;;;;,rRXXrrrrrrrrr",
      "rrrrrrrrrrrrrrR,,,,,...;;r;;;r;r;;rXXXXrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,,..r;rr;;;r;r;;,rXXrrrrrrrrrr",
      "rrrrrrrrrrrrrrrR,,,..r;;;;;;;;;;;;,rRrrrrrrrrrrr",
      "rrrrrrrrrrrrrrR,,,,..,;;;;;;;;;;;;,,Rrrrrrrrrrrr",
      "rrrrrrrrrrrrrRr,,,r..,;;\"rr;;;;;;;;,TRrrrrrrrrrr",
      "rrrrrrrrrrrrrXXXXX,.:,,r\";;;;r;;,,,,,,Rrrrrrrrrr",
      "rrrrrrrrrrrrRXcccr:::.r;r;;;r;;;,,,,,,Rrrrrrrrrr",
      "rrrrrrrrrrrrRXccc::,...;;;;;;;;,,,,,,,,Rrrrrrrrr",
      "rrrrrrrrrrRRrXXXXX;,,....,;;;;,,,,,,,,,,Rrrrrrrr",
      "rrrrrrrrRRr,,,rrrr;,,,......;;,,,,,,,,,,;Rrrrrrr",
      "rrrrrrrRrr,,,,,,,,,,,,,,,....;;;;,,,,,,,,;RrrrrR",
      "rrrrRRRrr,,,Tr,,,,,,,,,,;,;...,,,,,,,,,,,;;RRRRr",
      "RRRRrrrr,,,,r,,;,,,,,,,;;;;,..,,,,,,,,,,,;;rrrr;",
      "rrrrr,;,,,,,,,,,,,T,,,,,,;,\"\"..\"r,,,,,,,,,,,,,,,",
      ",;;;;;;;,,,,,,,,,TTT,,,,,,,,,..\"r,;;;,,,,,,,,,,r",
      ",,;;;;;;,,,,,,,rrTTT,,,,,,,,.,,,XrT;,,TTTT,,TT,\"",
      ",,;;;;;;,,,,,,,,,,,,,,,,T,,..,,,,,;;,TTTTT,TTT,,",
      "\"\";;;;;,,,,,,,,,,,,,,,,,;,...,,,,,r,,,rTTT,rT,,,",
      "\";,,,;,,,,,::,,,,,,,,,,,;...,,,,,,,,,,,,,;\"\";,,,",
      ";;,,,;,,,,,::::,,,,,r,,,...,,,,rr,,,,,,,,;;;;,,\"",
      ";,,\",rrr,,,,,,::::,,,,,,..,,,,,TTT,,,,,,,;;;;,,,",
      ",,,\"\"TTT,,,,,,,,:::::,,...,,,,rTTTT,,,,,,,;;;;,,",
      "r,r,rTTTrrr,,,,,,,,:::::.,,,r,rTTT,rr,,,,r;,rrrr",
      "FFFFFFFFFFFrr,,,,,,,,,,:.,,,T,;;,,,,,rrrrrrrFFFF",
      "FFFFFFFFFFFFFrr,,,rr\",..rr,r;;;rrrrrrFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFrrrFFFF..FF,TrrrFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFFFFFF",
      "FFFFFFFFFFFFFFFFFFFFFF...FFFFFFFFFFFFFFFFFFFFFFF",
    ],
    objects: [
      {"type":"sign","x":21,"y":39,"text":R.T('map.snow_field.snowpass.objects.0.text')},
      {"type":"examine","x":31,"y":31,"event":"snow_pass_cairn"},
      {"type":"examine","x":18,"y":22,"event":"snow_pass_hut"},
      {"type":"waylamp","id":"wl_snow_39_43","x":27,"y":34,"lit":true},
      {"type":"waylamp","id":"wl_snow_39_38","x":23,"y":8,"lit":true},
      {"type":"prop","id":"tent","x":8,"y":32},
      {"type":"prop","id":"firewood","x":9,"y":34},
      {"type":"prop","id":"lantern","x":7,"y":33},
      {"type":"chest","id":"f_snowpass_c1","x":15,"y":21,"item":"i_ether","n":1},
    ],
    npcs: [
      {"id":"snow_trapper","look":"npc_snow_man","name":R.T('map.snow_field.snowpass.snow_trapper.name'),"x":11,"y":33,"dir":"s","move":"still","talk":"world_snow_trapper","reward":"hint","key":"world_snow_trapper"},
    ],
    spawns: {"south":{"x":23,"y":42,"dir":"n"},"north":{"x":24,"y":1,"dir":"s"}},
    exits: [{"x":23,"y":43,"w":2,"h":1,"to":{"map":"f_windhill","spawn":"pass"}},{"x":24,"y":0,"w":2,"h":1,"to":{"map":"f_lake","spawn":"south"}}],
    triggers: [],
    tilePatches: [],
    zones: [{"rect":null,"zone":"zw_snow"}],
    weather: "blizzard",
    art: {"image":"field/under/f_snowpass","painted":[],"overlay":"field/under/f_snowpass_over"},
    meta: {"sub":R.T('map.snow_field.snowpass.meta.sub'),"worldRect":[98,104,44,40]},
    links: {},
  });
})(window.RPG);
