// 生成物（design/art_ref/gen/env/_tools/under/snow/field/ の areas.py → fit.py → tomap.py）。手で直さない: 配置は areas.py、当たりは fit.py で作り直す。
// 雪原のエリア f_lake「凍った湖」（ユールの西の湖と、つららの崖、56×44）。エリア切り替えのフィールド（maps/field_00_kit.js・snow_field_00_kit.js）。
//   出口: s → f_snowpass.north, e → yule.gate_w, n → f_floe.south
//   絵: field/under/f_lake（v2/assets/env/field/under/。無ければマスから焼く）。文は src/i18n/ja/maps_snow.js（map.snow_field.lake.*）
(function (R) {
  'use strict';
  R.Snow.fieldArea("f_lake", {
    name: R.T('map.snow_field.lake.name'), region: "r_snow", outside: "wall_snow",
    rows: [
      "rrrrrrR,,,,\"\"\"swwwwwwwwwwsswwwwwwwwwwws,,,,,,,FFFFFFFFFF",
      "rrrrrrR,,,,,\",swwwwwwwwwwsswwwwwwwwwwws,,,,,,,FFFFFFFFFF",
      "rrrrrrR;;,,,,,swwwwwwwwwwsswwwwwwwwwwws,,,,,,,,FFFFFFFFF",
      "rrrrrrR;;;,,b,swwwwwwwwwwsswwwwwwwwwwws,,,,,,,,FFFFFFFFF",
      "rrrrrrR;T;,,b,swwwwwwwwwwwsswwwwwwwwwws\"\"\",,,T,FFFFFFFFF",
      "rrrrrrR;;;;;b,swwwwwwwwwwwsswwwwwwwwwwss\"\",,,,,FFFFFFFFF",
      "rrrrrrR;;;,;;;swwwwwwwwwwwsswwwwwwwwwwws\"b,,,r,FFFFFFFFF",
      "rrrrrrR;;;,,;;swwwwwwwwwwwsswwwwwwwwwwwss\",,,,,FFFFFFFFF",
      "rrrrrrR;;;;,;;swwwwwwwwwwwsswwwwwwwwwwwwssbr,,,,FFFFFFFF",
      "rrrrrrR;;;;;,sswwwwwwwwwwwsswwwwwwwwwwwwws,,,,,,FFFFFFFF",
      "rrrrrrrR;;;;;swwwwwwwwwwwwsswwwwwwwwwwwwwssb,,,,,FFFFFFF",
      "rrrrrrrR;,;;;swwwwwwwwwwwwsswwwwwwwwwwwwwws,b,,;;FFFFFFF",
      "rrrrrrrR;,;;;swwwwwwwwwwwwwsswwwrrrwwwwwwws,b,,,,FFFFFFF",
      "rrrrrrrR,;;;;sswwwwwwwwwwwwsswwrrXrrwwwwwssb,,,;;FFFFFFF",
      "rrrrrrrR;;;;;;swwwwwwwwwwwwsswwwrrrwwwwwws,b,,T;;FFFFFFF",
      "rrrrrrrrR;,,;,swwwwwwwwwwwwsswwwwwwwwwwwssb,,,;;;;FFFFFF",
      "rrrrrrrrR,,,,,swwwwwwwwwwwwsswwwwwwwwwwws,b,,,;;;;;;;,,,",
      "rrrrrrrrR,,,,,swwwwwwwwwwwwsswwwwwwwwwwss,,,,,,;;;;;;;;;",
      "rrrrrrrrR,,,,,sswwwwwwwwwwwsswwwwwwwwwws,,,,,,;;;;;,;;XX",
      "rrrrrrrrR,,,,,,swwwwwwwwwwwsswwwwwwwwsssb,,,,,,;;;T,,,XX",
      "rrrrrrrrR,,,,,,sswwwwwwwwwwsswwwwwwwss,b,,,,,,,,;TTT\"\"XX",
      "rrrrrrrrR,,,,,,rswwwwwwwwwwsswwwwwwssbb\",,,;;,T;;;,,,,XX",
      "rrrrrrrR,,,;;;,Tsswwwwwwwwwsswwwwwssb,\",\";;;;;;,,,,,,,XX",
      "rrrrrrrR,,;;;;,,,ssswwwwwwwwsswwwssb,,,\"\";;;\"\"TTT,,,,,XX",
      "rrrrrrrR,;;;;r,,,,,ssswwwwwwssssss,,,,,r\";;\";;TTT,,,,,XX",
      "rrrrrrR,,;;;;;;,,,,,,sssssssss,,,r,,,,,,\"\";;;;TTT,,,,,XX",
      "rrrrrrR,,,;;;;;;,,,,,b,,,,,,ss,,br,,,,,;,,;;;;;,,,,,,,XX",
      "rrrrrrR,,,,,,;;;;,,,,,bbbb,,ss,,r;,,,,,;,,;;;;;,,,;,,,XX",
      "rrrrrrR,,,,,\"\"\";;;;;;,,,,,,,ss,,,;,,,,,,,,;;;;;;,;;,\"XXX",
      "rrrrrrXXXX,,;;;;r;;;;,,,,,T,ss;,,,,,,,;;;;;;;;;;;;;;,\",,",
      "rrrrrrXXXX,,;;;;;;;;;,,,,,,,ss;;,,TT,,;;;;;;;;;;........",
      "rrrrrr,,,,::::;;;;;;;,,;,,,;,s;;;;;,,,;;;;;;;...........",
      "rrrrrrrR,,,,:::::;;;;,;;;;;;;;;;,;,,\"...........;;,,,,,,",
      "rrrrrrrR;,,,;;;::::;;;,;;;;;;;;,,............,,,,,,,,XXX",
      "rrrrrrrrR;;;;r;;;;:::;;;;;;;;;;........;;;;,,,,,,,,,,,XX",
      "rrrrrrrrR;;;;;;;;;;;:::::;;;;;...,,,,,,,,;,,,,,,,,,,T,XX",
      "rrrrrrrR,;;;;;\";\"\";;;;;::::::..;;,,,,,,,,,,,r,,,,,T,,,XX",
      "rrrrrrrR,;;T;;;\"TT;;;;;;;;;::.;;\",,,,TTT,,,,,,,,,,,,,,XX",
      "rrrrrrRFF;;;;;;\"TTT;T;;;;;;..;;;,,,,TTTT\",,,,,,,,,,,,,XX",
      "rrrrrRFFFF;;FFFFFFFFFF;;;;;..;;;;,,,,TTT\",,,;;,,,FFF,,XX",
      "rrRRRFFFFFFFFFFFFFFFFFFF;;;..;;;;,,,,,T,,;;;FFFFFFFFFFXX",
      "RRFFFFFFFFFFFFFFFFFFFFFFFF...;;;;,,,,FFFFFFFFFFFFFFFFFXX",
      "FFFFFFFFFFFFFFFFFFFFFFFFFF...FFFFFFFFFFFFFFFFFFFFFFFFFXX",
      "FFFFFFFFFFFFFFFFFFFFFFFFFFF..FFFFFFFFFFFFFFFFFFFFFFFFFFF",
    ],
    objects: [
      {"type":"door","x":7,"y":30,"w":2,"look":"none","to":{"map":"icicle_1","spawn":"entrance"}},
      {"type":"sign","x":11,"y":33,"text":R.T('map.snow_field.lake.objects.1.text')},
      {"type":"sign","x":32,"y":36,"text":R.T('map.snow_field.lake.objects.2.text')},
      {"type":"examine","x":31,"y":34,"event":"world_snow_lake"},
      {"type":"prop","id":"sled","x":26,"y":34},
      {"type":"prop","id":"ice_hole","x":36,"y":25},
      {"type":"prop","id":"ice_crystal","x":10,"y":27},
      {"type":"prop","id":"ice_crystal","x":12,"y":30},
      {"type":"waylamp","id":"wl_snow_26_37","x":19,"y":33,"lit":true},
      {"type":"waylamp","id":"wl_snow_42_32","x":45,"y":33,"lit":true},
      {"type":"prop","id":"tent","x":10,"y":18},
      {"type":"prop","id":"firewood","x":11,"y":19},
      {"type":"prop","id":"snow_lamp","x":9,"y":19},
      {"type":"examine","x":13,"y":21,"event":"snow_mat","mat":"snow_mat_ice"},
    ],
    npcs: [

    ],
    spawns: {"south":{"x":27,"y":42,"dir":"n"},"yule":{"x":54,"y":30,"dir":"w"},"north":{"x":26,"y":1,"dir":"s"},"icicle":{"x":8,"y":31,"dir":"s"}},
    exits: [{"x":27,"y":43,"w":2,"h":1,"to":{"map":"f_snowpass","spawn":"north"}},{"x":55,"y":30,"w":1,"h":2,"to":{"map":"yule","spawn":"gate_w"}},{"x":26,"y":0,"w":2,"h":1,"to":{"map":"f_floe","spawn":"south"},"cond":"cleared_r_snow"}],
    triggers: [],
    tilePatches: [{"cond":{"not":"cleared_r_snow"},"rect":[25,0,5,24],"rows":["ww   ","ww   ","ww   ","ww   "," ww  "," ww  "," ww  "," ww  "," ww  "," ww  "," ww  "," ww  ","  ww ","  ww ","  ww ","  ww ","  ww ","  ww ","  ww ","  ww ","  ww ","  ww ","  ww ","   ww"]}],
    zones: [{"rect":null,"zone":"zw_snow"}],
    weather: "snow",
    weatherCond: "!cleared_r_snow",
    art: {"image":"field/under/f_lake","painted":[]},
    meta: {"sub":R.T('map.snow_field.lake.meta.sub'),"worldRect":[60,44,84,64]},
    links: {"yule_w":{"map":"f_lake","spawn":"yule"},"icicle":{"map":"f_lake","spawn":"icicle"}},
  });
})(window.RPG);
